/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_OutOfMemory 1
#define ERROR_UnexpectedRParen 2
#define ERROR_UnexpectedEof 3
#define ERROR_UnexpectedToken 4
#define ERROR_InvalidQuote 5
#define ERROR_InvalidIf 6
#define ERROR_InvalidDefine 7
#define ERROR_InvalidLambda 8
#define ERROR_InvalidExpr 9
#define ERROR_NotCallable 10
#define ERROR_InvalidClosure 11
#define ERROR_InvalidEnv 12
#define ERROR_UnboundSymbol 13
#define ERROR_WrongArity 14
#define ERROR_NotACons 15
#define ERROR_NotAnInt 16
#define ERROR_DivisionByZero 17
#define ERROR_InvalidParams 18
#define ERROR_Unreachable 19
#define ERROR_InvalidDigit 20
#define ERROR_TooManyArgs 21
#define ERROR_TooFewArgs 22

#include "builtins.h"
#include "value.h"
#include "util.h"
#include "sand.h"


ErrorUnion_Ptr_zS_5_Value zF_42_builtin_cons(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    struct zS_5_Value* __tmp_try_7_19;
    ErrorUnion_Ptr_zS_5_Value __tmp_try_res_7_20;
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    __tmp_try_res_7_20 = zF_33_alloc_cons(args.ptr[0], args.ptr[1], arena);
    if (__tmp_try_res_7_20.is_error) {
        return __tmp_try_res_7_20;
    }
    __tmp_try_7_19 = __tmp_try_res_7_20.data.payload;
    {
        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_19;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5_Value zF_43_builtin_car(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    if (args.len != 1) {
        {
            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
/* DEBUG: emitSwitch start */
    {
        struct zS_5_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case zE_8_Value_Tag_Cons:
            {
                /* DEBUG: capture data */
                struct zS_4_ConsData data;
                memcpy(&data, &switch_tmp.data.Cons, sizeof(struct zS_4_ConsData));
{
                {
                    ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                    __return_val.is_error = 0;
                    __return_val.data.payload = data.car;
                    return __return_val;
                }
            }            }
            break;
        default:
{
                {
                    ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                    __return_val.is_error = 1;
                    __return_val.data.err = ERROR_NotACons;
                    return __return_val;
                }
            }            break;
    }
    }
}

ErrorUnion_Ptr_zS_5_Value zF_44_builtin_cdr(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    if (args.len != 1) {
        {
            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
/* DEBUG: emitSwitch start */
    {
        struct zS_5_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case zE_8_Value_Tag_Cons:
            {
                /* DEBUG: capture data */
                struct zS_4_ConsData data;
                memcpy(&data, &switch_tmp.data.Cons, sizeof(struct zS_4_ConsData));
{
                {
                    ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                    __return_val.is_error = 0;
                    __return_val.data.payload = data.cdr;
                    return __return_val;
                }
            }            }
            break;
        default:
{
                {
                    ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                    __return_val.is_error = 1;
                    __return_val.data.err = ERROR_NotACons;
                    return __return_val;
                }
            }            break;
    }
    }
}

ErrorUnion_Ptr_zS_5_Value zF_45_builtin_add(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    i64 sum = 0;
    struct zS_5_Value* __tmp_try_7_17;
    ErrorUnion_Ptr_zS_5_Value __tmp_try_res_7_18;
    sum = 0;
    {
        Slice_Ptr_zS_5_Value __for_iter_1 = args;
        size_t __for_idx_1 = 0;
        size_t __for_len_1 = __for_iter_1.len;
        __loop_0_start: ;
        while (__for_idx_1 < __for_len_1) {
            struct zS_5_Value* arg = __for_iter_1.ptr[__for_idx_1];
{
/* DEBUG: emitSwitch start */
                {
                    struct zS_5_Value switch_tmp = *arg;
                    switch (switch_tmp.tag) {
                    case zE_8_Value_Tag_Int:
                        {
                            /* DEBUG: capture val */
                            i64 val;
                            val = switch_tmp.data.Int;
{
                            sum += val;
                        }                        }
                        break;
                    default:
{
                            {
                                ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                                __return_val.is_error = 1;
                                __return_val.data.err = ERROR_NotAnInt;
                                return __return_val;
                            }
                        }                        break;
                }
                }
            }
            __loop_0_continue: ;
            __for_idx_1++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    __tmp_try_res_7_18 = zF_34_alloc_int(sum, arena);
    if (__tmp_try_res_7_18.is_error) {
        return __tmp_try_res_7_18;
    }
    __tmp_try_7_17 = __tmp_try_res_7_18.data.payload;
    {
        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_17;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5_Value zF_46_builtin_sub(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    i64 res = 0;
    usize i = 1;
    struct zS_5_Value* __tmp_try_7_13;
    ErrorUnion_Ptr_zS_5_Value __tmp_try_res_7_14;
    if (args.len == 0) {
        {
            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    res = 0;
/* DEBUG: emitSwitch start */
    {
        struct zS_5_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case zE_8_Value_Tag_Int:
            {
                /* DEBUG: capture val */
                i64 val;
                val = switch_tmp.data.Int;
{
                res = val;
            }            }
            break;
        default:
{
                {
                    ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                    __return_val.is_error = 1;
                    __return_val.data.err = ERROR_NotAnInt;
                    return __return_val;
                }
            }            break;
    }
    }
    if (args.len == 1) {
        struct zS_5_Value* __tmp_try_9_15;
        ErrorUnion_Ptr_zS_5_Value __tmp_try_res_9_16;
        __tmp_try_res_9_16 = zF_34_alloc_int(-res, arena);
        if (__tmp_try_res_9_16.is_error) {
            return __tmp_try_res_9_16;
        }
        __tmp_try_9_15 = __tmp_try_res_9_16.data.payload;
        {
            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
            __return_val.is_error = 0;
            __return_val.data.payload = __tmp_try_9_15;
            return __return_val;
        }
    }
    i = 1;
    __loop_0_start: ;
    if (!(i < args.len)) goto __loop_0_end;
    {
/* DEBUG: emitSwitch start */
        {
            struct zS_5_Value switch_tmp_1 = *args.ptr[i];
            switch (switch_tmp_1.tag) {
            case zE_8_Value_Tag_Int:
                {
                    /* DEBUG: capture val */
                    i64 val_1;
                    val_1 = switch_tmp_1.data.Int;
{
                    res -= val_1;
                }                }
                break;
            default:
{
                    {
                        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                        __return_val.is_error = 1;
                        __return_val.data.err = ERROR_NotAnInt;
                        return __return_val;
                    }
                }                break;
        }
        }
        i += 1;
    }
    __loop_0_continue: ;
    goto __loop_0_start;
    __loop_0_end: ;
    __tmp_try_res_7_14 = zF_34_alloc_int(res, arena);
    if (__tmp_try_res_7_14.is_error) {
        return __tmp_try_res_7_14;
    }
    __tmp_try_7_13 = __tmp_try_res_7_14.data.payload;
    {
        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_13;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5_Value zF_47_builtin_mul(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    i64 res = 1;
    struct zS_5_Value* __tmp_try_7_11;
    ErrorUnion_Ptr_zS_5_Value __tmp_try_res_7_12;
    res = 1;
    {
        Slice_Ptr_zS_5_Value __for_iter_1 = args;
        size_t __for_idx_1 = 0;
        size_t __for_len_1 = __for_iter_1.len;
        __loop_0_start: ;
        while (__for_idx_1 < __for_len_1) {
            struct zS_5_Value* arg = __for_iter_1.ptr[__for_idx_1];
{
/* DEBUG: emitSwitch start */
                {
                    struct zS_5_Value switch_tmp = *arg;
                    switch (switch_tmp.tag) {
                    case zE_8_Value_Tag_Int:
                        {
                            /* DEBUG: capture val */
                            i64 val;
                            val = switch_tmp.data.Int;
{
                            res *= val;
                        }                        }
                        break;
                    default:
{
                            {
                                ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                                __return_val.is_error = 1;
                                __return_val.data.err = ERROR_NotAnInt;
                                return __return_val;
                            }
                        }                        break;
                }
                }
            }
            __loop_0_continue: ;
            __for_idx_1++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    __tmp_try_res_7_12 = zF_34_alloc_int(res, arena);
    if (__tmp_try_res_7_12.is_error) {
        return __tmp_try_res_7_12;
    }
    __tmp_try_7_11 = __tmp_try_res_7_12.data.payload;
    {
        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_11;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5_Value zF_48_builtin_div(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    i64 res = 0;
    usize i = 1;
    struct zS_5_Value* __tmp_try_7_9;
    ErrorUnion_Ptr_zS_5_Value __tmp_try_res_7_10;
    if (args.len == 0) {
        {
            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    res = 0;
/* DEBUG: emitSwitch start */
    {
        struct zS_5_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case zE_8_Value_Tag_Int:
            {
                /* DEBUG: capture val */
                i64 val;
                val = switch_tmp.data.Int;
{
                res = val;
            }            }
            break;
        default:
{
                {
                    ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                    __return_val.is_error = 1;
                    __return_val.data.err = ERROR_NotAnInt;
                    return __return_val;
                }
            }            break;
    }
    }
    i = 1;
    __loop_0_start: ;
    if (!(i < args.len)) goto __loop_0_end;
    {
/* DEBUG: emitSwitch start */
        {
            struct zS_5_Value switch_tmp_1 = *args.ptr[i];
            switch (switch_tmp_1.tag) {
            case zE_8_Value_Tag_Int:
                {
                    /* DEBUG: capture val */
                    i64 val_1;
                    val_1 = switch_tmp_1.data.Int;
{
                    if (val_1 == 0) {
                        {
                            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                            __return_val.is_error = 1;
                            __return_val.data.err = ERROR_DivisionByZero;
                            return __return_val;
                        }
                    }
                    res /= val_1;
                }                }
                break;
            default:
{
                    {
                        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                        __return_val.is_error = 1;
                        __return_val.data.err = ERROR_NotAnInt;
                        return __return_val;
                    }
                }                break;
        }
        }
        i += 1;
    }
    __loop_0_continue: ;
    goto __loop_0_start;
    __loop_0_end: ;
    __tmp_try_res_7_10 = zF_34_alloc_int(res, arena);
    if (__tmp_try_res_7_10.is_error) {
        return __tmp_try_res_7_10;
    }
    __tmp_try_7_9 = __tmp_try_res_7_10.data.payload;
    {
        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_9;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5_Value zF_49_builtin_eq(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    struct zS_5_Value* a;
    struct zS_5_Value* b;
    int res = 0;
    struct zS_5_Value* __tmp_try_7_7;
    ErrorUnion_Ptr_zS_5_Value __tmp_try_res_7_8;
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    a = args.ptr[0];
    b = args.ptr[1];
    res = 0;
/* DEBUG: emitSwitch start */
    {
        struct zS_5_Value switch_tmp = *a;
        switch (switch_tmp.tag) {
        case zE_8_Value_Tag_Int:
            {
                /* DEBUG: capture av */
                i64 av;
                av = switch_tmp.data.Int;
{
/* DEBUG: emitSwitch start */
                {
                    struct zS_5_Value switch_tmp_1 = *b;
                    switch (switch_tmp_1.tag) {
                    case zE_8_Value_Tag_Int:
                        {
                            /* DEBUG: capture bv */
                            i64 bv;
                            bv = switch_tmp_1.data.Int;
{
                            res = av == bv;
                        }                        }
                        break;
                    default:
{
                        }                        break;
                }
                }
            }            }
            break;
        case zE_8_Value_Tag_Bool:
            {
                /* DEBUG: capture av */
                int av_1;
                av_1 = switch_tmp.data.Bool;
{
/* DEBUG: emitSwitch start */
                {
                    struct zS_5_Value switch_tmp_2 = *b;
                    switch (switch_tmp_2.tag) {
                    case zE_8_Value_Tag_Bool:
                        {
                            /* DEBUG: capture bv */
                            int bv_1;
                            bv_1 = switch_tmp_2.data.Bool;
{
                            res = av_1 == bv_1;
                        }                        }
                        break;
                    default:
{
                        }                        break;
                }
                }
            }            }
            break;
        case zE_8_Value_Tag_Symbol:
            {
                /* DEBUG: capture av */
                Slice_u8 av_2;
                av_2 = switch_tmp.data.Symbol;
{
/* DEBUG: emitSwitch start */
                {
                    struct zS_5_Value switch_tmp_3 = *b;
                    switch (switch_tmp_3.tag) {
                    case zE_8_Value_Tag_Symbol:
                        {
                            /* DEBUG: capture bv */
                            Slice_u8 bv_2;
                            bv_2 = switch_tmp_3.data.Symbol;
{
                            res = zF_11_mem_eql(av_2, bv_2);
                        }                        }
                        break;
                    default:
{
                        }                        break;
                }
                }
            }            }
            break;
        case zE_8_Value_Tag_Nil:
{
/* DEBUG: emitSwitch start */
                {
                    struct zS_5_Value switch_tmp_4 = *b;
                    switch (switch_tmp_4.tag) {
                    case zE_8_Value_Tag_Nil:
{
                            res = 1;
                        }                        break;
                    default:
{
                        }                        break;
                }
                }
            }            break;
        default:
{
                res = a == b;
            }            break;
    }
    }
    __tmp_try_res_7_8 = zF_35_alloc_bool(res, arena);
    if (__tmp_try_res_7_8.is_error) {
        return __tmp_try_res_7_8;
    }
    __tmp_try_7_7 = __tmp_try_res_7_8.data.payload;
    {
        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_7;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5_Value zF_50_builtin_is_nil(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    int res = 0;
    struct zS_5_Value* __tmp_try_7_5;
    ErrorUnion_Ptr_zS_5_Value __tmp_try_res_7_6;
    if (args.len != 1) {
        {
            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    res = 0;
/* DEBUG: emitSwitch start */
    {
        struct zS_5_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case zE_8_Value_Tag_Nil:
{
                res = 1;
            }            break;
        case zE_8_Value_Tag_Symbol:
            {
                /* DEBUG: capture s */
                Slice_u8 s;
                s = switch_tmp.data.Symbol;
{
                res = zF_11_mem_eql(s, __make_slice_u8("nil", 3));
            }            }
            break;
        default:
{
            }            break;
    }
    }
    __tmp_try_res_7_6 = zF_35_alloc_bool(res, arena);
    if (__tmp_try_res_7_6.is_error) {
        return __tmp_try_res_7_6;
    }
    __tmp_try_7_5 = __tmp_try_res_7_6.data.payload;
    {
        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_5;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5_Value zF_51_builtin_lt(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
/* DEBUG: emitSwitch start */
    {
        struct zS_5_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case zE_8_Value_Tag_Int:
            {
                /* DEBUG: capture av */
                i64 av;
                av = switch_tmp.data.Int;
{
/* DEBUG: emitSwitch start */
                {
                    struct zS_5_Value switch_tmp_1 = *args.ptr[1];
                    switch (switch_tmp_1.tag) {
                    case zE_8_Value_Tag_Int:
                        {
                            /* DEBUG: capture bv */
                            i64 bv;
                            bv = switch_tmp_1.data.Int;
{
                            struct zS_5_Value* __tmp_try_11_3;
                            ErrorUnion_Ptr_zS_5_Value __tmp_try_res_11_4;
                            __tmp_try_res_11_4 = zF_35_alloc_bool(av < bv, arena);
                            if (__tmp_try_res_11_4.is_error) {
                                return __tmp_try_res_11_4;
                            }
                            __tmp_try_11_3 = __tmp_try_res_11_4.data.payload;
                            {
                                ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                                __return_val.is_error = 0;
                                __return_val.data.payload = __tmp_try_11_3;
                                return __return_val;
                            }
                        }                        }
                        break;
                    default:
{
                        }                        break;
                }
                }
            }            }
            break;
        default:
{
            }            break;
    }
    }
    {
        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_NotAnInt;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5_Value zF_52_builtin_gt(Slice_Ptr_zS_5_Value args, struct zS_3_Sand* arena) {
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_zS_5_Value __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
/* DEBUG: emitSwitch start */
    {
        struct zS_5_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case zE_8_Value_Tag_Int:
            {
                /* DEBUG: capture av */
                i64 av;
                av = switch_tmp.data.Int;
{
/* DEBUG: emitSwitch start */
                {
                    struct zS_5_Value switch_tmp_1 = *args.ptr[1];
                    switch (switch_tmp_1.tag) {
                    case zE_8_Value_Tag_Int:
                        {
                            /* DEBUG: capture bv */
                            i64 bv;
                            bv = switch_tmp_1.data.Int;
{
                            struct zS_5_Value* __tmp_try_11_1;
                            ErrorUnion_Ptr_zS_5_Value __tmp_try_res_11_2;
                            __tmp_try_res_11_2 = zF_35_alloc_bool(av > bv, arena);
                            if (__tmp_try_res_11_2.is_error) {
                                return __tmp_try_res_11_2;
                            }
                            __tmp_try_11_1 = __tmp_try_res_11_2.data.payload;
                            {
                                ErrorUnion_Ptr_zS_5_Value __return_val = {0};
                                __return_val.is_error = 0;
                                __return_val.data.payload = __tmp_try_11_1;
                                return __return_val;
                            }
                        }                        }
                        break;
                    default:
{
                        }                        break;
                }
                }
            }            }
            break;
        default:
{
            }            break;
    }
    }
    {
        ErrorUnion_Ptr_zS_5_Value __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_NotAnInt;
        return __return_val;
    }
}
