#!/bin/sh
set -e
# Build script generated by Z98 bootstrap compiler

gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c zig_runtime.c -o zig_runtime.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c builtin.c -o builtin.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c util.c -o util.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c token.c -o token.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c sand.c -o sand.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c value.c -o value.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c builtins.c -o builtins.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c deep_copy.c -o deep_copy.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c env.c -o env.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c parser.c -o parser.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c eval.c -o eval.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c main.c -o main.o
gcc -m32 -o app zig_runtime.o builtin.o util.o token.o sand.o value.o builtins.o deep_copy.o env.o parser.o eval.o main.o
