/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_OutOfMemory 1
#define ERROR_UnexpectedRParen 2
#define ERROR_UnexpectedEof 3
#define ERROR_UnexpectedToken 4
#define ERROR_InvalidQuote 5
#define ERROR_InvalidIf 6
#define ERROR_InvalidDefine 7
#define ERROR_InvalidLambda 8
#define ERROR_InvalidExpr 9
#define ERROR_NotCallable 10
#define ERROR_InvalidClosure 11
#define ERROR_InvalidEnv 12
#define ERROR_UnboundSymbol 13
#define ERROR_WrongArity 14
#define ERROR_NotACons 15
#define ERROR_NotAnInt 16
#define ERROR_DivisionByZero 17
#define ERROR_InvalidParams 18
#define ERROR_Unreachable 19
#define ERROR_InvalidDigit 20
#define ERROR_TooManyArgs 21
#define ERROR_TooFewArgs 22

#include "sand.h"
#include "util.h"


struct zS_148163_Sand zF_148163_sand_init(Slice_u8 buffer) {
    {
        struct zS_148163_Sand __return_val = {0};
        __return_val.start = buffer.ptr;
        __return_val.pos = 0;
        __return_val.end = buffer.len;
        return __return_val;
    }
}

ErrorUnion_Ptr_u8 zF_148163_sand_alloc(struct zS_148163_Sand* sand, usize size, usize alignment) {
    usize mask;
    usize aligned_pos;
    unsigned char* res;
    mask = alignment - 1;
    aligned_pos = (sand->pos + mask) & ~mask;
    if (aligned_pos + size > sand->end) {
        {
            ErrorUnion_Ptr_u8 __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_OutOfMemory;
            return __return_val;
        }
    }
    res = sand->start + aligned_pos;
    sand->pos = aligned_pos + size;
    {
        ErrorUnion_Ptr_u8 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = res;
        return __return_val;
    }
}

void zF_148163_sand_reset(struct zS_148163_Sand* sand) {
    sand->pos = 0;
}
