/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_OutOfMemory 1
#define ERROR_UnexpectedRParen 2
#define ERROR_UnexpectedEof 3
#define ERROR_UnexpectedToken 4
#define ERROR_InvalidQuote 5
#define ERROR_InvalidIf 6
#define ERROR_InvalidDefine 7
#define ERROR_InvalidLambda 8
#define ERROR_InvalidExpr 9
#define ERROR_NotCallable 10
#define ERROR_InvalidClosure 11
#define ERROR_InvalidEnv 12
#define ERROR_UnboundSymbol 13
#define ERROR_WrongArity 14
#define ERROR_NotACons 15
#define ERROR_NotAnInt 16
#define ERROR_DivisionByZero 17
#define ERROR_InvalidParams 18
#define ERROR_Unreachable 19
#define ERROR_InvalidDigit 20
#define ERROR_TooManyArgs 21
#define ERROR_TooFewArgs 22

#include "value.h"
#include "sand.h"
#include "util.h"


ErrorUnion_Ptr_zS_5ed3ca_Value zF_5ed3ca_alloc_value(struct zS_148163_Sand* arena) {
    unsigned char* __tmp_try_5_13;
    ErrorUnion_Ptr_u8 __tmp_try_res_5_14;
    unsigned char* mem;
    __tmp_try_res_5_14 = zF_148163_sand_alloc(arena, 16, 8);
    if (__tmp_try_res_5_14.is_error) {
        {
            ErrorUnion_Ptr_zS_5ed3ca_Value __return_val = {0};
            __return_val.data.err = __tmp_try_res_5_14.data.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    __tmp_try_5_13 = __tmp_try_res_5_14.data.payload;
    mem = __tmp_try_5_13;
    {
        ErrorUnion_Ptr_zS_5ed3ca_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = (struct zS_5ed3ca_Value*)mem;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5ed3ca_Value zF_5ed3ca_alloc_cons(struct zS_5ed3ca_Value* car, struct zS_5ed3ca_Value* cdr, struct zS_148163_Sand* arena) {
    struct zS_5ed3ca_Value* __tmp_try_5_11;
    ErrorUnion_Ptr_zS_5ed3ca_Value __tmp_try_res_5_12;
    struct zS_5ed3ca_Value* v;
    __tmp_try_res_5_12 = zF_5ed3ca_alloc_value(arena);
    if (__tmp_try_res_5_12.is_error) {
        return __tmp_try_res_5_12;
    }
    __tmp_try_5_11 = __tmp_try_res_5_12.data.payload;
    v = __tmp_try_5_11;
    {
        struct zS_5ed3ca_Value* init_lval_tmp = &(*v);
        (*init_lval_tmp).tag = zE_1a36c1_Value_Tag_Cons;
        (*init_lval_tmp).data.Cons.car = car;
        (*init_lval_tmp).data.Cons.cdr = cdr;
    }
    {
        ErrorUnion_Ptr_zS_5ed3ca_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = v;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5ed3ca_Value zF_5ed3ca_alloc_int(i64 val, struct zS_148163_Sand* arena) {
    struct zS_5ed3ca_Value* __tmp_try_5_9;
    ErrorUnion_Ptr_zS_5ed3ca_Value __tmp_try_res_5_10;
    struct zS_5ed3ca_Value* v;
    __tmp_try_res_5_10 = zF_5ed3ca_alloc_value(arena);
    if (__tmp_try_res_5_10.is_error) {
        return __tmp_try_res_5_10;
    }
    __tmp_try_5_9 = __tmp_try_res_5_10.data.payload;
    v = __tmp_try_5_9;
    {
        struct zS_5ed3ca_Value* init_lval_tmp = &(*v);
        (*init_lval_tmp).tag = zE_1a36c1_Value_Tag_Int;
        (*init_lval_tmp).data.Int = val;
    }
    {
        ErrorUnion_Ptr_zS_5ed3ca_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = v;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5ed3ca_Value zF_5ed3ca_alloc_bool(int val, struct zS_148163_Sand* arena) {
    struct zS_5ed3ca_Value* __tmp_try_5_7;
    ErrorUnion_Ptr_zS_5ed3ca_Value __tmp_try_res_5_8;
    struct zS_5ed3ca_Value* v;
    __tmp_try_res_5_8 = zF_5ed3ca_alloc_value(arena);
    if (__tmp_try_res_5_8.is_error) {
        return __tmp_try_res_5_8;
    }
    __tmp_try_5_7 = __tmp_try_res_5_8.data.payload;
    v = __tmp_try_5_7;
    {
        struct zS_5ed3ca_Value* init_lval_tmp = &(*v);
        (*init_lval_tmp).tag = zE_1a36c1_Value_Tag_Bool;
        (*init_lval_tmp).data.Bool = val;
    }
    {
        ErrorUnion_Ptr_zS_5ed3ca_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = v;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5ed3ca_Value zF_5ed3ca_alloc_symbol(Slice_u8 name, struct zS_148163_Sand* arena) {
    struct zS_5ed3ca_Value* __tmp_try_5_5;
    ErrorUnion_Ptr_zS_5ed3ca_Value __tmp_try_res_5_6;
    struct zS_5ed3ca_Value* v;
    __tmp_try_res_5_6 = zF_5ed3ca_alloc_value(arena);
    if (__tmp_try_res_5_6.is_error) {
        return __tmp_try_res_5_6;
    }
    __tmp_try_5_5 = __tmp_try_res_5_6.data.payload;
    v = __tmp_try_5_5;
    {
        struct zS_5ed3ca_Value* init_lval_tmp = &(*v);
        (*init_lval_tmp).tag = zE_1a36c1_Value_Tag_Symbol;
        (*init_lval_tmp).data.Symbol = name;
    }
    {
        ErrorUnion_Ptr_zS_5ed3ca_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = v;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5ed3ca_Value zF_5ed3ca_alloc_nil(struct zS_148163_Sand* arena) {
    struct zS_5ed3ca_Value* __tmp_try_5_3;
    ErrorUnion_Ptr_zS_5ed3ca_Value __tmp_try_res_5_4;
    struct zS_5ed3ca_Value* v;
    __tmp_try_res_5_4 = zF_5ed3ca_alloc_value(arena);
    if (__tmp_try_res_5_4.is_error) {
        return __tmp_try_res_5_4;
    }
    __tmp_try_5_3 = __tmp_try_res_5_4.data.payload;
    v = __tmp_try_5_3;
    {
        struct zS_5ed3ca_Value* init_lval_tmp = &(*v);
        (*init_lval_tmp).tag = zE_1a36c1_Value_Tag_Nil;
    }
    {
        ErrorUnion_Ptr_zS_5ed3ca_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = v;
        return __return_val;
    }
}

ErrorUnion_Ptr_zS_5ed3ca_Value zF_5ed3ca_alloc_builtin(void * f, struct zS_148163_Sand* arena) {
    struct zS_5ed3ca_Value* __tmp_try_5_1;
    ErrorUnion_Ptr_zS_5ed3ca_Value __tmp_try_res_5_2;
    struct zS_5ed3ca_Value* v;
    __tmp_try_res_5_2 = zF_5ed3ca_alloc_value(arena);
    if (__tmp_try_res_5_2.is_error) {
        return __tmp_try_res_5_2;
    }
    __tmp_try_5_1 = __tmp_try_res_5_2.data.payload;
    v = __tmp_try_5_1;
    {
        struct zS_5ed3ca_Value* init_lval_tmp = &(*v);
        (*init_lval_tmp).tag = zE_1a36c1_Value_Tag_Builtin;
        (*init_lval_tmp).data.Builtin = f;
    }
    {
        ErrorUnion_Ptr_zS_5ed3ca_Value __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = v;
        return __return_val;
    }
}
