@echo off
:: Build script generated by RetroZig bootstrap compiler
:: Optimized for MSVC 6.0 on Windows 98

cl.exe /nologo /W3 /I. /c zig_runtime.c
cl.exe /nologo /W3 /I. /c builtin.c
cl.exe /nologo /W3 /I. /c test.c
link.exe /nologo /out:app.exe *.obj
