/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OpenFailed 1
#define ERROR_ReadFailed 2
#define ERROR_SeekFailed 3
#define ERROR_TooLarge 4
#define ERROR_InvalidSyntax 5
#define ERROR_UnexpectedEnd 6
#define ERROR_ExpectedValue 7
#define ERROR_ExpectedKey 8
#define ERROR_ExpectedColon 9
#define ERROR_ExpectedCommaOrEnd 10
#define ERROR_OutOfMemory 11

#include "main.h"
#include "file.h"
#include "json.h"


#ifndef ZIG_SLICE_Slice_z_json_JsonValue
#define ZIG_SLICE_Slice_z_json_JsonValue
typedef struct { struct z_json_JsonValue* ptr; usize len; } Slice_z_json_JsonValue;
static RETR_UNUSED_FUNC Slice_z_json_JsonValue __make_slice_z_json_JsonValue(struct z_json_JsonValue* ptr, usize len) {
    Slice_z_json_JsonValue s;
    s.ptr = ptr;
    s.len = len;
    return s;
}
#endif

#ifndef ZIG_SLICE_Slice_z_json_JsonObjectEntry
#define ZIG_SLICE_Slice_z_json_JsonObjectEntry
typedef struct { struct z_json_JsonObjectEntry* ptr; usize len; } Slice_z_json_JsonObjectEntry;
static RETR_UNUSED_FUNC Slice_z_json_JsonObjectEntry __make_slice_z_json_JsonObjectEntry(struct z_json_JsonObjectEntry* ptr, usize len) {
    Slice_z_json_JsonObjectEntry s;
    s.ptr = ptr;
    s.len = len;
    return s;
}
#endif

#ifndef ZIG_SLICE_Slice_u8
#define ZIG_SLICE_Slice_u8
typedef struct { unsigned char* ptr; usize len; } Slice_u8;
static RETR_UNUSED_FUNC Slice_u8 __make_slice_u8(unsigned char* ptr, usize len) {
    Slice_u8 s;
    s.ptr = ptr;
    s.len = len;
    return s;
}
#endif

#ifndef ZIG_ERRORUNION_ErrorUnion_Slice_u8
#define ZIG_ERRORUNION_ErrorUnion_Slice_u8
typedef struct {
    union {
        Slice_u8 payload;
        int err;
    } data;
    int is_error;
} ErrorUnion_Slice_u8;
#endif

#ifndef ZIG_ERRORUNION_ErrorUnion_z_json_JsonValue
#define ZIG_ERRORUNION_ErrorUnion_z_json_JsonValue
typedef struct {
    union {
        struct z_json_JsonValue payload;
        int err;
    } data;
    int is_error;
} ErrorUnion_z_json_JsonValue;
#endif

extern struct Arena* zig_default_arena;
void __bootstrap_write(unsigned char const*, usize);
static void printIndent(usize);
static void printValue(struct z_json_JsonValue, usize);

void __bootstrap_print(unsigned char const* s);

extern void __bootstrap_write(unsigned char const* s, usize len);

void __bootstrap_print_int(int i);

static void printIndent(usize level) {
    usize i;
    i = 0;
    while (i < level) {
        unsigned char const* space;
        space = "  ";
        __bootstrap_print(space);
        i += 1;
    }
}

static void printValue(struct z_json_JsonValue val, usize level) {
    if (val.tag == z_json_JsonValueTag_Null) {
        unsigned char const* null_ptr;
        null_ptr = "null";
        __bootstrap_print(null_ptr);
    } else     if (val.tag == z_json_JsonValueTag_Boolean) {
        if (val.data.boolean) {
            unsigned char const* true_ptr;
            true_ptr = "true";
            __bootstrap_print(true_ptr);
        } else {
            unsigned char const* false_ptr;
            false_ptr = "false";
            __bootstrap_print(false_ptr);
        }
    } else     if (val.tag == z_json_JsonValueTag_Number) {
        unsigned char const* num_ptr;
        num_ptr = "<number>";
        __bootstrap_print(num_ptr);
    } else     if (val.tag == z_json_JsonValueTag_String) {
        unsigned char const* quote_ptr;
        quote_ptr = "\"";
        __bootstrap_print(quote_ptr);
        __bootstrap_write(val.data.string.ptr, val.data.string.len);
        __bootstrap_print(quote_ptr);
    } else     if (val.tag == z_json_JsonValueTag_Array) {
        unsigned char const* lbr_ptr;
        Slice_z_json_JsonValue arr;
        unsigned char const* rbr_ptr;
        lbr_ptr = "[";
        __bootstrap_print(lbr_ptr);
        arr = val.data.array;
        if (arr.len > 0) {
            unsigned char const* nl_ptr;
            usize i;
            nl_ptr = "\n";
            __bootstrap_print(nl_ptr);
            i = 0;
            while (i < arr.len) {
                unsigned char const* nl2_ptr;
                printIndent(level + 1);
                printValue(arr.ptr[i], level + 1);
                if (i < arr.len - 1) {
                    unsigned char const* comma_ptr;
                    comma_ptr = ",";
                    __bootstrap_print(comma_ptr);
                }
                nl2_ptr = "\n";
                __bootstrap_print(nl2_ptr);
                i += 1;
            }
            printIndent(level);
        }
        rbr_ptr = "]";
        __bootstrap_print(rbr_ptr);
    } else     if (val.tag == z_json_JsonValueTag_Object) {
        unsigned char const* lbr_ptr_1;
        Slice_z_json_JsonObjectEntry obj;
        unsigned char const* rbr_ptr_1;
        lbr_ptr_1 = "{";
        __bootstrap_print(lbr_ptr_1);
        obj = val.data.object;
        if (obj.len > 0) {
            unsigned char const* nl_ptr_1;
            usize i_1;
            nl_ptr_1 = "\n";
            __bootstrap_print(nl_ptr_1);
            i_1 = 0;
            while (i_1 < obj.len) {
                unsigned char const* quote_ptr_1;
                unsigned char const* sep_ptr;
                struct z_json_JsonValue* inner_ptr;
                unsigned char const* nl2_ptr_1;
                printIndent(level + 1);
                quote_ptr_1 = "\"";
                __bootstrap_print(quote_ptr_1);
                __bootstrap_write(obj.ptr[i_1].key.ptr, obj.ptr[i_1].key.len);
                sep_ptr = "\": ";
                __bootstrap_print(sep_ptr);
                inner_ptr = obj.ptr[i_1].value;
                printValue(*inner_ptr, level + 1);
                if (i_1 < obj.len - 1) {
                    unsigned char const* comma_ptr_1;
                    comma_ptr_1 = ",";
                    __bootstrap_print(comma_ptr_1);
                }
                nl2_ptr_1 = "\n";
                __bootstrap_print(nl2_ptr_1);
                i_1 += 1;
            }
            printIndent(level);
        }
        rbr_ptr_1 = "}";
        __bootstrap_print(rbr_ptr_1);
    }





}

int main(int argc, char* argv[]) {
    struct Arena* arena_ptr;
    Slice_u8 __tmp_catch_5_3;
    ErrorUnion_Slice_u8 __tmp_catch_res_5_4;
    Slice_u8 content;
    struct z_json_JsonValue __tmp_catch_5_1;
    ErrorUnion_z_json_JsonValue __tmp_catch_res_5_2;
    struct z_json_JsonValue parsed;
    unsigned char const* nl2_ptr;
    arena_ptr = zig_default_arena;
    __tmp_catch_res_5_4 = z_file_readFile(arena_ptr, __make_slice_u8("test.json", 9));
    if (__tmp_catch_res_5_4.is_error) {
        int err;
        err = __tmp_catch_res_5_4.data.err;
        {
            unsigned char const* err_msg;
            unsigned char const* nl_ptr;
            err_msg = "Error reading file: ";
            __bootstrap_print(err_msg);
            __bootstrap_print_int((int)err);
            nl_ptr = "\n";
            __bootstrap_print(nl_ptr);
            return 0;
        }
    } else {
        __tmp_catch_5_3 = __tmp_catch_res_5_4.data.payload;
    }
    content = __tmp_catch_5_3;
    __tmp_catch_res_5_2 = z_json_parseJson(arena_ptr, content);
    if (__tmp_catch_res_5_2.is_error) {
        int err_1;
        err_1 = __tmp_catch_res_5_2.data.err;
        {
            unsigned char const* parse_msg;
            unsigned char const* nl_ptr_1;
            parse_msg = "Parse error: ";
            __bootstrap_print(parse_msg);
            __bootstrap_print_int((int)err_1);
            nl_ptr_1 = "\n";
            __bootstrap_print(nl_ptr_1);
            return 0;
        }
    } else {
        __tmp_catch_5_1 = __tmp_catch_res_5_2.data.payload;
    }
    parsed = __tmp_catch_5_1;
    printValue(parsed, 0);
    nl2_ptr = "\n";
    __bootstrap_print(nl2_ptr);
    return 0;
}
