/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "allocator.h"


struct zS_26b5a9a4_43f95de6_Sand zF_26b5a9a4_3b926c3f_sandInit(Slice_u8 buf) {
    struct zS_26b5a9a4_43f95de6_Sand s;
    usize used;
    s.start = buf.ptr;
    s.pos = 0;
    s.end = buf.len;
    s.peak = 0;
    used = s.pos;
    if (used > s.peak) {
        s.peak = used;
    }
    return s;
}

ErrorUnion_Ptr_u8 zF_26b5a9a4_6fa59c42_sandAlloc(struct zS_26b5a9a4_43f95de6_Sand* sand, usize size, usize alignment) {
    usize mask;
    usize aligned;
    usize new_pos;
    unsigned char* result;
    mask = alignment - 1;
    aligned = (sand->pos + mask) & ~mask;
    new_pos = aligned + size;
    if (new_pos > sand->end) {
        {
            ErrorUnion_Ptr_u8 __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_OutOfMemory;
            return __return_val;
        }
    }
    result = sand->start + aligned;
    sand->pos = new_pos;
    if (new_pos > sand->peak) {
        sand->peak = new_pos;
    }
    {
        ErrorUnion_Ptr_u8 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = result;
        return __return_val;
    }
}

void zF_26b5a9a4_abb8d26c_sandReset(struct zS_26b5a9a4_43f95de6_Sand* sand) {
    sand->pos = 0;
}

struct zS_26b5a9a4_d34e314a_CompilerAlloc zF_26b5a9a4_61b35879_initCompilerAlloc(void) {
    unsigned char perm_buf[1048576];
    unsigned char mod_buf[524288];
    unsigned char scr_buf[262144];
    {
        struct zS_26b5a9a4_d34e314a_CompilerAlloc __return_val = {0};
        __return_val.permanent = zF_26b5a9a4_3b926c3f_sandInit(__make_slice_u8(&perm_buf[0], 1048576 - 0));
        __return_val.module = zF_26b5a9a4_3b926c3f_sandInit(__make_slice_u8(&mod_buf[0], 524288 - 0));
        __return_val.scratch = zF_26b5a9a4_3b926c3f_sandInit(__make_slice_u8(&scr_buf[0], 262144 - 0));
        __return_val.max_mem = __bootstrap_u32_from_i32(16 * 1024 * 1024);
        return __return_val;
    }
}

void zF_26b5a9a4_23996229_checkCombinedPeak(struct zS_26b5a9a4_d34e314a_CompilerAlloc* alloc) {
    unsigned int total;
    total = (unsigned int)alloc->permanent.peak + alloc->module.peak + alloc->scratch.peak;
    if (total > alloc->max_mem) {
        __loop_0_start: ;
        if (!(1)) goto __loop_0_end;
        {
        }
        goto __loop_0_start;
        __loop_0_end: ;
    }
}

struct zS_26b5a9a4_ac61a78a_TrackingAllocator zF_26b5a9a4_b3747739_trackingAllocatorInit(struct zS_26b5a9a4_43f95de6_Sand* arena) {
    {
        struct zS_26b5a9a4_ac61a78a_TrackingAllocator __return_val = {0};
        __return_val.arena = arena;
        __return_val.total_allocated = 0U;
        __return_val.peak_allocated = 0U;
        __return_val.allocation_count = 0U;
        return __return_val;
    }
}

ErrorUnion_Ptr_u8 zF_26b5a9a4_322d8837_trackingAlloc(struct zS_26b5a9a4_ac61a78a_TrackingAllocator* tracker, usize size, usize alignment) {
    unsigned char* __tmp_try_5_1;
    ErrorUnion_Ptr_u8 __tmp_try_res_5_2;
    unsigned char* ptr;
    __tmp_try_res_5_2 = zF_26b5a9a4_6fa59c42_sandAlloc(tracker->arena, size, alignment);
    if (__tmp_try_res_5_2.is_error) {
        return __tmp_try_res_5_2;
    }
    __tmp_try_5_1 = __tmp_try_res_5_2.data.payload;
    ptr = __tmp_try_5_1;
    (void)(tracker->allocation_count += 1);
    (void)(tracker->total_allocated += (unsigned int)size);
    if (tracker->total_allocated > tracker->peak_allocated) {
        tracker->peak_allocated = tracker->total_allocated;
    }
    {
        ErrorUnion_Ptr_u8 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = ptr;
        return __return_val;
    }
}

void zF_26b5a9a4_11308219_trackingReset(struct zS_26b5a9a4_ac61a78a_TrackingAllocator* tracker) {
    zF_26b5a9a4_abb8d26c_sandReset(tracker->arena);
    tracker->total_allocated = 0U;
}

unsigned int zF_26b5a9a4_80c485d5_trackingPeak(struct zS_26b5a9a4_ac61a78a_TrackingAllocator* tracker) {
    return tracker->peak_allocated;
}
