@echo off
:: Build script generated by Z98 bootstrap compiler
:: Optimized for MinGW

:: NOTE: If you get "undefined reference to WinMain@16" errors,
:: try removing the -mconsole flag from the linking step.

gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c zig_runtime.c -o zig_runtime.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c net_runtime.c -o net_runtime.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c builtin.c -o builtin.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c allocator.c -o allocator.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c hash.c -o hash.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c mem.c -o mem.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c util.c -o util.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c pal.c -o pal.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c name_mangler.c -o name_mangler.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c growable_array.c -o growable_array.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c token.c -o token.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c source_manager.c -o source_manager.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c string_interner.c -o string_interner.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c diagnostics.c -o diagnostics.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c lexer.c -o lexer.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c main.c -o main.o
gcc -m32 -mconsole -static-libgcc -o app.exe zig_runtime.o net_runtime.o builtin.o allocator.o hash.o mem.o util.o pal.o name_mangler.o growable_array.o token.o source_manager.o string_interner.o diagnostics.o lexer.o main.o 
