@echo off
:: Build script generated by Z98 bootstrap compiler
:: Optimized for MinGW 3.x on Windows 98

g++ -std=c++98 -m32 -mconsole -static-libgcc -Isrc/include src/bootstrap/bootstrap_all.cpp -o zig0.exe -lwsock32
