@echo off
:: Build script generated by Z98 bootstrap compiler
:: Optimized for MinGW

:: NOTE: If you get "undefined reference to WinMain@16" errors,
:: try removing the -mconsole flag from the linking step.

gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c zig_runtime.c -o zig_runtime.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c builtin.c -o builtin.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c hello.c -o hello.o
gcc -m32 -mconsole -static-libgcc -o app.exe zig_runtime.o builtin.o hello.o
