/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "lexer_tests.h"
#include "pal.h"
#include "allocator.h"
#include "string_interner.h"
#include "mem.h"
#include "source_manager.h"
#include "diagnostics.h"
#include "token.h"
#include "lexer.h"


struct zS_26b5a9a4_43f95de6_Sand;
struct zS_4c1e99d4_67d40cc9_StringInterner;
struct zS_2b6fc0a6_29be27be_SourceManager;
struct zS_9daadfc5_490018d3_DiagnosticCollector;
struct zS_89baa7c0_7a3512d8_Token;
#ifndef ZIG_ENUM_zS_89baa7c0_facdb0ca_TokenKind
#define ZIG_ENUM_zS_89baa7c0_facdb0ca_TokenKind
enum zS_89baa7c0_facdb0ca_TokenKind {
    zS_89baa7c0_facdb0ca_TokenKind_integer_literal = 0,
    zS_89baa7c0_facdb0ca_TokenKind_float_literal = 1,
    zS_89baa7c0_facdb0ca_TokenKind_string_literal = 2,
    zS_89baa7c0_facdb0ca_TokenKind_char_literal = 3,
    zS_89baa7c0_facdb0ca_TokenKind_identifier = 4,
    zS_89baa7c0_facdb0ca_TokenKind_builtin_identifier = 5,
    zS_89baa7c0_facdb0ca_TokenKind_lparen = 6,
    zS_89baa7c0_facdb0ca_TokenKind_rparen = 7,
    zS_89baa7c0_facdb0ca_TokenKind_lbracket = 8,
    zS_89baa7c0_facdb0ca_TokenKind_rbracket = 9,
    zS_89baa7c0_facdb0ca_TokenKind_lbrace = 10,
    zS_89baa7c0_facdb0ca_TokenKind_rbrace = 11,
    zS_89baa7c0_facdb0ca_TokenKind_semicolon = 12,
    zS_89baa7c0_facdb0ca_TokenKind_colon = 13,
    zS_89baa7c0_facdb0ca_TokenKind_comma = 14,
    zS_89baa7c0_facdb0ca_TokenKind_dot = 15,
    zS_89baa7c0_facdb0ca_TokenKind_at_sign = 16,
    zS_89baa7c0_facdb0ca_TokenKind_underscore = 17,
    zS_89baa7c0_facdb0ca_TokenKind_question_mark = 18,
    zS_89baa7c0_facdb0ca_TokenKind_bang = 19,
    zS_89baa7c0_facdb0ca_TokenKind_plus = 20,
    zS_89baa7c0_facdb0ca_TokenKind_minus = 21,
    zS_89baa7c0_facdb0ca_TokenKind_star = 22,
    zS_89baa7c0_facdb0ca_TokenKind_slash = 23,
    zS_89baa7c0_facdb0ca_TokenKind_percent = 24,
    zS_89baa7c0_facdb0ca_TokenKind_ampersand = 25,
    zS_89baa7c0_facdb0ca_TokenKind_pipe = 26,
    zS_89baa7c0_facdb0ca_TokenKind_caret = 27,
    zS_89baa7c0_facdb0ca_TokenKind_tilde = 28,
    zS_89baa7c0_facdb0ca_TokenKind_shl = 29,
    zS_89baa7c0_facdb0ca_TokenKind_shr = 30,
    zS_89baa7c0_facdb0ca_TokenKind_eq_eq = 31,
    zS_89baa7c0_facdb0ca_TokenKind_bang_eq = 32,
    zS_89baa7c0_facdb0ca_TokenKind_less = 33,
    zS_89baa7c0_facdb0ca_TokenKind_less_eq = 34,
    zS_89baa7c0_facdb0ca_TokenKind_greater = 35,
    zS_89baa7c0_facdb0ca_TokenKind_greater_eq = 36,
    zS_89baa7c0_facdb0ca_TokenKind_eq = 37,
    zS_89baa7c0_facdb0ca_TokenKind_plus_eq = 38,
    zS_89baa7c0_facdb0ca_TokenKind_minus_eq = 39,
    zS_89baa7c0_facdb0ca_TokenKind_star_eq = 40,
    zS_89baa7c0_facdb0ca_TokenKind_slash_eq = 41,
    zS_89baa7c0_facdb0ca_TokenKind_percent_eq = 42,
    zS_89baa7c0_facdb0ca_TokenKind_ampersand_eq = 43,
    zS_89baa7c0_facdb0ca_TokenKind_pipe_eq = 44,
    zS_89baa7c0_facdb0ca_TokenKind_caret_eq = 45,
    zS_89baa7c0_facdb0ca_TokenKind_shl_eq = 46,
    zS_89baa7c0_facdb0ca_TokenKind_shr_eq = 47,
    zS_89baa7c0_facdb0ca_TokenKind_dot_dot = 48,
    zS_89baa7c0_facdb0ca_TokenKind_dot_dot_dot = 49,
    zS_89baa7c0_facdb0ca_TokenKind_dot_lbrace = 50,
    zS_89baa7c0_facdb0ca_TokenKind_dot_star = 51,
    zS_89baa7c0_facdb0ca_TokenKind_fat_arrow = 52,
    zS_89baa7c0_facdb0ca_TokenKind_kw_const = 53,
    zS_89baa7c0_facdb0ca_TokenKind_kw_var = 54,
    zS_89baa7c0_facdb0ca_TokenKind_kw_fn = 55,
    zS_89baa7c0_facdb0ca_TokenKind_kw_pub = 56,
    zS_89baa7c0_facdb0ca_TokenKind_kw_extern = 57,
    zS_89baa7c0_facdb0ca_TokenKind_kw_export = 58,
    zS_89baa7c0_facdb0ca_TokenKind_kw_test = 59,
    zS_89baa7c0_facdb0ca_TokenKind_kw_struct = 60,
    zS_89baa7c0_facdb0ca_TokenKind_kw_enum = 61,
    zS_89baa7c0_facdb0ca_TokenKind_kw_union = 62,
    zS_89baa7c0_facdb0ca_TokenKind_kw_if = 63,
    zS_89baa7c0_facdb0ca_TokenKind_kw_else = 64,
    zS_89baa7c0_facdb0ca_TokenKind_kw_while = 65,
    zS_89baa7c0_facdb0ca_TokenKind_kw_for = 66,
    zS_89baa7c0_facdb0ca_TokenKind_kw_switch = 67,
    zS_89baa7c0_facdb0ca_TokenKind_kw_return = 68,
    zS_89baa7c0_facdb0ca_TokenKind_kw_break = 69,
    zS_89baa7c0_facdb0ca_TokenKind_kw_continue = 70,
    zS_89baa7c0_facdb0ca_TokenKind_kw_defer = 71,
    zS_89baa7c0_facdb0ca_TokenKind_kw_errdefer = 72,
    zS_89baa7c0_facdb0ca_TokenKind_kw_try = 73,
    zS_89baa7c0_facdb0ca_TokenKind_kw_catch = 74,
    zS_89baa7c0_facdb0ca_TokenKind_kw_orelse = 75,
    zS_89baa7c0_facdb0ca_TokenKind_kw_error = 76,
    zS_89baa7c0_facdb0ca_TokenKind_kw_and = 77,
    zS_89baa7c0_facdb0ca_TokenKind_kw_or = 78,
    zS_89baa7c0_facdb0ca_TokenKind_kw_true = 79,
    zS_89baa7c0_facdb0ca_TokenKind_kw_false = 80,
    zS_89baa7c0_facdb0ca_TokenKind_kw_null = 81,
    zS_89baa7c0_facdb0ca_TokenKind_kw_undefined = 82,
    zS_89baa7c0_facdb0ca_TokenKind_kw_unreachable = 83,
    zS_89baa7c0_facdb0ca_TokenKind_kw_void = 84,
    zS_89baa7c0_facdb0ca_TokenKind_kw_bool = 85,
    zS_89baa7c0_facdb0ca_TokenKind_kw_noreturn = 86,
    zS_89baa7c0_facdb0ca_TokenKind_kw_c_char = 87,
    zS_89baa7c0_facdb0ca_TokenKind_eof = 88,
    zS_89baa7c0_facdb0ca_TokenKind_err_token = 89
};
typedef enum zS_89baa7c0_facdb0ca_TokenKind zS_89baa7c0_facdb0ca_TokenKind;

#endif /* ZIG_ENUM_zS_89baa7c0_facdb0ca_TokenKind */

union zS_89baa7c0_39b0b709_TokenValue;
struct zS_a012675f_c8a65756_Lexer;
#ifndef ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
#define ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
struct zS_26b5a9a4_43f95de6_Sand {
    unsigned char* start;
    usize pos;
    usize end;
    usize peak;
};

#endif /* ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand */

#ifndef ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner
#define ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner
struct zS_4c1e99d4_67d40cc9_StringInterner {
    struct zS_16d7ab7a_840ccd30_U32ArrayList* buckets;
    struct zS_4c1e99d4_face28fc_InternArrayList* entries;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner */

#ifndef ZIG_STRUCT_zS_2b6fc0a6_29be27be_SourceManager
#define ZIG_STRUCT_zS_2b6fc0a6_29be27be_SourceManager
struct zS_2b6fc0a6_29be27be_SourceManager {
    struct zS_2b6fc0a6_c93555ae_SourceFileArrayList* files;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_2b6fc0a6_29be27be_SourceManager */

#ifndef ZIG_STRUCT_zS_9daadfc5_490018d3_DiagnosticCollector
#define ZIG_STRUCT_zS_9daadfc5_490018d3_DiagnosticCollector
struct zS_9daadfc5_490018d3_DiagnosticCollector {
    struct zS_9daadfc5_8924c34d_DiagnosticArrayList* diagnostics;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
    struct zS_2b6fc0a6_29be27be_SourceManager* source_manager;
    struct zS_4c1e99d4_67d40cc9_StringInterner* interner;
    usize error_count;
    usize warning_count;
    usize max_diagnostics;
};

#endif /* ZIG_STRUCT_zS_9daadfc5_490018d3_DiagnosticCollector */

#ifndef ZIG_STRUCT_zS_89baa7c0_7a3512d8_Token
#define ZIG_STRUCT_zS_89baa7c0_7a3512d8_Token
struct zS_89baa7c0_7a3512d8_Token {
    enum zS_89baa7c0_facdb0ca_TokenKind kind;
    unsigned int span_start;
    unsigned short span_len;
    union zS_89baa7c0_39b0b709_TokenValue value;
};

#endif /* ZIG_STRUCT_zS_89baa7c0_7a3512d8_Token */

#ifndef ZIG_UNION_zS_89baa7c0_39b0b709_TokenValue
#define ZIG_UNION_zS_89baa7c0_39b0b709_TokenValue
union zS_89baa7c0_39b0b709_TokenValue {
    u64 int_val;
    double float_val;
    unsigned int string_id;
};

#endif /* ZIG_UNION_zS_89baa7c0_39b0b709_TokenValue */

#ifndef ZIG_STRUCT_zS_a012675f_c8a65756_Lexer
#define ZIG_STRUCT_zS_a012675f_c8a65756_Lexer
struct zS_a012675f_c8a65756_Lexer {
    Slice_u8 source;
    usize pos;
    unsigned int line;
    unsigned int col;
    unsigned int file_id;
    struct zS_4c1e99d4_67d40cc9_StringInterner* interner;
    struct zS_9daadfc5_490018d3_DiagnosticCollector* diag;
    struct zS_16d7ab7a_95cf740f_U8ArrayList* string_buf;
};

#endif /* ZIG_STRUCT_zS_a012675f_c8a65756_Lexer */

static unsigned char zV_0e44da37_88984050_arena_buf[32768];
static struct zS_26b5a9a4_43f95de6_Sand zV_0e44da37_238d96d9_sand;
static struct zS_4c1e99d4_67d40cc9_StringInterner zV_0e44da37_473bb154_interner;
static struct zS_2b6fc0a6_29be27be_SourceManager zV_0e44da37_7b335cb5_source_man;
static struct zS_9daadfc5_490018d3_DiagnosticCollector zV_0e44da37_3d8db5b8_diag;
static void zF_0e44da37_1aabccf3_initTestHarness(void);
static struct zS_a012675f_c8a65756_Lexer zF_0e44da37_ee308f0d_makeLexer(Slice_u8);
static void zF_0e44da37_950a9ba8_assertEqU64(u64, u64, unsigned int);
static void zF_0e44da37_04dfdc16_assertEqString(Slice_u8, unsigned int, unsigned int);
static Slice_u8 zF_0e44da37_10ab4fb9_formatU64(u64, Slice_u8, usize);
static void zF_0e44da37_6d869952_assertEqTokenKind(enum zS_89baa7c0_facdb0ca_TokenKind, enum zS_89baa7c0_facdb0ca_TokenKind, unsigned int);
static Slice_u8 zF_0e44da37_989f59de_formatU32(unsigned int, Slice_u8, usize);
static enum zS_89baa7c0_facdb0ca_TokenKind zF_0e44da37_d106041c_nextKind(struct zS_a012675f_c8a65756_Lexer*);
static struct zS_89baa7c0_7a3512d8_Token zF_0e44da37_c201aaaf_nextToken(struct zS_a012675f_c8a65756_Lexer*);
static void zF_0e44da37_5ba4803d_testIntegerOverflow(void);
static void zF_0e44da37_a98aac63_testFloatBasic(void);
static void zF_0e44da37_eabb1a7a_testFloatScientific(void);
static void zF_0e44da37_9b41aea8_testFloatNoFrac(void);
static void zF_0e44da37_94287773_testShiftOps(void);
static void zF_0e44da37_9053f59b_testFatArrow(void);
static void zF_0e44da37_e77424ef_testEqVariants(void);
static void zF_0e44da37_96bff60b_testBuiltinImport(void);
static void zF_0e44da37_c8464162_testBareAt(void);
static void zF_0e44da37_400a05ff_testBareUnderscore(void);
static void zF_0e44da37_43386fcf_testUnderscoreIdent(void);
static void zF_0e44da37_1918d290_testWhitespaceOnly(void);
static void zF_0e44da37_070b7ca1_testNestedComment(void);
static void zF_0e44da37_74a4aa3a_testUnterminatedComment(void);
static void zF_0e44da37_05e728d8_testStringBasic(void);
static void zF_0e44da37_ffa4604c_testCharEmpty(void);
static void zF_0e44da37_1ab89ec4_testStringUnterminated(void);
static void zF_0e44da37_ca0c345a_testStringEscapeHex(void);
static void zF_0e44da37_6c15e7ca_testBlockComments(void);
static void zF_0e44da37_8254a6f7_testLineComments(void);
static void zF_0e44da37_e460329e_testNumberSeparators(void);
static void zF_0e44da37_a1ccd837_testIntegerEdgeCases(void);
static void zF_0e44da37_4f9598c3_testFloatEdgeCases(void);
static void zF_0e44da37_8f399f31_testStringEscapeSequences(void);
static void zF_0e44da37_08f898ba_testCharEscapeSequences(void);
static void zF_0e44da37_fdba4d79_testEofBoundary(void);
static void zF_0e44da37_5c193e8e_testAllKeywords(void);
static void zF_0e44da37_c2ab0d40_testDotVariants(void);
static void zF_0e44da37_bb2610e6_testMultiTokenRecovery(void);
static void zF_0e44da37_38a75d39_testUnrecognizedChars(void);
static void zF_0e44da37_cbf6f1f8_testSwitchMultiProng(void);
static void zF_0e44da37_6543ac7f_testSwitchCapture(void);
static void zF_0e44da37_6970254f_testTryExpr(void);
static void zF_0e44da37_25805b5e_testErrorLiteral(void);
static void zF_0e44da37_887b5fc0_testNestedSwitch(void);
static void zF_0e44da37_b9b871e3_testIfExpr(void);
static void zF_0e44da37_818f24cd_testBuiltinCast(void);
static void zF_0e44da37_6c6918cc_testSliceSyntax(void);
static void zF_0e44da37_c5310d87_testOptionalCapture(void);
static void zF_0e44da37_d4542ab3_testDerefField(void);
static void zF_0e44da37_b03e0029_testIntegrationMandelbrot(void);
static void zF_0e44da37_3228c192_testIntegrationGameOfLife(void);
static void zF_0e44da37_ab23956f_testIntegrationMud(void);

static void zF_0e44da37_1aabccf3_initTestHarness(void) {
    zV_0e44da37_238d96d9_sand = zF_26b5a9a4_3b926c3f_sandInit(__make_slice_u8(&zV_0e44da37_88984050_arena_buf[0], 32768 - 0));
    zV_0e44da37_473bb154_interner = zF_4c1e99d4_610165ac_stringInternerInit(&zV_0e44da37_238d96d9_sand, 4);
    zV_0e44da37_7b335cb5_source_man = zF_2b6fc0a6_b845e969_sourceManagerInit(&zV_0e44da37_238d96d9_sand);
    zV_0e44da37_3d8db5b8_diag = zF_9daadfc5_178b11e8_diagnosticCollectorInit(&zV_0e44da37_238d96d9_sand, &zV_0e44da37_7b335cb5_source_man, &zV_0e44da37_473bb154_interner);
}

static struct zS_a012675f_c8a65756_Lexer zF_0e44da37_ee308f0d_makeLexer(Slice_u8 src) {
    return zF_a012675f_e7d69f49_lexerInit(src, 0, &zV_0e44da37_473bb154_interner, &zV_0e44da37_3d8db5b8_diag, &zV_0e44da37_238d96d9_sand);
}

static void zF_0e44da37_950a9ba8_assertEqU64(u64 expected, u64 actual, unsigned int line) {
    if (expected != actual) {
        unsigned char fmt_buf[24];
        Slice_u8 s_fail;
        Slice_u8 s_sp;
        Slice_u8 s_got;
        Slice_u8 s_nl;
        s_fail = __make_slice_u8("FAIL line ", 10);
        zF_6873a254_1dc3fa43_stderr_write(s_fail);
        zF_6873a254_1dc3fa43_stderr_write(zF_0e44da37_989f59de_formatU32(line, __make_slice_u8(&fmt_buf[0], 24 - 0), 24));
        s_sp = __make_slice_u8(" ", 1);
        zF_6873a254_1dc3fa43_stderr_write(s_sp);
        zF_6873a254_1dc3fa43_stderr_write(zF_0e44da37_10ab4fb9_formatU64(expected, __make_slice_u8(&fmt_buf[0], 24 - 0), 24));
        s_got = __make_slice_u8(" != ", 4);
        zF_6873a254_1dc3fa43_stderr_write(s_got);
        zF_6873a254_1dc3fa43_stderr_write(zF_0e44da37_10ab4fb9_formatU64(actual, __make_slice_u8(&fmt_buf[0], 24 - 0), 24));
        s_nl = __make_slice_u8("\n", 1);
        zF_6873a254_1dc3fa43_stderr_write(s_nl);
    }
}

static void zF_0e44da37_04dfdc16_assertEqString(Slice_u8 expected, unsigned int actual_id, unsigned int line) {
    if (!zF_edc59eed_700ff121_mem_eql(expected, zF_4c1e99d4_a62bda52_stringInternerGet(&zV_0e44da37_473bb154_interner, actual_id))) {
        unsigned char fmt_buf[24];
        Slice_u8 s_fail;
        Slice_u8 s_msg;
        s_fail = __make_slice_u8("FAIL line ", 10);
        zF_6873a254_1dc3fa43_stderr_write(s_fail);
        zF_6873a254_1dc3fa43_stderr_write(zF_0e44da37_989f59de_formatU32(line, __make_slice_u8(&fmt_buf[0], 24 - 0), 12));
        s_msg = __make_slice_u8(": string mismatch\n", 18);
        zF_6873a254_1dc3fa43_stderr_write(s_msg);
    }
}

static Slice_u8 zF_0e44da37_10ab4fb9_formatU64(u64 val, Slice_u8 buf, usize buf_len) {
    usize idx;
    u64 v;
    usize start;
    idx = buf_len - 1;
    v = val;
    buf.ptr[idx] = 0;
    (void)(idx -= 1);
    if (v == 0) {
        buf.ptr[idx] = '0';
        (void)(idx -= 1);
    } else {
        __loop_0_start: ;
        if (!(v > 0)) goto __loop_0_end;
        {
            buf.ptr[idx] = __bootstrap_u8_from_u32((unsigned int)'0' + __bootstrap_u32_from_u64(v % 10));
            v = v / 10;
            (void)(idx -= 1);
        }
        goto __loop_0_start;
        __loop_0_end: ;
    }
    start = idx + 1;
    return __make_slice_u8(buf.ptr + start, buf_len - start);
}

static void zF_0e44da37_6d869952_assertEqTokenKind(enum zS_89baa7c0_facdb0ca_TokenKind tk, enum zS_89baa7c0_facdb0ca_TokenKind expected, unsigned int line) {
    if (tk != expected) {
        unsigned char fmt_buf[24];
        Slice_u8 s_fail;
        Slice_u8 s_msg;
        s_fail = __make_slice_u8("FAIL line ", 10);
        zF_6873a254_1dc3fa43_stderr_write(s_fail);
        zF_6873a254_1dc3fa43_stderr_write(zF_0e44da37_989f59de_formatU32(line, __make_slice_u8(&fmt_buf[0], 24 - 0), 12));
        s_msg = __make_slice_u8(": token kind mismatch\n", 22);
        zF_6873a254_1dc3fa43_stderr_write(s_msg);
    }
}

static Slice_u8 zF_0e44da37_989f59de_formatU32(unsigned int val, Slice_u8 buf, usize buf_len) {
    usize idx;
    unsigned int v;
    usize start;
    idx = buf_len - 1;
    v = val;
    buf.ptr[idx] = 0;
    (void)(idx -= 1);
    if (v == 0) {
        buf.ptr[idx] = '0';
        (void)(idx -= 1);
    } else {
        __loop_0_start: ;
        if (!(v > 0)) goto __loop_0_end;
        {
            buf.ptr[idx] = __bootstrap_u8_from_u32((unsigned int)'0' + v % 10);
            v = v / 10;
            (void)(idx -= 1);
        }
        goto __loop_0_start;
        __loop_0_end: ;
    }
    start = idx + 1;
    return __make_slice_u8(buf.ptr + start, buf_len - start);
}

static enum zS_89baa7c0_facdb0ca_TokenKind zF_0e44da37_d106041c_nextKind(struct zS_a012675f_c8a65756_Lexer* l) {
    return zF_a012675f_2bdcba5b_lexerNextToken(l).kind;
}

static struct zS_89baa7c0_7a3512d8_Token zF_0e44da37_c201aaaf_nextToken(struct zS_a012675f_c8a65756_Lexer* l) {
    return zF_a012675f_2bdcba5b_lexerNextToken(l);
}

void zF_0e44da37_6a4c766d_runLexerUnitTests(void) {
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_5ba4803d_testIntegerOverflow();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_a98aac63_testFloatBasic();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_eabb1a7a_testFloatScientific();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_9b41aea8_testFloatNoFrac();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_94287773_testShiftOps();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_9053f59b_testFatArrow();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_e77424ef_testEqVariants();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_96bff60b_testBuiltinImport();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_c8464162_testBareAt();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_400a05ff_testBareUnderscore();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_43386fcf_testUnderscoreIdent();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_1918d290_testWhitespaceOnly();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_070b7ca1_testNestedComment();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_74a4aa3a_testUnterminatedComment();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_05e728d8_testStringBasic();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_ffa4604c_testCharEmpty();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_1ab89ec4_testStringUnterminated();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_ca0c345a_testStringEscapeHex();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_6c15e7ca_testBlockComments();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_8254a6f7_testLineComments();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_e460329e_testNumberSeparators();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_a1ccd837_testIntegerEdgeCases();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_4f9598c3_testFloatEdgeCases();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_8f399f31_testStringEscapeSequences();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_08f898ba_testCharEscapeSequences();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_fdba4d79_testEofBoundary();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_5c193e8e_testAllKeywords();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_c2ab0d40_testDotVariants();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_bb2610e6_testMultiTokenRecovery();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_38a75d39_testUnrecognizedChars();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_cbf6f1f8_testSwitchMultiProng();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_6543ac7f_testSwitchCapture();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_6970254f_testTryExpr();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_25805b5e_testErrorLiteral();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_887b5fc0_testNestedSwitch();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_b9b871e3_testIfExpr();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_818f24cd_testBuiltinCast();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_6c6918cc_testSliceSyntax();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_c5310d87_testOptionalCapture();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_d4542ab3_testDerefField();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_b03e0029_testIntegrationMandelbrot();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_3228c192_testIntegrationGameOfLife();
    zF_0e44da37_1aabccf3_initTestHarness();
    zF_0e44da37_ab23956f_testIntegrationMud();
}

static void zF_0e44da37_5ba4803d_testIntegerOverflow(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    struct zS_89baa7c0_7a3512d8_Token t;
    u64 expected_max = 0;
    s = __make_slice_u8("99999999999999999999", 20);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    t = zF_0e44da37_c201aaaf_nextToken(&l);
    zF_0e44da37_6d869952_assertEqTokenKind(t.kind, zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    (void)(expected_max -= 1);
    zF_0e44da37_950a9ba8_assertEqU64(expected_max, t.value.int_val, 0U);
}

static void zF_0e44da37_a98aac63_testFloatBasic(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("3.14", 4);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 0U);
}

static void zF_0e44da37_eabb1a7a_testFloatScientific(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("1.0e-5", 6);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 0U);
}

static void zF_0e44da37_9b41aea8_testFloatNoFrac(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("2.0", 3);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 0U);
}

static void zF_0e44da37_94287773_testShiftOps(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("<< >> <<= >>=", 13);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_shl, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_shr, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_shl_eq, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_shr_eq, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
}

static void zF_0e44da37_9053f59b_testFatArrow(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("=>", 2);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_fat_arrow, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
}

static void zF_0e44da37_e77424ef_testEqVariants(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("= == =>", 7);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eq, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eq_eq, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_fat_arrow, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
}

static void zF_0e44da37_96bff60b_testBuiltinImport(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("@import", 7);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_builtin_identifier, 0U);
}

static void zF_0e44da37_c8464162_testBareAt(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("@+", 2);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_err_token, 0U);
}

static void zF_0e44da37_400a05ff_testBareUnderscore(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("_", 1);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_underscore, 0U);
}

static void zF_0e44da37_43386fcf_testUnderscoreIdent(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("_foo", 4);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 0U);
}

static void zF_0e44da37_1918d290_testWhitespaceOnly(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("   \t\n  ", 7);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
}

static void zF_0e44da37_070b7ca1_testNestedComment(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("42 /* a /* b */ c */ 43", 23);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
}

static void zF_0e44da37_74a4aa3a_testUnterminatedComment(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("42 /* no close", 14);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
}

static void zF_0e44da37_05e728d8_testStringBasic(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    struct zS_89baa7c0_7a3512d8_Token t;
    Slice_u8 expected;
    s = __make_slice_u8("\"hello\"", 7);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    t = zF_0e44da37_c201aaaf_nextToken(&l);
    zF_0e44da37_6d869952_assertEqTokenKind(t.kind, zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
    expected = __make_slice_u8("hello", 5);
    zF_0e44da37_04dfdc16_assertEqString(expected, t.value.string_id, 0U);
}

static void zF_0e44da37_ffa4604c_testCharEmpty(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("''", 2);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_char_literal, 0U);
}

static void zF_0e44da37_1ab89ec4_testStringUnterminated(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    struct zS_89baa7c0_7a3512d8_Token t;
    s = __make_slice_u8("\"hello", 6);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    t = zF_0e44da37_c201aaaf_nextToken(&l);
    zF_0e44da37_6d869952_assertEqTokenKind(t.kind, zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
}

static void zF_0e44da37_ca0c345a_testStringEscapeHex(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    struct zS_89baa7c0_7a3512d8_Token t;
    Slice_u8 got;
    s = __make_slice_u8("\"\\xFF\"", 6);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    t = zF_0e44da37_c201aaaf_nextToken(&l);
    zF_0e44da37_6d869952_assertEqTokenKind(t.kind, zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
    got = zF_4c1e99d4_a62bda52_stringInternerGet(&zV_0e44da37_473bb154_interner, t.value.string_id);
    if (got.len != 1 || got.ptr[0] != 255) {
        Slice_u8 s_fail;
        s_fail = __make_slice_u8("FAIL: string \\xFF content\n", 26);
        zF_6873a254_1dc3fa43_stderr_write(s_fail);
    }
}

static void zF_0e44da37_6c15e7ca_testBlockComments(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    Slice_u8 s2;
    struct zS_a012675f_c8a65756_Lexer l2;
    Slice_u8 s3;
    struct zS_a012675f_c8a65756_Lexer l3;
    Slice_u8 s4;
    struct zS_a012675f_c8a65756_Lexer l4;
    s = __make_slice_u8("/* comment */42", 15);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    s2 = __make_slice_u8("/* outer /* inner */ */99", 25);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s2);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    s3 = __make_slice_u8("42/* comment */", 15);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s3);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
    s4 = __make_slice_u8("/*", 2);
    l4 = zF_0e44da37_ee308f0d_makeLexer(s4);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l4), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
}

static void zF_0e44da37_8254a6f7_testLineComments(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    Slice_u8 s2;
    struct zS_a012675f_c8a65756_Lexer l2;
    Slice_u8 s3;
    struct zS_a012675f_c8a65756_Lexer l3;
    s = __make_slice_u8("// line comment\n99", 18);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    s2 = __make_slice_u8("99 // trailing comment", 22);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s2);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
    s3 = __make_slice_u8("// comment at eof", 17);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s3);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
}

static void zF_0e44da37_e460329e_testNumberSeparators(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    struct zS_89baa7c0_7a3512d8_Token t;
    Slice_u8 s2;
    struct zS_a012675f_c8a65756_Lexer l2;
    struct zS_89baa7c0_7a3512d8_Token t2;
    Slice_u8 s3;
    struct zS_a012675f_c8a65756_Lexer l3;
    struct zS_89baa7c0_7a3512d8_Token t3;
    Slice_u8 s4;
    struct zS_a012675f_c8a65756_Lexer l4;
    struct zS_89baa7c0_7a3512d8_Token t4;
    Slice_u8 s5;
    struct zS_a012675f_c8a65756_Lexer l5;
    s = __make_slice_u8("1_000_000", 9);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    t = zF_0e44da37_c201aaaf_nextToken(&l);
    zF_0e44da37_6d869952_assertEqTokenKind(t.kind, zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_950a9ba8_assertEqU64(1000000, t.value.int_val, 0U);
    s2 = __make_slice_u8("0xFFFF_FFFF", 11);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s2);
    t2 = zF_0e44da37_c201aaaf_nextToken(&l2);
    zF_0e44da37_6d869952_assertEqTokenKind(t2.kind, zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_950a9ba8_assertEqU64(4294967295LL, t2.value.int_val, 0U);
    s3 = __make_slice_u8("0b1010_0101", 11);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s3);
    t3 = zF_0e44da37_c201aaaf_nextToken(&l3);
    zF_0e44da37_6d869952_assertEqTokenKind(t3.kind, zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_950a9ba8_assertEqU64(165, t3.value.int_val, 0U);
    s4 = __make_slice_u8("0o77_00", 7);
    l4 = zF_0e44da37_ee308f0d_makeLexer(s4);
    t4 = zF_0e44da37_c201aaaf_nextToken(&l4);
    zF_0e44da37_6d869952_assertEqTokenKind(t4.kind, zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_950a9ba8_assertEqU64(4032, t4.value.int_val, 0U);
    s5 = __make_slice_u8("3.141_59", 8);
    l5 = zF_0e44da37_ee308f0d_makeLexer(s5);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l5), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 0U);
}

static void zF_0e44da37_a1ccd837_testIntegerEdgeCases(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    struct zS_89baa7c0_7a3512d8_Token t;
    Slice_u8 s2;
    struct zS_a012675f_c8a65756_Lexer l2;
    struct zS_89baa7c0_7a3512d8_Token t2;
    u64 expected_max = 0;
    Slice_u8 s3;
    struct zS_a012675f_c8a65756_Lexer l3;
    struct zS_89baa7c0_7a3512d8_Token t3;
    Slice_u8 s4;
    struct zS_a012675f_c8a65756_Lexer l4;
    struct zS_89baa7c0_7a3512d8_Token t4;
    Slice_u8 s5;
    struct zS_a012675f_c8a65756_Lexer l5;
    struct zS_89baa7c0_7a3512d8_Token t5;
    s = __make_slice_u8("0", 1);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    t = zF_0e44da37_c201aaaf_nextToken(&l);
    zF_0e44da37_6d869952_assertEqTokenKind(t.kind, zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_950a9ba8_assertEqU64(0, t.value.int_val, 0U);
    s2 = __make_slice_u8("18446744073709551615", 20);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s2);
    t2 = zF_0e44da37_c201aaaf_nextToken(&l2);
    zF_0e44da37_6d869952_assertEqTokenKind(t2.kind, zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    (void)(expected_max -= 1);
    zF_0e44da37_950a9ba8_assertEqU64(expected_max, t2.value.int_val, 0U);
    s3 = __make_slice_u8("0x0", 3);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s3);
    t3 = zF_0e44da37_c201aaaf_nextToken(&l3);
    zF_0e44da37_6d869952_assertEqTokenKind(t3.kind, zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_950a9ba8_assertEqU64(0, t3.value.int_val, 0U);
    s4 = __make_slice_u8("0b0", 3);
    l4 = zF_0e44da37_ee308f0d_makeLexer(s4);
    t4 = zF_0e44da37_c201aaaf_nextToken(&l4);
    zF_0e44da37_6d869952_assertEqTokenKind(t4.kind, zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_950a9ba8_assertEqU64(0, t4.value.int_val, 0U);
    s5 = __make_slice_u8("0o0", 3);
    l5 = zF_0e44da37_ee308f0d_makeLexer(s5);
    t5 = zF_0e44da37_c201aaaf_nextToken(&l5);
    zF_0e44da37_6d869952_assertEqTokenKind(t5.kind, zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_950a9ba8_assertEqU64(0, t5.value.int_val, 0U);
}

static void zF_0e44da37_4f9598c3_testFloatEdgeCases(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    Slice_u8 s2;
    struct zS_a012675f_c8a65756_Lexer l2;
    Slice_u8 s3;
    struct zS_a012675f_c8a65756_Lexer l3;
    Slice_u8 s4;
    struct zS_a012675f_c8a65756_Lexer l4;
    Slice_u8 s5;
    struct zS_a012675f_c8a65756_Lexer l5;
    Slice_u8 s6;
    struct zS_a012675f_c8a65756_Lexer l6;
    s = __make_slice_u8("1e10", 4);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 0U);
    s2 = __make_slice_u8("1e-10", 5);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s2);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 0U);
    s3 = __make_slice_u8("1.0e10", 6);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s3);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 0U);
    s4 = __make_slice_u8("0..10", 5);
    l4 = zF_0e44da37_ee308f0d_makeLexer(s4);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l4), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l4), zS_89baa7c0_facdb0ca_TokenKind_dot_dot, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l4), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    s5 = __make_slice_u8("0.0", 3);
    l5 = zF_0e44da37_ee308f0d_makeLexer(s5);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l5), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 0U);
    s6 = __make_slice_u8("3.0e+5", 6);
    l6 = zF_0e44da37_ee308f0d_makeLexer(s6);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l6), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 0U);
}

static void zF_0e44da37_8f399f31_testStringEscapeSequences(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    Slice_u8 s2;
    struct zS_a012675f_c8a65756_Lexer l2;
    Slice_u8 s3;
    struct zS_a012675f_c8a65756_Lexer l3;
    Slice_u8 s4;
    struct zS_a012675f_c8a65756_Lexer l4;
    Slice_u8 s5;
    struct zS_a012675f_c8a65756_Lexer l5;
    Slice_u8 s6;
    struct zS_a012675f_c8a65756_Lexer l6;
    Slice_u8 s7;
    struct zS_a012675f_c8a65756_Lexer l7;
    Slice_u8 s8;
    struct zS_a012675f_c8a65756_Lexer l8;
    Slice_u8 s9;
    struct zS_a012675f_c8a65756_Lexer l9;
    s = __make_slice_u8("\"\\n\"", 4);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
    s2 = __make_slice_u8("\"\\t\"", 4);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s2);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
    s3 = __make_slice_u8("\"\\r\"", 4);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s3);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
    s4 = __make_slice_u8("\"\\\\\"", 4);
    l4 = zF_0e44da37_ee308f0d_makeLexer(s4);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l4), zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
    s5 = __make_slice_u8("\"\\\"\"", 4);
    l5 = zF_0e44da37_ee308f0d_makeLexer(s5);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l5), zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
    s6 = __make_slice_u8("\"\\0\"", 4);
    l6 = zF_0e44da37_ee308f0d_makeLexer(s6);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l6), zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
    s7 = __make_slice_u8("\"\\x41\"", 6);
    l7 = zF_0e44da37_ee308f0d_makeLexer(s7);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l7), zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
    s8 = __make_slice_u8("\"\\x\"", 4);
    l8 = zF_0e44da37_ee308f0d_makeLexer(s8);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l8), zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
    s9 = __make_slice_u8("\"\\z\"", 4);
    l9 = zF_0e44da37_ee308f0d_makeLexer(s9);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l9), zS_89baa7c0_facdb0ca_TokenKind_string_literal, 0U);
}

static void zF_0e44da37_08f898ba_testCharEscapeSequences(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    Slice_u8 s2;
    struct zS_a012675f_c8a65756_Lexer l2;
    Slice_u8 s3;
    struct zS_a012675f_c8a65756_Lexer l3;
    Slice_u8 s4;
    struct zS_a012675f_c8a65756_Lexer l4;
    Slice_u8 s5;
    struct zS_a012675f_c8a65756_Lexer l5;
    Slice_u8 s6;
    struct zS_a012675f_c8a65756_Lexer l6;
    Slice_u8 s7;
    struct zS_a012675f_c8a65756_Lexer l7;
    Slice_u8 s8;
    struct zS_a012675f_c8a65756_Lexer l8;
    Slice_u8 s9;
    struct zS_a012675f_c8a65756_Lexer l9;
    struct zS_89baa7c0_7a3512d8_Token t9;
    s = __make_slice_u8("'\\n'", 4);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_char_literal, 0U);
    s2 = __make_slice_u8("'\\t'", 4);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s2);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_char_literal, 0U);
    s3 = __make_slice_u8("'\\r'", 4);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s3);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_char_literal, 0U);
    s4 = __make_slice_u8("'\\\\'", 4);
    l4 = zF_0e44da37_ee308f0d_makeLexer(s4);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l4), zS_89baa7c0_facdb0ca_TokenKind_char_literal, 0U);
    s5 = __make_slice_u8("'\\''", 4);
    l5 = zF_0e44da37_ee308f0d_makeLexer(s5);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l5), zS_89baa7c0_facdb0ca_TokenKind_char_literal, 0U);
    s6 = __make_slice_u8("'\\0'", 4);
    l6 = zF_0e44da37_ee308f0d_makeLexer(s6);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l6), zS_89baa7c0_facdb0ca_TokenKind_char_literal, 0U);
    s7 = __make_slice_u8("'\\x41'", 6);
    l7 = zF_0e44da37_ee308f0d_makeLexer(s7);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l7), zS_89baa7c0_facdb0ca_TokenKind_char_literal, 0U);
    s8 = __make_slice_u8("'\\z'", 4);
    l8 = zF_0e44da37_ee308f0d_makeLexer(s8);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l8), zS_89baa7c0_facdb0ca_TokenKind_char_literal, 0U);
    s9 = __make_slice_u8("'a'", 3);
    l9 = zF_0e44da37_ee308f0d_makeLexer(s9);
    t9 = zF_0e44da37_c201aaaf_nextToken(&l9);
    zF_0e44da37_6d869952_assertEqTokenKind(t9.kind, zS_89baa7c0_facdb0ca_TokenKind_char_literal, 0U);
    zF_0e44da37_950a9ba8_assertEqU64('a', t9.value.int_val, 0U);
}

static void zF_0e44da37_fdba4d79_testEofBoundary(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    struct zS_a012675f_c8a65756_Lexer l2;
    Slice_u8 s3;
    struct zS_a012675f_c8a65756_Lexer l3;
    s = __make_slice_u8("", 0);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
    s3 = __make_slice_u8("42", 2);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s3);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_eof, 0U);
}

static void zF_0e44da37_5c193e8e_testAllKeywords(void) {
    Slice_u8 s_const;
    struct zS_a012675f_c8a65756_Lexer l1;
    Slice_u8 s_var;
    struct zS_a012675f_c8a65756_Lexer l2;
    Slice_u8 s_fn;
    struct zS_a012675f_c8a65756_Lexer l3;
    Slice_u8 s_pub;
    struct zS_a012675f_c8a65756_Lexer l4;
    Slice_u8 s_extern;
    struct zS_a012675f_c8a65756_Lexer l5;
    Slice_u8 s_export;
    struct zS_a012675f_c8a65756_Lexer l6;
    Slice_u8 s_test;
    struct zS_a012675f_c8a65756_Lexer l7;
    Slice_u8 s_struct;
    struct zS_a012675f_c8a65756_Lexer l8;
    Slice_u8 s_enum;
    struct zS_a012675f_c8a65756_Lexer l9;
    Slice_u8 s_union;
    struct zS_a012675f_c8a65756_Lexer l10;
    Slice_u8 s_if;
    struct zS_a012675f_c8a65756_Lexer l11;
    Slice_u8 s_else;
    struct zS_a012675f_c8a65756_Lexer l12;
    Slice_u8 s_while;
    struct zS_a012675f_c8a65756_Lexer l13;
    Slice_u8 s_for;
    struct zS_a012675f_c8a65756_Lexer l14;
    Slice_u8 s_switch;
    struct zS_a012675f_c8a65756_Lexer l15;
    Slice_u8 s_return;
    struct zS_a012675f_c8a65756_Lexer l16;
    Slice_u8 s_break;
    struct zS_a012675f_c8a65756_Lexer l17;
    Slice_u8 s_continue;
    struct zS_a012675f_c8a65756_Lexer l18;
    Slice_u8 s_defer;
    struct zS_a012675f_c8a65756_Lexer l19;
    Slice_u8 s_errdefer;
    struct zS_a012675f_c8a65756_Lexer l20;
    Slice_u8 s_try;
    struct zS_a012675f_c8a65756_Lexer l21;
    Slice_u8 s_catch;
    struct zS_a012675f_c8a65756_Lexer l22;
    Slice_u8 s_orelse;
    struct zS_a012675f_c8a65756_Lexer l23;
    Slice_u8 s_error;
    struct zS_a012675f_c8a65756_Lexer l24;
    Slice_u8 s_and;
    struct zS_a012675f_c8a65756_Lexer l25;
    Slice_u8 s_or;
    struct zS_a012675f_c8a65756_Lexer l26;
    Slice_u8 s_true;
    struct zS_a012675f_c8a65756_Lexer l27;
    Slice_u8 s_false;
    struct zS_a012675f_c8a65756_Lexer l28;
    Slice_u8 s_null;
    struct zS_a012675f_c8a65756_Lexer l29;
    Slice_u8 s_undefined;
    struct zS_a012675f_c8a65756_Lexer l30;
    Slice_u8 s_unreachable;
    struct zS_a012675f_c8a65756_Lexer l31;
    Slice_u8 s_void;
    struct zS_a012675f_c8a65756_Lexer l32;
    Slice_u8 s_bool;
    struct zS_a012675f_c8a65756_Lexer l33;
    Slice_u8 s_noreturn;
    struct zS_a012675f_c8a65756_Lexer l34;
    Slice_u8 s_c_char;
    struct zS_a012675f_c8a65756_Lexer l35;
    s_const = __make_slice_u8("const", 5);
    l1 = zF_0e44da37_ee308f0d_makeLexer(s_const);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l1), zS_89baa7c0_facdb0ca_TokenKind_kw_const, 1U);
    s_var = __make_slice_u8("var", 3);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s_var);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_kw_var, 2U);
    s_fn = __make_slice_u8("fn", 2);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s_fn);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_kw_fn, 3U);
    s_pub = __make_slice_u8("pub", 3);
    l4 = zF_0e44da37_ee308f0d_makeLexer(s_pub);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l4), zS_89baa7c0_facdb0ca_TokenKind_kw_pub, 4U);
    s_extern = __make_slice_u8("extern", 6);
    l5 = zF_0e44da37_ee308f0d_makeLexer(s_extern);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l5), zS_89baa7c0_facdb0ca_TokenKind_kw_extern, 5U);
    s_export = __make_slice_u8("export", 6);
    l6 = zF_0e44da37_ee308f0d_makeLexer(s_export);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l6), zS_89baa7c0_facdb0ca_TokenKind_kw_export, 6U);
    s_test = __make_slice_u8("test", 4);
    l7 = zF_0e44da37_ee308f0d_makeLexer(s_test);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l7), zS_89baa7c0_facdb0ca_TokenKind_kw_test, 7U);
    s_struct = __make_slice_u8("struct", 6);
    l8 = zF_0e44da37_ee308f0d_makeLexer(s_struct);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l8), zS_89baa7c0_facdb0ca_TokenKind_kw_struct, 8U);
    s_enum = __make_slice_u8("enum", 4);
    l9 = zF_0e44da37_ee308f0d_makeLexer(s_enum);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l9), zS_89baa7c0_facdb0ca_TokenKind_kw_enum, 9U);
    s_union = __make_slice_u8("union", 5);
    l10 = zF_0e44da37_ee308f0d_makeLexer(s_union);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l10), zS_89baa7c0_facdb0ca_TokenKind_kw_union, 10U);
    s_if = __make_slice_u8("if", 2);
    l11 = zF_0e44da37_ee308f0d_makeLexer(s_if);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l11), zS_89baa7c0_facdb0ca_TokenKind_kw_if, 11U);
    s_else = __make_slice_u8("else", 4);
    l12 = zF_0e44da37_ee308f0d_makeLexer(s_else);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l12), zS_89baa7c0_facdb0ca_TokenKind_kw_else, 12U);
    s_while = __make_slice_u8("while", 5);
    l13 = zF_0e44da37_ee308f0d_makeLexer(s_while);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l13), zS_89baa7c0_facdb0ca_TokenKind_kw_while, 13U);
    s_for = __make_slice_u8("for", 3);
    l14 = zF_0e44da37_ee308f0d_makeLexer(s_for);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l14), zS_89baa7c0_facdb0ca_TokenKind_kw_for, 14U);
    s_switch = __make_slice_u8("switch", 6);
    l15 = zF_0e44da37_ee308f0d_makeLexer(s_switch);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l15), zS_89baa7c0_facdb0ca_TokenKind_kw_switch, 15U);
    s_return = __make_slice_u8("return", 6);
    l16 = zF_0e44da37_ee308f0d_makeLexer(s_return);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l16), zS_89baa7c0_facdb0ca_TokenKind_kw_return, 16U);
    s_break = __make_slice_u8("break", 5);
    l17 = zF_0e44da37_ee308f0d_makeLexer(s_break);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l17), zS_89baa7c0_facdb0ca_TokenKind_kw_break, 17U);
    s_continue = __make_slice_u8("continue", 8);
    l18 = zF_0e44da37_ee308f0d_makeLexer(s_continue);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l18), zS_89baa7c0_facdb0ca_TokenKind_kw_continue, 18U);
    s_defer = __make_slice_u8("defer", 5);
    l19 = zF_0e44da37_ee308f0d_makeLexer(s_defer);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l19), zS_89baa7c0_facdb0ca_TokenKind_kw_defer, 19U);
    s_errdefer = __make_slice_u8("errdefer", 8);
    l20 = zF_0e44da37_ee308f0d_makeLexer(s_errdefer);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l20), zS_89baa7c0_facdb0ca_TokenKind_kw_errdefer, 20U);
    s_try = __make_slice_u8("try", 3);
    l21 = zF_0e44da37_ee308f0d_makeLexer(s_try);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l21), zS_89baa7c0_facdb0ca_TokenKind_kw_try, 21U);
    s_catch = __make_slice_u8("catch", 5);
    l22 = zF_0e44da37_ee308f0d_makeLexer(s_catch);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l22), zS_89baa7c0_facdb0ca_TokenKind_kw_catch, 22U);
    s_orelse = __make_slice_u8("orelse", 6);
    l23 = zF_0e44da37_ee308f0d_makeLexer(s_orelse);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l23), zS_89baa7c0_facdb0ca_TokenKind_kw_orelse, 23U);
    s_error = __make_slice_u8("error", 5);
    l24 = zF_0e44da37_ee308f0d_makeLexer(s_error);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l24), zS_89baa7c0_facdb0ca_TokenKind_kw_error, 24U);
    s_and = __make_slice_u8("and", 3);
    l25 = zF_0e44da37_ee308f0d_makeLexer(s_and);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l25), zS_89baa7c0_facdb0ca_TokenKind_kw_and, 25U);
    s_or = __make_slice_u8("or", 2);
    l26 = zF_0e44da37_ee308f0d_makeLexer(s_or);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l26), zS_89baa7c0_facdb0ca_TokenKind_kw_or, 26U);
    s_true = __make_slice_u8("true", 4);
    l27 = zF_0e44da37_ee308f0d_makeLexer(s_true);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l27), zS_89baa7c0_facdb0ca_TokenKind_kw_true, 27U);
    s_false = __make_slice_u8("false", 5);
    l28 = zF_0e44da37_ee308f0d_makeLexer(s_false);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l28), zS_89baa7c0_facdb0ca_TokenKind_kw_false, 28U);
    s_null = __make_slice_u8("null", 4);
    l29 = zF_0e44da37_ee308f0d_makeLexer(s_null);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l29), zS_89baa7c0_facdb0ca_TokenKind_kw_null, 29U);
    s_undefined = __make_slice_u8("undefined", 9);
    l30 = zF_0e44da37_ee308f0d_makeLexer(s_undefined);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l30), zS_89baa7c0_facdb0ca_TokenKind_kw_undefined, 30U);
    s_unreachable = __make_slice_u8("unreachable", 11);
    l31 = zF_0e44da37_ee308f0d_makeLexer(s_unreachable);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l31), zS_89baa7c0_facdb0ca_TokenKind_kw_unreachable, 31U);
    s_void = __make_slice_u8("void", 4);
    l32 = zF_0e44da37_ee308f0d_makeLexer(s_void);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l32), zS_89baa7c0_facdb0ca_TokenKind_kw_void, 32U);
    s_bool = __make_slice_u8("bool", 4);
    l33 = zF_0e44da37_ee308f0d_makeLexer(s_bool);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l33), zS_89baa7c0_facdb0ca_TokenKind_kw_bool, 33U);
    s_noreturn = __make_slice_u8("noreturn", 8);
    l34 = zF_0e44da37_ee308f0d_makeLexer(s_noreturn);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l34), zS_89baa7c0_facdb0ca_TokenKind_kw_noreturn, 34U);
    s_c_char = __make_slice_u8("c_char", 6);
    l35 = zF_0e44da37_ee308f0d_makeLexer(s_c_char);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l35), zS_89baa7c0_facdb0ca_TokenKind_kw_c_char, 35U);
}

static void zF_0e44da37_c2ab0d40_testDotVariants(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    Slice_u8 s2;
    struct zS_a012675f_c8a65756_Lexer l2;
    Slice_u8 s3;
    struct zS_a012675f_c8a65756_Lexer l3;
    Slice_u8 s4;
    struct zS_a012675f_c8a65756_Lexer l4;
    Slice_u8 s5;
    struct zS_a012675f_c8a65756_Lexer l5;
    Slice_u8 s6;
    struct zS_a012675f_c8a65756_Lexer l6;
    s = __make_slice_u8(".", 1);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot, 0U);
    s2 = __make_slice_u8("..", 2);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s2);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_dot_dot, 0U);
    s3 = __make_slice_u8("...", 3);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s3);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_dot_dot_dot, 0U);
    s4 = __make_slice_u8(".{", 2);
    l4 = zF_0e44da37_ee308f0d_makeLexer(s4);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l4), zS_89baa7c0_facdb0ca_TokenKind_dot_lbrace, 0U);
    s5 = __make_slice_u8(".*", 2);
    l5 = zF_0e44da37_ee308f0d_makeLexer(s5);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l5), zS_89baa7c0_facdb0ca_TokenKind_dot_star, 0U);
    s6 = __make_slice_u8("....", 4);
    l6 = zF_0e44da37_ee308f0d_makeLexer(s6);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l6), zS_89baa7c0_facdb0ca_TokenKind_dot_dot_dot, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l6), zS_89baa7c0_facdb0ca_TokenKind_dot, 0U);
}

static void zF_0e44da37_bb2610e6_testMultiTokenRecovery(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    Slice_u8 s2;
    struct zS_a012675f_c8a65756_Lexer l2;
    s = __make_slice_u8("42 ` 99", 7);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_err_token, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 0U);
    s2 = __make_slice_u8("@", 1);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s2);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_err_token, 0U);
}

static void zF_0e44da37_38a75d39_testUnrecognizedChars(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    Slice_u8 s2;
    struct zS_a012675f_c8a65756_Lexer l2;
    Slice_u8 s3;
    struct zS_a012675f_c8a65756_Lexer l3;
    s = __make_slice_u8("`", 1);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_err_token, 0U);
    s2 = __make_slice_u8("@`", 2);
    l2 = zF_0e44da37_ee308f0d_makeLexer(s2);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_err_token, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l2), zS_89baa7c0_facdb0ca_TokenKind_err_token, 0U);
    s3 = __make_slice_u8("`@`", 3);
    l3 = zF_0e44da37_ee308f0d_makeLexer(s3);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_err_token, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_err_token, 0U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l3), zS_89baa7c0_facdb0ca_TokenKind_err_token, 0U);
}

static void zF_0e44da37_cbf6f1f8_testSwitchMultiProng(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("switch (x) { .A, .B, .C => {}, else => unreachable }", 52);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_switch, 1300U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lparen, 1301U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1302U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rparen, 1303U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1304U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot, 1305U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1306U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_comma, 1307U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot, 1308U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1309U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_comma, 1310U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot, 1311U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1312U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_fat_arrow, 1313U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1314U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1315U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_comma, 1316U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_else, 1317U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_fat_arrow, 1318U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_unreachable, 1319U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1320U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1321U);
}

static void zF_0e44da37_6543ac7f_testSwitchCapture(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("switch (x) { .A => |v| v, else => unreachable }", 47);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_switch, 1400U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lparen, 1401U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1402U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rparen, 1403U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1404U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot, 1405U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1406U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_fat_arrow, 1407U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_pipe, 1408U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1409U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_pipe, 1410U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1411U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_comma, 1412U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_else, 1413U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_fat_arrow, 1414U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_unreachable, 1415U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1416U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1417U);
}

static void zF_0e44da37_6970254f_testTryExpr(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("try foo(bar, baz)", 17);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_try, 1420U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1421U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lparen, 1422U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1423U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_comma, 1424U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1425U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rparen, 1426U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1427U);
}

static void zF_0e44da37_25805b5e_testErrorLiteral(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("return error.InvalidQuote", 25);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_return, 1430U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_error, 1431U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot, 1432U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1433U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1434U);
}

static void zF_0e44da37_887b5fc0_testNestedSwitch(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("switch (a) { .X => switch (b) { .Y => {}, else => {} }, else => {} }", 68);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_switch, 1440U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lparen, 1441U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1442U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rparen, 1443U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1444U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot, 1445U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1446U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_fat_arrow, 1447U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_switch, 1448U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lparen, 1449U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1450U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rparen, 1451U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1452U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot, 1453U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1454U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_fat_arrow, 1455U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1456U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1457U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_comma, 1458U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_else, 1459U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_fat_arrow, 1460U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1461U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1462U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1463U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_comma, 1464U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_else, 1465U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_fat_arrow, 1466U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1467U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1468U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1469U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1470U);
}

static void zF_0e44da37_b9b871e3_testIfExpr(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("if (cond) a else b", 18);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_if, 1480U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lparen, 1481U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1482U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rparen, 1483U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1484U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_else, 1485U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1486U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1487U);
}

static void zF_0e44da37_818f24cd_testBuiltinCast(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("@ptrCast([*]u8, ptr)", 20);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_builtin_identifier, 1490U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lparen, 1491U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbracket, 1492U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_star, 1493U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbracket, 1494U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1495U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_comma, 1496U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1497U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rparen, 1498U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1499U);
}

static void zF_0e44da37_6c6918cc_testSliceSyntax(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("arr[0..len]", 11);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1500U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbracket, 1501U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_integer_literal, 1502U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot_dot, 1503U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1504U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbracket, 1505U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1506U);
}

static void zF_0e44da37_c5310d87_testOptionalCapture(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("if (opt) |val| {}", 17);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_if, 1510U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lparen, 1511U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1512U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rparen, 1513U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_pipe, 1514U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1515U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_pipe, 1516U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1517U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1518U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1519U);
}

static void zF_0e44da37_d4542ab3_testDerefField(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("curr_expr.*", 11);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1520U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot_star, 1521U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1522U);
}

static void zF_0e44da37_b03e0029_testIntegrationMandelbrot(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("const s: f64 = 3.5; var x = 2.0; var y = 1.0e-5;", 48);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_const, 1600U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1601U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_colon, 1602U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1603U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eq, 1604U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 1605U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_semicolon, 1606U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_var, 1607U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1608U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eq, 1609U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 1610U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_semicolon, 1611U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_var, 1612U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1613U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eq, 1614U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_float_literal, 1615U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_semicolon, 1616U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1617U);
}

static void zF_0e44da37_3228c192_testIntegrationGameOfLife(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("const Cell = union(enum) { Dead, Alive }; var c: Cell = .{ .Alive = {} };", 73);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_const, 1620U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1621U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eq, 1622U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_union, 1623U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lparen, 1624U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_enum, 1625U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rparen, 1626U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1627U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1628U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_comma, 1629U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1630U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1631U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_semicolon, 1632U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_var, 1633U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1634U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_colon, 1635U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1636U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eq, 1637U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot_lbrace, 1638U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_dot, 1639U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1640U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eq, 1641U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbrace, 1642U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1643U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbrace, 1644U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_semicolon, 1645U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1646U);
}

static void zF_0e44da37_ab23956f_testIntegrationMud(void) {
    Slice_u8 s;
    struct zS_a012675f_c8a65756_Lexer l;
    s = __make_slice_u8("const msg: []const u8 = \"Welcome\\r\\n\";", 38);
    l = zF_0e44da37_ee308f0d_makeLexer(s);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_const, 1650U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1651U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_colon, 1652U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_lbracket, 1653U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_rbracket, 1654U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_kw_const, 1655U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_identifier, 1656U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eq, 1657U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_string_literal, 1658U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_semicolon, 1659U);
    zF_0e44da37_6d869952_assertEqTokenKind(zF_0e44da37_d106041c_nextKind(&l), zS_89baa7c0_facdb0ca_TokenKind_eof, 1660U);
}
