/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OutOfMemory 1

/* Master Single Translation Unit (STU) file */

#include "arena.c"
#include "value.c"
#include "repro_bug.c"
