/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "main.h"
#include "allocator.h"
#include "string_interner.h"
#include "source_manager.h"
#include "diagnostics.h"
#include "name_mangler.h"
#include "token.h"
#include "dump.h"
#include "lexer.h"
#include "pal.h"
#include "parser.h"
#include "ast.h"


struct zS_26b5a9a4_43f95de6_Sand;
struct zS_26b5a9a4_d34e314a_CompilerAlloc;
struct zS_4c1e99d4_67d40cc9_StringInterner;
struct zS_2b6fc0a6_29be27be_SourceManager;
struct zS_9daadfc5_490018d3_DiagnosticCollector;
struct zS_ab5e085b_2cf354c9_NameMangler;
#ifndef ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
#define ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
struct zS_26b5a9a4_43f95de6_Sand {
    unsigned char* start;
    usize pos;
    usize end;
    usize peak;
};

#endif /* ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand */

#ifndef ZIG_STRUCT_zS_26b5a9a4_d34e314a_CompilerAlloc
#define ZIG_STRUCT_zS_26b5a9a4_d34e314a_CompilerAlloc
struct zS_26b5a9a4_d34e314a_CompilerAlloc {
    struct zS_26b5a9a4_43f95de6_Sand permanent;
    struct zS_26b5a9a4_43f95de6_Sand module;
    struct zS_26b5a9a4_43f95de6_Sand scratch;
    unsigned int max_mem;
};

#endif /* ZIG_STRUCT_zS_26b5a9a4_d34e314a_CompilerAlloc */

#ifndef ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner
#define ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner
struct zS_4c1e99d4_67d40cc9_StringInterner {
    struct zS_16d7ab7a_840ccd30_U32ArrayList* buckets;
    struct zS_4c1e99d4_face28fc_InternArrayList* entries;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner */

#ifndef ZIG_STRUCT_zS_2b6fc0a6_29be27be_SourceManager
#define ZIG_STRUCT_zS_2b6fc0a6_29be27be_SourceManager
struct zS_2b6fc0a6_29be27be_SourceManager {
    struct zS_2b6fc0a6_c93555ae_SourceFileArrayList* files;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_2b6fc0a6_29be27be_SourceManager */

#ifndef ZIG_STRUCT_zS_9daadfc5_490018d3_DiagnosticCollector
#define ZIG_STRUCT_zS_9daadfc5_490018d3_DiagnosticCollector
struct zS_9daadfc5_490018d3_DiagnosticCollector {
    struct zS_9daadfc5_8924c34d_DiagnosticArrayList* diagnostics;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
    struct zS_2b6fc0a6_29be27be_SourceManager* source_manager;
    struct zS_4c1e99d4_67d40cc9_StringInterner* interner;
    usize error_count;
    usize warning_count;
    usize max_diagnostics;
};

#endif /* ZIG_STRUCT_zS_9daadfc5_490018d3_DiagnosticCollector */

#ifndef ZIG_STRUCT_zS_ab5e085b_2cf354c9_NameMangler
#define ZIG_STRUCT_zS_ab5e085b_2cf354c9_NameMangler
struct zS_ab5e085b_2cf354c9_NameMangler {
    unsigned int counter;
};

#endif /* ZIG_STRUCT_zS_ab5e085b_2cf354c9_NameMangler */

static void zF_127049be_d936318d_runCompiler(struct zS_127049be_ec2a6e74_CompilerContext*);
static void zF_127049be_5b77106c_phase_ImportResolution(struct zS_127049be_ec2a6e74_CompilerContext*);
static void zF_127049be_0f16c0b2_phase_SymbolRegistration(struct zS_127049be_ec2a6e74_CompilerContext*);
static void zF_127049be_3b5109a5_phase_TypeResolution(struct zS_127049be_ec2a6e74_CompilerContext*);
static void zF_127049be_9d1ddda1_phase_SemanticAnalysis(struct zS_127049be_ec2a6e74_CompilerContext*);
static void zF_127049be_e59e4f1d_phase_LIRLowering(struct zS_127049be_ec2a6e74_CompilerContext*);
static void zF_127049be_360ba038_phase_C89Emission(struct zS_127049be_ec2a6e74_CompilerContext*);
static struct zS_127049be_a3e1e511_CompilerCli zF_127049be_63a08883_parseArgs(void);
static int zF_127049be_fe9362ca_matchFlag(Slice_u8, Slice_u8);
static Slice_u8 zF_127049be_c99c8b7c_cstrToSlice(unsigned char const*);
static unsigned int zF_127049be_48fe8a0b_parseSize(unsigned char const*);
static unsigned int zF_127049be_f1af05a0_parseU32(unsigned char const*);
static enum zS_127049be_b8a04c98_ColorMode zF_127049be_46538142_parseColorMode(unsigned char const*);
static enum zS_127049be_b6e8e37d_ErrorFormat zF_127049be_a46d5897_parseErrorFormat(unsigned char const*);
static void zF_127049be_0da25b91_printUsage(void);

int main(int argc, char* argv[]) {
    struct zS_127049be_a3e1e511_CompilerCli cli;
    struct zS_26b5a9a4_d34e314a_CompilerAlloc compiler_alloc;
    struct zS_26b5a9a4_43f95de6_Sand perm_sand;
    struct zS_4c1e99d4_67d40cc9_StringInterner interner;
    struct zS_2b6fc0a6_29be27be_SourceManager source_man;
    struct zS_9daadfc5_490018d3_DiagnosticCollector diag;
    struct zS_ab5e085b_2cf354c9_NameMangler name_mangler;
    struct zS_127049be_ec2a6e74_CompilerContext ctx;
    zF_6873a254_00b68800_initArgs(argc, (unsigned char const**)argv);
    cli = zF_127049be_63a08883_parseArgs();
    if (cli.sanity_test_mode) {
        struct zS_26b5a9a4_d34e314a_CompilerAlloc compiler_alloc_1;
        struct zS_26b5a9a4_43f95de6_Sand perm_sand_1;
        struct zS_4c1e99d4_67d40cc9_StringInterner interner_1;
        struct zS_2b6fc0a6_29be27be_SourceManager source_man_1;
        struct zS_9daadfc5_490018d3_DiagnosticCollector diag_1;
        compiler_alloc_1 = zF_26b5a9a4_61b35879_initCompilerAlloc();
        perm_sand_1 = compiler_alloc_1.permanent;
        interner_1 = zF_4c1e99d4_610165ac_stringInternerInit(&perm_sand_1, 4);
        source_man_1 = zF_2b6fc0a6_b845e969_sourceManagerInit(&perm_sand_1);
        diag_1 = zF_9daadfc5_178b11e8_diagnosticCollectorInit(&perm_sand_1, &source_man_1, &interner_1);
        compiler_alloc_1.permanent = perm_sand_1;
        zF_89baa7c0_aa606f4f_initKeywordTable(&perm_sand_1);
        zF_a012675f_448880f3_lexerTestSanityCheck();
        {
            return 0;
        }
    }
    if (cli.test_mode) {
        Slice_u8 msg;
        msg = __make_slice_u8("error: use test_main.zig for test mode\n", 39);
        zF_6873a254_1dc3fa43_stderr_write(msg);
        zF_6873a254_25b9f2e7_exit(1);
        {
            return 0;
        }
    }
    if (cli.input_file.len == 0) {
        zF_127049be_0da25b91_printUsage();
        {
            return 0;
        }
    }
    if (cli.dump_tokens) {
        struct zS_26b5a9a4_d34e314a_CompilerAlloc compiler_alloc_2;
        struct zS_26b5a9a4_43f95de6_Sand perm_sand_2;
        struct zS_4c1e99d4_67d40cc9_StringInterner interner_2;
        struct zS_2b6fc0a6_29be27be_SourceManager source_man_2;
        struct zS_9daadfc5_490018d3_DiagnosticCollector diag_2;
        Slice_u8 __tmp_orelse_7_1;
        Optional_Slice_u8 __tmp_orelse_res_7_2;
        Slice_u8 source;
        struct zS_26b5a9a4_43f95de6_Sand module_sand;
        struct zS_a012675f_c8a65756_Lexer lex;
        compiler_alloc_2 = zF_26b5a9a4_61b35879_initCompilerAlloc();
        perm_sand_2 = compiler_alloc_2.permanent;
        interner_2 = zF_4c1e99d4_610165ac_stringInternerInit(&perm_sand_2, 4);
        source_man_2 = zF_2b6fc0a6_b845e969_sourceManagerInit(&perm_sand_2);
        diag_2 = zF_9daadfc5_178b11e8_diagnosticCollectorInit(&perm_sand_2, &source_man_2, &interner_2);
        compiler_alloc_2.permanent = perm_sand_2;
        zF_89baa7c0_aa606f4f_initKeywordTable(&perm_sand_2);
        __tmp_orelse_res_7_2 = zF_6873a254_5576b025_readFile(cli.input_file, &perm_sand_2);
        if (__tmp_orelse_res_7_2.has_value) {
            __tmp_orelse_7_1 = __tmp_orelse_res_7_2.value;
        } else {
            Slice_u8 msg_1;
            msg_1 = __make_slice_u8("error: could not read input file\n", 33);
            zF_6873a254_1dc3fa43_stderr_write(msg_1);
            zF_6873a254_25b9f2e7_exit(1);
            {
                return 0;
            }
        }
        source = __tmp_orelse_7_1;
        module_sand = compiler_alloc_2.module;
        lex = zF_a012675f_e7d69f49_lexerInit(source, 0, &interner_2, &diag_2, &module_sand);
        zF_26cee869_94f57799_dumpTokens(&lex, &interner_2);
        {
            return 0;
        }
    }
    compiler_alloc = zF_26b5a9a4_61b35879_initCompilerAlloc();
    compiler_alloc.max_mem = cli.max_mem;
    perm_sand = compiler_alloc.permanent;
    interner = zF_4c1e99d4_610165ac_stringInternerInit(&perm_sand, 4);
    source_man = zF_2b6fc0a6_b845e969_sourceManagerInit(&perm_sand);
    diag = zF_9daadfc5_178b11e8_diagnosticCollectorInit(&perm_sand, &source_man, &interner);
    diag.max_diagnostics = (usize)cli.max_errors;
    compiler_alloc.permanent = perm_sand;
    zF_89baa7c0_aa606f4f_initKeywordTable(&perm_sand);
    name_mangler = zF_ab5e085b_1f08a8de_nameManglerInit();
    ctx.cli = cli;
    ctx.alloc = &compiler_alloc;
    ctx.interner = &interner;
    ctx.diag = &diag;
    ctx.source_man = &source_man;
    ctx.name_mangler = &name_mangler;
    zF_127049be_d936318d_runCompiler(&ctx);
    return 0;
}

static void zF_127049be_d936318d_runCompiler(struct zS_127049be_ec2a6e74_CompilerContext* ctx) {
    zF_127049be_5b77106c_phase_ImportResolution(ctx);
    zF_26b5a9a4_23996229_checkCombinedPeak(ctx->alloc);
    if (zF_9daadfc5_b734257d_diagnosticCollectorHasErrors(ctx->diag)) {
        zF_9daadfc5_3ea45a74_diagnosticCollectorPrintAll(ctx->diag);
        zF_6873a254_25b9f2e7_exit(2);
    }
    zF_127049be_0f16c0b2_phase_SymbolRegistration(ctx);
    zF_26b5a9a4_23996229_checkCombinedPeak(ctx->alloc);
    zF_127049be_3b5109a5_phase_TypeResolution(ctx);
    zF_26b5a9a4_23996229_checkCombinedPeak(ctx->alloc);
    if (zF_9daadfc5_b734257d_diagnosticCollectorHasErrors(ctx->diag)) {
        zF_9daadfc5_3ea45a74_diagnosticCollectorPrintAll(ctx->diag);
        zF_6873a254_25b9f2e7_exit(2);
    }
    zF_127049be_9d1ddda1_phase_SemanticAnalysis(ctx);
    zF_26b5a9a4_23996229_checkCombinedPeak(ctx->alloc);
    if (zF_9daadfc5_b734257d_diagnosticCollectorHasErrors(ctx->diag)) {
        zF_9daadfc5_3ea45a74_diagnosticCollectorPrintAll(ctx->diag);
        zF_6873a254_25b9f2e7_exit(2);
    }
    zF_127049be_e59e4f1d_phase_LIRLowering(ctx);
    zF_26b5a9a4_23996229_checkCombinedPeak(ctx->alloc);
    if (zF_9daadfc5_b734257d_diagnosticCollectorHasErrors(ctx->diag)) {
        zF_9daadfc5_3ea45a74_diagnosticCollectorPrintAll(ctx->diag);
        zF_6873a254_25b9f2e7_exit(2);
    }
    zF_127049be_360ba038_phase_C89Emission(ctx);
    zF_26b5a9a4_23996229_checkCombinedPeak(ctx->alloc);
    zF_9daadfc5_3ea45a74_diagnosticCollectorPrintAll(ctx->diag);
    if (ctx->cli.warnings_as_errors && zF_9daadfc5_3ff34e2d_diagnosticCollectorWarningCount(ctx->diag) > 0) {
        zF_6873a254_25b9f2e7_exit(1);
    }
    (void)(ctx->cli.track_memory);
    (void)(ctx->alloc->permanent.peak);
    (void)(ctx->alloc->module.peak);
    (void)(ctx->alloc->scratch.peak);
}

static void zF_127049be_5b77106c_phase_ImportResolution(struct zS_127049be_ec2a6e74_CompilerContext* ctx) {
    zF_26b5a9a4_abb8d26c_sandReset(&ctx->alloc->scratch);
    (void)(ctx);
}

static void zF_127049be_0f16c0b2_phase_SymbolRegistration(struct zS_127049be_ec2a6e74_CompilerContext* ctx) {
    zF_26b5a9a4_abb8d26c_sandReset(&ctx->alloc->scratch);
    (void)(ctx);
}

static void zF_127049be_3b5109a5_phase_TypeResolution(struct zS_127049be_ec2a6e74_CompilerContext* ctx) {
    zF_26b5a9a4_abb8d26c_sandReset(&ctx->alloc->scratch);
    (void)(ctx);
}

static void zF_127049be_9d1ddda1_phase_SemanticAnalysis(struct zS_127049be_ec2a6e74_CompilerContext* ctx) {
    zF_26b5a9a4_abb8d26c_sandReset(&ctx->alloc->scratch);
    (void)(ctx);
}

static void zF_127049be_e59e4f1d_phase_LIRLowering(struct zS_127049be_ec2a6e74_CompilerContext* ctx) {
    (void)(ctx);
}

static void zF_127049be_360ba038_phase_C89Emission(struct zS_127049be_ec2a6e74_CompilerContext* ctx) {
    (void)(ctx);
}

static struct zS_127049be_a3e1e511_CompilerCli zF_127049be_63a08883_parseArgs(void) {
    Slice_u8 empty_str;
    Slice_u8 dot_str;
    struct zS_127049be_a3e1e511_CompilerCli cli;
    int argc;
    int i = 1;
    Slice_u8 s_dump_tokens;
    Slice_u8 s_dump_ast;
    Slice_u8 s_dump_types;
    Slice_u8 s_dump_lir;
    Slice_u8 s_max_mem;
    Slice_u8 s_max_errors;
    Slice_u8 s_output_dir;
    Slice_u8 s_quiet;
    Slice_u8 s_test;
    Slice_u8 s_sanity_test;
    Slice_u8 s_warnings;
    Slice_u8 s_color;
    Slice_u8 s_error_format;
    Slice_u8 s_track_memory;
    Slice_u8 s_include;
    Slice_u8 s_t;
    Slice_u8 s_a;
    Slice_u8 s_y;
    Slice_u8 s_l;
    Slice_u8 s_m;
    Slice_u8 s_e;
    Slice_u8 s_o;
    Slice_u8 s_q;
    Slice_u8 s_W;
    empty_str = __make_slice_u8("", 0);
    dot_str = __make_slice_u8(".", 1);
    cli.input_file = empty_str;
    cli.output_dir = dot_str;
    cli.dump_tokens = 0;
    cli.dump_ast = 0;
    cli.dump_types = 0;
    cli.dump_lir = 0;
    cli.max_mem = __bootstrap_u32_from_i32(16 * 1024 * 1024);
    cli.max_errors = 256U;
    cli.color = zS_127049be_b8a04c98_ColorMode_auto;
    cli.error_format = zS_127049be_b6e8e37d_ErrorFormat_human;
    cli.warnings_as_errors = 0;
    cli.quiet = 0;
    cli.test_mode = 0;
    cli.sanity_test_mode = 0;
    cli.track_memory = 0;
    cli.include_count = 0U;
    argc = zF_6873a254_edf9c674_argCount();
    s_dump_tokens = __make_slice_u8("--dump-tokens", 13);
    s_dump_ast = __make_slice_u8("--dump-ast", 10);
    s_dump_types = __make_slice_u8("--dump-types", 12);
    s_dump_lir = __make_slice_u8("--dump-lir", 10);
    s_max_mem = __make_slice_u8("--max-mem", 9);
    s_max_errors = __make_slice_u8("--max-errors", 12);
    s_output_dir = __make_slice_u8("--output-dir", 12);
    s_quiet = __make_slice_u8("--quiet", 7);
    s_test = __make_slice_u8("--test", 6);
    s_sanity_test = __make_slice_u8("--sanity-test", 13);
    s_warnings = __make_slice_u8("--warnings-as-errors", 20);
    s_color = __make_slice_u8("--color", 7);
    s_error_format = __make_slice_u8("--error-format", 14);
    s_track_memory = __make_slice_u8("--track-memory", 14);
    s_include = __make_slice_u8("-I", 2);
    s_t = __make_slice_u8("-t", 2);
    s_a = __make_slice_u8("-a", 2);
    s_y = __make_slice_u8("-y", 2);
    s_l = __make_slice_u8("-l", 2);
    s_m = __make_slice_u8("-m", 2);
    s_e = __make_slice_u8("-e", 2);
    s_o = __make_slice_u8("-o", 2);
    s_q = __make_slice_u8("-q", 2);
    s_W = __make_slice_u8("-W", 2);
    __loop_0_start: ;
    if (!(i < argc)) goto __loop_0_end;
    {
        unsigned char const* arg_ptr;
        Slice_u8 arg;
        arg_ptr = zF_6873a254_b1633bd7_argGet(i);
        arg = zF_127049be_c99c8b7c_cstrToSlice(arg_ptr);
        if (arg.len > 0 && arg.ptr[0] == '-') {
            if (zF_127049be_fe9362ca_matchFlag(arg, s_dump_tokens) || zF_127049be_fe9362ca_matchFlag(arg, s_t)) {
                cli.dump_tokens = 1;
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_dump_ast) || zF_127049be_fe9362ca_matchFlag(arg, s_a)) {
                cli.dump_ast = 1;
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_dump_types) || zF_127049be_fe9362ca_matchFlag(arg, s_y)) {
                cli.dump_types = 1;
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_dump_lir) || zF_127049be_fe9362ca_matchFlag(arg, s_l)) {
                cli.dump_lir = 1;
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_max_mem) || zF_127049be_fe9362ca_matchFlag(arg, s_m)) {
                (void)(i += 1);
                if (i < argc) {
                    cli.max_mem = zF_127049be_48fe8a0b_parseSize(zF_6873a254_b1633bd7_argGet(i));
                }
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_max_errors) || zF_127049be_fe9362ca_matchFlag(arg, s_e)) {
                (void)(i += 1);
                if (i < argc) {
                    cli.max_errors = zF_127049be_f1af05a0_parseU32(zF_6873a254_b1633bd7_argGet(i));
                }
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_output_dir) || zF_127049be_fe9362ca_matchFlag(arg, s_o)) {
                (void)(i += 1);
                if (i < argc) {
                    cli.output_dir = zF_127049be_c99c8b7c_cstrToSlice(zF_6873a254_b1633bd7_argGet(i));
                }
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_quiet) || zF_127049be_fe9362ca_matchFlag(arg, s_q)) {
                cli.quiet = 1;
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_test)) {
                cli.test_mode = 1;
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_sanity_test)) {
                cli.sanity_test_mode = 1;
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_warnings) || zF_127049be_fe9362ca_matchFlag(arg, s_W)) {
                cli.warnings_as_errors = 1;
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_color)) {
                (void)(i += 1);
                if (i < argc) {
                    cli.color = zF_127049be_46538142_parseColorMode(zF_6873a254_b1633bd7_argGet(i));
                }
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_error_format)) {
                (void)(i += 1);
                if (i < argc) {
                    cli.error_format = zF_127049be_a46d5897_parseErrorFormat(zF_6873a254_b1633bd7_argGet(i));
                }
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_track_memory)) {
                cli.track_memory = 1;
            } else             if (zF_127049be_fe9362ca_matchFlag(arg, s_include)) {
                (void)(i += 1);
                if (i < argc && cli.include_count < 16) {
                    cli.include_dirs[(usize)cli.include_count] = zF_127049be_c99c8b7c_cstrToSlice(zF_6873a254_b1633bd7_argGet(i));
                    (void)(cli.include_count += 1);
                }
            } else {
                cli.input_file = zF_127049be_c99c8b7c_cstrToSlice(arg_ptr);
            }














        } else {
            cli.input_file = zF_127049be_c99c8b7c_cstrToSlice(arg_ptr);
        }
        (void)(i += 1);
    }
    goto __loop_0_start;
    __loop_0_end: ;
    return cli;
}

static int zF_127049be_fe9362ca_matchFlag(Slice_u8 arg, Slice_u8 flag) {
    usize j = 0;
    if (arg.len != flag.len) {
        return 0;
    }
    __loop_0_start: ;
    if (!(j < arg.len)) goto __loop_0_end;
    {
        if (arg.ptr[j] != flag.ptr[j]) {
            return 0;
        }
        (void)(j += 1);
    }
    goto __loop_0_start;
    __loop_0_end: ;
    return 1;
}

static Slice_u8 zF_127049be_c99c8b7c_cstrToSlice(unsigned char const* ptr) {
    usize len = 0;
    __loop_0_start: ;
    if (!(ptr[len] != 0)) goto __loop_0_end;
    {
        (void)(len += 1);
    }
    goto __loop_0_start;
    __loop_0_end: ;
    return __make_slice_u8(ptr + 0, len - 0);
}

static unsigned int zF_127049be_48fe8a0b_parseSize(unsigned char const* ptr) {
    Slice_u8 s;
    unsigned int val = 0;
    usize i = 0;
    s = zF_127049be_c99c8b7c_cstrToSlice(ptr);
    __loop_0_start: ;
    if (!(i < s.len)) goto __loop_0_end;
    {
        unsigned char c;
        c = s.ptr[i];
        if (c >= '0' && c <= '9') {
            val = val * 10 + (unsigned int)c - '0';
        } else         if (c == 'k' || c == 'K') {
            val = val * 1024;
        } else         if (c == 'm' || c == 'M') {
            val = val * 1024 * 1024;
        } else         if (c == 'g' || c == 'G') {
            val = val * 1024 * 1024 * 1024;
        }



        (void)(i += 1);
    }
    goto __loop_0_start;
    __loop_0_end: ;
    return val;
}

static unsigned int zF_127049be_f1af05a0_parseU32(unsigned char const* ptr) {
    Slice_u8 s;
    unsigned int val = 0;
    usize i = 0;
    s = zF_127049be_c99c8b7c_cstrToSlice(ptr);
    __loop_0_start: ;
    if (!(i < s.len)) goto __loop_0_end;
    {
        unsigned char c;
        c = s.ptr[i];
        if (c >= '0' && c <= '9') {
            val = val * 10 + (unsigned int)c - '0';
        }
        (void)(i += 1);
    }
    goto __loop_0_start;
    __loop_0_end: ;
    return val;
}

static enum zS_127049be_b8a04c98_ColorMode zF_127049be_46538142_parseColorMode(unsigned char const* ptr) {
    Slice_u8 s;
    Slice_u8 s_always;
    Slice_u8 s_never;
    s = zF_127049be_c99c8b7c_cstrToSlice(ptr);
    s_always = __make_slice_u8("always", 6);
    s_never = __make_slice_u8("never", 5);
    if (zF_127049be_fe9362ca_matchFlag(s, s_always)) {
        return zS_127049be_b8a04c98_ColorMode_always;
    }
    if (zF_127049be_fe9362ca_matchFlag(s, s_never)) {
        return zS_127049be_b8a04c98_ColorMode_never;
    }
    return zS_127049be_b8a04c98_ColorMode_auto;
}

static enum zS_127049be_b6e8e37d_ErrorFormat zF_127049be_a46d5897_parseErrorFormat(unsigned char const* ptr) {
    Slice_u8 s;
    Slice_u8 s_json;
    Slice_u8 s_sarif;
    s = zF_127049be_c99c8b7c_cstrToSlice(ptr);
    s_json = __make_slice_u8("json", 4);
    s_sarif = __make_slice_u8("sarif", 5);
    if (zF_127049be_fe9362ca_matchFlag(s, s_json)) {
        return zS_127049be_b6e8e37d_ErrorFormat_json;
    }
    if (zF_127049be_fe9362ca_matchFlag(s, s_sarif)) {
        return zS_127049be_b6e8e37d_ErrorFormat_sarif;
    }
    return zS_127049be_b6e8e37d_ErrorFormat_human;
}

static void zF_127049be_0da25b91_printUsage(void) {
    Slice_u8 msg;
    msg = __make_slice_u8("zig1 - Z98 self-hosted compiler - usage: zig1 [options] <input.zig>\n", 68);
    zF_6873a254_1dc3fa43_stderr_write(msg);
}
