/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "name_mangler.h"


struct zS_ab5e085b_2cf354c9_NameMangler zF_ab5e085b_1f08a8de_nameManglerInit(void) {
    {
        struct zS_ab5e085b_2cf354c9_NameMangler __return_val = {0};
        __return_val.counter = 0U;
        return __return_val;
    }
}
