/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "parser.h"
#include "token.h"
#include "ast.h"
#include "allocator.h"
#include "diagnostics.h"
#include "string_interner.h"
#include "growable_array.h"


struct zS_89baa7c0_7a3512d8_Token;
#ifndef ZIG_ENUM_zS_89baa7c0_facdb0ca_TokenKind
#define ZIG_ENUM_zS_89baa7c0_facdb0ca_TokenKind
enum zS_89baa7c0_facdb0ca_TokenKind {
    zS_89baa7c0_facdb0ca_TokenKind_integer_literal = 0,
    zS_89baa7c0_facdb0ca_TokenKind_float_literal = 1,
    zS_89baa7c0_facdb0ca_TokenKind_string_literal = 2,
    zS_89baa7c0_facdb0ca_TokenKind_char_literal = 3,
    zS_89baa7c0_facdb0ca_TokenKind_identifier = 4,
    zS_89baa7c0_facdb0ca_TokenKind_builtin_identifier = 5,
    zS_89baa7c0_facdb0ca_TokenKind_lparen = 6,
    zS_89baa7c0_facdb0ca_TokenKind_rparen = 7,
    zS_89baa7c0_facdb0ca_TokenKind_lbracket = 8,
    zS_89baa7c0_facdb0ca_TokenKind_rbracket = 9,
    zS_89baa7c0_facdb0ca_TokenKind_lbrace = 10,
    zS_89baa7c0_facdb0ca_TokenKind_rbrace = 11,
    zS_89baa7c0_facdb0ca_TokenKind_semicolon = 12,
    zS_89baa7c0_facdb0ca_TokenKind_colon = 13,
    zS_89baa7c0_facdb0ca_TokenKind_comma = 14,
    zS_89baa7c0_facdb0ca_TokenKind_dot = 15,
    zS_89baa7c0_facdb0ca_TokenKind_at_sign = 16,
    zS_89baa7c0_facdb0ca_TokenKind_underscore = 17,
    zS_89baa7c0_facdb0ca_TokenKind_question_mark = 18,
    zS_89baa7c0_facdb0ca_TokenKind_bang = 19,
    zS_89baa7c0_facdb0ca_TokenKind_plus = 20,
    zS_89baa7c0_facdb0ca_TokenKind_minus = 21,
    zS_89baa7c0_facdb0ca_TokenKind_star = 22,
    zS_89baa7c0_facdb0ca_TokenKind_slash = 23,
    zS_89baa7c0_facdb0ca_TokenKind_percent = 24,
    zS_89baa7c0_facdb0ca_TokenKind_ampersand = 25,
    zS_89baa7c0_facdb0ca_TokenKind_pipe = 26,
    zS_89baa7c0_facdb0ca_TokenKind_caret = 27,
    zS_89baa7c0_facdb0ca_TokenKind_tilde = 28,
    zS_89baa7c0_facdb0ca_TokenKind_shl = 29,
    zS_89baa7c0_facdb0ca_TokenKind_shr = 30,
    zS_89baa7c0_facdb0ca_TokenKind_eq_eq = 31,
    zS_89baa7c0_facdb0ca_TokenKind_bang_eq = 32,
    zS_89baa7c0_facdb0ca_TokenKind_less = 33,
    zS_89baa7c0_facdb0ca_TokenKind_less_eq = 34,
    zS_89baa7c0_facdb0ca_TokenKind_greater = 35,
    zS_89baa7c0_facdb0ca_TokenKind_greater_eq = 36,
    zS_89baa7c0_facdb0ca_TokenKind_eq = 37,
    zS_89baa7c0_facdb0ca_TokenKind_plus_eq = 38,
    zS_89baa7c0_facdb0ca_TokenKind_minus_eq = 39,
    zS_89baa7c0_facdb0ca_TokenKind_star_eq = 40,
    zS_89baa7c0_facdb0ca_TokenKind_slash_eq = 41,
    zS_89baa7c0_facdb0ca_TokenKind_percent_eq = 42,
    zS_89baa7c0_facdb0ca_TokenKind_ampersand_eq = 43,
    zS_89baa7c0_facdb0ca_TokenKind_pipe_eq = 44,
    zS_89baa7c0_facdb0ca_TokenKind_caret_eq = 45,
    zS_89baa7c0_facdb0ca_TokenKind_shl_eq = 46,
    zS_89baa7c0_facdb0ca_TokenKind_shr_eq = 47,
    zS_89baa7c0_facdb0ca_TokenKind_dot_dot = 48,
    zS_89baa7c0_facdb0ca_TokenKind_dot_dot_dot = 49,
    zS_89baa7c0_facdb0ca_TokenKind_dot_lbrace = 50,
    zS_89baa7c0_facdb0ca_TokenKind_dot_star = 51,
    zS_89baa7c0_facdb0ca_TokenKind_fat_arrow = 52,
    zS_89baa7c0_facdb0ca_TokenKind_kw_const = 53,
    zS_89baa7c0_facdb0ca_TokenKind_kw_var = 54,
    zS_89baa7c0_facdb0ca_TokenKind_kw_fn = 55,
    zS_89baa7c0_facdb0ca_TokenKind_kw_pub = 56,
    zS_89baa7c0_facdb0ca_TokenKind_kw_extern = 57,
    zS_89baa7c0_facdb0ca_TokenKind_kw_export = 58,
    zS_89baa7c0_facdb0ca_TokenKind_kw_test = 59,
    zS_89baa7c0_facdb0ca_TokenKind_kw_struct = 60,
    zS_89baa7c0_facdb0ca_TokenKind_kw_enum = 61,
    zS_89baa7c0_facdb0ca_TokenKind_kw_union = 62,
    zS_89baa7c0_facdb0ca_TokenKind_kw_if = 63,
    zS_89baa7c0_facdb0ca_TokenKind_kw_else = 64,
    zS_89baa7c0_facdb0ca_TokenKind_kw_while = 65,
    zS_89baa7c0_facdb0ca_TokenKind_kw_for = 66,
    zS_89baa7c0_facdb0ca_TokenKind_kw_switch = 67,
    zS_89baa7c0_facdb0ca_TokenKind_kw_return = 68,
    zS_89baa7c0_facdb0ca_TokenKind_kw_break = 69,
    zS_89baa7c0_facdb0ca_TokenKind_kw_continue = 70,
    zS_89baa7c0_facdb0ca_TokenKind_kw_defer = 71,
    zS_89baa7c0_facdb0ca_TokenKind_kw_errdefer = 72,
    zS_89baa7c0_facdb0ca_TokenKind_kw_try = 73,
    zS_89baa7c0_facdb0ca_TokenKind_kw_catch = 74,
    zS_89baa7c0_facdb0ca_TokenKind_kw_orelse = 75,
    zS_89baa7c0_facdb0ca_TokenKind_kw_error = 76,
    zS_89baa7c0_facdb0ca_TokenKind_kw_and = 77,
    zS_89baa7c0_facdb0ca_TokenKind_kw_or = 78,
    zS_89baa7c0_facdb0ca_TokenKind_kw_true = 79,
    zS_89baa7c0_facdb0ca_TokenKind_kw_false = 80,
    zS_89baa7c0_facdb0ca_TokenKind_kw_null = 81,
    zS_89baa7c0_facdb0ca_TokenKind_kw_undefined = 82,
    zS_89baa7c0_facdb0ca_TokenKind_kw_unreachable = 83,
    zS_89baa7c0_facdb0ca_TokenKind_kw_void = 84,
    zS_89baa7c0_facdb0ca_TokenKind_kw_bool = 85,
    zS_89baa7c0_facdb0ca_TokenKind_kw_noreturn = 86,
    zS_89baa7c0_facdb0ca_TokenKind_kw_c_char = 87,
    zS_89baa7c0_facdb0ca_TokenKind_eof = 88,
    zS_89baa7c0_facdb0ca_TokenKind_err_token = 89
};
typedef enum zS_89baa7c0_facdb0ca_TokenKind zS_89baa7c0_facdb0ca_TokenKind;

#endif /* ZIG_ENUM_zS_89baa7c0_facdb0ca_TokenKind */

struct zS_c313e0ed_6592c721_AstStore;
struct zS_26b5a9a4_43f95de6_Sand;
struct zS_9daadfc5_490018d3_DiagnosticCollector;
struct zS_4c1e99d4_67d40cc9_StringInterner;
struct zS_16d7ab7a_840ccd30_U32ArrayList;
#ifndef ZIG_ENUM_zS_c313e0ed_906c25e2_AstKind
#define ZIG_ENUM_zS_c313e0ed_906c25e2_AstKind
enum zS_c313e0ed_906c25e2_AstKind {
    zS_c313e0ed_906c25e2_AstKind_err = 0,
    zS_c313e0ed_906c25e2_AstKind_var_decl = 1,
    zS_c313e0ed_906c25e2_AstKind_fn_decl = 2,
    zS_c313e0ed_906c25e2_AstKind_struct_decl = 3,
    zS_c313e0ed_906c25e2_AstKind_enum_decl = 4,
    zS_c313e0ed_906c25e2_AstKind_union_decl = 5,
    zS_c313e0ed_906c25e2_AstKind_field_decl = 6,
    zS_c313e0ed_906c25e2_AstKind_param_decl = 7,
    zS_c313e0ed_906c25e2_AstKind_test_decl = 8,
    zS_c313e0ed_906c25e2_AstKind_error_set_decl = 9,
    zS_c313e0ed_906c25e2_AstKind_int_literal = 10,
    zS_c313e0ed_906c25e2_AstKind_float_literal = 11,
    zS_c313e0ed_906c25e2_AstKind_string_literal = 12,
    zS_c313e0ed_906c25e2_AstKind_char_literal = 13,
    zS_c313e0ed_906c25e2_AstKind_bool_literal = 14,
    zS_c313e0ed_906c25e2_AstKind_null_literal = 15,
    zS_c313e0ed_906c25e2_AstKind_undefined_literal = 16,
    zS_c313e0ed_906c25e2_AstKind_unreachable_expr = 17,
    zS_c313e0ed_906c25e2_AstKind_enum_literal = 18,
    zS_c313e0ed_906c25e2_AstKind_error_literal = 19,
    zS_c313e0ed_906c25e2_AstKind_tuple_literal = 20,
    zS_c313e0ed_906c25e2_AstKind_struct_init = 21,
    zS_c313e0ed_906c25e2_AstKind_field_init = 22,
    zS_c313e0ed_906c25e2_AstKind_ident_expr = 23,
    zS_c313e0ed_906c25e2_AstKind_field_access = 24,
    zS_c313e0ed_906c25e2_AstKind_index_access = 25,
    zS_c313e0ed_906c25e2_AstKind_slice_expr = 26,
    zS_c313e0ed_906c25e2_AstKind_deref = 27,
    zS_c313e0ed_906c25e2_AstKind_address_of = 28,
    zS_c313e0ed_906c25e2_AstKind_fn_call = 29,
    zS_c313e0ed_906c25e2_AstKind_builtin_call = 30,
    zS_c313e0ed_906c25e2_AstKind_paren_expr = 31,
    zS_c313e0ed_906c25e2_AstKind_add = 32,
    zS_c313e0ed_906c25e2_AstKind_sub = 33,
    zS_c313e0ed_906c25e2_AstKind_mul = 34,
    zS_c313e0ed_906c25e2_AstKind_div = 35,
    zS_c313e0ed_906c25e2_AstKind_mod_op = 36,
    zS_c313e0ed_906c25e2_AstKind_bit_and = 37,
    zS_c313e0ed_906c25e2_AstKind_bit_or = 38,
    zS_c313e0ed_906c25e2_AstKind_bit_xor = 39,
    zS_c313e0ed_906c25e2_AstKind_shl = 40,
    zS_c313e0ed_906c25e2_AstKind_shr = 41,
    zS_c313e0ed_906c25e2_AstKind_bool_and = 42,
    zS_c313e0ed_906c25e2_AstKind_bool_or = 43,
    zS_c313e0ed_906c25e2_AstKind_cmp_eq = 44,
    zS_c313e0ed_906c25e2_AstKind_cmp_ne = 45,
    zS_c313e0ed_906c25e2_AstKind_cmp_lt = 46,
    zS_c313e0ed_906c25e2_AstKind_cmp_le = 47,
    zS_c313e0ed_906c25e2_AstKind_cmp_gt = 48,
    zS_c313e0ed_906c25e2_AstKind_cmp_ge = 49,
    zS_c313e0ed_906c25e2_AstKind_assign = 50,
    zS_c313e0ed_906c25e2_AstKind_add_assign = 51,
    zS_c313e0ed_906c25e2_AstKind_sub_assign = 52,
    zS_c313e0ed_906c25e2_AstKind_mul_assign = 53,
    zS_c313e0ed_906c25e2_AstKind_div_assign = 54,
    zS_c313e0ed_906c25e2_AstKind_mod_assign = 55,
    zS_c313e0ed_906c25e2_AstKind_shl_assign = 56,
    zS_c313e0ed_906c25e2_AstKind_shr_assign = 57,
    zS_c313e0ed_906c25e2_AstKind_and_assign = 58,
    zS_c313e0ed_906c25e2_AstKind_xor_assign = 59,
    zS_c313e0ed_906c25e2_AstKind_or_assign = 60,
    zS_c313e0ed_906c25e2_AstKind_negate = 61,
    zS_c313e0ed_906c25e2_AstKind_bool_not = 62,
    zS_c313e0ed_906c25e2_AstKind_bit_not = 63,
    zS_c313e0ed_906c25e2_AstKind_try_expr = 64,
    zS_c313e0ed_906c25e2_AstKind_catch_expr = 65,
    zS_c313e0ed_906c25e2_AstKind_orelse_expr = 66,
    zS_c313e0ed_906c25e2_AstKind_if_stmt = 67,
    zS_c313e0ed_906c25e2_AstKind_if_expr = 68,
    zS_c313e0ed_906c25e2_AstKind_if_capture = 69,
    zS_c313e0ed_906c25e2_AstKind_while_stmt = 70,
    zS_c313e0ed_906c25e2_AstKind_while_capture = 71,
    zS_c313e0ed_906c25e2_AstKind_for_stmt = 72,
    zS_c313e0ed_906c25e2_AstKind_switch_expr = 73,
    zS_c313e0ed_906c25e2_AstKind_switch_prong = 74,
    zS_c313e0ed_906c25e2_AstKind_block = 75,
    zS_c313e0ed_906c25e2_AstKind_return_stmt = 76,
    zS_c313e0ed_906c25e2_AstKind_break_stmt = 77,
    zS_c313e0ed_906c25e2_AstKind_continue_stmt = 78,
    zS_c313e0ed_906c25e2_AstKind_defer_stmt = 79,
    zS_c313e0ed_906c25e2_AstKind_errdefer_stmt = 80,
    zS_c313e0ed_906c25e2_AstKind_labeled_stmt = 81,
    zS_c313e0ed_906c25e2_AstKind_expr_stmt = 82,
    zS_c313e0ed_906c25e2_AstKind_ptr_type = 83,
    zS_c313e0ed_906c25e2_AstKind_many_ptr_type = 84,
    zS_c313e0ed_906c25e2_AstKind_array_type = 85,
    zS_c313e0ed_906c25e2_AstKind_slice_type = 86,
    zS_c313e0ed_906c25e2_AstKind_optional_type = 87,
    zS_c313e0ed_906c25e2_AstKind_error_union_type = 88,
    zS_c313e0ed_906c25e2_AstKind_fn_type = 89,
    zS_c313e0ed_906c25e2_AstKind_import_expr = 90,
    zS_c313e0ed_906c25e2_AstKind_module_root = 91,
    zS_c313e0ed_906c25e2_AstKind_payload_capture = 92,
    zS_c313e0ed_906c25e2_AstKind_range_exclusive = 93,
    zS_c313e0ed_906c25e2_AstKind_range_inclusive = 94
};
typedef enum zS_c313e0ed_906c25e2_AstKind zS_c313e0ed_906c25e2_AstKind;

#endif /* ZIG_ENUM_zS_c313e0ed_906c25e2_AstKind */

struct zS_a8a3052c_39daa34f_ParseToken;
struct zS_a8a3052c_244bd7c4_OpInfo;
#ifndef ZIG_STRUCT_zS_89baa7c0_7a3512d8_Token
#define ZIG_STRUCT_zS_89baa7c0_7a3512d8_Token
struct zS_89baa7c0_7a3512d8_Token {
    enum zS_89baa7c0_facdb0ca_TokenKind kind;
    unsigned int span_start;
    unsigned short span_len;
    union zS_89baa7c0_39b0b709_TokenValue value;
};

#endif /* ZIG_STRUCT_zS_89baa7c0_7a3512d8_Token */

#ifndef ZIG_STRUCT_zS_c313e0ed_6592c721_AstStore
#define ZIG_STRUCT_zS_c313e0ed_6592c721_AstStore
#ifndef ZIG_STRUCT_zS_c313e0ed_1adfeb96_anon_1
#define ZIG_STRUCT_zS_c313e0ed_1adfeb96_anon_1
struct zS_c313e0ed_1adfeb96_anon_1 {
    struct zS_c313e0ed_f3385aec_AstNode* items;
    usize len;
    usize capacity;
};

#endif /* ZIG_STRUCT_zS_c313e0ed_1adfeb96_anon_1 */

#ifndef ZIG_STRUCT_zS_c313e0ed_19dfea03_anon_2
#define ZIG_STRUCT_zS_c313e0ed_19dfea03_anon_2
struct zS_c313e0ed_19dfea03_anon_2 {
    unsigned int* items;
    usize len;
    usize capacity;
};

#endif /* ZIG_STRUCT_zS_c313e0ed_19dfea03_anon_2 */

#ifndef ZIG_STRUCT_zS_c313e0ed_18dfe870_anon_3
#define ZIG_STRUCT_zS_c313e0ed_18dfe870_anon_3
struct zS_c313e0ed_18dfe870_anon_3 {
    unsigned int* items;
    usize len;
    usize capacity;
};

#endif /* ZIG_STRUCT_zS_c313e0ed_18dfe870_anon_3 */

#ifndef ZIG_STRUCT_zS_c313e0ed_1fdff375_anon_4
#define ZIG_STRUCT_zS_c313e0ed_1fdff375_anon_4
struct zS_c313e0ed_1fdff375_anon_4 {
    u64* items;
    usize len;
    usize capacity;
};

#endif /* ZIG_STRUCT_zS_c313e0ed_1fdff375_anon_4 */

#ifndef ZIG_STRUCT_zS_c313e0ed_1edff1e2_anon_5
#define ZIG_STRUCT_zS_c313e0ed_1edff1e2_anon_5
struct zS_c313e0ed_1edff1e2_anon_5 {
    double* items;
    usize len;
    usize capacity;
};

#endif /* ZIG_STRUCT_zS_c313e0ed_1edff1e2_anon_5 */

#ifndef ZIG_STRUCT_zS_c313e0ed_1ddff04f_anon_6
#define ZIG_STRUCT_zS_c313e0ed_1ddff04f_anon_6
struct zS_c313e0ed_1ddff04f_anon_6 {
    unsigned int* items;
    usize len;
    usize capacity;
};

#endif /* ZIG_STRUCT_zS_c313e0ed_1ddff04f_anon_6 */

#ifndef ZIG_STRUCT_zS_c313e0ed_1cdfeebc_anon_7
#define ZIG_STRUCT_zS_c313e0ed_1cdfeebc_anon_7
struct zS_c313e0ed_1cdfeebc_anon_7 {
    struct zS_c313e0ed_42ae50fe_FnProto* items;
    usize len;
    usize capacity;
};

#endif /* ZIG_STRUCT_zS_c313e0ed_1cdfeebc_anon_7 */

struct zS_c313e0ed_6592c721_AstStore {
    struct zS_c313e0ed_1adfeb96_anon_1 nodes;
    struct zS_c313e0ed_19dfea03_anon_2 extra_children;
    struct zS_c313e0ed_18dfe870_anon_3 identifiers;
    struct zS_c313e0ed_1fdff375_anon_4 int_values;
    struct zS_c313e0ed_1edff1e2_anon_5 float_values;
    struct zS_c313e0ed_1ddff04f_anon_6 string_values;
    struct zS_c313e0ed_1cdfeebc_anon_7 fn_protos;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_c313e0ed_6592c721_AstStore */

struct zS_c313e0ed_1adfeb96_anon_1;
struct zS_c313e0ed_19dfea03_anon_2;
struct zS_c313e0ed_18dfe870_anon_3;
struct zS_c313e0ed_1fdff375_anon_4;
struct zS_c313e0ed_1edff1e2_anon_5;
struct zS_c313e0ed_1ddff04f_anon_6;
struct zS_c313e0ed_1cdfeebc_anon_7;
#ifndef ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
#define ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
struct zS_26b5a9a4_43f95de6_Sand {
    unsigned char* start;
    usize pos;
    usize end;
    usize peak;
};

#endif /* ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand */

#ifndef ZIG_STRUCT_zS_9daadfc5_490018d3_DiagnosticCollector
#define ZIG_STRUCT_zS_9daadfc5_490018d3_DiagnosticCollector
struct zS_9daadfc5_490018d3_DiagnosticCollector {
    struct zS_9daadfc5_8924c34d_DiagnosticArrayList* diagnostics;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
    struct zS_2b6fc0a6_29be27be_SourceManager* source_manager;
    struct zS_4c1e99d4_67d40cc9_StringInterner* interner;
    usize error_count;
    usize warning_count;
    usize max_diagnostics;
};

#endif /* ZIG_STRUCT_zS_9daadfc5_490018d3_DiagnosticCollector */

#ifndef ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner
#define ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner
struct zS_4c1e99d4_67d40cc9_StringInterner {
    struct zS_16d7ab7a_840ccd30_U32ArrayList* buckets;
    struct zS_4c1e99d4_face28fc_InternArrayList* entries;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner */

#ifndef ZIG_STRUCT_zS_16d7ab7a_840ccd30_U32ArrayList
#define ZIG_STRUCT_zS_16d7ab7a_840ccd30_U32ArrayList
struct zS_16d7ab7a_840ccd30_U32ArrayList {
    unsigned int* items;
    usize len;
    usize capacity;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_16d7ab7a_840ccd30_U32ArrayList */

static ErrorUnion_u32 zF_a8a3052c_14d0bec7_parserAddBinary(struct zS_a8a3052c_21144d98_Parser*, struct zS_89baa7c0_7a3512d8_Token, unsigned int, unsigned int);
static ErrorUnion_u32 zF_a8a3052c_6548ea96_parserParseIntLiteral(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_764ea86b_parserParseFloatLiteral(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_61532a56_parserParseStringLiteral(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_7dd152a1_parserParseCharLiteral(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_ce63b9e1_parserParseBoolLiteral(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_3ac86cb3_parserParseSingleToken(struct zS_a8a3052c_21144d98_Parser*, enum zS_c313e0ed_906c25e2_AstKind);
static ErrorUnion_u32 zF_a8a3052c_20e2a797_parserParseIdentExpr(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_5d58ea1d_parserParsePrefixUnary(struct zS_a8a3052c_21144d98_Parser*, enum zS_c313e0ed_906c25e2_AstKind);
static ErrorUnion_u32 zF_a8a3052c_b9f4f90f_parserParseGroupedExpr(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_b72bdbcd_parserParseBuiltinCall(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_428daa37_parserParseErrorLiteral(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_b5b93414_parserParseTryExpr(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_19d70a82_parserParseAnonymousLiteral(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_f5491176_parserParseEnumLiteral(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_4f301fea_parserParseIfExpr(struct zS_a8a3052c_21144d98_Parser*);
static ErrorUnion_u32 zF_a8a3052c_8cd8d6e1_parserParseSwitchExpr(struct zS_a8a3052c_21144d98_Parser*);

struct zS_a8a3052c_21144d98_Parser zF_a8a3052c_ce1bae95_parserInit(Slice_zS_89baa7c0_7a3512d8_Token tokens, Slice_u8 source, struct zS_c313e0ed_6592c721_AstStore* store, struct zS_4c1e99d4_67d40cc9_StringInterner* interner, struct zS_9daadfc5_490018d3_DiagnosticCollector* diag, struct zS_26b5a9a4_43f95de6_Sand* alloc) {
    struct zS_89baa7c0_7a3512d8_Token* t_ptr;
    t_ptr = (struct zS_89baa7c0_7a3512d8_Token*)tokens.ptr;
    {
        struct zS_a8a3052c_21144d98_Parser __return_val = {0};
        __return_val.tokens_ptr = t_ptr;
        __return_val.tokens_len = tokens.len;
        __return_val.source_ptr = (unsigned char*)source.ptr;
        __return_val.source_len = source.len;
        __return_val.pos = 0;
        __return_val.store = store;
        __return_val.interner = interner;
        __return_val.diag = diag;
        __return_val.allocator = alloc;
        __return_val.child_buf_len = 0;
        __return_val.child_buf_capacity = 0;
        return __return_val;
    }
}

Slice_u8 zF_a8a3052c_ea3de80f_parserTokenText(struct zS_a8a3052c_21144d98_Parser* self, struct zS_a8a3052c_39daa34f_ParseToken tok) {
    usize start;
    usize end;
    start = (usize)tok.span_start;
    end = start + (usize)tok.span_len;
    return __make_slice_u8(self->source_ptr + start, end - start);
}

struct zS_89baa7c0_7a3512d8_Token zF_a8a3052c_95e6e4e0_parserPeek(struct zS_a8a3052c_21144d98_Parser* self) {
    if (self->pos >= self->tokens_len) {
        return self->tokens_ptr[self->tokens_len - 1];
    }
    return self->tokens_ptr[self->pos];
}

struct zS_89baa7c0_7a3512d8_Token zF_a8a3052c_a879fdea_parserPeekN(struct zS_a8a3052c_21144d98_Parser* self, usize n) {
    usize idx;
    idx = self->pos + n;
    if (idx >= self->tokens_len) {
        return self->tokens_ptr[self->tokens_len - 1];
    }
    return self->tokens_ptr[idx];
}

struct zS_89baa7c0_7a3512d8_Token zF_a8a3052c_33256f43_parserAdvance(struct zS_a8a3052c_21144d98_Parser* self) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    tok = zF_a8a3052c_95e6e4e0_parserPeek(self);
    if (self->pos < self->tokens_len) {
        (void)(self->pos += 1);
    }
    return tok;
}

ErrorUnion_zS_a8a3052c_39daa34f_ParseToken zF_a8a3052c_48a6f942_parserExpect(struct zS_a8a3052c_21144d98_Parser* self, enum zS_89baa7c0_facdb0ca_TokenKind kind) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    tok = zF_a8a3052c_95e6e4e0_parserPeek(self);
    if (tok.kind != kind) {
        Slice_u8 expect_msg;
        expect_msg = __make_slice_u8("bad tok", 7);
        zF_a8a3052c_3ad126e8_parserAddError(self, tok, expect_msg);
        {
            ErrorUnion_zS_a8a3052c_39daa34f_ParseToken __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_UnexpectedToken;
            return __return_val;
        }
    }
    if (self->pos < self->tokens_len) {
        (void)(self->pos += 1);
    }
    {
        ErrorUnion_zS_a8a3052c_39daa34f_ParseToken __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload.kind = tok.kind;
        __return_val.data.payload.span_start = tok.span_start;
        __return_val.data.payload.span_len = tok.span_len;
        return __return_val;
    }
}

void zF_a8a3052c_3ad126e8_parserAddError(struct zS_a8a3052c_21144d98_Parser* self, struct zS_89baa7c0_7a3512d8_Token tok, Slice_u8 msg) {
    zF_9daadfc5_b5a4ed39_diagnosticCollectorAdd(self->diag, 0, 2000, 0U, tok.span_start, tok.span_start + (unsigned int)tok.span_len, msg);
}

void zF_a8a3052c_0cd6998b_parserSynchronize(struct zS_a8a3052c_21144d98_Parser* self) {
    __loop_0_start: ;
    if (!(self->pos < self->tokens_len)) goto __loop_0_end;
    {
        enum zS_89baa7c0_facdb0ca_TokenKind k;
        k = self->tokens_ptr[self->pos].kind;
        if (k == zS_89baa7c0_facdb0ca_TokenKind_semicolon || k == zS_89baa7c0_facdb0ca_TokenKind_rbrace || k == zS_89baa7c0_facdb0ca_TokenKind_kw_fn || k == zS_89baa7c0_facdb0ca_TokenKind_kw_const || k == zS_89baa7c0_facdb0ca_TokenKind_kw_var || k == zS_89baa7c0_facdb0ca_TokenKind_kw_pub || k == zS_89baa7c0_facdb0ca_TokenKind_kw_test || k == zS_89baa7c0_facdb0ca_TokenKind_eof) {
            return;
        }
        (void)(self->pos += 1);
    }
    goto __loop_0_start;
    __loop_0_end: ;
}

ErrorUnion_u32 zF_a8a3052c_c7ea9b4b_parserParseExprPrec(struct zS_a8a3052c_21144d98_Parser* self, enum zS_a8a3052c_4258ebb9_Prec min_prec) {
    unsigned int __tmp_try_5_11;
    ErrorUnion_u32 __tmp_try_res_5_12;
    unsigned int lhs;
    __tmp_try_res_5_12 = zF_a8a3052c_b05fc3c0_parserParsePrimary(self);
    if (__tmp_try_res_5_12.is_error) {
        return __tmp_try_res_5_12;
    }
    __tmp_try_5_11 = __tmp_try_res_5_12.data.payload;
    lhs = __tmp_try_5_11;
    __loop_0_start: ;
    if (!(1)) goto __loop_0_end;
    {
        struct zS_89baa7c0_7a3512d8_Token tok;
        unsigned char has_info = 0;
        struct zS_a8a3052c_244bd7c4_OpInfo info;
        enum zS_a8a3052c_4258ebb9_Prec next_min;
        unsigned int rhs;
        unsigned int __tmp_try_8_7;
        ErrorUnion_u32 __tmp_try_res_8_8;
        tok = zF_a8a3052c_95e6e4e0_parserPeek(self);
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo opt_tmp;
            opt_tmp = zF_a8a3052c_f55b638a_getInfixInfo(tok.kind);
            if (opt_tmp.has_value) {
                struct zS_a8a3052c_244bd7c4_OpInfo val;
                val = opt_tmp.value;
{
                    info = val;
                    has_info = 1;
                }            }
        }
        if (has_info == 0) {
            /* defers for break */
            goto __loop_0_end;
        }
        if (zF_a8a3052c_f4dd8358_precToInt(info.prec) < zF_a8a3052c_f4dd8358_precToInt(min_prec)) {
            /* defers for break */
            goto __loop_0_end;
        }
        (void)(zF_a8a3052c_33256f43_parserAdvance(self));
        if (info.right_assoc) {
            next_min = info.prec;
        } else {
            next_min = zF_a8a3052c_e02cae07_precFromInt(zF_a8a3052c_f4dd8358_precToInt(info.prec) + 1);
        }
        if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_catch) {
            {
                ErrorUnion_u32 __return_val = {0};
                __return_val.is_error = 1;
                __return_val.data.err = ERROR_UnexpectedToken;
                return __return_val;
            }
        } else         if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_orelse) {
            {
                ErrorUnion_u32 __return_val = {0};
                __return_val.is_error = 1;
                __return_val.data.err = ERROR_UnexpectedToken;
                return __return_val;
            }
        } else {
            unsigned int __tmp_try_11_9;
            ErrorUnion_u32 __tmp_try_res_11_10;
            __tmp_try_res_11_10 = zF_a8a3052c_c7ea9b4b_parserParseExprPrec(self, next_min);
            if (__tmp_try_res_11_10.is_error) {
                return __tmp_try_res_11_10;
            }
            __tmp_try_11_9 = __tmp_try_res_11_10.data.payload;
            rhs = __tmp_try_11_9;
        }

        __tmp_try_res_8_8 = zF_a8a3052c_14d0bec7_parserAddBinary(self, tok, lhs, rhs);
        if (__tmp_try_res_8_8.is_error) {
            return __tmp_try_res_8_8;
        }
        __tmp_try_8_7 = __tmp_try_res_8_8.data.payload;
        lhs = __tmp_try_8_7;
    }
    goto __loop_0_start;
    __loop_0_end: ;
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = lhs;
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_14d0bec7_parserAddBinary(struct zS_a8a3052c_21144d98_Parser* self, struct zS_89baa7c0_7a3512d8_Token tok, unsigned int lhs, unsigned int rhs) {
    enum zS_c313e0ed_906c25e2_AstKind kind;
    unsigned char found = 0;
    unsigned int end;
/* DEBUG: emitSwitch start */
    switch (tok.kind) {
        case zS_89baa7c0_facdb0ca_TokenKind_plus:
{
                kind = zS_c313e0ed_906c25e2_AstKind_add;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_minus:
{
                kind = zS_c313e0ed_906c25e2_AstKind_sub;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_star:
{
                kind = zS_c313e0ed_906c25e2_AstKind_mul;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_slash:
{
                kind = zS_c313e0ed_906c25e2_AstKind_div;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_percent:
{
                kind = zS_c313e0ed_906c25e2_AstKind_mod_op;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_ampersand:
{
                kind = zS_c313e0ed_906c25e2_AstKind_bit_and;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_pipe:
{
                kind = zS_c313e0ed_906c25e2_AstKind_bit_or;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_caret:
{
                kind = zS_c313e0ed_906c25e2_AstKind_bit_xor;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_shl:
{
                kind = zS_c313e0ed_906c25e2_AstKind_shl;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_shr:
{
                kind = zS_c313e0ed_906c25e2_AstKind_shr;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_kw_and:
{
                kind = zS_c313e0ed_906c25e2_AstKind_bool_and;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_kw_or:
{
                kind = zS_c313e0ed_906c25e2_AstKind_bool_or;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_eq_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_cmp_eq;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_bang_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_cmp_ne;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_less:
{
                kind = zS_c313e0ed_906c25e2_AstKind_cmp_lt;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_less_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_cmp_le;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_greater:
{
                kind = zS_c313e0ed_906c25e2_AstKind_cmp_gt;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_greater_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_cmp_ge;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_assign;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_plus_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_add_assign;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_minus_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_sub_assign;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_star_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_mul_assign;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_slash_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_div_assign;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_percent_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_mod_assign;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_shl_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_shl_assign;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_shr_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_shr_assign;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_ampersand_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_and_assign;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_pipe_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_or_assign;
                found = 1;
            }            break;
        case zS_89baa7c0_facdb0ca_TokenKind_caret_eq:
{
                kind = zS_c313e0ed_906c25e2_AstKind_xor_assign;
                found = 1;
            }            break;
        default:
{
            }            break;
    }
    if (found == 0) {
        Slice_u8 add_msg;
        add_msg = __make_slice_u8("bad op", 6);
        zF_a8a3052c_3ad126e8_parserAddError(self, tok, add_msg);
        {
            ErrorUnion_u32 __return_val = {0};
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_UnexpectedToken;
            return __return_val;
        }
    }
    end = tok.span_start + (unsigned int)tok.span_len;
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = zF_c313e0ed_eeeed775_astStoreAddNode(self->store, kind, 0, tok.span_start, end, lhs, rhs, 0, 0);
        return __return_val;
    }
}

ErrorUnion_u32 zF_a8a3052c_b05fc3c0_parserParsePrimary(struct zS_a8a3052c_21144d98_Parser* self) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    Slice_u8 primary_msg;
    tok = zF_a8a3052c_95e6e4e0_parserPeek(self);
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_integer_literal) {
        return zF_a8a3052c_6548ea96_parserParseIntLiteral(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_float_literal) {
        return zF_a8a3052c_764ea86b_parserParseFloatLiteral(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_string_literal) {
        return zF_a8a3052c_61532a56_parserParseStringLiteral(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_char_literal) {
        return zF_a8a3052c_7dd152a1_parserParseCharLiteral(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_true) {
        return zF_a8a3052c_ce63b9e1_parserParseBoolLiteral(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_false) {
        return zF_a8a3052c_ce63b9e1_parserParseBoolLiteral(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_null) {
        return zF_a8a3052c_3ac86cb3_parserParseSingleToken(self, zS_c313e0ed_906c25e2_AstKind_null_literal);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_undefined) {
        return zF_a8a3052c_3ac86cb3_parserParseSingleToken(self, zS_c313e0ed_906c25e2_AstKind_undefined_literal);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_unreachable) {
        return zF_a8a3052c_3ac86cb3_parserParseSingleToken(self, zS_c313e0ed_906c25e2_AstKind_unreachable_expr);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_identifier) {
        return zF_a8a3052c_20e2a797_parserParseIdentExpr(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_builtin_identifier) {
        return zF_a8a3052c_b72bdbcd_parserParseBuiltinCall(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_error) {
        return zF_a8a3052c_428daa37_parserParseErrorLiteral(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_minus) {
        return zF_a8a3052c_5d58ea1d_parserParsePrefixUnary(self, zS_c313e0ed_906c25e2_AstKind_negate);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_bang) {
        return zF_a8a3052c_5d58ea1d_parserParsePrefixUnary(self, zS_c313e0ed_906c25e2_AstKind_bool_not);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_tilde) {
        return zF_a8a3052c_5d58ea1d_parserParsePrefixUnary(self, zS_c313e0ed_906c25e2_AstKind_bit_not);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_ampersand) {
        return zF_a8a3052c_5d58ea1d_parserParsePrefixUnary(self, zS_c313e0ed_906c25e2_AstKind_address_of);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_try) {
        return zF_a8a3052c_b5b93414_parserParseTryExpr(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_lparen) {
        return zF_a8a3052c_b9f4f90f_parserParseGroupedExpr(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_dot_lbrace) {
        return zF_a8a3052c_19d70a82_parserParseAnonymousLiteral(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_dot) {
        return zF_a8a3052c_f5491176_parserParseEnumLiteral(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_if) {
        return zF_a8a3052c_4f301fea_parserParseIfExpr(self);
    }
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_switch) {
        return zF_a8a3052c_8cd8d6e1_parserParseSwitchExpr(self);
    }
    primary_msg = __make_slice_u8("bad expr", 8);
    zF_a8a3052c_3ad126e8_parserAddError(self, tok, primary_msg);
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_UnexpectedToken;
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_6548ea96_parserParseIntLiteral(struct zS_a8a3052c_21144d98_Parser* self) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    unsigned int end;
    tok = zF_a8a3052c_33256f43_parserAdvance(self);
    end = tok.span_start + (unsigned int)tok.span_len;
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = zF_c313e0ed_b98b4cad_astStoreAddIntLiteral(self->store, tok.value.int_val, tok.span_start, end);
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_764ea86b_parserParseFloatLiteral(struct zS_a8a3052c_21144d98_Parser* self) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    unsigned int end;
    tok = zF_a8a3052c_33256f43_parserAdvance(self);
    end = tok.span_start + (unsigned int)tok.span_len;
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = zF_c313e0ed_94cb00fc_astStoreAddFloatLiteral(self->store, tok.value.float_val, tok.span_start, end);
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_61532a56_parserParseStringLiteral(struct zS_a8a3052c_21144d98_Parser* self) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    struct zS_a8a3052c_39daa34f_ParseToken pt;
    Slice_u8 text;
    unsigned int id;
    unsigned int end;
    tok = zF_a8a3052c_33256f43_parserAdvance(self);
    pt.kind = tok.kind;
    pt.span_start = tok.span_start;
    pt.span_len = tok.span_len;
    text = zF_a8a3052c_ea3de80f_parserTokenText(self, pt);
    id = zF_4c1e99d4_eb67b606_stringInternerIntern(self->interner, text);
    end = tok.span_start + (unsigned int)tok.span_len;
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = zF_c313e0ed_9743289f_astStoreAddStringLiteral(self->store, id, tok.span_start, end);
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_7dd152a1_parserParseCharLiteral(struct zS_a8a3052c_21144d98_Parser* self) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    unsigned int end;
    tok = zF_a8a3052c_33256f43_parserAdvance(self);
    end = tok.span_start + (unsigned int)tok.span_len;
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = zF_c313e0ed_eeeed775_astStoreAddNode(self->store, zS_c313e0ed_906c25e2_AstKind_char_literal, 0, tok.span_start, end, 0, 0, 0, 0);
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_ce63b9e1_parserParseBoolLiteral(struct zS_a8a3052c_21144d98_Parser* self) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    unsigned char val = 0;
    unsigned int end;
    tok = zF_a8a3052c_33256f43_parserAdvance(self);
    if (tok.kind == zS_89baa7c0_facdb0ca_TokenKind_kw_true) {
        val = 1;
    }
    end = tok.span_start + (unsigned int)tok.span_len;
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = zF_c313e0ed_eeeed775_astStoreAddNode(self->store, zS_c313e0ed_906c25e2_AstKind_bool_literal, val, tok.span_start, end, 0, 0, 0, 0);
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_3ac86cb3_parserParseSingleToken(struct zS_a8a3052c_21144d98_Parser* self, enum zS_c313e0ed_906c25e2_AstKind kind) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    unsigned int end;
    tok = zF_a8a3052c_33256f43_parserAdvance(self);
    end = tok.span_start + (unsigned int)tok.span_len;
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = zF_c313e0ed_eeeed775_astStoreAddNode(self->store, kind, 0, tok.span_start, end, 0, 0, 0, 0);
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_20e2a797_parserParseIdentExpr(struct zS_a8a3052c_21144d98_Parser* self) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    struct zS_a8a3052c_39daa34f_ParseToken pt;
    unsigned int id;
    unsigned int end;
    tok = zF_a8a3052c_33256f43_parserAdvance(self);
    pt.kind = tok.kind;
    pt.span_start = tok.span_start;
    pt.span_len = tok.span_len;
    id = zF_4c1e99d4_eb67b606_stringInternerIntern(self->interner, zF_a8a3052c_ea3de80f_parserTokenText(self, pt));
    end = tok.span_start + (unsigned int)tok.span_len;
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = zF_c313e0ed_1c79e2e6_astStoreAddIdentifier(self->store, zS_c313e0ed_906c25e2_AstKind_ident_expr, id, tok.span_start, end);
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_5d58ea1d_parserParsePrefixUnary(struct zS_a8a3052c_21144d98_Parser* self, enum zS_c313e0ed_906c25e2_AstKind kind) {
    struct zS_89baa7c0_7a3512d8_Token tok;
    unsigned int __tmp_try_5_5;
    ErrorUnion_u32 __tmp_try_res_5_6;
    unsigned int operand;
    unsigned int end;
    tok = zF_a8a3052c_33256f43_parserAdvance(self);
    __tmp_try_res_5_6 = zF_a8a3052c_c7ea9b4b_parserParseExprPrec(self, zS_a8a3052c_4258ebb9_Prec_prefix);
    if (__tmp_try_res_5_6.is_error) {
        return __tmp_try_res_5_6;
    }
    __tmp_try_5_5 = __tmp_try_res_5_6.data.payload;
    operand = __tmp_try_5_5;
    end = tok.span_start + (unsigned int)tok.span_len;
    (void)(operand);
    (void)(end);
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_UnexpectedToken;
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_b9f4f90f_parserParseGroupedExpr(struct zS_a8a3052c_21144d98_Parser* self) {
    unsigned int __tmp_try_5_3;
    ErrorUnion_u32 __tmp_try_res_5_4;
    unsigned int inner;
    struct zS_a8a3052c_39daa34f_ParseToken __tmp_try_6_1;
    ErrorUnion_zS_a8a3052c_39daa34f_ParseToken __tmp_try_res_6_2;
    (void)(zF_a8a3052c_33256f43_parserAdvance(self));
    __tmp_try_res_5_4 = zF_a8a3052c_c7ea9b4b_parserParseExprPrec(self, zS_a8a3052c_4258ebb9_Prec_assignment);
    if (__tmp_try_res_5_4.is_error) {
        return __tmp_try_res_5_4;
    }
    __tmp_try_5_3 = __tmp_try_res_5_4.data.payload;
    inner = __tmp_try_5_3;
    __tmp_try_res_6_2 = zF_a8a3052c_48a6f942_parserExpect(self, zS_89baa7c0_facdb0ca_TokenKind_rparen);
    if (__tmp_try_res_6_2.is_error) {
        {
            ErrorUnion_u32 __return_val = {0};
            __return_val.data.err = __tmp_try_res_6_2.data.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    __tmp_try_6_1 = __tmp_try_res_6_2.data.payload;
    (void)(__tmp_try_6_1);
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 0;
        __return_val.data.payload = inner;
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_b72bdbcd_parserParseBuiltinCall(struct zS_a8a3052c_21144d98_Parser* self) {
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_UnexpectedToken;
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_428daa37_parserParseErrorLiteral(struct zS_a8a3052c_21144d98_Parser* self) {
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_UnexpectedToken;
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_b5b93414_parserParseTryExpr(struct zS_a8a3052c_21144d98_Parser* self) {
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_UnexpectedToken;
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_19d70a82_parserParseAnonymousLiteral(struct zS_a8a3052c_21144d98_Parser* self) {
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_UnexpectedToken;
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_f5491176_parserParseEnumLiteral(struct zS_a8a3052c_21144d98_Parser* self) {
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_UnexpectedToken;
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_4f301fea_parserParseIfExpr(struct zS_a8a3052c_21144d98_Parser* self) {
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_UnexpectedToken;
        return __return_val;
    }
}

static ErrorUnion_u32 zF_a8a3052c_8cd8d6e1_parserParseSwitchExpr(struct zS_a8a3052c_21144d98_Parser* self) {
    {
        ErrorUnion_u32 __return_val = {0};
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_UnexpectedToken;
        return __return_val;
    }
}

unsigned char zF_a8a3052c_f4dd8358_precToInt(enum zS_a8a3052c_4258ebb9_Prec p) {
    return (unsigned char)(unsigned char)p;
}

enum zS_a8a3052c_4258ebb9_Prec zF_a8a3052c_e02cae07_precFromInt(unsigned char v) {
    return (enum zS_a8a3052c_4258ebb9_Prec)v;
}

Optional_zS_a8a3052c_244bd7c4_OpInfo zF_a8a3052c_f55b638a_getInfixInfo(enum zS_89baa7c0_facdb0ca_TokenKind kind) {
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_plus_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_minus_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_star_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_slash_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_percent_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_shl_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_shr_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_ampersand_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_pipe_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_caret_eq) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_assignment;
            __return_val.value.right_assoc = 1;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_kw_orelse) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_prec_orelse;
            __return_val.value.right_assoc = 1;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_kw_catch) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_prec_catch;
            __return_val.value.right_assoc = 1;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_kw_or) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_bool_or;
            __return_val.value.right_assoc = 0;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_kw_and) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_bool_and;
            __return_val.value.right_assoc = 0;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_eq_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_bang_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_less || kind == zS_89baa7c0_facdb0ca_TokenKind_less_eq || kind == zS_89baa7c0_facdb0ca_TokenKind_greater || kind == zS_89baa7c0_facdb0ca_TokenKind_greater_eq) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_comparison;
            __return_val.value.right_assoc = 0;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_pipe) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_bit_or;
            __return_val.value.right_assoc = 0;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_caret) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_bit_xor;
            __return_val.value.right_assoc = 0;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_ampersand) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_bit_and;
            __return_val.value.right_assoc = 0;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_shl || kind == zS_89baa7c0_facdb0ca_TokenKind_shr) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_shift;
            __return_val.value.right_assoc = 0;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_plus || kind == zS_89baa7c0_facdb0ca_TokenKind_minus) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_additive;
            __return_val.value.right_assoc = 0;
            return __return_val;
        }
    }
    if (kind == zS_89baa7c0_facdb0ca_TokenKind_star || kind == zS_89baa7c0_facdb0ca_TokenKind_slash || kind == zS_89baa7c0_facdb0ca_TokenKind_percent) {
        {
            Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
            __return_val.has_value = 1;
            __return_val.value.prec = zS_a8a3052c_4258ebb9_Prec_multiply;
            __return_val.value.right_assoc = 0;
            return __return_val;
        }
    }
    {
        Optional_zS_a8a3052c_244bd7c4_OpInfo __return_val = {0};
        __return_val.has_value = 0;
        return __return_val;
    }
}
