/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

#include "repro_struct_init.h"


i64 zF_d3381c_test_switch_capture(struct zS_d3381c_Value* v) {
/* DEBUG: emitSwitch start */
    {
        struct zS_d3381c_Value switch_tmp = *v;
        switch (switch_tmp.tag) {
        case zE_0cb520_Value_Tag_Int:
            {
                /* DEBUG: capture val */
                i64 val;
                val = switch_tmp.data.Int;
{
                return val;
            }            }
            break;
        case zE_0cb520_Value_Tag_Cons:
            {
                /* DEBUG: capture data */
                struct zS_0cb520_anon_1 data;
                memcpy(&data, &switch_tmp.data.Cons, sizeof(struct zS_0cb520_anon_1));
{
                return zF_d3381c_test_switch_capture(data.car);
            }            }
            break;
        default:
{
                __bootstrap_panic("reached unreachable", __FILE__, __LINE__);
            }            break;
    }
    }
}

int main(int argc, char* argv[]) {
    struct zS_d3381c_Value v;
    v.tag = zE_0cb520_Value_Tag_Int;
    v.data.Int = 42LL;
    (void)(zF_d3381c_test_switch_capture(&v));
    return 0;
}
