/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

#include "std_debug.h"



void __bootstrap_print(unsigned char const* s);

void __bootstrap_print_int(int n);

void zF_15eec6_print(unsigned char const* fmt, ...) {
    __bootstrap_print(fmt);
}

void zF_15eec6_printInt(int n) {
    __bootstrap_print_int(n);
}
