/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

static void takeSlice(Slice_u8 s) {
    (void)(s);
}

int main(int argc, char* argv[]) {
    Slice_u8 s;
    takeSlice(__make_slice_u8("hello", 5));
    s = __make_slice_u8("world", 5);
    (void)(s);
    return 0;
}
