/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "token.h"
#include "mem.h"
#include "allocator.h"


struct zS_26b5a9a4_43f95de6_Sand;
struct zS_89baa7c0_28f04bce_KeywordEntry;
#ifndef ZIG_ENUM_zS_89baa7c0_facdb0ca_TokenKind
#define ZIG_ENUM_zS_89baa7c0_facdb0ca_TokenKind
enum zS_89baa7c0_facdb0ca_TokenKind {
    zS_89baa7c0_facdb0ca_TokenKind_integer_literal = 0,
    zS_89baa7c0_facdb0ca_TokenKind_float_literal = 1,
    zS_89baa7c0_facdb0ca_TokenKind_string_literal = 2,
    zS_89baa7c0_facdb0ca_TokenKind_char_literal = 3,
    zS_89baa7c0_facdb0ca_TokenKind_identifier = 4,
    zS_89baa7c0_facdb0ca_TokenKind_builtin_identifier = 5,
    zS_89baa7c0_facdb0ca_TokenKind_lparen = 6,
    zS_89baa7c0_facdb0ca_TokenKind_rparen = 7,
    zS_89baa7c0_facdb0ca_TokenKind_lbracket = 8,
    zS_89baa7c0_facdb0ca_TokenKind_rbracket = 9,
    zS_89baa7c0_facdb0ca_TokenKind_lbrace = 10,
    zS_89baa7c0_facdb0ca_TokenKind_rbrace = 11,
    zS_89baa7c0_facdb0ca_TokenKind_semicolon = 12,
    zS_89baa7c0_facdb0ca_TokenKind_colon = 13,
    zS_89baa7c0_facdb0ca_TokenKind_comma = 14,
    zS_89baa7c0_facdb0ca_TokenKind_dot = 15,
    zS_89baa7c0_facdb0ca_TokenKind_at_sign = 16,
    zS_89baa7c0_facdb0ca_TokenKind_underscore = 17,
    zS_89baa7c0_facdb0ca_TokenKind_question_mark = 18,
    zS_89baa7c0_facdb0ca_TokenKind_bang = 19,
    zS_89baa7c0_facdb0ca_TokenKind_plus = 20,
    zS_89baa7c0_facdb0ca_TokenKind_minus = 21,
    zS_89baa7c0_facdb0ca_TokenKind_star = 22,
    zS_89baa7c0_facdb0ca_TokenKind_slash = 23,
    zS_89baa7c0_facdb0ca_TokenKind_percent = 24,
    zS_89baa7c0_facdb0ca_TokenKind_ampersand = 25,
    zS_89baa7c0_facdb0ca_TokenKind_pipe = 26,
    zS_89baa7c0_facdb0ca_TokenKind_caret = 27,
    zS_89baa7c0_facdb0ca_TokenKind_tilde = 28,
    zS_89baa7c0_facdb0ca_TokenKind_shl = 29,
    zS_89baa7c0_facdb0ca_TokenKind_shr = 30,
    zS_89baa7c0_facdb0ca_TokenKind_eq_eq = 31,
    zS_89baa7c0_facdb0ca_TokenKind_bang_eq = 32,
    zS_89baa7c0_facdb0ca_TokenKind_less = 33,
    zS_89baa7c0_facdb0ca_TokenKind_less_eq = 34,
    zS_89baa7c0_facdb0ca_TokenKind_greater = 35,
    zS_89baa7c0_facdb0ca_TokenKind_greater_eq = 36,
    zS_89baa7c0_facdb0ca_TokenKind_eq = 37,
    zS_89baa7c0_facdb0ca_TokenKind_plus_eq = 38,
    zS_89baa7c0_facdb0ca_TokenKind_minus_eq = 39,
    zS_89baa7c0_facdb0ca_TokenKind_star_eq = 40,
    zS_89baa7c0_facdb0ca_TokenKind_slash_eq = 41,
    zS_89baa7c0_facdb0ca_TokenKind_percent_eq = 42,
    zS_89baa7c0_facdb0ca_TokenKind_ampersand_eq = 43,
    zS_89baa7c0_facdb0ca_TokenKind_pipe_eq = 44,
    zS_89baa7c0_facdb0ca_TokenKind_caret_eq = 45,
    zS_89baa7c0_facdb0ca_TokenKind_shl_eq = 46,
    zS_89baa7c0_facdb0ca_TokenKind_shr_eq = 47,
    zS_89baa7c0_facdb0ca_TokenKind_dot_dot = 48,
    zS_89baa7c0_facdb0ca_TokenKind_dot_dot_dot = 49,
    zS_89baa7c0_facdb0ca_TokenKind_dot_lbrace = 50,
    zS_89baa7c0_facdb0ca_TokenKind_dot_star = 51,
    zS_89baa7c0_facdb0ca_TokenKind_fat_arrow = 52,
    zS_89baa7c0_facdb0ca_TokenKind_kw_const = 53,
    zS_89baa7c0_facdb0ca_TokenKind_kw_var = 54,
    zS_89baa7c0_facdb0ca_TokenKind_kw_fn = 55,
    zS_89baa7c0_facdb0ca_TokenKind_kw_pub = 56,
    zS_89baa7c0_facdb0ca_TokenKind_kw_extern = 57,
    zS_89baa7c0_facdb0ca_TokenKind_kw_export = 58,
    zS_89baa7c0_facdb0ca_TokenKind_kw_test = 59,
    zS_89baa7c0_facdb0ca_TokenKind_kw_struct = 60,
    zS_89baa7c0_facdb0ca_TokenKind_kw_enum = 61,
    zS_89baa7c0_facdb0ca_TokenKind_kw_union = 62,
    zS_89baa7c0_facdb0ca_TokenKind_kw_if = 63,
    zS_89baa7c0_facdb0ca_TokenKind_kw_else = 64,
    zS_89baa7c0_facdb0ca_TokenKind_kw_while = 65,
    zS_89baa7c0_facdb0ca_TokenKind_kw_for = 66,
    zS_89baa7c0_facdb0ca_TokenKind_kw_switch = 67,
    zS_89baa7c0_facdb0ca_TokenKind_kw_return = 68,
    zS_89baa7c0_facdb0ca_TokenKind_kw_break = 69,
    zS_89baa7c0_facdb0ca_TokenKind_kw_continue = 70,
    zS_89baa7c0_facdb0ca_TokenKind_kw_defer = 71,
    zS_89baa7c0_facdb0ca_TokenKind_kw_errdefer = 72,
    zS_89baa7c0_facdb0ca_TokenKind_kw_try = 73,
    zS_89baa7c0_facdb0ca_TokenKind_kw_catch = 74,
    zS_89baa7c0_facdb0ca_TokenKind_kw_orelse = 75,
    zS_89baa7c0_facdb0ca_TokenKind_kw_error = 76,
    zS_89baa7c0_facdb0ca_TokenKind_kw_and = 77,
    zS_89baa7c0_facdb0ca_TokenKind_kw_or = 78,
    zS_89baa7c0_facdb0ca_TokenKind_kw_true = 79,
    zS_89baa7c0_facdb0ca_TokenKind_kw_false = 80,
    zS_89baa7c0_facdb0ca_TokenKind_kw_null = 81,
    zS_89baa7c0_facdb0ca_TokenKind_kw_undefined = 82,
    zS_89baa7c0_facdb0ca_TokenKind_kw_unreachable = 83,
    zS_89baa7c0_facdb0ca_TokenKind_kw_void = 84,
    zS_89baa7c0_facdb0ca_TokenKind_kw_bool = 85,
    zS_89baa7c0_facdb0ca_TokenKind_kw_noreturn = 86,
    zS_89baa7c0_facdb0ca_TokenKind_kw_c_char = 87,
    zS_89baa7c0_facdb0ca_TokenKind_eof = 88,
    zS_89baa7c0_facdb0ca_TokenKind_err_token = 89
};
typedef enum zS_89baa7c0_facdb0ca_TokenKind zS_89baa7c0_facdb0ca_TokenKind;

#endif /* ZIG_ENUM_zS_89baa7c0_facdb0ca_TokenKind */

#ifndef ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
#define ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
struct zS_26b5a9a4_43f95de6_Sand {
    unsigned char* start;
    usize pos;
    usize end;
    usize peak;
};

#endif /* ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand */

Slice_zS_89baa7c0_28f04bce_KeywordEntry zV_89baa7c0_8c1e49a4_keyword_table;
usize zV_89baa7c0_5ad3148f_keyword_count = 0;
void zF_89baa7c0_aa606f4f_initKeywordTable(struct zS_26b5a9a4_43f95de6_Sand* alloc) {
    unsigned char* __tmp_catch_5_1 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_2;
    unsigned char* raw;
    struct zS_89baa7c0_28f04bce_KeywordEntry* table;
    usize i = 0;
    __tmp_catch_res_5_2 = zF_26b5a9a4_6fa59c42_sandAlloc(alloc, 12 * 35, 4);
    if (__tmp_catch_res_5_2.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_1 = __tmp_catch_res_5_2.data.payload;
    }
    raw = __tmp_catch_5_1;
    table = (struct zS_89baa7c0_28f04bce_KeywordEntry*)raw;
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp = &(table[i]);
        (*init_lval_tmp).name = __make_slice_u8("const", 5);
        (*init_lval_tmp).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_const;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_1 = &(table[i]);
        (*init_lval_tmp_1).name = __make_slice_u8("var", 3);
        (*init_lval_tmp_1).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_var;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_2 = &(table[i]);
        (*init_lval_tmp_2).name = __make_slice_u8("fn", 2);
        (*init_lval_tmp_2).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_fn;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_3 = &(table[i]);
        (*init_lval_tmp_3).name = __make_slice_u8("pub", 3);
        (*init_lval_tmp_3).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_pub;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_4 = &(table[i]);
        (*init_lval_tmp_4).name = __make_slice_u8("extern", 6);
        (*init_lval_tmp_4).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_extern;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_5 = &(table[i]);
        (*init_lval_tmp_5).name = __make_slice_u8("export", 6);
        (*init_lval_tmp_5).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_export;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_6 = &(table[i]);
        (*init_lval_tmp_6).name = __make_slice_u8("test", 4);
        (*init_lval_tmp_6).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_test;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_7 = &(table[i]);
        (*init_lval_tmp_7).name = __make_slice_u8("struct", 6);
        (*init_lval_tmp_7).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_struct;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_8 = &(table[i]);
        (*init_lval_tmp_8).name = __make_slice_u8("enum", 4);
        (*init_lval_tmp_8).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_enum;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_9 = &(table[i]);
        (*init_lval_tmp_9).name = __make_slice_u8("union", 5);
        (*init_lval_tmp_9).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_union;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_10 = &(table[i]);
        (*init_lval_tmp_10).name = __make_slice_u8("if", 2);
        (*init_lval_tmp_10).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_if;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_11 = &(table[i]);
        (*init_lval_tmp_11).name = __make_slice_u8("else", 4);
        (*init_lval_tmp_11).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_else;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_12 = &(table[i]);
        (*init_lval_tmp_12).name = __make_slice_u8("while", 5);
        (*init_lval_tmp_12).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_while;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_13 = &(table[i]);
        (*init_lval_tmp_13).name = __make_slice_u8("for", 3);
        (*init_lval_tmp_13).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_for;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_14 = &(table[i]);
        (*init_lval_tmp_14).name = __make_slice_u8("switch", 6);
        (*init_lval_tmp_14).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_switch;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_15 = &(table[i]);
        (*init_lval_tmp_15).name = __make_slice_u8("return", 6);
        (*init_lval_tmp_15).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_return;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_16 = &(table[i]);
        (*init_lval_tmp_16).name = __make_slice_u8("break", 5);
        (*init_lval_tmp_16).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_break;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_17 = &(table[i]);
        (*init_lval_tmp_17).name = __make_slice_u8("continue", 8);
        (*init_lval_tmp_17).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_continue;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_18 = &(table[i]);
        (*init_lval_tmp_18).name = __make_slice_u8("defer", 5);
        (*init_lval_tmp_18).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_defer;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_19 = &(table[i]);
        (*init_lval_tmp_19).name = __make_slice_u8("errdefer", 8);
        (*init_lval_tmp_19).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_errdefer;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_20 = &(table[i]);
        (*init_lval_tmp_20).name = __make_slice_u8("try", 3);
        (*init_lval_tmp_20).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_try;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_21 = &(table[i]);
        (*init_lval_tmp_21).name = __make_slice_u8("catch", 5);
        (*init_lval_tmp_21).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_catch;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_22 = &(table[i]);
        (*init_lval_tmp_22).name = __make_slice_u8("orelse", 6);
        (*init_lval_tmp_22).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_orelse;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_23 = &(table[i]);
        (*init_lval_tmp_23).name = __make_slice_u8("error", 5);
        (*init_lval_tmp_23).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_error;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_24 = &(table[i]);
        (*init_lval_tmp_24).name = __make_slice_u8("and", 3);
        (*init_lval_tmp_24).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_and;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_25 = &(table[i]);
        (*init_lval_tmp_25).name = __make_slice_u8("or", 2);
        (*init_lval_tmp_25).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_or;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_26 = &(table[i]);
        (*init_lval_tmp_26).name = __make_slice_u8("true", 4);
        (*init_lval_tmp_26).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_true;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_27 = &(table[i]);
        (*init_lval_tmp_27).name = __make_slice_u8("false", 5);
        (*init_lval_tmp_27).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_false;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_28 = &(table[i]);
        (*init_lval_tmp_28).name = __make_slice_u8("null", 4);
        (*init_lval_tmp_28).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_null;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_29 = &(table[i]);
        (*init_lval_tmp_29).name = __make_slice_u8("undefined", 9);
        (*init_lval_tmp_29).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_undefined;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_30 = &(table[i]);
        (*init_lval_tmp_30).name = __make_slice_u8("unreachable", 11);
        (*init_lval_tmp_30).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_unreachable;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_31 = &(table[i]);
        (*init_lval_tmp_31).name = __make_slice_u8("void", 4);
        (*init_lval_tmp_31).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_void;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_32 = &(table[i]);
        (*init_lval_tmp_32).name = __make_slice_u8("bool", 4);
        (*init_lval_tmp_32).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_bool;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_33 = &(table[i]);
        (*init_lval_tmp_33).name = __make_slice_u8("noreturn", 8);
        (*init_lval_tmp_33).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_noreturn;
    }
    (void)(i += 1);
    {
        struct zS_89baa7c0_28f04bce_KeywordEntry* init_lval_tmp_34 = &(table[i]);
        (*init_lval_tmp_34).name = __make_slice_u8("c_char", 6);
        (*init_lval_tmp_34).kind = zS_89baa7c0_facdb0ca_TokenKind_kw_c_char;
    }
    (void)(i += 1);
    zV_89baa7c0_8c1e49a4_keyword_table = __make_slice_zS_89baa7c0_28f04bce_KeywordEntry(table + 0, 35 - 0);
    zV_89baa7c0_5ad3148f_keyword_count = i;
}

Optional_zS_89baa7c0_facdb0ca_TokenKind zF_89baa7c0_3b776c71_lookupKeyword(Slice_u8 text) {
    usize i = 0;
    __loop_0_start: ;
    if (!(i < zV_89baa7c0_5ad3148f_keyword_count)) goto __loop_0_end;
    {
        if (zF_edc59eed_700ff121_mem_eql(zV_89baa7c0_8c1e49a4_keyword_table.ptr[i].name, text)) {
            {
                Optional_zS_89baa7c0_facdb0ca_TokenKind __return_val = {0};
                __return_val.has_value = 1;
                __return_val.value = zV_89baa7c0_8c1e49a4_keyword_table.ptr[i].kind;
                return __return_val;
            }
        }
        (void)(i += 1);
    }
    goto __loop_0_start;
    __loop_0_end: ;
    {
        Optional_zS_89baa7c0_facdb0ca_TokenKind __return_val = {0};
        __return_val.has_value = 0;
        return __return_val;
    }
}
