const std = @import("std");
const m1 = @import("m1.zig");
const m2 = @import("m2.zig");
const m3 = @import("m3.zig");
const m4 = @import("m4.zig");
const m5 = @import("m5.zig");
const m6 = @import("m6.zig");
const m7 = @import("m7.zig");
const m8 = @import("m8.zig");
const m9 = @import("m9.zig");
const m10 = @import("m10.zig");
const m11 = @import("m11.zig");
const m12 = @import("m12.zig");
const m13 = @import("m13.zig");
const m14 = @import("m14.zig");
const m15 = @import("m15.zig");
const m16 = @import("m16.zig");
const m17 = @import("m17.zig");
const m18 = @import("m18.zig");
const m19 = @import("m19.zig");
const m20 = @import("m20.zig");
const m21 = @import("m21.zig");
const m22 = @import("m22.zig");
const m23 = @import("m23.zig");
const m24 = @import("m24.zig");
const m25 = @import("m25.zig");
const m26 = @import("m26.zig");
const m27 = @import("m27.zig");
const m28 = @import("m28.zig");
const m29 = @import("m29.zig");
const m30 = @import("m30.zig");
const m31 = @import("m31.zig");
const m32 = @import("m32.zig");
const m33 = @import("m33.zig");
const m34 = @import("m34.zig");
const m35 = @import("m35.zig");
const m36 = @import("m36.zig");
const m37 = @import("m37.zig");
const m38 = @import("m38.zig");
const m39 = @import("m39.zig");
pub fn main() void {
    var s: u32 = 0;
    s += m1.make().v;
    std.io.printInt(m1.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m2.make().v;
    std.io.printInt(m2.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m3.make().v;
    std.io.printInt(m3.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m4.make().v;
    std.io.printInt(m4.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m5.make().v;
    std.io.printInt(m5.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m6.make().v;
    std.io.printInt(m6.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m7.make().v;
    std.io.printInt(m7.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m8.make().v;
    std.io.printInt(m8.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m9.make().v;
    std.io.printInt(m9.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m10.make().v;
    std.io.printInt(m10.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m11.make().v;
    std.io.printInt(m11.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m12.make().v;
    std.io.printInt(m12.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m13.make().v;
    std.io.printInt(m13.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m14.make().v;
    std.io.printInt(m14.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m15.make().v;
    std.io.printInt(m15.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m16.make().v;
    std.io.printInt(m16.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m17.make().v;
    std.io.printInt(m17.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m18.make().v;
    std.io.printInt(m18.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m19.make().v;
    std.io.printInt(m19.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m20.make().v;
    std.io.printInt(m20.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m21.make().v;
    std.io.printInt(m21.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m22.make().v;
    std.io.printInt(m22.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m23.make().v;
    std.io.printInt(m23.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m24.make().v;
    std.io.printInt(m24.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m25.make().v;
    std.io.printInt(m25.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m26.make().v;
    std.io.printInt(m26.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m27.make().v;
    std.io.printInt(m27.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m28.make().v;
    std.io.printInt(m28.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m29.make().v;
    std.io.printInt(m29.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m30.make().v;
    std.io.printInt(m30.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m31.make().v;
    std.io.printInt(m31.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m32.make().v;
    std.io.printInt(m32.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m33.make().v;
    std.io.printInt(m33.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m34.make().v;
    std.io.printInt(m34.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m35.make().v;
    std.io.printInt(m35.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m36.make().v;
    std.io.printInt(m36.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m37.make().v;
    std.io.printInt(m37.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m38.make().v;
    std.io.printInt(m38.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += m39.make().v;
    std.io.printInt(m39.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    std.io.printInt(s);
}
