/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OpenFailed 1
#define ERROR_ReadFailed 2
#define ERROR_SeekFailed 3
#define ERROR_TooLarge 4
#define ERROR_InvalidSyntax 5
#define ERROR_UnexpectedEnd 6
#define ERROR_ExpectedValue 7
#define ERROR_ExpectedKey 8
#define ERROR_ExpectedColon 9
#define ERROR_ExpectedCommaOrEnd 10
#define ERROR_OutOfMemory 11

#include "arena.h"



extern void * arena_alloc_default(usize size);

Slice_u8 z_arena_alloc_bytes(void * arena_ptr, usize count) {
    unsigned char* z_arena_ptr;
    z_arena_ptr = (unsigned char*)arena_alloc_default(count);
    return __make_slice_u8(z_arena_ptr + 0, count - 0);
}
