/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OpenFailed 1
#define ERROR_ReadFailed 2
#define ERROR_SeekFailed 3
#define ERROR_TooLarge 4
#define ERROR_InvalidSyntax 5
#define ERROR_UnexpectedEnd 6
#define ERROR_ExpectedValue 7
#define ERROR_ExpectedKey 8
#define ERROR_ExpectedColon 9
#define ERROR_ExpectedCommaOrEnd 10
#define ERROR_OutOfMemory 11

#include "file.h"


void * z_file_File = ;
static int z_file_SEEK_END = 2;
static int z_file_SEEK_SET = 0;
int z_file_FileError = ;
extern Optional_Ptr_void fopen(char const* filename, char const* mode);

extern unsigned int fread(unsigned char* buffer, unsigned int size, unsigned int count, void * file);

extern int fclose(void * file);

extern int fseek(void * file, i64 offset, int whence);

extern i64 ftell(void * file);

extern int ferror(void * file);

extern int feof(void * file);

extern double strtod(char const* nptr, unsigned char** endptr);

extern void * arena_alloc(void * arena, unsigned int size);

ErrorUnion_Slice_u8 z_file_readFile(void * arena, Slice_u8 path) {
    void * __tmp_orelse_5_1;
    Optional_Ptr_void __tmp_orelse_res_5_2;
    void * z_file_f;
    i64 z_file_size;
    unsigned int z_file_usize_size;
    unsigned char* z_file_buffer_ptr;
    Slice_u8 z_file_buffer;
    unsigned int z_file_bytes_read;
    __tmp_orelse_res_5_2 = fopen((char const*)path.ptr, "rb");
    if (__tmp_orelse_res_5_2.has_value) {
        __tmp_orelse_5_1 = __tmp_orelse_res_5_2.value;
    } else {
        {
            ErrorUnion_Slice_u8 __return_val;
            __return_val.data.err = ERROR_OpenFailed;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    z_file_f = __tmp_orelse_5_1;
    if (fseek(z_file_f, 0, z_file_SEEK_END) != 0) {
        {
            ErrorUnion_Slice_u8 __return_val;
            __return_val.data.err = ERROR_SeekFailed;
            __return_val.is_error = 1;
            {
                (void)(fclose(z_file_f));
            }
            return __return_val;
        }
    }
    z_file_size = ftell(z_file_f);
    if (z_file_size < 0) {
        {
            ErrorUnion_Slice_u8 __return_val;
            __return_val.data.err = ERROR_SeekFailed;
            __return_val.is_error = 1;
            {
                (void)(fclose(z_file_f));
            }
            return __return_val;
        }
    }
    if (fseek(z_file_f, 0, z_file_SEEK_SET) != 0) {
        {
            ErrorUnion_Slice_u8 __return_val;
            __return_val.data.err = ERROR_SeekFailed;
            __return_val.is_error = 1;
            {
                (void)(fclose(z_file_f));
            }
            return __return_val;
        }
    }
    z_file_usize_size = __bootstrap_usize_from_i64(z_file_size);
    z_file_buffer_ptr = (unsigned char*)arena_alloc(arena, z_file_usize_size);
    z_file_buffer = __make_slice_u8(z_file_buffer_ptr + 0, z_file_usize_size - 0);
    z_file_bytes_read = fread(z_file_buffer.ptr, 1, z_file_usize_size, z_file_f);
    if (z_file_bytes_read != z_file_usize_size) {
        {
            ErrorUnion_Slice_u8 __return_val;
            __return_val.data.err = ERROR_ReadFailed;
            __return_val.is_error = 1;
            {
                (void)(fclose(z_file_f));
            }
            return __return_val;
        }
    }
    if (ferror(z_file_f) != 0) {
        {
            ErrorUnion_Slice_u8 __return_val;
            __return_val.data.err = ERROR_ReadFailed;
            __return_val.is_error = 1;
            {
                (void)(fclose(z_file_f));
            }
            return __return_val;
        }
    }
    {
        ErrorUnion_Slice_u8 __return_val;
        __return_val.data.payload = z_file_buffer;
        __return_val.is_error = 0;
        {
            (void)(fclose(z_file_f));
        }
        return __return_val;
    }
}
