/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OpenFailed 1
#define ERROR_ReadFailed 2
#define ERROR_SeekFailed 3
#define ERROR_TooLarge 4
#define ERROR_InvalidSyntax 5
#define ERROR_UnexpectedEnd 6
#define ERROR_ExpectedValue 7
#define ERROR_ExpectedKey 8
#define ERROR_ExpectedColon 9
#define ERROR_ExpectedCommaOrEnd 10
#define ERROR_OutOfMemory 11

#include "json.h"
#include "file.h"

struct z_json_Parser;

struct z_json_Parser {
    Slice_u8 input;
    unsigned int pos;
    void * arena;
};

#ifndef ZIG_ERRORUNION_ErrorUnion_void
#define ZIG_ERRORUNION_ErrorUnion_void
typedef struct {
    int err;
    int is_error;
} ErrorUnion_void;
#endif

#ifndef ZIG_ERRORUNION_ErrorUnion_Ptr_z_json_JsonValue
#define ZIG_ERRORUNION_ErrorUnion_Ptr_z_json_JsonValue
typedef struct {
    union {
        struct z_json_JsonValue* payload;
        int err;
    } data;
    int is_error;
} ErrorUnion_Ptr_z_json_JsonValue;
#endif

#ifndef ZIG_ERRORUNION_ErrorUnion_f64
#define ZIG_ERRORUNION_ErrorUnion_f64
typedef struct {
    union {
        double payload;
        int err;
    } data;
    int is_error;
} ErrorUnion_f64;
#endif

int z_json_ParseError = ;
extern void * arena_alloc(void * arena, unsigned int size);

static unsigned char z_json_peek(struct z_json_Parser* self) {
    unsigned char __tmp_if_5_49;
    if (self->pos < self->input.len) {
        __tmp_if_5_49 = self->input.ptr[self->pos];
    } else {
        __tmp_if_5_49 = 0;
    }
    return __tmp_if_5_49;
}

static void z_json_advance(struct z_json_Parser* self) {
    if (self->pos < self->input.len) {
        self->pos += 1;
    }
}

static void z_json_skipWhitespace(struct z_json_Parser* self) {
    while (self->pos < self->input.len) {
        unsigned char z_json_c;
        z_json_c = self->input.ptr[self->pos];
        if (z_json_c == ' ' || z_json_c == '\t' || z_json_c == '\n' || z_json_c == '\r') {
            self->pos += 1;
            /* defers for continue */
            continue;
        }
        /* defers for break */
        break;
    }
}

static ErrorUnion_void z_json_expect(struct z_json_Parser* self, unsigned char c) {
    if (z_json_peek(self) != c) {
        {
            ErrorUnion_void __return_val;
            __return_val.err = ERROR_ExpectedValue;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    z_json_advance(self);
    {
        ErrorUnion_void __implicit_ret = {0};
        return __implicit_ret;
    }
}

static struct z_json_JsonValue* z_json_createJsonValue(struct z_json_Parser* p, enum z_json_JsonValueTag tag) {
    struct z_json_JsonValue* z_json_v_ptr;
    union z_json_JsonData* z_json_d_ptr;
    z_json_v_ptr = (struct z_json_JsonValue*)arena_alloc(p->arena, 8);
    z_json_d_ptr = (union z_json_JsonData*)arena_alloc(p->arena, 8);
    z_json_v_ptr->tag = tag;
    z_json_v_ptr->data = z_json_d_ptr;
    return z_json_v_ptr;
}

ErrorUnion_z_json_JsonValue z_json_parseJson(void * arena, Slice_u8 input) {
    struct z_json_Parser z_json_p;
    struct z_json_JsonValue* __tmp_try_5_47;
    ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_5_48;
    struct z_json_JsonValue* z_json_result;
    z_json_p.input = input;
    z_json_p.pos = 0;
    z_json_p.arena = arena;
    __tmp_try_res_5_48 = z_json_parseValue(&z_json_p);
    if (__tmp_try_res_5_48.is_error) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.data.err = __tmp_try_res_5_48.data.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    __tmp_try_5_47 = __tmp_try_res_5_48.data.payload;
    z_json_result = __tmp_try_5_47;
    z_json_skipWhitespace(&z_json_p);
    if (z_json_p.pos < z_json_p.input.len) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.data.err = ERROR_InvalidSyntax;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    {
        ErrorUnion_z_json_JsonValue __return_val;
        __return_val.data.payload = *z_json_result;
        __return_val.is_error = 0;
        return __return_val;
    }
}

static ErrorUnion_Ptr_z_json_JsonValue z_json_parseValue(struct z_json_Parser* p) {
    unsigned char z_json_ch;
    z_json_skipWhitespace(p);
    z_json_ch = z_json_peek(p);
    if (z_json_ch == 'n') {
        struct z_json_JsonValue* __tmp_try_7_45;
        ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_7_46;
        __tmp_try_res_7_46 = z_json_parseNull(p);
        if (__tmp_try_res_7_46.is_error) {
            return __tmp_try_res_7_46;
        }
        __tmp_try_7_45 = __tmp_try_res_7_46.data.payload;
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.payload = __tmp_try_7_45;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    if (z_json_ch == 't' || z_json_ch == 'f') {
        struct z_json_JsonValue* __tmp_try_7_43;
        ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_7_44;
        __tmp_try_res_7_44 = z_json_parseBoolean(p);
        if (__tmp_try_res_7_44.is_error) {
            return __tmp_try_res_7_44;
        }
        __tmp_try_7_43 = __tmp_try_res_7_44.data.payload;
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.payload = __tmp_try_7_43;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    if (z_json_ch == '"') {
        struct z_json_JsonValue* __tmp_try_7_41;
        ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_7_42;
        __tmp_try_res_7_42 = z_json_parseString(p);
        if (__tmp_try_res_7_42.is_error) {
            return __tmp_try_res_7_42;
        }
        __tmp_try_7_41 = __tmp_try_res_7_42.data.payload;
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.payload = __tmp_try_7_41;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    if ((z_json_ch >= '0' && z_json_ch <= '9') || z_json_ch == '-') {
        struct z_json_JsonValue* __tmp_try_7_39;
        ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_7_40;
        __tmp_try_res_7_40 = z_json_parseNumber(p);
        if (__tmp_try_res_7_40.is_error) {
            return __tmp_try_res_7_40;
        }
        __tmp_try_7_39 = __tmp_try_res_7_40.data.payload;
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.payload = __tmp_try_7_39;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    if (z_json_ch == '[') {
        struct z_json_JsonValue* __tmp_try_7_37;
        ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_7_38;
        __tmp_try_res_7_38 = z_json_parseArray(p);
        if (__tmp_try_res_7_38.is_error) {
            return __tmp_try_res_7_38;
        }
        __tmp_try_7_37 = __tmp_try_res_7_38.data.payload;
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.payload = __tmp_try_7_37;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    if (z_json_ch == '{') {
        struct z_json_JsonValue* __tmp_try_7_35;
        ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_7_36;
        __tmp_try_res_7_36 = z_json_parseObject(p);
        if (__tmp_try_res_7_36.is_error) {
            return __tmp_try_res_7_36;
        }
        __tmp_try_7_35 = __tmp_try_res_7_36.data.payload;
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.payload = __tmp_try_7_35;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    {
        ErrorUnion_Ptr_z_json_JsonValue __return_val;
        __return_val.data.err = ERROR_ExpectedValue;
        __return_val.is_error = 1;
        return __return_val;
    }
}

static int z_json_slice_eql(Slice_u8 a, Slice_u8 b) {
    unsigned int z_json_i;
    if (a.len != b.len) {
        return 0;
    }
    z_json_i = 0;
    while (z_json_i < a.len) {
        if (a.ptr[z_json_i] != b.ptr[z_json_i]) {
            return 0;
        }
        z_json_i += 1;
    }
    return 1;
}

static ErrorUnion_Ptr_z_json_JsonValue z_json_parseNull(struct z_json_Parser* p) {
    Slice_u8 z_json_input;
    unsigned int z_json_pos;
    z_json_input = p->input;
    z_json_pos = p->pos;
    if (z_json_input.len - z_json_pos < 4 || !z_json_slice_eql(__make_slice_u8((__make_slice_u8(z_json_input.ptr + z_json_pos, z_json_input.len - z_json_pos)).ptr + 0, 4 - 0), __make_slice_u8("null", 4))) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = ERROR_InvalidSyntax;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    p->pos += 4;
    {
        ErrorUnion_Ptr_z_json_JsonValue __return_val;
        __return_val.data.payload = z_json_createJsonValue(p, z_json_JsonValueTag_Null);
        __return_val.is_error = 0;
        return __return_val;
    }
}

static ErrorUnion_Ptr_z_json_JsonValue z_json_parseBoolean(struct z_json_Parser* p) {
    Slice_u8 z_json_input;
    unsigned int z_json_pos;
    z_json_input = p->input;
    z_json_pos = p->pos;
    if (z_json_input.len - z_json_pos >= 4 && z_json_slice_eql(__make_slice_u8((__make_slice_u8(z_json_input.ptr + z_json_pos, z_json_input.len - z_json_pos)).ptr + 0, 4 - 0), __make_slice_u8("true", 4))) {
        struct z_json_JsonValue* z_json_v;
        p->pos += 4;
        z_json_v = z_json_createJsonValue(p, z_json_JsonValueTag_Boolean);
        z_json_v->data->Boolean = 1;
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.payload = z_json_v;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    if (z_json_input.len - z_json_pos >= 5 && z_json_slice_eql(__make_slice_u8((__make_slice_u8(z_json_input.ptr + z_json_pos, z_json_input.len - z_json_pos)).ptr + 0, 5 - 0), __make_slice_u8("false", 5))) {
        struct z_json_JsonValue* z_json_v_1;
        p->pos += 5;
        z_json_v_1 = z_json_createJsonValue(p, z_json_JsonValueTag_Boolean);
        z_json_v_1->data->Boolean = 0;
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.payload = z_json_v_1;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    {
        ErrorUnion_Ptr_z_json_JsonValue __return_val;
        __return_val.data.err = ERROR_InvalidSyntax;
        __return_val.is_error = 1;
        return __return_val;
    }
}

static ErrorUnion_Ptr_z_json_JsonValue z_json_parseString(struct z_json_Parser* p) {
    ErrorUnion_void __tmp_try_res_5_34;
    unsigned int z_json_start;
    Slice_u8 z_json_slice;
    ErrorUnion_void __tmp_try_res_5_32;
    struct z_json_JsonValue* z_json_v;
    __tmp_try_res_5_34 = z_json_expect(p, '"');
    if (__tmp_try_res_5_34.is_error) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = __tmp_try_res_5_34.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_start = p->pos;
    while (p->pos < p->input.len) {
        if (p->input.ptr[p->pos] == '"') {
            /* defers for break */
            break;
        }
        if (p->input.ptr[p->pos] == '\\') {
            p->pos += 1;
        }
        p->pos += 1;
    }
    if (p->pos >= p->input.len) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = ERROR_UnexpectedEnd;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    z_json_slice = __make_slice_u8(p->input.ptr + z_json_start, p->pos - z_json_start);
    __tmp_try_res_5_32 = z_json_expect(p, '"');
    if (__tmp_try_res_5_32.is_error) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = __tmp_try_res_5_32.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_v = z_json_createJsonValue(p, z_json_JsonValueTag_String);
    z_json_v->data->String = z_json_slice;
    {
        ErrorUnion_Ptr_z_json_JsonValue __return_val;
        __return_val.data.payload = z_json_v;
        __return_val.is_error = 0;
        return __return_val;
    }
}

static ErrorUnion_Ptr_z_json_JsonValue z_json_parseNumber(struct z_json_Parser* p) {
    unsigned int z_json_start;
    Slice_u8 z_json_slice;
    double __tmp_try_5_29;
    ErrorUnion_f64 __tmp_try_res_5_30;
    double z_json_val;
    struct z_json_JsonValue* z_json_v;
    z_json_start = p->pos;
    if (z_json_peek(p) == '-') {
        z_json_advance(p);
    }
    while (z_json_isDigit(z_json_peek(p))) {
        z_json_advance(p);
    }
    if (z_json_peek(p) == '.') {
        z_json_advance(p);
        while (z_json_isDigit(z_json_peek(p))) {
            z_json_advance(p);
        }
    }
    if (z_json_peek(p) == 'e' || z_json_peek(p) == 'E') {
        z_json_advance(p);
        if (z_json_peek(p) == '+' || z_json_peek(p) == '-') {
            z_json_advance(p);
        }
        while (z_json_isDigit(z_json_peek(p))) {
            z_json_advance(p);
        }
    }
    z_json_slice = __make_slice_u8(p->input.ptr + z_json_start, p->pos - z_json_start);
    __tmp_try_res_5_30 = z_json_parseFloat(z_json_slice);
    if (__tmp_try_res_5_30.is_error) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = __tmp_try_res_5_30.data.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    __tmp_try_5_29 = __tmp_try_res_5_30.data.payload;
    z_json_val = __tmp_try_5_29;
    z_json_v = z_json_createJsonValue(p, z_json_JsonValueTag_Number);
    z_json_v->data->Number = z_json_val;
    {
        ErrorUnion_Ptr_z_json_JsonValue __return_val;
        __return_val.data.payload = z_json_v;
        __return_val.is_error = 0;
        return __return_val;
    }
}

static int z_json_isDigit(unsigned char c) {
    return c >= '0' && c <= '9';
}

static ErrorUnion_f64 z_json_parseFloat(Slice_u8 s) {
    unsigned char z_json_buf[64];
    unsigned int z_json_i;
    char const* z_json_buf_ptr;
    double z_json_result;
    z_json_i = 0;
    while (z_json_i < s.len && z_json_i < 63) {
        z_json_buf[z_json_i] = s.ptr[z_json_i];
        z_json_i += 1;
    }
    z_json_buf[z_json_i] = 0;
    z_json_buf_ptr = (char const*)&z_json_buf;
    z_json_result = strtod(z_json_buf_ptr, (unsigned char**)&z_json_buf);
    {
        ErrorUnion_f64 __return_val;
        __return_val.data.payload = z_json_result;
        __return_val.is_error = 0;
        return __return_val;
    }
}

static ErrorUnion_Ptr_z_json_JsonValue z_json_parseArray(struct z_json_Parser* p) {
    ErrorUnion_void __tmp_try_res_5_28;
    unsigned int z_json_saved_pos;
    unsigned int z_json_count;
    ErrorUnion_void __tmp_try_res_5_24;
    struct z_json_JsonValue* z_json_arr_mem;
    Slice_z_json_JsonValue z_json_arr;
    unsigned int z_json_idx;
    ErrorUnion_void __tmp_try_res_5_20;
    struct z_json_JsonValue* z_json_v;
    __tmp_try_res_5_28 = z_json_expect(p, '[');
    if (__tmp_try_res_5_28.is_error) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = __tmp_try_res_5_28.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_skipWhitespace(p);
    z_json_saved_pos = p->pos;
    z_json_count = 0;
    if (z_json_peek(p) != ']') {
        while (1) {
            struct z_json_JsonValue* __tmp_try_10_25;
            ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_10_26;
            __tmp_try_res_10_26 = z_json_parseValue(p);
            if (__tmp_try_res_10_26.is_error) {
                return __tmp_try_res_10_26;
            }
            __tmp_try_10_25 = __tmp_try_res_10_26.data.payload;
            (void)(__tmp_try_10_25);
            z_json_count += 1;
            z_json_skipWhitespace(p);
            if (z_json_peek(p) == ',') {
                z_json_advance(p);
                z_json_skipWhitespace(p);
                /* defers for continue */
                continue;
            }
            /* defers for break */
            break;
        }
    }
    if (z_json_peek(p) != ']') {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = ERROR_ExpectedCommaOrEnd;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    __tmp_try_res_5_24 = z_json_expect(p, ']');
    if (__tmp_try_res_5_24.is_error) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = __tmp_try_res_5_24.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    p->pos = z_json_saved_pos;
    z_json_arr_mem = (struct z_json_JsonValue*)arena_alloc(p->arena, 8 * z_json_count);
    z_json_arr = __make_slice_z_json_JsonValue(z_json_arr_mem + 0, z_json_count - 0);
    z_json_idx = 0;
    if (z_json_peek(p) != ']') {
        while (z_json_idx < z_json_count) {
            struct z_json_JsonValue* __tmp_try_9_21;
            ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_9_22;
            struct z_json_JsonValue* z_json_val;
            __tmp_try_res_9_22 = z_json_parseValue(p);
            if (__tmp_try_res_9_22.is_error) {
                return __tmp_try_res_9_22;
            }
            __tmp_try_9_21 = __tmp_try_res_9_22.data.payload;
            z_json_val = __tmp_try_9_21;
            z_json_arr.ptr[z_json_idx] = *z_json_val;
            z_json_idx += 1;
            z_json_skipWhitespace(p);
            if (z_json_peek(p) == ',') {
                z_json_advance(p);
                z_json_skipWhitespace(p);
            }
        }
    }
    __tmp_try_res_5_20 = z_json_expect(p, ']');
    if (__tmp_try_res_5_20.is_error) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = __tmp_try_res_5_20.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_v = z_json_createJsonValue(p, z_json_JsonValueTag_Array);
    z_json_v->data->Array = z_json_arr;
    {
        ErrorUnion_Ptr_z_json_JsonValue __return_val;
        __return_val.data.payload = z_json_v;
        __return_val.is_error = 0;
        return __return_val;
    }
}

static ErrorUnion_Ptr_z_json_JsonValue z_json_parseObject(struct z_json_Parser* p) {
    ErrorUnion_void __tmp_try_res_5_18;
    unsigned int z_json_saved_pos;
    unsigned int z_json_count;
    ErrorUnion_void __tmp_try_res_5_10;
    struct z_json_Property* z_json_fields_mem;
    Slice_z_json_Property z_json_fields;
    unsigned int z_json_idx;
    ErrorUnion_void __tmp_try_res_5_2;
    struct z_json_JsonValue* z_json_v;
    __tmp_try_res_5_18 = z_json_expect(p, '{');
    if (__tmp_try_res_5_18.is_error) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = __tmp_try_res_5_18.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_skipWhitespace(p);
    z_json_saved_pos = p->pos;
    z_json_count = 0;
    if (z_json_peek(p) != '}') {
        while (1) {
            struct z_json_JsonValue* __tmp_try_9_15;
            ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_9_16;
            struct z_json_JsonValue* z_json_keyVal;
            ErrorUnion_void __tmp_try_res_9_14;
            struct z_json_JsonValue* __tmp_try_10_11;
            ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_10_12;
            __tmp_try_res_9_16 = z_json_parseString(p);
            if (__tmp_try_res_9_16.is_error) {
                return __tmp_try_res_9_16;
            }
            __tmp_try_9_15 = __tmp_try_res_9_16.data.payload;
            z_json_keyVal = __tmp_try_9_15;
            (void)(z_json_keyVal);
            z_json_skipWhitespace(p);
            __tmp_try_res_9_14 = z_json_expect(p, ':');
            if (__tmp_try_res_9_14.is_error) {
                {
                    ErrorUnion_Ptr_z_json_JsonValue __return_val;
                    __return_val.data.err = __tmp_try_res_9_14.err;
                    __return_val.is_error = 1;
                    return __return_val;
                }
            }
            0;
            __tmp_try_res_10_12 = z_json_parseValue(p);
            if (__tmp_try_res_10_12.is_error) {
                return __tmp_try_res_10_12;
            }
            __tmp_try_10_11 = __tmp_try_res_10_12.data.payload;
            (void)(__tmp_try_10_11);
            z_json_count += 1;
            z_json_skipWhitespace(p);
            if (z_json_peek(p) == ',') {
                z_json_advance(p);
                z_json_skipWhitespace(p);
                /* defers for continue */
                continue;
            }
            /* defers for break */
            break;
        }
    }
    if (z_json_peek(p) != '}') {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = ERROR_ExpectedCommaOrEnd;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    __tmp_try_res_5_10 = z_json_expect(p, '}');
    if (__tmp_try_res_5_10.is_error) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = __tmp_try_res_5_10.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    p->pos = z_json_saved_pos;
    z_json_fields_mem = (struct z_json_Property*)arena_alloc(p->arena, 12 * z_json_count);
    z_json_fields = __make_slice_z_json_Property(z_json_fields_mem + 0, z_json_count - 0);
    z_json_idx = 0;
    if (z_json_peek(p) != '}') {
        while (z_json_idx < z_json_count) {
            struct z_json_JsonValue* __tmp_try_9_7;
            ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_9_8;
            struct z_json_JsonValue* z_json_keyVal_1;
            Slice_u8 z_json_key;
            ErrorUnion_void __tmp_try_res_9_6;
            struct z_json_JsonValue* __tmp_try_9_3;
            ErrorUnion_Ptr_z_json_JsonValue __tmp_try_res_9_4;
            struct z_json_JsonValue* z_json_val;
            __tmp_try_res_9_8 = z_json_parseString(p);
            if (__tmp_try_res_9_8.is_error) {
                return __tmp_try_res_9_8;
            }
            __tmp_try_9_7 = __tmp_try_res_9_8.data.payload;
            z_json_keyVal_1 = __tmp_try_9_7;
            z_json_key = z_json_keyVal_1->data->String;
            z_json_skipWhitespace(p);
            __tmp_try_res_9_6 = z_json_expect(p, ':');
            if (__tmp_try_res_9_6.is_error) {
                {
                    ErrorUnion_Ptr_z_json_JsonValue __return_val;
                    __return_val.data.err = __tmp_try_res_9_6.err;
                    __return_val.is_error = 1;
                    return __return_val;
                }
            }
            0;
            __tmp_try_res_9_4 = z_json_parseValue(p);
            if (__tmp_try_res_9_4.is_error) {
                return __tmp_try_res_9_4;
            }
            __tmp_try_9_3 = __tmp_try_res_9_4.data.payload;
            z_json_val = __tmp_try_9_3;
            z_json_fields.ptr[z_json_idx].key = z_json_key;
            z_json_fields.ptr[z_json_idx].value = z_json_val;
            z_json_idx += 1;
            z_json_skipWhitespace(p);
            if (z_json_peek(p) == ',') {
                z_json_advance(p);
                z_json_skipWhitespace(p);
            }
        }
    }
    __tmp_try_res_5_2 = z_json_expect(p, '}');
    if (__tmp_try_res_5_2.is_error) {
        {
            ErrorUnion_Ptr_z_json_JsonValue __return_val;
            __return_val.data.err = __tmp_try_res_5_2.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_v = z_json_createJsonValue(p, z_json_JsonValueTag_Object);
    z_json_v->data->Object = z_json_fields;
    {
        ErrorUnion_Ptr_z_json_JsonValue __return_val;
        __return_val.data.payload = z_json_v;
        __return_val.is_error = 0;
        return __return_val;
    }
}
