/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OpenFailed 1
#define ERROR_ReadFailed 2
#define ERROR_SeekFailed 3
#define ERROR_TooLarge 4
#define ERROR_InvalidSyntax 5
#define ERROR_UnexpectedEnd 6
#define ERROR_ExpectedValue 7
#define ERROR_ExpectedKey 8
#define ERROR_ExpectedColon 9
#define ERROR_ExpectedCommaOrEnd 10
#define ERROR_OutOfMemory 11

#include "main.h"
#include "file.h"
#include "json.h"


#ifndef ZIG_SLICE_Slice_z_json_JsonValue
#define ZIG_SLICE_Slice_z_json_JsonValue
typedef struct { struct z_json_JsonValue* ptr; usize len; } Slice_z_json_JsonValue;
static RETR_UNUSED_FUNC Slice_z_json_JsonValue __make_slice_z_json_JsonValue(struct z_json_JsonValue* ptr, usize len) {
    Slice_z_json_JsonValue s;
    s.ptr = ptr;
    s.len = len;
    return s;
}
#endif

#ifndef ZIG_SLICE_Slice_z_json_Property
#define ZIG_SLICE_Slice_z_json_Property
typedef struct { struct z_json_Property* ptr; usize len; } Slice_z_json_Property;
static RETR_UNUSED_FUNC Slice_z_json_Property __make_slice_z_json_Property(struct z_json_Property* ptr, usize len) {
    Slice_z_json_Property s;
    s.ptr = ptr;
    s.len = len;
    return s;
}
#endif

#ifndef ZIG_SLICE_Slice_u8
#define ZIG_SLICE_Slice_u8
typedef struct { unsigned char* ptr; usize len; } Slice_u8;
static RETR_UNUSED_FUNC Slice_u8 __make_slice_u8(unsigned char* ptr, usize len) {
    Slice_u8 s;
    s.ptr = ptr;
    s.len = len;
    return s;
}
#endif

#ifndef ZIG_ERRORUNION_ErrorUnion_Slice_u8
#define ZIG_ERRORUNION_ErrorUnion_Slice_u8
typedef struct {
    union {
        Slice_u8 payload;
        int err;
    } data;
    int is_error;
} ErrorUnion_Slice_u8;
#endif

#ifndef ZIG_ERRORUNION_ErrorUnion_z_json_JsonValue
#define ZIG_ERRORUNION_ErrorUnion_z_json_JsonValue
typedef struct {
    union {
        struct z_json_JsonValue payload;
        int err;
    } data;
    int is_error;
} ErrorUnion_z_json_JsonValue;
#endif

extern struct Arena* zig_default_arena;
extern void __bootstrap_print(unsigned char const* s);

extern void __bootstrap_print_int(int val);

static void printIndent(unsigned int level) {
    unsigned int i;
    i = 0;
    while (i < level) {
        __bootstrap_print((unsigned char const*)"  ");
        i += 1;
    }
}

static void printValue(struct z_json_JsonValue val, unsigned int level) {
    enum z_json_JsonValueTag tag;
    tag = val.tag;
    if (tag == z_json_JsonValueTag_Null) {
        __bootstrap_print((unsigned char const*)"null");
    } else     if (tag == z_json_JsonValueTag_Boolean) {
        if (val.data->Boolean) {
            __bootstrap_print((unsigned char const*)"true");
        } else {
            __bootstrap_print((unsigned char const*)"false");
        }
    } else     if (tag == z_json_JsonValueTag_Number) {
        __bootstrap_print((unsigned char const*)"number");
    } else     if (tag == z_json_JsonValueTag_String) {
        __bootstrap_print((unsigned char const*)"\"");
        __bootstrap_print((unsigned char const*)val.data->String.ptr);
        __bootstrap_print((unsigned char const*)"\"");
    } else     if (tag == z_json_JsonValueTag_Array) {
        Slice_z_json_JsonValue arr;
        arr = val.data->Array;
        __bootstrap_print((unsigned char const*)"[");
        if (arr.len > 0) {
            unsigned int i;
            __bootstrap_print((unsigned char const*)"\n");
            i = 0;
            while (i < arr.len) {
                printIndent(level + 1);
                printValue(arr.ptr[i], level + 1);
                if (i < arr.len - 1) {
                    __bootstrap_print((unsigned char const*)",");
                }
                __bootstrap_print((unsigned char const*)"\n");
                i += 1;
            }
            printIndent(level);
        }
        __bootstrap_print((unsigned char const*)"]");
    } else     if (tag == z_json_JsonValueTag_Object) {
        Slice_z_json_Property obj;
        obj = val.data->Object;
        __bootstrap_print((unsigned char const*)"{");
        if (obj.len > 0) {
            unsigned int i_1;
            __bootstrap_print((unsigned char const*)"\n");
            i_1 = 0;
            while (i_1 < obj.len) {
                printIndent(level + 1);
                __bootstrap_print((unsigned char const*)"\"");
                __bootstrap_print((unsigned char const*)obj.ptr[i_1].key.ptr);
                __bootstrap_print((unsigned char const*)"\": ");
                printValue(*obj.ptr[i_1].value, level + 1);
                if (i_1 < obj.len - 1) {
                    __bootstrap_print((unsigned char const*)",");
                }
                __bootstrap_print((unsigned char const*)"\n");
                i_1 += 1;
            }
            printIndent(level);
        }
        __bootstrap_print((unsigned char const*)"}");
    }





}

int main(int argc, char* argv[]) {
    struct Arena** arena;
    Slice_u8 path;
    Slice_u8 __tmp_catch_5_3;
    ErrorUnion_Slice_u8 __tmp_catch_res_5_4;
    Slice_u8 content;
    struct z_json_JsonValue __tmp_catch_5_1;
    ErrorUnion_z_json_JsonValue __tmp_catch_res_5_2;
    struct z_json_JsonValue parsed;
    arena = &zig_default_arena;
    path = __make_slice_u8("test.json", 9);
    __tmp_catch_res_5_4 = z_file_readFile(arena, path);
    if (__tmp_catch_res_5_4.is_error) {
        int err;
        err = __tmp_catch_res_5_4.data.err;
        {
            __bootstrap_print((unsigned char const*)"Error reading file: ");
            __bootstrap_print_int((int)err);
            __bootstrap_print((unsigned char const*)"\n");
            return 0;
        }
    } else {
        __tmp_catch_5_3 = __tmp_catch_res_5_4.data.payload;
    }
    content = __tmp_catch_5_3;
    __tmp_catch_res_5_2 = z_json_parseJson(arena, content);
    if (__tmp_catch_res_5_2.is_error) {
        int err_1;
        err_1 = __tmp_catch_res_5_2.data.err;
        {
            __bootstrap_print((unsigned char const*)"Parse error: ");
            __bootstrap_print_int((int)err_1);
            __bootstrap_print((unsigned char const*)"\n");
            return 0;
        }
    } else {
        __tmp_catch_5_1 = __tmp_catch_res_5_2.data.payload;
    }
    parsed = __tmp_catch_5_1;
    printValue(parsed, 0);
    __bootstrap_print((unsigned char const*)"\n");
    return 0;
}
