/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

#include "incl.h"


extern void print(Slice_u8 msg);

int main(int argc, char* argv[]) {
    int z_incl_x;
    z_incl_x = 5;
    switch (z_incl_x) {
        case 1:
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 9:
        case 10:
{
                print(__make_slice_u8("range 1-10", 10));
            }            break;
        default:
{
                print(__make_slice_u8("else", 4));
            }            break;
    }
    return 0;
}
