/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

#include "std_debug.h"


extern void __bootstrap_print(unsigned char const* s);

extern void __bootstrap_print_int(int n);

void z_std_debug_print(unsigned char const* fmt, ...) {
    __bootstrap_print(fmt);
}

void z_std_debug_printInt(int n) {
    __bootstrap_print_int(n);
}
