// Generated batch runner for tests/main_batch5.cpp
#include "../src/bootstrap/bootstrap_all.cpp"
#include "test_utils.cpp"
#include "c89_validation/gcc_validator.cpp"
#include "c89_validation/msvc6_validator.cpp"
#include "double_free_analysis_tests.cpp"
#include "integration_tests.cpp"
#include "test_double_free_locations.cpp"
#include "test_double_free_path_aware.cpp"
#include "test_double_free_task_129.cpp"
#include "test_task_130_error_handling.cpp"
#include "test_task_130_loops.cpp"
#include "test_task_130_switch.cpp"
#include "main_batch5.cpp"
