// Generated batch runner for tests/main_batch60.cpp
#include "../src/bootstrap/bootstrap_all.cpp"
#include "test_utils.cpp"
#include "c89_validation/gcc_validator.cpp"
#include "c89_validation/msvc6_validator.cpp"
#include "unit/ast_clone_test.cpp"
#include "unit/ast_traversal_test.cpp"
#include "unit/parser_switch_stmt_test.cpp"
#include "integration/range_switch_tests.cpp"
#include "main_batch60.cpp"
