// Generated batch runner for tests/main_batch18.cpp
#include "../src/bootstrap/bootstrap_all.cpp"
#include "test_utils.cpp"
#include "c89_validation/gcc_validator.cpp"
#include "c89_validation/msvc6_validator.cpp"
#include "integration/array_tests.cpp"
#include "integration/defer_tests.cpp"
#include "integration/enum_tests.cpp"
#include "integration/for_tests.cpp"
#include "integration/rejection_tests.cpp"
#include "integration/switch_tests.cpp"
#include "integration/union_tests.cpp"
#include "main_batch18.cpp"
