// Generated batch runner for tests/main_batch38.cpp
#include "../src/bootstrap/bootstrap_all.cpp"
#include "test_utils.cpp"
#include "c89_validation/gcc_validator.cpp"
#include "c89_validation/msvc6_validator.cpp"
#include "integration/function_pointer_codegen_tests.cpp"
#include "test_fn_pointer_codegen.cpp"
#include "test_type_checker_fn_pointer.cpp"
#include "test_type_system_fn_pointer.cpp"
#include "test_validation_fn_pointer.cpp"
#include "main_batch38.cpp"
