// Generated batch runner for tests/main_batch9.cpp
#include "../src/bootstrap/bootstrap_all.cpp"
#include "test_utils.cpp"
#include "c89_validation/gcc_validator.cpp"
#include "c89_validation/msvc6_validator.cpp"
#include "lexer_decrement_test.cpp"
#include "task_156_multi_file_test.cpp"
#include "task_157_catalogue_test.cpp"
#include "test_milestone4_generics_integration.cpp"
#include "test_platform.cpp"
#include "test_task_157_implicit_detection.cpp"
#include "main_batch9.cpp"
