// Generated batch runner for tests/main_batch11.cpp
#include "../src/bootstrap/bootstrap_all.cpp"
#include "test_utils.cpp"
#include "c89_validation/gcc_validator.cpp"
#include "c89_validation/msvc6_validator.cpp"
#include "task_168_validation.cpp"
#include "test_call_site_lookup.cpp"
#include "test_call_syntax.cpp"
#include "test_forward_reference.cpp"
#include "test_indirect_calls.cpp"
#include "test_milestone4_lexer_parser.cpp"
#include "test_milestone4_name_mangling.cpp"
#include "test_optional_type.cpp"
#include "test_optional_type_checker.cpp"
#include "test_recursive_calls.cpp"
#include "test_task_165_resolution.cpp"
#include "type_checker_call_site_tests.cpp"
#include "main_batch11.cpp"
