// Generated batch runner for tests/main_batch4.cpp
#include "../src/bootstrap/bootstrap_all.cpp"
#include "test_utils.cpp"
#include "c89_validation/gcc_validator.cpp"
#include "c89_validation/msvc6_validator.cpp"
#include "bug_test_memory.cpp"
#include "lifetime_analysis_tests.cpp"
#include "memory_stability_tests.cpp"
#include "null_pointer_analysis_tests.cpp"
#include "task_119_test.cpp"
#include "test_c89_rejection.cpp"
#include "test_symbol_flags.cpp"
#include "test_utils_bug.cpp"
#include "type_checker_slice_expression_test.cpp"
#include "main_batch4.cpp"
