// Generated batch runner for tests/main_batch12.cpp
#include "../src/bootstrap/bootstrap_all.cpp"
#include "test_utils.cpp"
#include "c89_validation/gcc_validator.cpp"
#include "c89_validation/msvc6_validator.cpp"
#include "integration/arithmetic_tests.cpp"
#include "integration/function_call_tests.cpp"
#include "integration/function_decl_tests.cpp"
#include "integration/literal_tests.cpp"
#include "integration/variable_decl_tests.cpp"
#include "test_bootstrap_types.cpp"
#include "test_msvc_types.cpp"
#include "main_batch12.cpp"
