@echo off
:: Build script generated by Z98 bootstrap compiler
:: Optimized for MSVC 6.0 on Windows 98

cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c zig_runtime.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c builtin.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c util.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c token.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c sand.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c value.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c builtins.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c parser.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c deep_copy.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c env.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c eval.c
cl.exe /nologo /W3 /I. /Isrc/include /D_WIN32_WINDOWS=0x0410 /DWINVER=0x0410 /D_WIN32_WINNT=0x0400 /DNTDDI_VERSION=0x04000000 /c lisp_recursion.c
link.exe /nologo /subsystem:console /out:app.exe *.obj
