#include "test_declarations.hpp"
#include "test_runner_main.hpp"

int main(int argc, char* argv[]) {
    bool (*tests[])() = {
        test_Task142_ErrorFunctionDetection,
        test_Task142_ErrorFunctionRejection,
        test_Task143_TryExpressionDetection_Contexts,
        test_Task143_TryExpressionDetection_Nested,
        test_Task143_TryExpressionDetection_MultipleInStatement,
        test_CatchExpressionCatalogue_Basic,
        test_CatchExpressionCatalogue_Chaining,
        test_OrelseExpressionCatalogue_Basic,
        test_Task144_CatchExpressionDetection_Basic,
        test_Task144_CatchExpressionDetection_Chained,
        test_Task144_OrelseExpressionDetection,
        test_TypeChecker_VarDecl_Inferred_Crash,
        test_TypeChecker_VarDecl_Inferred_Loop,
        test_TypeChecker_VarDecl_Inferred_Multiple,
        test_C89Rejection_NestedTryInMemberAccess,
        test_C89Rejection_NestedTryInStructInitializer,
        test_C89Rejection_NestedTryInArrayAccess,
        test_ExtractionAnalysis_StackStrategy,
        test_ExtractionAnalysis_ArenaStrategy_LargePayload,
        test_ExtractionAnalysis_ArenaStrategy_DeepNesting,
        test_ExtractionAnalysis_OutParamStrategy,
        test_ExtractionAnalysis_ArenaStrategy_Alignment,
        test_ExtractionAnalysis_Linking,
        test_Task147_ErrDeferRejection,
        test_Task147_AnyErrorRejection,
        test_Task149_ErrorHandlingFeaturesCatalogued,
        test_Task150_ErrorTypeEliminatedFromFinalTypeSystem,
        test_C89Rejection_GenericFnDecl_ShouldBeRejected,
        test_C89Rejection_DeferAndErrDefer,
        test_C89Rejection_ErrorTypeInParam_ShouldBeRejected,
        test_Task150_MoreComprehensiveElimination,
        test_C89Rejection_ArraySliceExpression,
        test_Task151_ErrorTypeRejection,
        test_Task151_OptionalTypeRejection,
        test_FunctionNameCollisionSameScope,
        test_FunctionVariableCollisionSameScope,
        test_ShadowingAllowed,
        test_SignatureAnalysisNonC89Types,
        test_SignatureAnalysisManyParams,
        test_SignatureAnalysisMultiLevelPointers,
        test_SignatureAnalysisTypeAliasResolution,
        test_SignatureAnalysisArrayParameterWarning,
        test_SignatureAnalysisReturnTypeRejection,
        test_BreakContinue_Valid,
        test_BreakContinue_Invalid,
        test_BreakContinue_Codegen,
        test_ManyParameters_Call,
        test_ManyParameters_Generic
    };

    return run_batch(argc, argv, tests, sizeof(tests) / sizeof(tests[0]));
}
