#include "test_declarations.hpp"
#include "test_runner_main.hpp"

int main(int argc, char* argv[]) {
    bool (*tests[])() = {
        // Group 3A
        test_ASTNode_IntegerLiteral,
        test_ASTNode_FloatLiteral,
        test_ASTNode_CharLiteral,
        test_ASTNode_StringLiteral,
        test_ASTNode_Identifier,
        test_ASTNode_UnaryOp,
        test_ASTNode_BinaryOp,
        test_Parser_ParsePrimaryExpr_IntegerLiteral,
        test_Parser_ParsePrimaryExpr_FloatLiteral,
        test_Parser_ParsePrimaryExpr_CharLiteral,
        test_Parser_ParsePrimaryExpr_StringLiteral,
        test_Parser_ParsePrimaryExpr_Identifier,
        test_Parser_ParsePrimaryExpr_ParenthesizedExpression,
        // Group 3B
        test_Parser_FunctionCall_NoArgs,
        test_Parser_FunctionCall_WithArgs,
        test_Parser_FunctionCall_WithTrailingComma,
        test_Parser_ArrayAccess,
        test_Parser_ChainedPostfixOps,
        test_Parser_CompoundAssignment_Simple,
        test_Parser_CompoundAssignment_AllOperators,
        test_Parser_CompoundAssignment_RightAssociativity,
        test_Parser_CompoundAssignment_ComplexRHS,
        test_Parser_BinaryExpr_SimplePrecedence,
        test_Parser_BinaryExpr_LeftAssociativity,
        test_Parser_TryExpr_Simple,
        test_Parser_TryExpr_Chained,
        test_Parser_CatchExpression_Simple,
        test_Parser_CatchExpression_WithPayload,
        test_Parser_CatchExpression_MixedAssociativity,
        test_Parser_Orelse_IsLeftAssociative,
        test_Parser_Catch_IsLeftAssociative,
        test_Parser_CatchExpr_Simple,
        test_Parser_CatchExpr_LeftAssociativity,
        test_Parser_CatchExpr_MixedAssociativity,
        test_Parser_OrelseExpr_Simple,
        test_Parser_OrelseExpr_LeftAssociativity,
        test_Parser_OrelseExpr_Precedence,
        // Group 3C
        test_ASTNode_ContainerDeclarations,
        test_Parser_Struct_Error_MissingLBrace,
        test_Parser_Struct_Error_MissingRBrace,
        test_Parser_Struct_Error_MissingColon,
        test_Parser_Struct_Error_MissingType,
        test_Parser_Struct_Error_InvalidField,
        test_Parser_StructDeclaration_Simple,
        test_Parser_StructDeclaration_Empty,
        test_Parser_StructDeclaration_MultipleFields,
        test_Parser_StructDeclaration_WithTrailingComma,
        test_Parser_StructDeclaration_ComplexFieldType,
        test_ParserBug_TopLevelUnion,
        test_ParserBug_TopLevelStruct,
        test_ParserBug_UnionFieldNodeType,
        // Group 3D
        test_Parser_Enum_Empty,
        test_Parser_Enum_SimpleMembers,
        test_Parser_Enum_TrailingComma,
        test_Parser_Enum_WithValues,
        test_Parser_Enum_MixedMembers,
        test_Parser_Enum_WithBackingType,
        test_Parser_Enum_SyntaxError_MissingOpeningBrace,
        test_Parser_Enum_SyntaxError_MissingClosingBrace,
        test_Parser_Enum_SyntaxError_NoComma,
        test_Parser_Enum_SyntaxError_InvalidMember,
        test_Parser_Enum_SyntaxError_MissingInitializer,
        test_Parser_Enum_SyntaxError_BackingTypeNoParens,
        test_Parser_Enum_ComplexInitializer,
        // Group 3E
        test_Parser_FnDecl_ValidEmpty,
        test_Parser_FnDecl_Valid_NoArrow,
        test_Parser_FnDecl_Error_MissingReturnType,
        test_Parser_FnDecl_Error_MissingParens,
        test_Parser_NonEmptyFunctionBody,
        test_Parser_VarDecl_InsertsSymbolCorrectly,
        test_Parser_VarDecl_DetectsDuplicateSymbol,
        test_Parser_FnDecl_AndScopeManagement,
        // Group 3F
        test_ASTNode_ForStmt,
        test_ASTNode_SwitchExpr,
        test_Parser_IfStatement_Simple,
        test_Parser_IfStatement_WithElse,
        test_Parser_ParseEmptyBlock,
        test_Parser_ParseBlockWithEmptyStatement,
        test_Parser_ParseBlockWithMultipleEmptyStatements,
        test_Parser_ParseBlockWithNestedEmptyBlock,
        test_Parser_ParseBlockWithMultipleNestedEmptyBlocks,
        test_Parser_ParseBlockWithNestedBlockAndEmptyStatement,
        test_Parser_ErrDeferStatement_Simple,
        test_Parser_ComptimeBlock_Valid,
        test_Parser_NestedBlocks_AndShadowing,
        test_Parser_SymbolDoesNotLeakFromInnerScope,
        // Group 3G
        test_Parser_Error_OnUnexpectedToken,
        test_Parser_Error_OnMissingColon,
        test_Parser_IfStatement_Error_MissingLParen,
        test_Parser_IfStatement_Error_MissingRParen,
        test_Parser_IfStatement_Error_MissingThenBlock,
        test_Parser_IfStatement_Error_MissingElseBlock,
        test_Parser_BinaryExpr_Error_MissingRHS,
        test_Parser_TryExpr_InvalidSyntax,
        test_Parser_CatchExpression_Error_MissingElseExpr,
        test_Parser_CatchExpression_Error_IncompletePayload,
        test_Parser_CatchExpression_Error_MissingPipe,
        test_Parser_ErrDeferStatement_Error_MissingBlock,
        test_Parser_ComptimeBlock_Error_MissingExpression,
        test_Parser_ComptimeBlock_Error_MissingOpeningBrace,
        test_Parser_ComptimeBlock_Error_MissingClosingBrace,
        // Group 3H
        test_Parser_AbortOnAllocationFailure,
        test_Parser_TokenStreamLifetimeIsIndependentOfParserObject,
        test_ParserIntegration_VarDeclWithBinaryExpr,
        test_ParserIntegration_IfWithComplexCondition,
        test_ParserIntegration_WhileWithFunctionCall,
        test_ParserBug_LogicalOperatorSymbol,
        test_Parser_RecursionLimit,
        test_Parser_RecursionLimit_Unary,
        test_Parser_RecursionLimit_Binary,
        test_Parser_CopyIsSafeAndDoesNotDoubleFree,
        test_Parser_Bugfix_HandlesExpressionStatement
    };

    return run_batch(argc, argv, tests, sizeof(tests) / sizeof(tests[0]));
}
