#include "test_declarations.hpp"
#include "test_runner_main.hpp"

int main(int argc, char* argv[]) {
    bool (*tests[])() = {
        // Group 4A
        test_TypeChecker_IntegerLiteralInference,
        test_TypeChecker_FloatLiteralInference,
        test_TypeChecker_CharLiteralInference,
        test_TypeChecker_StringLiteralInference,
        test_TypeCheckerStringLiteralType,
        test_TypeCheckerIntegerLiteralType,
        test_TypeChecker_C89IntegerCompatibility,
        test_TypeResolution_ValidPrimitives,
        test_TypeResolution_InvalidOrUnsupported,
        test_TypeResolution_AllPrimitives,
        test_TypeChecker_BoolLiteral,
        test_TypeChecker_IntegerLiteral,
        test_TypeChecker_CharLiteral,
        test_TypeChecker_StringLiteral,
        test_TypeChecker_Identifier,
        // Group 4B
        test_TypeCheckerValidDeclarations,
        test_TypeCheckerInvalidDeclarations,
        test_TypeCheckerUndeclaredVariable,
        test_TypeChecker_VarDecl_Valid_Simple,
        test_TypeChecker_VarDecl_Invalid_Mismatch,
        test_TypeChecker_VarDecl_Invalid_Widening,
        test_TypeChecker_VarDecl_Multiple_Errors,
        // Group 4C
        test_ReturnTypeValidation_Valid,
        test_ReturnTypeValidation_Invalid,
        test_TypeCheckerFnDecl_ValidSimpleParams,
        test_TypeCheckerFnDecl_InvalidParamType,
        test_TypeCheckerVoidTests_ImplicitReturnInVoidFunction,
        test_TypeCheckerVoidTests_ExplicitReturnInVoidFunction,
        test_TypeCheckerVoidTests_ReturnValueInVoidFunction,
        test_TypeCheckerVoidTests_MissingReturnValueInNonVoidFunction,
        test_TypeCheckerVoidTests_ImplicitReturnInNonVoidFunction,
        test_TypeCheckerVoidTests_AllPathsReturnInNonVoidFunction,
        // Group 4D
        test_TypeChecker_AddressOf_RValueLiteral,
        test_TypeChecker_AddressOf_RValueExpression,
        test_TypeChecker_Dereference_ValidPointer,
        test_TypeChecker_Dereference_Invalid_NonPointer,
        test_TypeChecker_Dereference_VoidPointer,
        test_TypeChecker_Dereference_NullLiteral,
        test_TypeChecker_Dereference_ZeroLiteral,
        test_TypeChecker_Dereference_NestedPointer_REJECT,
        test_TypeChecker_Dereference_ConstPointer,
        test_TypeChecker_AddressOf_Valid_LValues,
        test_TypeCheckerPointerOps_AddressOf_ValidLValue,
        test_TypeCheckerPointerOps_Dereference_ValidPointer,
        test_TypeCheckerPointerOps_Dereference_InvalidNonPointer,
        // Group 4E
        test_TypeChecker_PointerArithmetic_ValidCases_ExplicitTyping,
        test_TypeChecker_PointerArithmetic_InvalidCases_ExplicitTyping,
        test_TypeCheckerVoidTests_PointerAddition,
        test_TypeCheckerPointerOps_Arithmetic_PointerInteger,
        test_TypeCheckerPointerOps_Arithmetic_PointerPointer,
        test_TypeCheckerPointerOps_Arithmetic_InvalidOperations,
        // Group 4F
        test_TypeCheckerBinaryOps_PointerArithmetic,
        test_TypeCheckerBinaryOps_NumericArithmetic,
        test_TypeCheckerBinaryOps_Comparison,
        test_TypeCheckerBinaryOps_Bitwise,
        test_TypeCheckerBinaryOps_Logical,
        test_TypeChecker_Bool_ComparisonOps,
        test_TypeChecker_Bool_LogicalOps,
        // Group 4G
        test_TypeCheckerControlFlow_IfStatementWithBooleanCondition,
        test_TypeCheckerControlFlow_IfStatementWithIntegerCondition,
        test_TypeCheckerControlFlow_IfStatementWithPointerCondition,
        test_TypeCheckerControlFlow_IfStatementWithFloatCondition,
        test_TypeCheckerControlFlow_IfStatementWithVoidCondition,
        test_TypeCheckerControlFlow_WhileStatementWithBooleanCondition,
        test_TypeCheckerControlFlow_WhileStatementWithIntegerCondition,
        test_TypeCheckerControlFlow_WhileStatementWithPointerCondition,
        test_TypeCheckerControlFlow_WhileStatementWithFloatCondition,
        test_TypeCheckerControlFlow_WhileStatementWithVoidCondition,
        // Group 4H
        test_TypeChecker_C89_StructFieldValidation_Slice,
        test_TypeChecker_C89_UnionFieldValidation_MultiLevelPointer,
        test_TypeChecker_C89_StructFieldValidation_ValidArray,
        test_TypeChecker_C89_UnionFieldValidation_ValidFields,
        test_TypeCheckerEnumTests_SignedIntegerOverflow,
        test_TypeCheckerEnumTests_SignedIntegerUnderflow,
        test_TypeCheckerEnumTests_UnsignedIntegerOverflow,
        test_TypeCheckerEnumTests_NegativeValueInUnsignedEnum,
        test_TypeCheckerEnumTests_AutoIncrementOverflow,
        test_TypeCheckerEnumTests_AutoIncrementSignedOverflow,
        test_TypeCheckerEnumTests_ValidValues,
        // Group 4I
        test_TypeChecker_ArrayAccessInBoundsWithNamedConstant,
        test_TypeChecker_RejectSlice,
        test_TypeChecker_ArrayAccessInBounds,
        test_TypeChecker_ArrayAccessOutOfBoundsPositive,
        test_TypeChecker_ArrayAccessOutOfBoundsNegative,
        test_TypeChecker_ArrayAccessOutOfBoundsExpression,
        test_TypeChecker_ArrayAccessWithVariable,
        test_TypeChecker_IndexingNonArray,
        test_TypeChecker_ArrayAccessWithNamedConstant,
        test_Assignment_IncompatiblePointers_Invalid,
        test_Assignment_ConstPointerToPointer_Invalid,
        test_Assignment_PointerToConstPointer_Valid,
        test_Assignment_VoidPointerToPointer_Valid,
        test_Assignment_PointerToVoidPointer_Valid,
        test_Assignment_PointerExactMatch_Valid,
        test_Assignment_NullToPointer_Valid,
        test_Assignment_NumericWidening_Fails,
        test_Assignment_ExactNumericMatch,
        test_TypeChecker_RejectNonConstantArraySize,
        test_TypeChecker_AcceptsValidArrayDeclaration,
        test_TypeCheckerVoidTests_DisallowVoidVariableDeclaration,
        test_TypeCompatibility,
        test_TypeToString_Reentrancy,
        test_TypeCheckerC89Compat_RejectFunctionWithTooManyArgs,
        test_TypeChecker_Call_WrongArgumentCount,
        test_TypeChecker_Call_IncompatibleArgumentType,
        test_TypeCheckerC89Compat_FloatWidening_Fails,
        test_C89TypeMapping_Validation,
        test_C89Compat_FunctionTypeValidation,
        test_TypeChecker_Bool_Literals,
        test_TypeChecker_CompoundAssignment_Valid,
        test_TypeChecker_CompoundAssignment_InvalidLValue,
        test_TypeChecker_CompoundAssignment_Bitwise,
        test_TypeChecker_CompoundAssignment_PointerArithmetic,
        test_TypeChecker_CompoundAssignment_InvalidTypes,
        test_DoubleFreeAnalyzer_CompoundAssignment
    };

    return run_batch(argc, argv, tests, sizeof(tests) / sizeof(tests[0]));
}
