#include "test_declarations.hpp"
#include "test_runner_main.hpp"

int main(int argc, char* argv[]) {
    bool (*tests[])() = {
        test_IfStatementIntegration_BoolCondition,
        test_IfStatementIntegration_IntCondition,
        test_IfStatementIntegration_PointerCondition,
        test_IfStatementIntegration_IfElse,
        test_IfStatementIntegration_ElseIfChain,
        test_IfStatementIntegration_NestedIf,
        test_IfStatementIntegration_LogicalAnd,
        test_IfStatementIntegration_LogicalOr,
        test_IfStatementIntegration_LogicalNot,
        test_IfStatementIntegration_EmptyBlocks,
        test_IfStatementIntegration_ReturnFromBranches,
        test_IfStatementIntegration_RejectFloatCondition,
        test_IfStatementIntegration_RejectBracelessIf,
        test_WhileLoopIntegration_BoolCondition,
        test_WhileLoopIntegration_IntCondition,
        test_WhileLoopIntegration_PointerCondition,
        test_WhileLoopIntegration_WithBreak,
        test_WhileLoopIntegration_WithContinue,
        test_WhileLoopIntegration_NestedWhile,
        test_WhileLoopIntegration_Scoping,
        test_WhileLoopIntegration_ComplexCondition,
        test_WhileLoopIntegration_RejectFloatCondition,
        test_WhileLoopIntegration_RejectBracelessWhile,
        test_WhileLoopIntegration_EmptyWhileBlock,
        test_StructIntegration_BasicNamedStruct,
        test_StructIntegration_MemberAccess,
        test_StructIntegration_NamedInitializerOrder,
        test_StructIntegration_RejectAnonymousStruct,
        test_StructIntegration_RejectStructMethods,
        test_StructIntegration_RejectSliceField,
        test_StructIntegration_RejectMultiLevelPointerField,
        test_PointerIntegration_AddressOfDereference,
        test_PointerIntegration_DereferenceExpression,
        test_PointerIntegration_PointerArithmeticAdd,
        test_PointerIntegration_PointerArithmeticSub,
        test_PointerIntegration_NullLiteral,
        test_PointerIntegration_NullComparison,
        test_PointerIntegration_PointerToStruct,
        test_PointerIntegration_VoidPointerAssignment,
        test_PointerIntegration_ConstAdding,
        test_PointerIntegration_ReturnLocalAddressError,
        test_PointerIntegration_DereferenceNullError,
        test_PointerIntegration_PointerPlusPointerError,
        test_PointerIntegration_DereferenceNonPointerError,
        test_PointerIntegration_AddressOfNonLValue,
        test_PointerIntegration_IncompatiblePointerAssignment,
        test_C89Validator_GCC_KnownGood,
        test_C89Validator_GCC_KnownBad,
        test_C89Validator_MSVC6_LongIdentifier,
        test_C89Validator_MSVC6_CppComment,
        test_C89Validator_MSVC6_LongLong,
        test_C89Validator_MSVC6_KnownGood
    };

    return run_batch(argc, argv, tests, sizeof(tests) / sizeof(tests[0]));
}
