#include "test_declarations.hpp"
#include "test_runner_main.hpp"

int main(int argc, char* argv[]) {
    bool (*tests[])() = {
        test_BootstrapTypes_Allowed_Primitives,
        test_BootstrapTypes_Allowed_Pointers,
        test_BootstrapTypes_Allowed_Arrays,
        test_BootstrapTypes_Allowed_Structs,
        test_BootstrapTypes_Allowed_Enums,
        test_BootstrapTypes_Rejected_Isize,
        test_BootstrapTypes_Rejected_Usize,
        test_BootstrapTypes_Rejected_MultiLevelPointer,
        test_BootstrapTypes_Rejected_Slice,
        test_BootstrapTypes_Rejected_ErrorUnion,
        test_BootstrapTypes_Rejected_Optional,
        test_BootstrapTypes_Rejected_FunctionPointer,
        test_BootstrapTypes_Rejected_TooManyArgs,
        test_BootstrapTypes_Rejected_MultiLevelPointer_StructField,
        test_BootstrapTypes_Rejected_Isize_Param,
        test_BootstrapTypes_Rejected_VoidVariable,
        test_MsvcCompatibility_Int64Mapping,
        test_MsvcCompatibility_TypeSizes,
        test_LiteralIntegration_IntegerDecimal,
        test_LiteralIntegration_IntegerHex,
        test_LiteralIntegration_IntegerUnsigned,
        test_LiteralIntegration_IntegerLong,
        test_LiteralIntegration_IntegerUnsignedLong,
        test_LiteralIntegration_FloatSimple,
        test_LiteralIntegration_FloatScientific,
        test_LiteralIntegration_FloatExplicitF64,
        test_LiteralIntegration_CharBasic,
        test_LiteralIntegration_CharEscape,
        test_LiteralIntegration_StringBasic,
        test_LiteralIntegration_StringEscape,
        test_LiteralIntegration_BoolTrue,
        test_LiteralIntegration_BoolFalse,
        test_LiteralIntegration_NullLiteral,
        test_LiteralIntegration_ExpressionStatement,
        test_VariableIntegration_BasicI32,
        test_VariableIntegration_BasicConstF64,
        test_VariableIntegration_GlobalVar,
        test_VariableIntegration_LocalVar,
        test_VariableIntegration_InferredInt,
        test_VariableIntegration_InferredFloat,
        test_VariableIntegration_InferredBool,
        test_VariableIntegration_MangleKeyword,
        test_VariableIntegration_MangleReserved,
        test_VariableIntegration_MangleLongName,
        test_VariableIntegration_DuplicateNameError,
        test_VariableIntegration_RejectSlice,
        test_VariableIntegration_PointerToVoid
    };

    return run_batch(argc, argv, tests, sizeof(tests) / sizeof(tests[0]));
}
