/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_Bad 1

#include "repro_switch_error.h"


#ifndef ZIG_ERRORUNION_ErrorUnion_i32
#define ZIG_ERRORUNION_ErrorUnion_i32
typedef struct {
    union {
        int payload;
        int err;
    } data;
    int is_error;
} ErrorUnion_i32;
#endif

static ErrorUnion_i32 z_repro_switch_error_foo(int);

static ErrorUnion_i32 z_repro_switch_error_foo(int cond) {
    ErrorUnion_i32 __tmp_switch_5_3;
    switch (cond) {
        case 1:
{
                __tmp_switch_5_3.is_error = 0;
                __tmp_switch_5_3.data.payload = 42;
            }            break;
        case 0:
{
                __tmp_switch_5_3.is_error = 1;
                __tmp_switch_5_3.data.err = ERROR_Bad;
            }            break;
        default:
{
                __bootstrap_panic("reached unreachable", __FILE__, __LINE__);
            }            break;
    }
    return __tmp_switch_5_3;
}

int main(int argc, char* argv[]) {
    int __tmp_catch_6_1;
    ErrorUnion_i32 __tmp_catch_res_6_2;
    __tmp_catch_res_6_2 = z_repro_switch_error_foo(1);
    if (__tmp_catch_res_6_2.is_error) {
        __tmp_catch_6_1 = 0;
    } else {
        __tmp_catch_6_1 = __tmp_catch_res_6_2.data.payload;
    }
    (void)(__tmp_catch_6_1);
    return 0;
}
