/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OpenFailed 1
#define ERROR_ReadFailed 2
#define ERROR_SeekFailed 3
#define ERROR_TooLarge 4
#define ERROR_InvalidSyntax 5
#define ERROR_UnexpectedEnd 6
#define ERROR_ExpectedValue 7
#define ERROR_ExpectedKey 8
#define ERROR_ExpectedColon 9
#define ERROR_ExpectedCommaOrEnd 10
#define ERROR_OutOfMemory 11

#include "json.h"
#include "file.h"
#include "arena.h"

struct z_json_Parser;

struct z_json_Parser {
    Slice_u8 input;
    usize pos;
    void * arena_ptr;
};

#ifndef ZIG_ERRORUNION_ErrorUnion_void
#define ZIG_ERRORUNION_ErrorUnion_void
typedef struct {
    int err;
    int is_error;
} ErrorUnion_void;
#endif

static unsigned char z_json_parser_peek(struct z_json_Parser*);
static void z_json_parser_advance(struct z_json_Parser*);
static void z_json_parser_skipWhitespace(struct z_json_Parser*);
static ErrorUnion_void z_json_parser_expect(struct z_json_Parser*, unsigned char);
static ErrorUnion_z_json_JsonValue z_json_parseValue(struct z_json_Parser*);
static ErrorUnion_z_json_JsonValue z_json_parseNull(struct z_json_Parser*);
static ErrorUnion_z_json_JsonValue z_json_parseBoolean(struct z_json_Parser*);
static ErrorUnion_z_json_JsonValue z_json_parseString(struct z_json_Parser*);
static ErrorUnion_z_json_JsonValue z_json_parseNumber(struct z_json_Parser*);
static int z_json_isDigit(unsigned char);
static double z_json_parseFloat(Slice_u8);
static ErrorUnion_z_json_JsonValue z_json_parseArray(struct z_json_Parser*);
static ErrorUnion_z_json_JsonValue z_json_parseObject(struct z_json_Parser*);

static unsigned char z_json_parser_peek(struct z_json_Parser* self) {
    unsigned char z_json_zero;
    z_json_zero = 0;
    if (self->pos < self->input.len) {
        return self->input.ptr[self->pos];
    } else {
        return z_json_zero;
    }
}

static void z_json_parser_advance(struct z_json_Parser* self) {
    if (self->pos < self->input.len) {
        self->pos += 1;
    }
}

static void z_json_parser_skipWhitespace(struct z_json_Parser* self) {
    while (self->pos < self->input.len) {
        unsigned char z_json_ch;
        z_json_ch = self->input.ptr[self->pos];
        if (z_json_ch == ' ' || z_json_ch == '\t' || z_json_ch == '\n' || z_json_ch == '\r') {
            self->pos += 1;
            /* defers for continue */
            continue;
        }
        /* defers for break */
        break;
    }
}

static ErrorUnion_void z_json_parser_expect(struct z_json_Parser* self, unsigned char c) {
    if (z_json_parser_peek(self) != c) {
        {
            ErrorUnion_void __return_val;
            __return_val.err = ERROR_ExpectedValue;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    z_json_parser_advance(self);
    {
        ErrorUnion_void __implicit_ret = {0};
        return __implicit_ret;
    }
}

ErrorUnion_z_json_JsonValue z_json_parseJson(void * arena_ptr, Slice_u8 input) {
    usize z_json_zero;
    struct z_json_Parser z_json_p;
    struct z_json_JsonValue __tmp_try_5_43;
    ErrorUnion_z_json_JsonValue __tmp_try_res_5_44;
    struct z_json_JsonValue z_json_result;
    z_json_zero = 0;
    z_json_p.input = input;
    z_json_p.pos = z_json_zero;
    z_json_p.arena_ptr = arena_ptr;
    __tmp_try_res_5_44 = z_json_parseValue(&z_json_p);
    if (__tmp_try_res_5_44.is_error) {
        return __tmp_try_res_5_44;
    }
    __tmp_try_5_43 = __tmp_try_res_5_44.data.payload;
    z_json_result = __tmp_try_5_43;
    z_json_parser_skipWhitespace(&z_json_p);
    if (z_json_p.pos < z_json_p.input.len) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.data.err = ERROR_InvalidSyntax;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    {
        ErrorUnion_z_json_JsonValue __return_val;
        __return_val.data.payload = z_json_result;
        __return_val.is_error = 0;
        return __return_val;
    }
}

static ErrorUnion_z_json_JsonValue z_json_parseValue(struct z_json_Parser* p) {
    unsigned char z_json_ch;
    z_json_parser_skipWhitespace(p);
    z_json_ch = z_json_parser_peek(p);
    if (z_json_ch == 'n') {
        ErrorUnion_z_json_JsonValue __tmp_try_7_41;
        ErrorUnion_z_json_JsonValue __tmp_try_res_7_42;
        __tmp_try_res_7_42 = z_json_parseNull(p);
        if (__tmp_try_res_7_42.is_error) {
            __tmp_try_7_41.is_error = 1;
            __tmp_try_7_41.data.err = __tmp_try_res_7_42.data.err;
        } else {
            __tmp_try_7_41.is_error = 0;
            __tmp_try_7_41.data.payload = __tmp_try_res_7_42.data.payload;
        }
        return __tmp_try_7_41;
    }
    if (z_json_ch == 't' || z_json_ch == 'f') {
        ErrorUnion_z_json_JsonValue __tmp_try_7_39;
        ErrorUnion_z_json_JsonValue __tmp_try_res_7_40;
        __tmp_try_res_7_40 = z_json_parseBoolean(p);
        if (__tmp_try_res_7_40.is_error) {
            __tmp_try_7_39.is_error = 1;
            __tmp_try_7_39.data.err = __tmp_try_res_7_40.data.err;
        } else {
            __tmp_try_7_39.is_error = 0;
            __tmp_try_7_39.data.payload = __tmp_try_res_7_40.data.payload;
        }
        return __tmp_try_7_39;
    }
    if (z_json_ch == '"') {
        ErrorUnion_z_json_JsonValue __tmp_try_7_37;
        ErrorUnion_z_json_JsonValue __tmp_try_res_7_38;
        __tmp_try_res_7_38 = z_json_parseString(p);
        if (__tmp_try_res_7_38.is_error) {
            __tmp_try_7_37.is_error = 1;
            __tmp_try_7_37.data.err = __tmp_try_res_7_38.data.err;
        } else {
            __tmp_try_7_37.is_error = 0;
            __tmp_try_7_37.data.payload = __tmp_try_res_7_38.data.payload;
        }
        return __tmp_try_7_37;
    }
    if ((z_json_ch >= '0' && z_json_ch <= '9') || z_json_ch == '-') {
        ErrorUnion_z_json_JsonValue __tmp_try_7_35;
        ErrorUnion_z_json_JsonValue __tmp_try_res_7_36;
        __tmp_try_res_7_36 = z_json_parseNumber(p);
        if (__tmp_try_res_7_36.is_error) {
            __tmp_try_7_35.is_error = 1;
            __tmp_try_7_35.data.err = __tmp_try_res_7_36.data.err;
        } else {
            __tmp_try_7_35.is_error = 0;
            __tmp_try_7_35.data.payload = __tmp_try_res_7_36.data.payload;
        }
        return __tmp_try_7_35;
    }
    if (z_json_ch == '[') {
        ErrorUnion_z_json_JsonValue __tmp_try_7_33;
        ErrorUnion_z_json_JsonValue __tmp_try_res_7_34;
        __tmp_try_res_7_34 = z_json_parseArray(p);
        if (__tmp_try_res_7_34.is_error) {
            __tmp_try_7_33.is_error = 1;
            __tmp_try_7_33.data.err = __tmp_try_res_7_34.data.err;
        } else {
            __tmp_try_7_33.is_error = 0;
            __tmp_try_7_33.data.payload = __tmp_try_res_7_34.data.payload;
        }
        return __tmp_try_7_33;
    }
    if (z_json_ch == '{') {
        ErrorUnion_z_json_JsonValue __tmp_try_7_31;
        ErrorUnion_z_json_JsonValue __tmp_try_res_7_32;
        __tmp_try_res_7_32 = z_json_parseObject(p);
        if (__tmp_try_res_7_32.is_error) {
            __tmp_try_7_31.is_error = 1;
            __tmp_try_7_31.data.err = __tmp_try_res_7_32.data.err;
        } else {
            __tmp_try_7_31.is_error = 0;
            __tmp_try_7_31.data.payload = __tmp_try_res_7_32.data.payload;
        }
        return __tmp_try_7_31;
    }
    {
        ErrorUnion_z_json_JsonValue __return_val;
        __return_val.data.err = ERROR_ExpectedValue;
        __return_val.is_error = 1;
        return __return_val;
    }
}

static ErrorUnion_z_json_JsonValue z_json_parseNull(struct z_json_Parser* p) {
    if (p->input.len - p->pos < 4) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.data.err = ERROR_InvalidSyntax;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    if (p->input.ptr[p->pos] == 'n' && p->input.ptr[p->pos + 1] == 'u' && p->input.ptr[p->pos + 2] == 'l' && p->input.ptr[p->pos + 3] == 'l') {
        struct z_json_JsonValue z_json_val;
        p->pos += 4;
        z_json_val.tag = z_json_JsonValueTag_Null;
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.data.payload = z_json_val;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    {
        ErrorUnion_z_json_JsonValue __return_val;
        __return_val.data.err = ERROR_InvalidSyntax;
        __return_val.is_error = 1;
        return __return_val;
    }
}

static ErrorUnion_z_json_JsonValue z_json_parseBoolean(struct z_json_Parser* p) {
    if (p->input.len - p->pos >= 4 && p->input.ptr[p->pos] == 't' && p->input.ptr[p->pos + 1] == 'r' && p->input.ptr[p->pos + 2] == 'u' && p->input.ptr[p->pos + 3] == 'e') {
        struct z_json_JsonValue z_json_val;
        p->pos += 4;
        z_json_val.tag = z_json_JsonValueTag_Boolean;
        z_json_val.data.boolean = 1;
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.data.payload = z_json_val;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    if (p->input.len - p->pos >= 5 && p->input.ptr[p->pos] == 'f' && p->input.ptr[p->pos + 1] == 'a' && p->input.ptr[p->pos + 2] == 'l' && p->input.ptr[p->pos + 3] == 's' && p->input.ptr[p->pos + 4] == 'e') {
        struct z_json_JsonValue z_json_val_1;
        p->pos += 5;
        z_json_val_1.tag = z_json_JsonValueTag_Boolean;
        z_json_val_1.data.boolean = 0;
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.data.payload = z_json_val_1;
            __return_val.is_error = 0;
            return __return_val;
        }
    }
    {
        ErrorUnion_z_json_JsonValue __return_val;
        __return_val.data.err = ERROR_InvalidSyntax;
        __return_val.is_error = 1;
        return __return_val;
    }
}

static ErrorUnion_z_json_JsonValue z_json_parseString(struct z_json_Parser* p) {
    ErrorUnion_void __tmp_try_res_5_30;
    usize z_json_start;
    Slice_u8 z_json_slice;
    ErrorUnion_void __tmp_try_res_5_28;
    struct z_json_JsonValue z_json_val;
    __tmp_try_res_5_30 = z_json_parser_expect(p, '"');
    if (__tmp_try_res_5_30.is_error) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_start = p->pos;
    while (p->pos < p->input.len) {
        if (p->input.ptr[p->pos] == '"') {
            /* defers for break */
            break;
        }
        if (p->input.ptr[p->pos] == '\\') {
            p->pos += 1;
        }
        p->pos += 1;
    }
    if (p->pos >= p->input.len) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.data.err = ERROR_UnexpectedEnd;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    z_json_slice = __make_slice_u8(p->input.ptr + z_json_start, p->pos - z_json_start);
    __tmp_try_res_5_28 = z_json_parser_expect(p, '"');
    if (__tmp_try_res_5_28.is_error) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_val.tag = z_json_JsonValueTag_String;
    z_json_val.data.string = z_json_slice;
    {
        ErrorUnion_z_json_JsonValue __return_val;
        __return_val.data.payload = z_json_val;
        __return_val.is_error = 0;
        return __return_val;
    }
}

static ErrorUnion_z_json_JsonValue z_json_parseNumber(struct z_json_Parser* p) {
    usize z_json_start;
    Slice_u8 z_json_slice;
    double z_json_val_f;
    struct z_json_JsonValue z_json_val;
    z_json_start = p->pos;
    if (z_json_parser_peek(p) == '-') {
        z_json_parser_advance(p);
    }
    while (z_json_isDigit(z_json_parser_peek(p))) {
        z_json_parser_advance(p);
    }
    if (z_json_parser_peek(p) == '.') {
        z_json_parser_advance(p);
        while (z_json_isDigit(z_json_parser_peek(p))) {
            z_json_parser_advance(p);
        }
    }
    if (z_json_parser_peek(p) == 'e' || z_json_parser_peek(p) == 'E') {
        z_json_parser_advance(p);
        if (z_json_parser_peek(p) == '+' || z_json_parser_peek(p) == '-') {
            z_json_parser_advance(p);
        }
        while (z_json_isDigit(z_json_parser_peek(p))) {
            z_json_parser_advance(p);
        }
    }
    z_json_slice = __make_slice_u8(p->input.ptr + z_json_start, p->pos - z_json_start);
    z_json_val_f = z_json_parseFloat(z_json_slice);
    z_json_val.tag = z_json_JsonValueTag_Number;
    z_json_val.data.number = z_json_val_f;
    {
        ErrorUnion_z_json_JsonValue __return_val;
        __return_val.data.payload = z_json_val;
        __return_val.is_error = 0;
        return __return_val;
    }
}

static int z_json_isDigit(unsigned char c) {
    return c >= '0' && c <= '9';
}

static double z_json_parseFloat(Slice_u8 s) {
    unsigned char z_json_buf[64];
    usize z_json_i;
    Optional_Ptr_c_char z_json_endptr;
    Optional_Ptr_c_char __tmp_arg_opt_5_25;
    char const* __tmp_arg_unwrapped_5_26;
    z_json_i = 0;
    while (z_json_i < s.len && z_json_i < 63) {
        z_json_buf[z_json_i] = s.ptr[z_json_i];
        z_json_i += 1;
    }
    z_json_buf[z_json_i] = 0;
    z_json_endptr.has_value = 0;
    __tmp_arg_opt_5_25 = z_json_endptr;
    if (__tmp_arg_opt_5_25.has_value) {
        __tmp_arg_unwrapped_5_26 = __tmp_arg_opt_5_25.value;
    } else {
        __tmp_arg_unwrapped_5_26 = 0;
    }
    return strtod((char const*)&z_json_buf[0], __tmp_arg_unwrapped_5_26);
}

static ErrorUnion_z_json_JsonValue z_json_parseArray(struct z_json_Parser* p) {
    ErrorUnion_void __tmp_try_res_5_24;
    usize z_json_count;
    usize z_json_saved_pos;
    Slice_u8 z_json_bytes;
    Slice_z_json_JsonValue z_json_arr;
    usize z_json_idx;
    ErrorUnion_void __tmp_try_res_5_18;
    struct z_json_JsonValue z_json_val;
    __tmp_try_res_5_24 = z_json_parser_expect(p, '[');
    if (__tmp_try_res_5_24.is_error) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_parser_skipWhitespace(p);
    z_json_count = 0;
    z_json_saved_pos = p->pos;
    if (z_json_parser_peek(p) != ']') {
        while (1) {
            struct z_json_JsonValue __tmp_try_10_21;
            ErrorUnion_z_json_JsonValue __tmp_try_res_10_22;
            __tmp_try_res_10_22 = z_json_parseValue(p);
            if (__tmp_try_res_10_22.is_error) {
                return __tmp_try_res_10_22;
            }
            __tmp_try_10_21 = __tmp_try_res_10_22.data.payload;
            (void)(__tmp_try_10_21);
            z_json_count += 1;
            z_json_parser_skipWhitespace(p);
            if (z_json_parser_peek(p) == ',') {
                z_json_parser_advance(p);
                z_json_parser_skipWhitespace(p);
                /* defers for continue */
                continue;
            }
            /* defers for break */
            break;
        }
        if (z_json_parser_peek(p) != ']') {
            {
                ErrorUnion_z_json_JsonValue __return_val;
                __return_val.data.err = ERROR_ExpectedCommaOrEnd;
                __return_val.is_error = 1;
                return __return_val;
            }
        }
    }
    p->pos = z_json_saved_pos;
    z_json_bytes = z_arena_alloc_bytes(z_json_count * 16);
    z_json_arr = __make_slice_z_json_JsonValue((struct z_json_JsonValue*)z_json_bytes.ptr + 0, z_json_count - 0);
    z_json_idx = 0;
    if (z_json_parser_peek(p) != ']') {
        while (z_json_idx < z_json_count) {
            struct z_json_JsonValue __tmp_try_10_19;
            ErrorUnion_z_json_JsonValue __tmp_try_res_10_20;
            __tmp_try_res_10_20 = z_json_parseValue(p);
            if (__tmp_try_res_10_20.is_error) {
                return __tmp_try_res_10_20;
            }
            __tmp_try_10_19 = __tmp_try_res_10_20.data.payload;
            z_json_arr.ptr[z_json_idx] = __tmp_try_10_19;
            z_json_idx += 1;
            z_json_parser_skipWhitespace(p);
            if (z_json_parser_peek(p) == ',') {
                z_json_parser_advance(p);
                z_json_parser_skipWhitespace(p);
                /* defers for continue */
                continue;
            }
            /* defers for break */
            break;
        }
    }
    __tmp_try_res_5_18 = z_json_parser_expect(p, ']');
    if (__tmp_try_res_5_18.is_error) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_val.tag = z_json_JsonValueTag_Array;
    z_json_val.data.array = z_json_arr;
    {
        ErrorUnion_z_json_JsonValue __return_val;
        __return_val.data.payload = z_json_val;
        __return_val.is_error = 0;
        return __return_val;
    }
}

static ErrorUnion_z_json_JsonValue z_json_parseObject(struct z_json_Parser* p) {
    ErrorUnion_void __tmp_try_res_5_16;
    usize z_json_count;
    usize z_json_saved_pos;
    Slice_u8 z_json_bytes;
    Slice_z_json_JsonObjectEntry z_json_fields;
    usize z_json_idx;
    ErrorUnion_void __tmp_try_res_5_2;
    struct z_json_JsonValue z_json_val;
    __tmp_try_res_5_16 = z_json_parser_expect(p, '{');
    if (__tmp_try_res_5_16.is_error) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_parser_skipWhitespace(p);
    z_json_count = 0;
    z_json_saved_pos = p->pos;
    if (z_json_parser_peek(p) != '}') {
        while (1) {
            struct z_json_JsonValue __tmp_try_9_13;
            ErrorUnion_z_json_JsonValue __tmp_try_res_9_14;
            struct z_json_JsonValue z_json_keyVal;
            ErrorUnion_void __tmp_try_res_9_12;
            struct z_json_JsonValue __tmp_try_10_9;
            ErrorUnion_z_json_JsonValue __tmp_try_res_10_10;
            __tmp_try_res_9_14 = z_json_parseString(p);
            if (__tmp_try_res_9_14.is_error) {
                return __tmp_try_res_9_14;
            }
            __tmp_try_9_13 = __tmp_try_res_9_14.data.payload;
            z_json_keyVal = __tmp_try_9_13;
            (void)(z_json_keyVal);
            z_json_parser_skipWhitespace(p);
            __tmp_try_res_9_12 = z_json_parser_expect(p, ':');
            if (__tmp_try_res_9_12.is_error) {
                {
                    ErrorUnion_z_json_JsonValue __return_val;
                    __return_val.is_error = 1;
                    return __return_val;
                }
            }
            0;
            __tmp_try_res_10_10 = z_json_parseValue(p);
            if (__tmp_try_res_10_10.is_error) {
                return __tmp_try_res_10_10;
            }
            __tmp_try_10_9 = __tmp_try_res_10_10.data.payload;
            (void)(__tmp_try_10_9);
            z_json_count += 1;
            z_json_parser_skipWhitespace(p);
            if (z_json_parser_peek(p) == ',') {
                z_json_parser_advance(p);
                z_json_parser_skipWhitespace(p);
                /* defers for continue */
                continue;
            }
            /* defers for break */
            break;
        }
        if (z_json_parser_peek(p) != '}') {
            {
                ErrorUnion_z_json_JsonValue __return_val;
                __return_val.data.err = ERROR_ExpectedCommaOrEnd;
                __return_val.is_error = 1;
                return __return_val;
            }
        }
    }
    p->pos = z_json_saved_pos;
    z_json_bytes = z_arena_alloc_bytes(z_json_count * 12);
    z_json_fields = __make_slice_z_json_JsonObjectEntry((struct z_json_JsonObjectEntry*)z_json_bytes.ptr + 0, z_json_count - 0);
    z_json_idx = 0;
    if (z_json_parser_peek(p) != '}') {
        while (z_json_idx < z_json_count) {
            struct z_json_JsonValue __tmp_try_9_7;
            ErrorUnion_z_json_JsonValue __tmp_try_res_9_8;
            struct z_json_JsonValue z_json_keyVal_1;
            Slice_u8 z_json_key;
            ErrorUnion_void __tmp_try_res_9_6;
            struct z_json_JsonValue __tmp_try_9_3;
            ErrorUnion_z_json_JsonValue __tmp_try_res_9_4;
            struct z_json_JsonValue z_json_val_1;
            Slice_u8 z_json_val_ptr_bytes;
            struct z_json_JsonValue* z_json_val_ptr;
            __tmp_try_res_9_8 = z_json_parseString(p);
            if (__tmp_try_res_9_8.is_error) {
                return __tmp_try_res_9_8;
            }
            __tmp_try_9_7 = __tmp_try_res_9_8.data.payload;
            z_json_keyVal_1 = __tmp_try_9_7;
            z_json_key = z_json_keyVal_1.data.string;
            z_json_parser_skipWhitespace(p);
            __tmp_try_res_9_6 = z_json_parser_expect(p, ':');
            if (__tmp_try_res_9_6.is_error) {
                {
                    ErrorUnion_z_json_JsonValue __return_val;
                    __return_val.is_error = 1;
                    return __return_val;
                }
            }
            0;
            __tmp_try_res_9_4 = z_json_parseValue(p);
            if (__tmp_try_res_9_4.is_error) {
                return __tmp_try_res_9_4;
            }
            __tmp_try_9_3 = __tmp_try_res_9_4.data.payload;
            z_json_val_1 = __tmp_try_9_3;
            z_json_val_ptr_bytes = z_arena_alloc_bytes(16);
            z_json_val_ptr = (struct z_json_JsonValue*)z_json_val_ptr_bytes.ptr;
            *z_json_val_ptr = z_json_val_1;
            z_json_fields.ptr[z_json_idx].key = z_json_key;
            z_json_fields.ptr[z_json_idx].value = z_json_val_ptr;
            z_json_idx += 1;
            z_json_parser_skipWhitespace(p);
            if (z_json_parser_peek(p) == ',') {
                z_json_parser_advance(p);
                z_json_parser_skipWhitespace(p);
                /* defers for continue */
                continue;
            }
            /* defers for break */
            break;
        }
    }
    __tmp_try_res_5_2 = z_json_parser_expect(p, '}');
    if (__tmp_try_res_5_2.is_error) {
        {
            ErrorUnion_z_json_JsonValue __return_val;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    0;
    z_json_val.tag = z_json_JsonValueTag_Object;
    z_json_val.data.object = z_json_fields;
    {
        ErrorUnion_z_json_JsonValue __return_val;
        __return_val.data.payload = z_json_val;
        __return_val.is_error = 0;
        return __return_val;
    }
}
