/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

#include "test.h"


static void private(void);

static void private(void) {
    Slice_u8 x;
}

int main(int argc, char* argv[]) {
    private();
    return 0;
}
