/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

#include "test.h"


struct Node;
ErrorUnion_Node get_node(void) {
    {
        ErrorUnion_Node __return_val;
        __return_val = ;
        return __return_val;
    }
}
