#!/bin/sh
set -e
# Build script generated by Z98 bootstrap compiler

gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -Isrc/include -c zig_runtime.c -o zig_runtime.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -Isrc/include -c builtin.c -o builtin.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -Isrc/include -c dict.c -o dict.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -Isrc/include -c io.c -o io.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -Isrc/include -c decompress.c -o decompress.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -Isrc/include -c compress.c -o compress.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -Isrc/include -c main.c -o main.o
gcc -m32 -o app zig_runtime.o builtin.o dict.o io.o decompress.o compress.o main.o
