/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_DictionaryFull 1
#define ERROR_InvalidInput 2
#define ERROR_IOError 3

#include "decompress.h"
#include "dict.h"
#include "io.h"


static unsigned char zF_149b62_emitAndGetFirst(struct zS_37a939_Dictionary*, int);

static unsigned char zF_149b62_emitAndGetFirst(struct zS_37a939_Dictionary* lzw_dict, int code) {
    int prefix;
    unsigned char z_char;
    unsigned char first;
    if (code < 256) {
        unsigned char c;
        c = __bootstrap_u8_from_i32(code);
        zF_387c31_writeByte(c);
        return c;
    }
    prefix = zF_37a939_getPrefix(lzw_dict, __bootstrap_usize_from_i32(code));
    z_char = zF_37a939_getChar(lzw_dict, __bootstrap_usize_from_i32(code));
    first = zF_149b62_emitAndGetFirst(lzw_dict, prefix);
    zF_387c31_writeByte(z_char);
    return first;
}

ErrorUnion_void zF_149b62_decompress(void) {
    int err_occurred = 0;
    struct zS_37a939_Dictionary lzw_dict;
    int first_code;
    int old_code;
    unsigned char z_char;
    zF_37a939_init(&lzw_dict);
    first_code = zF_387c31_readCode();
    if (first_code == -1) {
        {
            ErrorUnion_void __return_val = {0};
            if (__return_val.is_error) err_occurred = 1;
            if (err_occurred) {
                {
                    zF_387c31_printErr("Decompression aborted.");
                }
            }
            return __return_val;
        }
    }
    old_code = first_code;
    z_char = zF_149b62_emitAndGetFirst(&lzw_dict, old_code);
    __loop_0_start: ;
    if (!(1)) goto __loop_0_end;
    {
        int new_code;
        new_code = zF_387c31_readCode();
        if (new_code == -1) {
            /* defers for break */
            goto __loop_0_end;
        }
        if (__bootstrap_usize_from_i32(new_code) < lzw_dict.size) {
            z_char = zF_149b62_emitAndGetFirst(&lzw_dict, new_code);
            ;
        } else {
            unsigned char first;
            first = zF_149b62_emitAndGetFirst(&lzw_dict, old_code);
            zF_387c31_writeByte(first);
            ;
        }
        old_code = new_code;
    }
    goto __loop_0_start;
    __loop_0_end: ;
    {
        ErrorUnion_void __implicit_ret = {0};
        return __implicit_ret;
    }
}
