/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_DictionaryFull 1
#define ERROR_InvalidInput 2
#define ERROR_IOError 3

#include "main.h"
#include "dict.h"
#include "io.h"
#include "compress.h"
#include "decompress.h"


int getchar(void);

extern int getchar(void);

int main(void) {
    int choice;
    int next;
    zF_387c31_printStr("LZW Compressor/Decompressor Demo\n");
    zF_387c31_printStr("Select mode: [c]ompress, [d]ecompress: ");
    choice = getchar();
    next = getchar();
    if (next != (int)'\n' && next != -1) {
    }
    if (choice == (int)'c') {
        zF_387c31_printStr("Enter text to compress (end with EOF/Ctrl-D):\n");
        ;
        zF_387c31_writeByte('\n');
    } else     if (choice == (int)'d') {
        zF_387c31_printStr("Enter space-separated codes to decompress (end with EOF/Ctrl-D):\n");
        ;
        zF_387c31_writeByte('\n');
    } else {
        zF_387c31_printErr("Invalid choice!");
    }

    {
        zF_387c31_printStr("LZW Operation Finished.\n");
    }
    return 0;
}
