@echo off
:: Build script generated by Z98 bootstrap compiler
:: Optimized for MinGW

:: NOTE: If you get "undefined reference to WinMain@16" errors,
:: try removing the -mconsole flag from the linking step.

gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c zig_runtime.c -o zig_runtime.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c net_runtime.c -o net_runtime.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c builtin.c -o builtin.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c lib_a.c -o lib_a.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c lib_b.c -o lib_b.o
gcc -std=c89 -m32 -mconsole -static-libgcc -pedantic -Wall -O2 -I. -Isrc/include -c main.c -o main.o
gcc -m32 -mconsole -static-libgcc -o app.exe zig_runtime.o net_runtime.o builtin.o lib_a.o lib_b.o main.o
