/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

#include "lib_b.h"
#include "lib_a.h"


void zF_629ef6_use_lib_a(void) {
    const struct zS_a1fabf_MyStruct s = {10};
    zF_a1fabf_print_green(&(*zC_a1fabf_ANSI_GREEN)[0]);
    zV_a1fabf_global_counter = zV_a1fabf_global_counter + 1;
}
