/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

#include "lib_a.h"


const unsigned char const (* zC_a1fabf_ANSI_GREEN)[5] = "green";
int zV_a1fabf_global_counter = 0;
void zF_a1fabf_print_green(unsigned char const* s) {
}
