/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

#include "main.h"
#include "lib_a.h"
#include "lib_b.h"


int main(void) {
    zF_629ef6_use_lib_a();
    zF_a1fabf_print_green("Hello");
    return 0;
}
