/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

#include "quicksort.h"

extern void z_quicksort___bootstrap_print(unsigned char* s);

extern void z_quicksort___bootstrap_print_i(int n);

static void z_quicksort_quicksort(int* ptr, unsigned int len, int (* cmp)(int, int)) {
    int z_quicksort_pivot;
    unsigned int z_quicksort_i;
    unsigned int z_quicksort_j;
    if (ptr == ((void*)0)) {
        return;
    }
    if (len < 2) {
        return;
    }
    z_quicksort_pivot = ptr[0];
    z_quicksort_i = 1;
    z_quicksort_j = len - 1;
    while (z_quicksort_i <= z_quicksort_j) {
        if (cmp(ptr[z_quicksort_i], z_quicksort_pivot)) {
            z_quicksort_i += 1;
        } else         if (cmp(z_quicksort_pivot, ptr[z_quicksort_j])) {
            z_quicksort_j -= 1;
        } else {
            int z_quicksort_tmp;
            z_quicksort_tmp = ptr[z_quicksort_i];
            ptr[z_quicksort_i] = ptr[z_quicksort_j];
            ptr[z_quicksort_j] = z_quicksort_tmp;
            z_quicksort_i += 1;
            z_quicksort_j -= 1;
        }

    }
    ptr[0] = ptr[z_quicksort_j];
    ptr[z_quicksort_j] = z_quicksort_pivot;
    z_quicksort_quicksort(ptr, z_quicksort_j, cmp);
    z_quicksort_quicksort(ptr + z_quicksort_i, len - z_quicksort_i, cmp);
}

static int z_quicksort_lessThan(int a, int b) {
    return a < b;
}

static int z_quicksort_greaterThan(int a, int b) {
    return a > b;
}

static void z_quicksort_printArray(int* ptr, unsigned int len) {
    unsigned int z_quicksort_i;
    z_quicksort_i = 0;
    while (z_quicksort_i < len) {
        __bootstrap_print_int(ptr[z_quicksort_i]);
        __bootstrap_print(" ");
        z_quicksort_i += 1;
    }
    __bootstrap_print("\n");
}

int main(int argc, char* argv[]) {
    int z_quicksort_arr[10];
    z_quicksort_arr[0] = 3;
    z_quicksort_arr[1] = 1;
    z_quicksort_arr[2] = 4;
    z_quicksort_arr[3] = 1;
    z_quicksort_arr[4] = 5;
    z_quicksort_arr[5] = 9;
    z_quicksort_arr[6] = 2;
    z_quicksort_arr[7] = 6;
    z_quicksort_arr[8] = 5;
    z_quicksort_arr[9] = 3;
    __bootstrap_print("Original: 3 1 4 1 5 9 2 6 5 3\n");
    __bootstrap_print("Sorted (ascending): ");
    z_quicksort_quicksort((int*)&z_quicksort_arr, 10, z_quicksort_lessThan);
    z_quicksort_printArray((int*)&z_quicksort_arr, 10);
    __bootstrap_print("Sorted (descending): ");
    z_quicksort_quicksort((int*)&z_quicksort_arr, 10, z_quicksort_greaterThan);
    z_quicksort_printArray((int*)&z_quicksort_arr, 10);
}
