/* zig_pal.c - Platform Abstraction Layer (generated by zig1) */
#ifndef ZIG_PAL_C
#define ZIG_PAL_C
#include "zig_compat.h"

#ifdef _WIN32
#include <windows.h>
#else
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#endif

#ifdef _WIN32
typedef void* PlatFile;
#define PLAT_INVALID_FILE ((void*)(isize)-1)
#else
typedef int PlatFile;
#define PLAT_INVALID_FILE (-1)
#endif

static usize pal_strlen(const char* s)
{
#ifdef _WIN32
    const char* p = s;
    while (*p) p++;
    return (usize)(p - s);
#else
    return (usize)strlen(s);
#endif
}

static void pal_memcpy(void* dst, const void* src, usize n)
{
#ifdef _WIN32
    char* d = (char*)dst;
    const char* s = (const char*)src;
    while (n--) *d++ = *s++;
#else
    memcpy(dst, src, (size_t)n);
#endif
}

static void pal_reverse(char* buf, int len)
{
    int i = 0;
    int j = len - 1;
    while (i < j) {
        char t = buf[i];
        buf[i] = buf[j];
        buf[j] = t;
        i++;
        j--;
    }
}

static int pal_u64_to_str_buf(u64 value, char* buf, int bufsize)
{
    int i;
    if (bufsize <= 0) return 0;
    if (value == 0) {
        buf[0] = '0';
        buf[1] = '\0';
        return 1;
    }
    i = 0;
    while (value > 0 && i < bufsize - 1) {
        buf[i++] = '0' + (char)(value % 10);
        value /= 10;
    }
    buf[i] = '\0';
    pal_reverse(buf, i);
    return i;
}

void pal_print_stderr(const char* msg, usize len)
{
#ifdef _WIN32
    HANDLE h;
    DWORD written;
    if (!msg || len == 0) return;
    h = GetStdHandle(STD_ERROR_HANDLE);
    if (h == INVALID_HANDLE_VALUE || h == NULL) return;
    if (!WriteConsoleA(h, msg, (DWORD)len, &written, NULL))
        WriteFile(h, msg, (DWORD)len, &written, NULL);
#else
    write(2, msg, (size_t)len);
#endif
}

void pal_abort(void)
{
#ifdef _WIN32
    TerminateProcess(GetCurrentProcess(), 3);
#else
    abort();
#endif
}

int pal_i64_to_str(i64 value, char* buf, int bufsize)
{
    u64 uval;
    int is_neg;
    int dlen;
    if (bufsize <= 0) return 0;
    if (value == 0) {
        buf[0] = '0';
        buf[1] = '\0';
        return 1;
    }
    is_neg = (value < 0) ? 1 : 0;
    uval = is_neg ? (u64)(-(value + 1)) + 1 : (u64)value;
    if (is_neg) {
        buf[0] = '-';
        dlen = pal_u64_to_str_buf(uval, buf + 1, bufsize - 1);
        return dlen + 1;
    }
    return pal_u64_to_str_buf(uval, buf, bufsize);
}

int pal_u64_to_str(u64 value, char* buf, int bufsize)
{
    return pal_u64_to_str_buf(value, buf, bufsize);
}

int pal_f64_to_str(f64 value, char* buf, int bufsize)
{
    int int_len;
    int i;
    f64 frac_part;
    i64 int_part;
    u64 frac_int;
    int pos;
    if (bufsize < 2) {
        if (bufsize == 1) buf[0] = '\0';
        return 0;
    }
    if (value < 0.0) {
        buf[0] = '-';
        pos = 1;
        value = -value;
    } else {
        pos = 0;
    }
    int_part = (i64)value;
    int_len = pal_i64_to_str(int_part, buf + pos, bufsize - pos);
    if (int_len <= 0) return 0;
    pos += int_len;
    buf[pos++] = '.';
    frac_part = value - (f64)int_part;
    i = 0;
    while (i < 6 && pos < bufsize - 1) {
        frac_part *= 10.0;
        frac_int = (u64)frac_part;
        buf[pos++] = '0' + (char)(frac_int % 10);
        frac_part -= (f64)frac_int;
        i++;
    }
    while (pos > 0 && buf[pos - 1] == '0') pos--;
    if (buf[pos - 1] == '.') pos++;
    buf[pos] = '\0';
    return pos;
}

#if defined(_WIN32) && defined(ZIG_NO_CRT)
int main(void);
void __cdecl mainCRTStartup(void)
{
    int result = main();
    ExitProcess((UINT)result);
}
#endif

#endif /* ZIG_PAL_C */
