/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OutOfMemory 1
#define ERROR_UnexpectedRParen 2
#define ERROR_UnexpectedEof 3
#define ERROR_UnexpectedToken 4
#define ERROR_InvalidQuote 5
#define ERROR_InvalidIf 6
#define ERROR_InvalidDefine 7
#define ERROR_InvalidLambda 8
#define ERROR_InvalidExpr 9
#define ERROR_NotCallable 10
#define ERROR_InvalidClosure 11
#define ERROR_InvalidEnv 12
#define ERROR_UnboundSymbol 13
#define ERROR_WrongArity 14
#define ERROR_NotACons 15
#define ERROR_NotAnInt 16
#define ERROR_DivisionByZero 17
#define ERROR_InvalidParams 18
#define ERROR_Unreachable 19
#define ERROR_InvalidDigit 20
#define ERROR_TooManyArgs 21
#define ERROR_TooFewArgs 22

#include "builtins.h"
#include "value.h"
#include "util.h"
#include "sand.h"


ErrorUnion_Ptr_z_value_Value z_builtins_builtin_cons(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    struct z_value_Value* __tmp_try_7_19;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_20;
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    __tmp_try_res_7_20 = z_value_alloc_cons(args.ptr[0], args.ptr[1], arena);
    if (__tmp_try_res_7_20.is_error) {
        return __tmp_try_res_7_20;
    }
    __tmp_try_7_19 = __tmp_try_res_7_20.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_19;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_car(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    if (args.len != 1) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
/* DEBUG: emitSwitch start */
    {
        struct z_value_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case z_value_Value_Tag_Cons:
            {
                /* DEBUG: capture data */
                struct {
                    struct z_value_Value* car;
                    struct z_value_Value* cdr;
                } data = switch_tmp.data.Cons;
{
                {
                    ErrorUnion_Ptr_z_value_Value __return_val;
                    __return_val.is_error = 0;
                    __return_val.data.payload = data.car;
                    return __return_val;
                }
            }            }
            break;
        default:
{
                {
                    ErrorUnion_Ptr_z_value_Value __return_val;
                    __return_val.is_error = 1;
                    __return_val.data.err = ERROR_NotACons;
                    return __return_val;
                }
            }            break;
    }
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_cdr(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    if (args.len != 1) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
/* DEBUG: emitSwitch start */
    {
        struct z_value_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case z_value_Value_Tag_Cons:
            {
                /* DEBUG: capture data */
                struct {
                    struct z_value_Value* car;
                    struct z_value_Value* cdr;
                } data = switch_tmp.data.Cons;
{
                {
                    ErrorUnion_Ptr_z_value_Value __return_val;
                    __return_val.is_error = 0;
                    __return_val.data.payload = data.cdr;
                    return __return_val;
                }
            }            }
            break;
        default:
{
                {
                    ErrorUnion_Ptr_z_value_Value __return_val;
                    __return_val.is_error = 1;
                    __return_val.data.err = ERROR_NotACons;
                    return __return_val;
                }
            }            break;
    }
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_add(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    i64 z_builtins_sum;
    struct z_value_Value* __tmp_try_7_17;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_18;
    z_builtins_sum = 0;
    {
        Slice_Ptr_z_value_Value __for_iter_1 = args;
        size_t __for_idx_1 = 0;
        size_t __for_len_1 = __for_iter_1.len;
        __loop_0_start: ;
        while (__for_idx_1 < __for_len_1) {
            struct z_value_Value* arg = __for_iter_1.ptr[__for_idx_1];
{
/* DEBUG: emitSwitch start */
                {
                    struct z_value_Value switch_tmp = *arg;
                    switch (switch_tmp.tag) {
                    case z_value_Value_Tag_Int:
                        {
                            /* DEBUG: capture val */
                            i64 val = switch_tmp.data.Int;
{
                            z_builtins_sum += val;
                        }                        }
                        break;
                    default:
{
                            {
                                ErrorUnion_Ptr_z_value_Value __return_val;
                                __return_val.is_error = 1;
                                __return_val.data.err = ERROR_NotAnInt;
                                return __return_val;
                            }
                        }                        break;
                }
                }
            }
            __loop_0_continue: ;
            __for_idx_1++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    __tmp_try_res_7_18 = z_value_alloc_int(z_builtins_sum, arena);
    if (__tmp_try_res_7_18.is_error) {
        return __tmp_try_res_7_18;
    }
    __tmp_try_7_17 = __tmp_try_res_7_18.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_17;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_sub(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    i64 z_builtins_res;
    usize z_builtins_i;
    struct z_value_Value* __tmp_try_7_13;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_14;
    if (args.len == 0) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    z_builtins_res = 0;
/* DEBUG: emitSwitch start */
    {
        struct z_value_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case z_value_Value_Tag_Int:
            {
                /* DEBUG: capture val */
                i64 val = switch_tmp.data.Int;
{
                z_builtins_res = val;
            }            }
            break;
        default:
{
                {
                    ErrorUnion_Ptr_z_value_Value __return_val;
                    __return_val.is_error = 1;
                    __return_val.data.err = ERROR_NotAnInt;
                    return __return_val;
                }
            }            break;
    }
    }
    if (args.len == 1) {
        struct z_value_Value* __tmp_try_9_15;
        ErrorUnion_Ptr_z_value_Value __tmp_try_res_9_16;
        __tmp_try_res_9_16 = z_value_alloc_int(-z_builtins_res, arena);
        if (__tmp_try_res_9_16.is_error) {
            return __tmp_try_res_9_16;
        }
        __tmp_try_9_15 = __tmp_try_res_9_16.data.payload;
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 0;
            __return_val.data.payload = __tmp_try_9_15;
            return __return_val;
        }
    }
    z_builtins_i = 1;
    __loop_0_start: ;
    if (!(z_builtins_i < args.len)) goto __loop_0_end;
    {
/* DEBUG: emitSwitch start */
        {
            struct z_value_Value switch_tmp_1 = *args.ptr[z_builtins_i];
            switch (switch_tmp_1.tag) {
            case z_value_Value_Tag_Int:
                {
                    /* DEBUG: capture val */
                    i64 val_1 = switch_tmp_1.data.Int;
{
                    z_builtins_res -= val_1;
                }                }
                break;
            default:
{
                    {
                        ErrorUnion_Ptr_z_value_Value __return_val;
                        __return_val.is_error = 1;
                        __return_val.data.err = ERROR_NotAnInt;
                        return __return_val;
                    }
                }                break;
        }
        }
        z_builtins_i += 1;
    }
    __loop_0_continue: ;
    goto __loop_0_start;
    __loop_0_end: ;
    __tmp_try_res_7_14 = z_value_alloc_int(z_builtins_res, arena);
    if (__tmp_try_res_7_14.is_error) {
        return __tmp_try_res_7_14;
    }
    __tmp_try_7_13 = __tmp_try_res_7_14.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_13;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_mul(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    i64 z_builtins_res;
    struct z_value_Value* __tmp_try_7_11;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_12;
    z_builtins_res = 1;
    {
        Slice_Ptr_z_value_Value __for_iter_1 = args;
        size_t __for_idx_1 = 0;
        size_t __for_len_1 = __for_iter_1.len;
        __loop_0_start: ;
        while (__for_idx_1 < __for_len_1) {
            struct z_value_Value* arg = __for_iter_1.ptr[__for_idx_1];
{
/* DEBUG: emitSwitch start */
                {
                    struct z_value_Value switch_tmp = *arg;
                    switch (switch_tmp.tag) {
                    case z_value_Value_Tag_Int:
                        {
                            /* DEBUG: capture val */
                            i64 val = switch_tmp.data.Int;
{
                            z_builtins_res *= val;
                        }                        }
                        break;
                    default:
{
                            {
                                ErrorUnion_Ptr_z_value_Value __return_val;
                                __return_val.is_error = 1;
                                __return_val.data.err = ERROR_NotAnInt;
                                return __return_val;
                            }
                        }                        break;
                }
                }
            }
            __loop_0_continue: ;
            __for_idx_1++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    __tmp_try_res_7_12 = z_value_alloc_int(z_builtins_res, arena);
    if (__tmp_try_res_7_12.is_error) {
        return __tmp_try_res_7_12;
    }
    __tmp_try_7_11 = __tmp_try_res_7_12.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_11;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_div(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    i64 z_builtins_res;
    usize z_builtins_i;
    struct z_value_Value* __tmp_try_7_9;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_10;
    if (args.len == 0) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    z_builtins_res = 0;
/* DEBUG: emitSwitch start */
    {
        struct z_value_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case z_value_Value_Tag_Int:
            {
                /* DEBUG: capture val */
                i64 val = switch_tmp.data.Int;
{
                z_builtins_res = val;
            }            }
            break;
        default:
{
                {
                    ErrorUnion_Ptr_z_value_Value __return_val;
                    __return_val.is_error = 1;
                    __return_val.data.err = ERROR_NotAnInt;
                    return __return_val;
                }
            }            break;
    }
    }
    z_builtins_i = 1;
    __loop_0_start: ;
    if (!(z_builtins_i < args.len)) goto __loop_0_end;
    {
/* DEBUG: emitSwitch start */
        {
            struct z_value_Value switch_tmp_1 = *args.ptr[z_builtins_i];
            switch (switch_tmp_1.tag) {
            case z_value_Value_Tag_Int:
                {
                    /* DEBUG: capture val */
                    i64 val_1 = switch_tmp_1.data.Int;
{
                    if (val_1 == 0) {
                        {
                            ErrorUnion_Ptr_z_value_Value __return_val;
                            __return_val.is_error = 1;
                            __return_val.data.err = ERROR_DivisionByZero;
                            return __return_val;
                        }
                    }
                    z_builtins_res /= val_1;
                }                }
                break;
            default:
{
                    {
                        ErrorUnion_Ptr_z_value_Value __return_val;
                        __return_val.is_error = 1;
                        __return_val.data.err = ERROR_NotAnInt;
                        return __return_val;
                    }
                }                break;
        }
        }
        z_builtins_i += 1;
    }
    __loop_0_continue: ;
    goto __loop_0_start;
    __loop_0_end: ;
    __tmp_try_res_7_10 = z_value_alloc_int(z_builtins_res, arena);
    if (__tmp_try_res_7_10.is_error) {
        return __tmp_try_res_7_10;
    }
    __tmp_try_7_9 = __tmp_try_res_7_10.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_9;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_eq(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    struct z_value_Value* z_builtins_a;
    struct z_value_Value* z_builtins_b;
    int z_builtins_res;
    struct z_value_Value* __tmp_try_7_7;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_8;
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    z_builtins_a = args.ptr[0];
    z_builtins_b = args.ptr[1];
    z_builtins_res = 0;
/* DEBUG: emitSwitch start */
    {
        struct z_value_Value switch_tmp = *z_builtins_a;
        switch (switch_tmp.tag) {
        case z_value_Value_Tag_Int:
            {
                /* DEBUG: capture av */
                i64 av = switch_tmp.data.Int;
{
/* DEBUG: emitSwitch start */
                {
                    struct z_value_Value switch_tmp_1 = *z_builtins_b;
                    switch (switch_tmp_1.tag) {
                    case z_value_Value_Tag_Int:
                        {
                            /* DEBUG: capture bv */
                            i64 bv = switch_tmp_1.data.Int;
{
                            z_builtins_res = av == bv;
                        }                        }
                        break;
                    default:
{
                        }                        break;
                }
                }
            }            }
            break;
        case z_value_Value_Tag_Bool:
            {
                /* DEBUG: capture av */
                int av_1 = switch_tmp.data.Bool;
{
/* DEBUG: emitSwitch start */
                {
                    struct z_value_Value switch_tmp_2 = *z_builtins_b;
                    switch (switch_tmp_2.tag) {
                    case z_value_Value_Tag_Bool:
                        {
                            /* DEBUG: capture bv */
                            int bv_1 = switch_tmp_2.data.Bool;
{
                            z_builtins_res = av_1 == bv_1;
                        }                        }
                        break;
                    default:
{
                        }                        break;
                }
                }
            }            }
            break;
        case z_value_Value_Tag_Symbol:
            {
                /* DEBUG: capture av */
                Slice_u8 av_2 = switch_tmp.data.Symbol;
{
/* DEBUG: emitSwitch start */
                {
                    struct z_value_Value switch_tmp_3 = *z_builtins_b;
                    switch (switch_tmp_3.tag) {
                    case z_value_Value_Tag_Symbol:
                        {
                            /* DEBUG: capture bv */
                            Slice_u8 bv_2 = switch_tmp_3.data.Symbol;
{
                            z_builtins_res = z_util_mem_eql(av_2, bv_2);
                        }                        }
                        break;
                    default:
{
                        }                        break;
                }
                }
            }            }
            break;
        case z_value_Value_Tag_Nil:
{
/* DEBUG: emitSwitch start */
                {
                    struct z_value_Value switch_tmp_4 = *z_builtins_b;
                    switch (switch_tmp_4.tag) {
                    case z_value_Value_Tag_Nil:
{
                            z_builtins_res = 1;
                        }                        break;
                    default:
{
                        }                        break;
                }
                }
            }            break;
        default:
{
                z_builtins_res = z_builtins_a == z_builtins_b;
            }            break;
    }
    }
    __tmp_try_res_7_8 = z_value_alloc_bool(z_builtins_res, arena);
    if (__tmp_try_res_7_8.is_error) {
        return __tmp_try_res_7_8;
    }
    __tmp_try_7_7 = __tmp_try_res_7_8.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_7;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_is_nil(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    int z_builtins_res;
    struct z_value_Value* __tmp_try_7_5;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_6;
    if (args.len != 1) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    z_builtins_res = 0;
/* DEBUG: emitSwitch start */
    {
        struct z_value_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case z_value_Value_Tag_Nil:
{
                z_builtins_res = 1;
            }            break;
        case z_value_Value_Tag_Symbol:
            {
                /* DEBUG: capture s */
                Slice_u8 s = switch_tmp.data.Symbol;
{
                z_builtins_res = z_util_mem_eql(s, __make_slice_u8("nil", 3));
            }            }
            break;
        default:
{
            }            break;
    }
    }
    __tmp_try_res_7_6 = z_value_alloc_bool(z_builtins_res, arena);
    if (__tmp_try_res_7_6.is_error) {
        return __tmp_try_res_7_6;
    }
    __tmp_try_7_5 = __tmp_try_res_7_6.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_5;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_lt(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
/* DEBUG: emitSwitch start */
    {
        struct z_value_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case z_value_Value_Tag_Int:
            {
                /* DEBUG: capture av */
                i64 av = switch_tmp.data.Int;
{
/* DEBUG: emitSwitch start */
                {
                    struct z_value_Value switch_tmp_1 = *args.ptr[1];
                    switch (switch_tmp_1.tag) {
                    case z_value_Value_Tag_Int:
                        {
                            /* DEBUG: capture bv */
                            i64 bv = switch_tmp_1.data.Int;
{
                            struct z_value_Value* __tmp_try_11_3;
                            ErrorUnion_Ptr_z_value_Value __tmp_try_res_11_4;
                            __tmp_try_res_11_4 = z_value_alloc_bool(av < bv, arena);
                            if (__tmp_try_res_11_4.is_error) {
                                return __tmp_try_res_11_4;
                            }
                            __tmp_try_11_3 = __tmp_try_res_11_4.data.payload;
                            {
                                ErrorUnion_Ptr_z_value_Value __return_val;
                                __return_val.is_error = 0;
                                __return_val.data.payload = __tmp_try_11_3;
                                return __return_val;
                            }
                        }                        }
                        break;
                    default:
{
                        }                        break;
                }
                }
            }            }
            break;
        default:
{
            }            break;
    }
    }
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_NotAnInt;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_gt(Slice_Ptr_z_value_Value args, struct z_sand_Sand* arena) {
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
/* DEBUG: emitSwitch start */
    {
        struct z_value_Value switch_tmp = *args.ptr[0];
        switch (switch_tmp.tag) {
        case z_value_Value_Tag_Int:
            {
                /* DEBUG: capture av */
                i64 av = switch_tmp.data.Int;
{
/* DEBUG: emitSwitch start */
                {
                    struct z_value_Value switch_tmp_1 = *args.ptr[1];
                    switch (switch_tmp_1.tag) {
                    case z_value_Value_Tag_Int:
                        {
                            /* DEBUG: capture bv */
                            i64 bv = switch_tmp_1.data.Int;
{
                            struct z_value_Value* __tmp_try_11_1;
                            ErrorUnion_Ptr_z_value_Value __tmp_try_res_11_2;
                            __tmp_try_res_11_2 = z_value_alloc_bool(av > bv, arena);
                            if (__tmp_try_res_11_2.is_error) {
                                return __tmp_try_res_11_2;
                            }
                            __tmp_try_11_1 = __tmp_try_res_11_2.data.payload;
                            {
                                ErrorUnion_Ptr_z_value_Value __return_val;
                                __return_val.is_error = 0;
                                __return_val.data.payload = __tmp_try_11_1;
                                return __return_val;
                            }
                        }                        }
                        break;
                    default:
{
                        }                        break;
                }
                }
            }            }
            break;
        default:
{
            }            break;
    }
    }
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_NotAnInt;
        return __return_val;
    }
}
