#!/bin/sh
set -e
# Build script generated by Z98 bootstrap compiler

gcc -std=c89 -m32 -pedantic -Wall -O2 -Isrc/include -I. -c zig_runtime.c -o zig_runtime.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -Isrc/include -I. -c builtin.c -o builtin.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -Isrc/include -I. -c std_debug.c -o std_debug.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -Isrc/include -I. -c std.c -o std.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -Isrc/include -I. -c greetings.c -o greetings.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -Isrc/include -I. -c main.c -o main.o
gcc -m32 -o app zig_runtime.o builtin.o std_debug.o std.o greetings.o main.o
