#!/bin/sh
set -e
# Build script generated by Z98 bootstrap compiler

gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c zig_runtime.c -o zig_runtime.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c builtin.c -o builtin.o
gcc -std=c89 -m32 -pedantic -Wall -O2 -I. -c nested_defer.c -o nested_defer.o
gcc -m32 -o app zig_runtime.o builtin.o nested_defer.o
