/* Generated by Z98 bootstrap compiler */
#include "zig_runtime.h"

#include "issue_temporary_scope.h"


void foo(int);
static void z_issue_temporary_scope_do_test(int);

extern void foo(int x);

static void z_issue_temporary_scope_do_test(int cond) {
    int __tmp_if_5_1;
    int z_issue_temporary_scope_y;
    if (cond) {
        __tmp_if_5_1 = 42;
    } else {
        __tmp_if_5_1 = 24;
    }
    z_issue_temporary_scope_y = __tmp_if_5_1;
    foo(z_issue_temporary_scope_y);
}

int main(int argc, char* argv[]) {
    z_issue_temporary_scope_do_test(1);
    return 0;
}
