/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

#include "wcl_test.h"


static void z_wcl_test_test_while_continue(void);
static void z_wcl_test_test_labeled_while_c(void);

void __bootstrap_print(unsigned char const* s);

void __bootstrap_print_int(int i);

static void z_wcl_test_test_while_continue(void) {
    int z_wcl_test_i;
    int z_wcl_test_count;
    z_wcl_test_i = 0;
    z_wcl_test_count = 0;
    __loop_0_start: ;
    if (!(z_wcl_test_i < 10)) goto __loop_0_end;
    {
        if (z_wcl_test_i == 5) {
            __bootstrap_print("continuing at 5\n");
            /* defers for continue */
            goto __loop_0_continue;
        }
        z_wcl_test_count += 1;
    }
    __loop_0_continue: ;
    (void)(z_wcl_test_i += 1);
    goto __loop_0_start;
    __loop_0_end: ;
    __bootstrap_print("Final count (should be 9): ");
    __bootstrap_print_int(z_wcl_test_count);
    __bootstrap_print("\n");
    __bootstrap_print("Final i (should be 10): ");
    __bootstrap_print_int(z_wcl_test_i);
    __bootstrap_print("\n");
}

static void z_wcl_test_test_labeled_while_c(void) {
    int z_wcl_test_i;
    int z_wcl_test_count;
    z_wcl_test_i = 0;
    z_wcl_test_count = 0;
    __loop_0_start: ;
    if (!(z_wcl_test_i < 10)) goto __loop_0_end;
    {
        if (z_wcl_test_i == 3) {
            __bootstrap_print("labeled continue at 3\n");
            /* defers for continue */
            goto __loop_0_continue;
        }
        if (z_wcl_test_i == 7) {
            __bootstrap_print("unlabeled continue in labeled loop at 7\n");
            /* defers for continue */
            goto __loop_0_continue;
        }
        z_wcl_test_count += 1;
    }
    __loop_0_continue: ;
    (void)(z_wcl_test_i += 1);
    goto __loop_0_start;
    __loop_0_end: ;
    __bootstrap_print("Final count (should be 8): ");
    __bootstrap_print_int(z_wcl_test_count);
    __bootstrap_print("\n");
}

int main(int argc, char* argv[]) {
    z_wcl_test_test_while_continue();
    z_wcl_test_test_labeled_while_c();
    return 0;
}
