/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OpenFailed 1
#define ERROR_ReadFailed 2
#define ERROR_SeekFailed 3
#define ERROR_TooLarge 4
#define ERROR_InvalidSyntax 5
#define ERROR_ExpectedValue 6

#include "file.h"


#ifndef ZIG_OPTIONAL_Optional_Ptr_void
#define ZIG_OPTIONAL_Optional_Ptr_void
typedef struct {
    void * value;
    int has_value;
} Optional_Ptr_void;
#endif

static int z_file_SEEK_END = 2;
static int z_file_SEEK_SET = 0;
extern Optional_Ptr_void fopen(char const* filename, char const* mode);

extern usize fread(unsigned char* buffer, usize size, usize count, void * file);

extern int fclose(void * file);

extern int fseek(void * file, i64 offset, int whence);

extern i64 ftell(void * file);

extern int ferror(void * file);

extern int feof(void * file);

extern void * arena_alloc(void * arena, usize size);

ErrorUnion_Slice_u8 z_file_readFile(void * arena, Slice_u8 path) {
    void * z_file_f;
    i64 z_file_size;
    usize z_file_usize_size;
    void * z_file_buffer_void;
    unsigned char* z_file_buffer;
    usize z_file_bytes_read;
    {
        Optional_Ptr_void __orelse_res = fopen((char const*)path.ptr, "rb");
        if (__orelse_res.has_value) {
            z_file_f = __orelse_res.value;
        } else {
            {
                ErrorUnion_Slice_u8 __return_val;
                __return_val.data.err = ERROR_OpenFailed;
                __return_val.is_error = 1;
                return __return_val;
            }
        }
    }
    if (fseek(z_file_f, 0, z_file_SEEK_END) != 0) {
        {
            ErrorUnion_Slice_u8 __return_val;
            __return_val.data.err = ERROR_SeekFailed;
            __return_val.is_error = 1;
            {
                (void)(fclose(z_file_f));
            }
            return __return_val;
        }
    }
    z_file_size = ftell(z_file_f);
    if (z_file_size < 0) {
        {
            ErrorUnion_Slice_u8 __return_val;
            __return_val.data.err = ERROR_SeekFailed;
            __return_val.is_error = 1;
            {
                (void)(fclose(z_file_f));
            }
            return __return_val;
        }
    }
    if (fseek(z_file_f, 0, z_file_SEEK_SET) != 0) {
        {
            ErrorUnion_Slice_u8 __return_val;
            __return_val.data.err = ERROR_SeekFailed;
            __return_val.is_error = 1;
            {
                (void)(fclose(z_file_f));
            }
            return __return_val;
        }
    }
    z_file_usize_size = __bootstrap_usize_from_i64(z_file_size);
    z_file_buffer_void = arena_alloc(arena, z_file_usize_size);
    z_file_buffer = (unsigned char*)z_file_buffer_void;
    z_file_bytes_read = fread(z_file_buffer, 1, z_file_usize_size, z_file_f);
    if (z_file_bytes_read != z_file_usize_size) {
        {
            ErrorUnion_Slice_u8 __return_val;
            __return_val.data.err = ERROR_ReadFailed;
            __return_val.is_error = 1;
            {
                (void)(fclose(z_file_f));
            }
            return __return_val;
        }
    }
    {
        ErrorUnion_Slice_u8 __return_val;
        __return_val.data.payload = __make_slice_u8(z_file_buffer + 0, z_file_usize_size - 0);
        __return_val.is_error = 0;
        {
            (void)(fclose(z_file_f));
        }
        return __return_val;
    }
}
