/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Master Single Translation Unit (STU) file */

#include "main_module.c"
#include "greetings.c"
#include "std.c"
#include "std_debug.c"
