/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

#include "std_debug.h"

extern void z_std_debug___bootstrap_print(unsigned char* s);

extern void z_std_debug___bootstrap_print_i(int n);

void z_std_debug_print(unsigned char* msg) {
    __bootstrap_print(msg);
}

void z_std_debug_printInt(int n) {
    __bootstrap_print_int(n);
}
