/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

#include "main.h"
#include "std.h"

static void swap(int (* arr)[10], unsigned int i, unsigned int j) {
    int temp;
    temp = (*arr)[i];
    (*arr)[i] = (*arr)[j];
    (*arr)[j] = temp;
}

static void heapify(int (* arr)[10], unsigned int n, unsigned int i) {
    unsigned int largest;
    unsigned int l;
    unsigned int r;
    largest = i;
    l = 2 * i + 1;
    r = 2 * i + 2;
    if (l < n && (*arr)[l] > (*arr)[largest]) {
        largest = l;
    }
    if (r < n && (*arr)[r] > (*arr)[largest]) {
        largest = r;
    }
    if (largest != i) {
        swap(arr, i, largest);
        heapify(arr, n, largest);
    }
}

static void heapSort(int (* arr)[10]) {
    int n;
    int i;
    int j;
    n = 10;
    i = (int)n / 2 - 1;
    while (i >= 0) {
        heapify(arr, n, __bootstrap_usize_from_i32(i));
        i -= 1;
    }
    j = (int)n - 1;
    while (j > 0) {
        swap(arr, 0, __bootstrap_usize_from_i32(j));
        heapify(arr, __bootstrap_usize_from_i32(j), 0);
        j -= 1;
    }
}

int main(int argc, char* argv[]) {
    int arr[10];
    unsigned int k;
    arr[0] = 12;
    arr[1] = 11;
    arr[2] = 13;
    arr[3] = 5;
    arr[4] = 6;
    arr[5] = 7;
    arr[6] = 20;
    arr[7] = 1;
    arr[8] = 15;
    arr[9] = 3;
    heapSort(&arr);
    k = 0;
    while (k < 10) {
        z_std_debug_printInt(arr[k]);
        k += 1;
    }
}
