#!/bin/bash
set -e
# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ZIG0="$SCRIPT_DIR/../../zig0"
cd "$SCRIPT_DIR"

echo "Compiling LZW demo..."
# The compiler generates output in the same directory by default if given a directory path
$ZIG0 main.zig -o ./

# build_target.sh is generated by zig0
chmod +x build_target.sh
./build_target.sh

echo ""
echo "LZW Demo Build Successful."
echo "You can now run it with: ./app"
