@echo off
:: Build script generated by Z98 bootstrap compiler
:: Optimized for MSVC 6.0 on Windows 98

cl.exe /nologo /W3 /I. /c zig_runtime.c
cl.exe /nologo /W3 /I. /c builtin.c
cl.exe /nologo /W3 /I. /c tagged_union_layout.c
link.exe /nologo /out:app.exe *.obj
