/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

#include "greetings.h"
#include "std.h"


void zF_44e31f_sayHello(void) {
    __bootstrap_print("Hello, world!\n");
}
