/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OutOfMemory 1
#define ERROR_InvalidDigit 2
#define ERROR_WrongArity 3
#define ERROR_NotACons 4
#define ERROR_NotAnInt 5
#define ERROR_DivisionByZero 6
#define ERROR_UnboundSymbol 7
#define ERROR_InvalidQuote 8
#define ERROR_InvalidIf 9
#define ERROR_InvalidDefine 10
#define ERROR_InvalidLambda 11
#define ERROR_InvalidExpr 12
#define ERROR_TooManyArgs 13
#define ERROR_InvalidParams 14
#define ERROR_TooFewArgs 15
#define ERROR_NotCallable 16
#define ERROR_UnexpectedEof 17
#define ERROR_UnexpectedRParen 18
#define ERROR_UnexpectedToken 19
#define ERROR_ExpectedRParen 20

#include "builtins.h"
#include "value.h"
#include "util.h"


ErrorUnion_Ptr_z_value_Value z_builtins_builtin_cons(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    struct z_value_Value* __tmp_try_7_19;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_20;
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    __tmp_try_res_7_20 = z_value_alloc_cons(args.ptr[0], args.ptr[1], arena);
    if (__tmp_try_res_7_20.is_error) {
        return __tmp_try_res_7_20;
    }
    __tmp_try_7_19 = __tmp_try_res_7_20.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_19;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_car(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    if (args.len != 1) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    if (args.ptr[0]->tag == z_value_ValueTag_Cons) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 0;
            __return_val.data.payload = args.ptr[0]->data.Cons.car;
            return __return_val;
        }
    }
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_NotACons;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_cdr(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    if (args.len != 1) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    if (args.ptr[0]->tag == z_value_ValueTag_Cons) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 0;
            __return_val.data.payload = args.ptr[0]->data.Cons.cdr;
            return __return_val;
        }
    }
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_NotACons;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_add(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    i64 z_builtins_sum;
    struct z_value_Value* __tmp_try_7_17;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_18;
    z_builtins_sum = 0;
    {
        Slice_Ptr_z_value_Value __for_iter_1 = args;
        size_t __for_idx_1 = 0;
        size_t __for_len_1 = __for_iter_1.len;
        __loop_0_start: ;
        while (__for_idx_1 < __for_len_1) {
            struct z_value_Value* arg = __for_iter_1.ptr[__for_idx_1];
{
                if (arg->tag == z_value_ValueTag_Int) {
                    z_builtins_sum += arg->data.Int;
                } else {
                    {
                        ErrorUnion_Ptr_z_value_Value __return_val;
                        __return_val.is_error = 1;
                        __return_val.data.err = ERROR_NotAnInt;
                        return __return_val;
                    }
                }
            }
            __loop_0_continue: ;
            __for_idx_1++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    __tmp_try_res_7_18 = z_value_alloc_int(z_builtins_sum, arena);
    if (__tmp_try_res_7_18.is_error) {
        return __tmp_try_res_7_18;
    }
    __tmp_try_7_17 = __tmp_try_res_7_18.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_17;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_sub(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    i64 z_builtins_res;
    usize z_builtins_i;
    struct z_value_Value* __tmp_try_7_13;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_14;
    if (args.len == 0) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    z_builtins_res = 0;
    if (args.ptr[0]->tag == z_value_ValueTag_Int) {
        z_builtins_res = args.ptr[0]->data.Int;
    } else {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_NotAnInt;
            return __return_val;
        }
    }
    if (args.len == 1) {
        struct z_value_Value* __tmp_try_9_15;
        ErrorUnion_Ptr_z_value_Value __tmp_try_res_9_16;
        __tmp_try_res_9_16 = z_value_alloc_int(-z_builtins_res, arena);
        if (__tmp_try_res_9_16.is_error) {
            return __tmp_try_res_9_16;
        }
        __tmp_try_9_15 = __tmp_try_res_9_16.data.payload;
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 0;
            __return_val.data.payload = __tmp_try_9_15;
            return __return_val;
        }
    }
    z_builtins_i = 1;
    __loop_0_start: ;
    if (!(z_builtins_i < args.len)) goto __loop_0_end;
    {
        if (args.ptr[z_builtins_i]->tag == z_value_ValueTag_Int) {
            z_builtins_res -= args.ptr[z_builtins_i]->data.Int;
        } else {
            {
                ErrorUnion_Ptr_z_value_Value __return_val;
                __return_val.is_error = 1;
                __return_val.data.err = ERROR_NotAnInt;
                return __return_val;
            }
        }
        z_builtins_i += 1;
    }
    __loop_0_continue: ;
    goto __loop_0_start;
    __loop_0_end: ;
    __tmp_try_res_7_14 = z_value_alloc_int(z_builtins_res, arena);
    if (__tmp_try_res_7_14.is_error) {
        return __tmp_try_res_7_14;
    }
    __tmp_try_7_13 = __tmp_try_res_7_14.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_13;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_mul(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    i64 z_builtins_res;
    struct z_value_Value* __tmp_try_7_11;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_12;
    z_builtins_res = 1;
    {
        Slice_Ptr_z_value_Value __for_iter_1 = args;
        size_t __for_idx_1 = 0;
        size_t __for_len_1 = __for_iter_1.len;
        __loop_0_start: ;
        while (__for_idx_1 < __for_len_1) {
            struct z_value_Value* arg = __for_iter_1.ptr[__for_idx_1];
{
                if (arg->tag == z_value_ValueTag_Int) {
                    z_builtins_res *= arg->data.Int;
                } else {
                    {
                        ErrorUnion_Ptr_z_value_Value __return_val;
                        __return_val.is_error = 1;
                        __return_val.data.err = ERROR_NotAnInt;
                        return __return_val;
                    }
                }
            }
            __loop_0_continue: ;
            __for_idx_1++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    __tmp_try_res_7_12 = z_value_alloc_int(z_builtins_res, arena);
    if (__tmp_try_res_7_12.is_error) {
        return __tmp_try_res_7_12;
    }
    __tmp_try_7_11 = __tmp_try_res_7_12.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_11;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_div(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    i64 z_builtins_res;
    usize z_builtins_i;
    struct z_value_Value* __tmp_try_7_9;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_10;
    if (args.len == 0) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    z_builtins_res = 0;
    if (args.ptr[0]->tag == z_value_ValueTag_Int) {
        z_builtins_res = args.ptr[0]->data.Int;
    } else {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_NotAnInt;
            return __return_val;
        }
    }
    z_builtins_i = 1;
    __loop_0_start: ;
    if (!(z_builtins_i < args.len)) goto __loop_0_end;
    {
        if (args.ptr[z_builtins_i]->tag == z_value_ValueTag_Int) {
            i64 z_builtins_v;
            z_builtins_v = args.ptr[z_builtins_i]->data.Int;
            if (z_builtins_v == 0) {
                {
                    ErrorUnion_Ptr_z_value_Value __return_val;
                    __return_val.is_error = 1;
                    __return_val.data.err = ERROR_DivisionByZero;
                    return __return_val;
                }
            }
            z_builtins_res /= z_builtins_v;
        } else {
            {
                ErrorUnion_Ptr_z_value_Value __return_val;
                __return_val.is_error = 1;
                __return_val.data.err = ERROR_NotAnInt;
                return __return_val;
            }
        }
        z_builtins_i += 1;
    }
    __loop_0_continue: ;
    goto __loop_0_start;
    __loop_0_end: ;
    __tmp_try_res_7_10 = z_value_alloc_int(z_builtins_res, arena);
    if (__tmp_try_res_7_10.is_error) {
        return __tmp_try_res_7_10;
    }
    __tmp_try_7_9 = __tmp_try_res_7_10.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_9;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_eq(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    struct z_value_Value* z_builtins_a;
    struct z_value_Value* z_builtins_b;
    int z_builtins_res;
    struct z_value_Value* __tmp_try_7_7;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_8;
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    z_builtins_a = args.ptr[0];
    z_builtins_b = args.ptr[1];
    z_builtins_res = 0;
    if (z_builtins_a->tag == z_value_ValueTag_Int) {
        if (z_builtins_b->tag == z_value_ValueTag_Int) {
            z_builtins_res = z_builtins_a->data.Int == z_builtins_b->data.Int;
        }
    } else     if (z_builtins_a->tag == z_value_ValueTag_Bool) {
        if (z_builtins_b->tag == z_value_ValueTag_Bool) {
            z_builtins_res = z_builtins_a->data.Bool == z_builtins_b->data.Bool;
        }
    } else     if (z_builtins_a->tag == z_value_ValueTag_Symbol) {
        if (z_builtins_b->tag == z_value_ValueTag_Symbol) {
            z_builtins_res = z_util_mem_eql(z_builtins_a->data.Symbol, z_builtins_b->data.Symbol);
        }
    } else     if (z_builtins_a->tag == z_value_ValueTag_Nil) {
        if (z_builtins_b->tag == z_value_ValueTag_Nil) {
            z_builtins_res = 1;
        }
    } else {
        z_builtins_res = z_builtins_a == z_builtins_b;
    }



    __tmp_try_res_7_8 = z_value_alloc_bool(z_builtins_res, arena);
    if (__tmp_try_res_7_8.is_error) {
        return __tmp_try_res_7_8;
    }
    __tmp_try_7_7 = __tmp_try_res_7_8.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_7;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_is_nil(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    int z_builtins_res;
    struct z_value_Value* __tmp_try_7_5;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_6;
    if (args.len != 1) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    z_builtins_res = 0;
    if (args.ptr[0]->tag == z_value_ValueTag_Nil) {
        z_builtins_res = 1;
    } else     if (args.ptr[0]->tag == z_value_ValueTag_Symbol) {
        z_builtins_res = z_util_mem_eql(args.ptr[0]->data.Symbol, __make_slice_u8("nil", 3));
    }

    __tmp_try_res_7_6 = z_value_alloc_bool(z_builtins_res, arena);
    if (__tmp_try_res_7_6.is_error) {
        return __tmp_try_res_7_6;
    }
    __tmp_try_7_5 = __tmp_try_res_7_6.data.payload;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = __tmp_try_7_5;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_lt(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    if (args.ptr[0]->tag == z_value_ValueTag_Int && args.ptr[1]->tag == z_value_ValueTag_Int) {
        struct z_value_Value* __tmp_try_9_3;
        ErrorUnion_Ptr_z_value_Value __tmp_try_res_9_4;
        __tmp_try_res_9_4 = z_value_alloc_bool(args.ptr[0]->data.Int < args.ptr[1]->data.Int, arena);
        if (__tmp_try_res_9_4.is_error) {
            return __tmp_try_res_9_4;
        }
        __tmp_try_9_3 = __tmp_try_res_9_4.data.payload;
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 0;
            __return_val.data.payload = __tmp_try_9_3;
            return __return_val;
        }
    }
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_NotAnInt;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_value_Value z_builtins_builtin_gt(Slice_Ptr_z_value_Value args, struct z_sand_LispSand* arena) {
    if (args.len != 2) {
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 1;
            __return_val.data.err = ERROR_WrongArity;
            return __return_val;
        }
    }
    if (args.ptr[0]->tag == z_value_ValueTag_Int && args.ptr[1]->tag == z_value_ValueTag_Int) {
        struct z_value_Value* __tmp_try_9_1;
        ErrorUnion_Ptr_z_value_Value __tmp_try_res_9_2;
        __tmp_try_res_9_2 = z_value_alloc_bool(args.ptr[0]->data.Int > args.ptr[1]->data.Int, arena);
        if (__tmp_try_res_9_2.is_error) {
            return __tmp_try_res_9_2;
        }
        __tmp_try_9_1 = __tmp_try_res_9_2.data.payload;
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 0;
            __return_val.data.payload = __tmp_try_9_1;
            return __return_val;
        }
    }
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_NotAnInt;
        return __return_val;
    }
}
