@echo off
:: Build script generated by RetroZig bootstrap compiler
:: Optimized for MSVC 6.0 on Windows 98

cl.exe /nologo /W3 /I. /c zig_runtime.c
cl.exe /nologo /W3 /I. /c builtin.c
cl.exe /nologo /W3 /I. /c sand.c
cl.exe /nologo /W3 /I. /c value.c
cl.exe /nologo /W3 /I. /c util.c
cl.exe /nologo /W3 /I. /c builtins.c
cl.exe /nologo /W3 /I. /c env.c
cl.exe /nologo /W3 /I. /c token.c
cl.exe /nologo /W3 /I. /c eval.c
cl.exe /nologo /W3 /I. /c parser.c
cl.exe /nologo /W3 /I. /c main.c
link.exe /nologo /out:app.exe *.obj
