/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OutOfMemory 1
#define ERROR_InvalidDigit 2
#define ERROR_WrongArity 3
#define ERROR_NotACons 4
#define ERROR_NotAnInt 5
#define ERROR_DivisionByZero 6
#define ERROR_UnboundSymbol 7
#define ERROR_InvalidQuote 8
#define ERROR_InvalidIf 9
#define ERROR_InvalidDefine 10
#define ERROR_InvalidLambda 11
#define ERROR_InvalidExpr 12
#define ERROR_TooManyArgs 13
#define ERROR_InvalidParams 14
#define ERROR_TooFewArgs 15
#define ERROR_NotCallable 16
#define ERROR_UnexpectedEof 17
#define ERROR_UnexpectedRParen 18
#define ERROR_UnexpectedToken 19
#define ERROR_ExpectedRParen 20

#include "env.h"
#include "value.h"
#include "util.h"
#include "sand.h"


ErrorUnion_Ptr_z_value_Value z_env_env_lookup(Slice_u8 name, Optional_Ptr_z_env_EnvNode env) {
    Optional_Ptr_z_env_EnvNode z_env_cur;
    z_env_cur = env;
    __loop_0_start: ;
    while (1) {
        Optional_Ptr_z_env_EnvNode opt_tmp = z_env_cur;
        if (!opt_tmp.has_value) goto __loop_0_end;
        struct z_env_EnvNode* node = opt_tmp.value;
{
            if (z_util_mem_eql(node->symbol, name)) {
                {
                    ErrorUnion_Ptr_z_value_Value __return_val;
                    __return_val.is_error = 0;
                    __return_val.data.payload = node->value;
                    return __return_val;
                }
            }
            z_env_cur = node->next;
        }
        __loop_0_continue: ;
        goto __loop_0_start;
    }
    __loop_0_end: ;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 1;
        __return_val.data.err = ERROR_UnboundSymbol;
        return __return_val;
    }
}

ErrorUnion_Ptr_z_env_EnvNode z_env_env_extend(Slice_u8 name, struct z_value_Value* val, Optional_Ptr_z_env_EnvNode env, struct z_sand_LispSand* sand) {
    unsigned char* __tmp_try_5_1;
    ErrorUnion_Ptr_u8 __tmp_try_res_5_2;
    unsigned char* z_env_node_mem;
    struct z_env_EnvNode* z_env_node;
    __tmp_try_res_5_2 = z_sand_lisp_sand_alloc(sand, 20, 4);
    if (__tmp_try_res_5_2.is_error) {
        {
            ErrorUnion_Ptr_z_env_EnvNode __return_val;
            __return_val.data.err = __tmp_try_res_5_2.data.err;
            __return_val.is_error = 1;
            return __return_val;
        }
    }
    __tmp_try_5_1 = __tmp_try_res_5_2.data.payload;
    z_env_node_mem = __tmp_try_5_1;
    z_env_node = (struct z_env_EnvNode*)z_env_node_mem;
    z_env_node->symbol = name;
    z_env_node->value = val;
    z_env_node->next = env;
    {
        ErrorUnion_Ptr_z_env_EnvNode __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = z_env_node;
        return __return_val;
    }
}
