/* Generated by RetroZig bootstrap compiler */
#include "zig_runtime.h"

/* Error tags */
#define ERROR_OutOfMemory 1
#define ERROR_InvalidDigit 2
#define ERROR_WrongArity 3
#define ERROR_NotACons 4
#define ERROR_NotAnInt 5
#define ERROR_DivisionByZero 6
#define ERROR_UnboundSymbol 7
#define ERROR_InvalidQuote 8
#define ERROR_InvalidIf 9
#define ERROR_InvalidDefine 10
#define ERROR_InvalidLambda 11
#define ERROR_InvalidExpr 12
#define ERROR_TooManyArgs 13
#define ERROR_InvalidParams 14
#define ERROR_TooFewArgs 15
#define ERROR_NotCallable 16
#define ERROR_UnexpectedEof 17
#define ERROR_UnexpectedRParen 18
#define ERROR_UnexpectedToken 19
#define ERROR_ExpectedRParen 20

#include "util.h"
#include "value.h"


int z_util_mem_eql(Slice_u8 a, Slice_u8 b) {
    usize z_util_i;
    if (a.len != b.len) {
        return 0;
    }
    z_util_i = 0;
    __loop_0_start: ;
    if (!(z_util_i < a.len)) goto __loop_0_end;
    {
        if (a.ptr[z_util_i] != b.ptr[z_util_i]) {
            return 0;
        }
        z_util_i += 1;
    }
    __loop_0_continue: ;
    goto __loop_0_start;
    __loop_0_end: ;
    return 1;
}

ErrorUnion_i64 z_util_parse_int(Slice_u8 s) {
    i64 z_util_val;
    usize z_util_i;
    int z_util_negative;
    ErrorUnion_i64 __tmp_if_5_9;
    z_util_val = 0;
    z_util_i = 0;
    z_util_negative = 0;
    if (s.len > 0 && s.ptr[0] == '-') {
        z_util_negative = 1;
        z_util_i += 1;
    }
    __loop_0_start: ;
    if (!(z_util_i < s.len)) goto __loop_0_end;
    {
        unsigned char z_util_c;
        z_util_c = s.ptr[z_util_i];
        if (z_util_c < '0' || z_util_c > '9') {
            {
                ErrorUnion_i64 __return_val;
                __return_val.is_error = 1;
                __return_val.data.err = ERROR_InvalidDigit;
                return __return_val;
            }
        }
        z_util_val = z_util_val * 10 + (i64)z_util_c - '0';
        z_util_i += 1;
    }
    __loop_0_continue: ;
    goto __loop_0_start;
    __loop_0_end: ;
    if (z_util_negative) {
        __tmp_if_5_9.is_error = 0;
        __tmp_if_5_9.data.payload = -z_util_val;
    } else {
        __tmp_if_5_9.is_error = 0;
        __tmp_if_5_9.data.payload = z_util_val;
    }
    return __tmp_if_5_9;
}

ErrorUnion_Ptr_z_value_Value z_util_deep_copy(struct z_value_Value* v, struct z_sand_LispSand* perm_sand) {
    struct z_value_Value* __tmp_try_5_1;
    ErrorUnion_Ptr_z_value_Value __tmp_try_res_5_2;
    struct z_value_Value* z_util_new_v;
    if (v->tag == z_value_ValueTag_Cons) {
        struct z_value_Value* __tmp_try_7_7;
        ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_8;
        struct z_value_Value* z_util_new_car;
        struct z_value_Value* __tmp_try_7_5;
        ErrorUnion_Ptr_z_value_Value __tmp_try_res_7_6;
        struct z_value_Value* z_util_new_cdr;
        struct z_value_Value* __tmp_try_9_3;
        ErrorUnion_Ptr_z_value_Value __tmp_try_res_9_4;
        __tmp_try_res_7_8 = z_util_deep_copy(v->data.Cons.car, perm_sand);
        if (__tmp_try_res_7_8.is_error) {
            return __tmp_try_res_7_8;
        }
        __tmp_try_7_7 = __tmp_try_res_7_8.data.payload;
        z_util_new_car = __tmp_try_7_7;
        __tmp_try_res_7_6 = z_util_deep_copy(v->data.Cons.cdr, perm_sand);
        if (__tmp_try_res_7_6.is_error) {
            return __tmp_try_res_7_6;
        }
        __tmp_try_7_5 = __tmp_try_res_7_6.data.payload;
        z_util_new_cdr = __tmp_try_7_5;
        __tmp_try_res_9_4 = z_value_alloc_cons(z_util_new_car, z_util_new_cdr, perm_sand);
        if (__tmp_try_res_9_4.is_error) {
            return __tmp_try_res_9_4;
        }
        __tmp_try_9_3 = __tmp_try_res_9_4.data.payload;
        {
            ErrorUnion_Ptr_z_value_Value __return_val;
            __return_val.is_error = 0;
            __return_val.data.payload = __tmp_try_9_3;
            return __return_val;
        }
    }
    __tmp_try_res_5_2 = z_value_alloc_value(perm_sand);
    if (__tmp_try_res_5_2.is_error) {
        return __tmp_try_res_5_2;
    }
    __tmp_try_5_1 = __tmp_try_res_5_2.data.payload;
    z_util_new_v = __tmp_try_5_1;
    z_util_new_v->tag = v->tag;
    z_util_new_v->data = v->data;
    {
        ErrorUnion_Ptr_z_value_Value __return_val;
        __return_val.is_error = 0;
        __return_val.data.payload = z_util_new_v;
        return __return_val;
    }
}
