const std = @import("std");
const m01 = @import("m01.zig");
const m02 = @import("m02.zig");
const m03 = @import("m03.zig");
const m04 = @import("m04.zig");
const m05 = @import("m05.zig");
const m06 = @import("m06.zig");
const m07 = @import("m07.zig");
const m08 = @import("m08.zig");
const m09 = @import("m09.zig");
const m10 = @import("m10.zig");
const m11 = @import("m11.zig");
const m12 = @import("m12.zig");
const m13 = @import("m13.zig");
const m14 = @import("m14.zig");
const m15 = @import("m15.zig");
const m16 = @import("m16.zig");
const m17 = @import("m17.zig");
const m18 = @import("m18.zig");
const m19 = @import("m19.zig");
const m20 = @import("m20.zig");
const m21 = @import("m21.zig");
const m22 = @import("m22.zig");
const m23 = @import("m23.zig");
const m24 = @import("m24.zig");
const m25 = @import("m25.zig");
const m26 = @import("m26.zig");
const m27 = @import("m27.zig");
const m28 = @import("m28.zig");
const m29 = @import("m29.zig");
const m30 = @import("m30.zig");
const m31 = @import("m31.zig");
const m32 = @import("m32.zig");
const m33 = @import("m33.zig");
const m34 = @import("m34.zig");
const m35 = @import("m35.zig");
const m36 = @import("m36.zig");
const m37 = @import("m37.zig");
const m38 = @import("m38.zig");
pub fn main() void {
    var a = m01.makeSand();
    var b = m02.makeIntern();
    var c = m03.makeSource();
    var d = m04.makeDiag();
    var e = m38.make();
    var f = m38.make2();
    var s: u32 = 0;
    s += a.v;
    std.io.writeByte(@intCast(u8, ' '));
    std.io.printInt(a.v);
    s += b.v;
    std.io.writeByte(@intCast(u8, ' '));
    std.io.printInt(b.v);
    s += c.v;
    std.io.writeByte(@intCast(u8, ' '));
    std.io.printInt(c.v);
    s += d.v;
    std.io.writeByte(@intCast(u8, ' '));
    std.io.printInt(d.v);
    s += e.v;
    std.io.writeByte(@intCast(u8, ' '));
    std.io.printInt(e.v);
    s += f.v;
    std.io.writeByte(@intCast(u8, ' '));
    std.io.printInt(f.v);
    std.io.writeByte(@intCast(u8, ' '));
    std.io.printInt(s);
}
