const std = @import("std");
const root_a = @import("root_a.zig");
const root_b = @import("root_b.zig");
const root_c = @import("root_c.zig");
const root_d = @import("root_d.zig");
const root_e = @import("root_e.zig");
const root_f = @import("root_f.zig");
pub fn main() void {
    var s: u32 = 0;
    s += root_a.g1.make().v;
    std.io.printInt(root_a.g1.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_a.g2.make().v;
    std.io.printInt(root_a.g2.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_a.g3.make().v;
    std.io.printInt(root_a.g3.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_a.g4.make().v;
    std.io.printInt(root_a.g4.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_b.g1.make().v;
    std.io.printInt(root_b.g1.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_b.g2.make().v;
    std.io.printInt(root_b.g2.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_b.g3.make().v;
    std.io.printInt(root_b.g3.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_b.g4.make().v;
    std.io.printInt(root_b.g4.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_c.g1.make().v;
    std.io.printInt(root_c.g1.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_c.g2.make().v;
    std.io.printInt(root_c.g2.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_c.g3.make().v;
    std.io.printInt(root_c.g3.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_c.g4.make().v;
    std.io.printInt(root_c.g4.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_d.g1.make().v;
    std.io.printInt(root_d.g1.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_d.g2.make().v;
    std.io.printInt(root_d.g2.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_d.g3.make().v;
    std.io.printInt(root_d.g3.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_d.g4.make().v;
    std.io.printInt(root_d.g4.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_e.g1.make().v;
    std.io.printInt(root_e.g1.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_e.g2.make().v;
    std.io.printInt(root_e.g2.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_e.g3.make().v;
    std.io.printInt(root_e.g3.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_e.g4.make().v;
    std.io.printInt(root_e.g4.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_f.g1.make().v;
    std.io.printInt(root_f.g1.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_f.g2.make().v;
    std.io.printInt(root_f.g2.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_f.g3.make().v;
    std.io.printInt(root_f.g3.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    s += root_f.g4.make().v;
    std.io.printInt(root_f.g4.make().v);
    std.io.writeByte(@intCast(u8, ' '));
    std.io.printInt(s);
}
