const std = @import("std");
pub fn main() void {
    var maxv: i32 = 2147483647;
    var minv: i32 = -2147483648;
    var one: i32 = 1;
    var negone: i32 = -1;
    var a: i32 = 46341;
    var b: i32 = 46341;
    var c: i32 = -46341;
    var sh: i32 = 31;
    var sh30: i32 = 30;
    var m8: i8 = 127;
    var n8: i8 = -128;
    var o8: i8 = 1;
    var m16: i16 = 32767;
    var n16: i16 = -32768;
    var o16: i16 = 1;
    var x: i32 = 0;
    var y8: i8 = 0;
    var y16: i16 = 0;
    x = maxv +| one;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    x = minv +| negone;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    x = minv -| one;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    x = maxv -| negone;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    x = a *| b;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    x = c *| b;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    x = maxv *| one;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    x = minv *| one;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    x = one <<| sh;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    x = one <<| sh30;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    x = negone <<| sh;
    std.io.printInt(x);
    std.io.writeByte(@intCast(u8, ' '));
    y8 = m8 +| o8;
    std.io.printInt(y8);
    std.io.writeByte(@intCast(u8, ' '));
    y8 = n8 -| o8;
    std.io.printInt(y8);
    std.io.writeByte(@intCast(u8, ' '));
    y8 = m8 *| o8;
    std.io.printInt(y8);
    std.io.writeByte(@intCast(u8, ' '));
    y8 = o8 <<| 7;
    std.io.printInt(y8);
    std.io.writeByte(@intCast(u8, ' '));
    y16 = m16 +| o16;
    std.io.printInt(y16);
    std.io.writeByte(@intCast(u8, ' '));
    y16 = n16 -| o16;
    std.io.printInt(y16);
    std.io.writeByte(@intCast(u8, ' '));
    y16 = m16 *| o16;
    std.io.printInt(y16);
    std.io.writeByte(@intCast(u8, ' '));
    y16 = o16 <<| 15;
    std.io.printInt(y16);
}
