/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "diagnostics.h"
#include "allocator.h"
#include "source_manager.h"
#include "mem.h"
#include "string_interner.h"
#include "pal.h"


struct zS_26b5a9a4_43f95de6_Sand;
struct zS_2b6fc0a6_29be27be_SourceManager;
struct zS_4c1e99d4_67d40cc9_StringInterner;
struct zS_9daadfc5_bac763ac_Diagnostic;
#ifndef ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
#define ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
struct zS_26b5a9a4_43f95de6_Sand {
    unsigned char* start;
    usize pos;
    usize end;
    usize peak;
};

#endif /* ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand */

#ifndef ZIG_STRUCT_zS_2b6fc0a6_29be27be_SourceManager
#define ZIG_STRUCT_zS_2b6fc0a6_29be27be_SourceManager
struct zS_2b6fc0a6_29be27be_SourceManager {
    struct zS_2b6fc0a6_c93555ae_SourceFileArrayList* files;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_2b6fc0a6_29be27be_SourceManager */

#ifndef ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner
#define ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner
struct zS_4c1e99d4_67d40cc9_StringInterner {
    struct zS_16d7ab7a_840ccd30_U32ArrayList* buckets;
    struct zS_4c1e99d4_face28fc_InternArrayList* entries;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_4c1e99d4_67d40cc9_StringInterner */

const unsigned short zC_9daadfc5_88ccf5b7_ERR_1000_UNTERMINATED_STRING = 0;
const unsigned short zC_9daadfc5_cfecd254_1001_UNTERMINATED_BLOCK_COMMENT = 1;
const unsigned short zC_9daadfc5_eb956f85_ERR_1002_INVALID_CHAR_LITERAL = 2;
const unsigned short zC_9daadfc5_e57f8393_ERR_1003_INVALID_ESCAPE = 3;
const unsigned short zC_9daadfc5_ffecce4b_ERR_1004_BARE_AT_SIGN = 4;
const unsigned short zC_9daadfc5_d74828fa_ERR_1005_UNRECOGNIZED_CHAR = 5;
const unsigned short zC_9daadfc5_164aa48c_WARN_1010_UNRECOGNIZED_ESCAPE = 6;
const unsigned short zC_9daadfc5_247cc8b1_WARN_1011_INTEGER_OVERFLOW = 7;
const usize zC_9daadfc5_026c1e34_MAX_DIAGNOSTICS = 256;
static Slice_u8 zF_9daadfc5_ba10ec31_getLevelName(unsigned char);
static unsigned int zF_9daadfc5_ebac3b9b_formatU32(unsigned int, Slice_u8);
static void zF_9daadfc5_dff904ce_writeStr(Slice_u8);
static int zF_9daadfc5_347d1cec_compareDiag(struct zS_9daadfc5_bac763ac_Diagnostic const*, struct zS_9daadfc5_bac763ac_Diagnostic const*);
static void zF_9daadfc5_7d11c958_sortDiagnostics(Slice_zS_9daadfc5_bac763ac_Diagnostic);

static Slice_u8 zF_9daadfc5_ba10ec31_getLevelName(unsigned char level) {
/* DEBUG: emitSwitch start */
    switch (level) {
        case 0:
{
                Slice_u8 s;
                s = __make_slice_u8("error", 5);
                return s;
            }            break;
        case 1:
{
                Slice_u8 s_1;
                s_1 = __make_slice_u8("warning", 7);
                return s_1;
            }            break;
        case 2:
{
                Slice_u8 s_2;
                s_2 = __make_slice_u8("info", 4);
                return s_2;
            }            break;
        case 3:
{
                Slice_u8 s_3;
                s_3 = __make_slice_u8("note", 4);
                return s_3;
            }            break;
        default:
{
                Slice_u8 s_4;
                s_4 = __make_slice_u8("unknown", 7);
                return s_4;
            }            break;
    }
}

static unsigned int zF_9daadfc5_ebac3b9b_formatU32(unsigned int value, Slice_u8 buf) {
    unsigned int v;
    unsigned int i;
    v = value;
    i = (unsigned int)buf.len;
    if (v == 0) {
        (void)(i -= 1);
        buf.ptr[(usize)i] = '0';
    } else {
        __loop_0_start: ;
        if (!(v > 0 && i > 0)) goto __loop_0_end;
        {
            (void)(i -= 1);
            buf.ptr[(usize)i] = '0' + __bootstrap_u8_from_u32(v % 10);
            v = v / 10;
        }
        goto __loop_0_start;
        __loop_0_end: ;
    }
    return (unsigned int)buf.len - i;
}

static void zF_9daadfc5_dff904ce_writeStr(Slice_u8 s) {
    zF_6873a254_1dc3fa43_stderr_write(s);
}

static int zF_9daadfc5_347d1cec_compareDiag(struct zS_9daadfc5_bac763ac_Diagnostic const* a, struct zS_9daadfc5_bac763ac_Diagnostic const* b) {
    if (a->file_id != b->file_id) {
        return __bootstrap_i32_from_u32(a->file_id) - __bootstrap_i32_from_u32(b->file_id);
    }
    if (a->span_start != b->span_start) {
        return __bootstrap_i32_from_u32(a->span_start) - __bootstrap_i32_from_u32(b->span_start);
    }
    if (a->level != b->level) {
        return (int)a->level - (int)b->level;
    }
    return 0;
}

static void zF_9daadfc5_7d11c958_sortDiagnostics(Slice_zS_9daadfc5_bac763ac_Diagnostic diags) {
    usize i = 1;
    __loop_0_start: ;
    if (!(i < diags.len)) goto __loop_0_end;
    {
        struct zS_9daadfc5_bac763ac_Diagnostic key;
        int j;
        key = diags.ptr[i];
        j = __bootstrap_i32_from_usize(i);
        __loop_1_start: ;
        if (!(j > 0 && zF_9daadfc5_347d1cec_compareDiag(&diags.ptr[__bootstrap_usize_from_i32(j - 1)], &key) > 0)) goto __loop_1_end;
        {
            diags.ptr[__bootstrap_usize_from_i32(j)] = diags.ptr[__bootstrap_usize_from_i32(j - 1)];
            (void)(j -= 1);
        }
        goto __loop_1_start;
        __loop_1_end: ;
        diags.ptr[__bootstrap_usize_from_i32(j)] = key;
        (void)(i += 1);
    }
    goto __loop_0_start;
    __loop_0_end: ;
}

struct zS_9daadfc5_8924c34d_DiagnosticArrayList zF_9daadfc5_aa9157ce_diagnosticArrayListInit(struct zS_26b5a9a4_43f95de6_Sand* allocator) {
    {
        struct zS_9daadfc5_8924c34d_DiagnosticArrayList __return_val = {0};
        __return_val.len = 0;
        __return_val.capacity = 0;
        __return_val.allocator = allocator;
        return __return_val;
    }
}

void zF_9daadfc5_0800ad7e_agnosticArrayListEnsureCapacity(struct zS_9daadfc5_8924c34d_DiagnosticArrayList* self, usize new_capacity) {
    usize new_cap;
    unsigned char* __tmp_catch_5_5 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_6;
    unsigned char* raw;
    struct zS_9daadfc5_bac763ac_Diagnostic* new_items;
    if (new_capacity <= self->capacity) {
        return;
    }
    new_cap = new_capacity;
    if (new_cap < self->capacity * 2) {
        new_cap = self->capacity * 2;
    }
    if (new_cap < 8) {
        new_cap = 8;
    }
    __tmp_catch_res_5_6 = zF_26b5a9a4_6fa59c42_sandAlloc(self->allocator, 36 * new_cap, 4);
    if (__tmp_catch_res_5_6.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_5 = __tmp_catch_res_5_6.data.payload;
    }
    raw = __tmp_catch_5_5;
    new_items = (struct zS_9daadfc5_bac763ac_Diagnostic*)raw;
    {
        Slice_zS_9daadfc5_bac763ac_Diagnostic for_iter;
        usize for_idx;
        usize for_len;
        for_iter = __make_slice_zS_9daadfc5_bac763ac_Diagnostic(self->items + 0, self->len - 0);
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            struct zS_9daadfc5_bac763ac_Diagnostic item;
            item = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                new_items[i] = item;
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    self->items = new_items;
    self->capacity = new_cap;
}

void zF_9daadfc5_07a08eec_diagnosticArrayListAppend(struct zS_9daadfc5_8924c34d_DiagnosticArrayList* self, struct zS_9daadfc5_bac763ac_Diagnostic value) {
    zF_9daadfc5_0800ad7e_agnosticArrayListEnsureCapacity(self, self->len + 1);
    self->items[self->len] = value;
    (void)(self->len += 1);
}

Slice_zS_9daadfc5_bac763ac_Diagnostic zF_9daadfc5_3c86285a_diagnosticArrayListGetSlice(struct zS_9daadfc5_8924c34d_DiagnosticArrayList* self) {
    return __make_slice_zS_9daadfc5_bac763ac_Diagnostic(self->items + 0, self->len - 0);
}

struct zS_9daadfc5_490018d3_DiagnosticCollector zF_9daadfc5_178b11e8_diagnosticCollectorInit(struct zS_26b5a9a4_43f95de6_Sand* allocator, struct zS_2b6fc0a6_29be27be_SourceManager* source_manager, struct zS_4c1e99d4_67d40cc9_StringInterner* interner) {
    unsigned char* __tmp_catch_5_3 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_4;
    unsigned char* d_raw;
    struct zS_9daadfc5_8924c34d_DiagnosticArrayList* d_ptr;
    __tmp_catch_res_5_4 = zF_26b5a9a4_6fa59c42_sandAlloc(allocator, 16, 4);
    if (__tmp_catch_res_5_4.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_3 = __tmp_catch_res_5_4.data.payload;
    }
    d_raw = __tmp_catch_5_3;
    d_ptr = (struct zS_9daadfc5_8924c34d_DiagnosticArrayList*)d_raw;
    *d_ptr = zF_9daadfc5_aa9157ce_diagnosticArrayListInit(allocator);
    {
        struct zS_9daadfc5_490018d3_DiagnosticCollector __return_val = {0};
        __return_val.diagnostics = d_ptr;
        __return_val.allocator = allocator;
        __return_val.source_manager = source_manager;
        __return_val.interner = interner;
        __return_val.error_count = 0;
        __return_val.warning_count = 0;
        __return_val.max_diagnostics = zC_9daadfc5_026c1e34_MAX_DIAGNOSTICS;
        return __return_val;
    }
}

unsigned int zF_9daadfc5_116b4422_diagnosticCollectorIntern(struct zS_9daadfc5_490018d3_DiagnosticCollector* self, Slice_u8 msg) {
    return zF_4c1e99d4_eb67b606_stringInternerIntern(self->interner, msg);
}

void zF_9daadfc5_b5a4ed39_diagnosticCollectorAdd(struct zS_9daadfc5_490018d3_DiagnosticCollector* self, unsigned char level, unsigned short code, unsigned int file_id, unsigned int span_start, unsigned int span_end, Slice_u8 message) {
    unsigned int msg_id;
    struct zS_9daadfc5_bac763ac_Diagnostic __tmp_agg_6_1;
    if (code == 9999) {
        return;
    }
    if (self->diagnostics->len >= self->max_diagnostics) {
        Slice_u8 overflow_msg;
        unsigned int msg_id_1;
        struct zS_9daadfc5_bac763ac_Diagnostic __tmp_agg_8_2;
        overflow_msg = __make_slice_u8("too many errors, stopping", 25);
        msg_id_1 = zF_4c1e99d4_eb67b606_stringInternerIntern(self->interner, overflow_msg);
        __tmp_agg_8_2.level = 0;
        __tmp_agg_8_2.code = 9999;
        __tmp_agg_8_2.file_id = file_id;
        __tmp_agg_8_2.span_start = span_start;
        __tmp_agg_8_2.span_end = span_end;
        __tmp_agg_8_2.message_id = msg_id_1;
        __tmp_agg_8_2.note_count = 0;
        __tmp_agg_8_2.note_ids[0] = 0U;
        __tmp_agg_8_2.note_ids[1] = 0U;
        __tmp_agg_8_2.note_ids[2] = 0U;
        zF_9daadfc5_07a08eec_diagnosticArrayListAppend(self->diagnostics, __tmp_agg_8_2);
        (void)(self->error_count += 1);
        return;
    }
    msg_id = zF_4c1e99d4_eb67b606_stringInternerIntern(self->interner, message);
    __tmp_agg_6_1.level = level;
    __tmp_agg_6_1.code = code;
    __tmp_agg_6_1.file_id = file_id;
    __tmp_agg_6_1.span_start = span_start;
    __tmp_agg_6_1.span_end = span_end;
    __tmp_agg_6_1.message_id = msg_id;
    __tmp_agg_6_1.note_count = 0;
    __tmp_agg_6_1.note_ids[0] = 0U;
    __tmp_agg_6_1.note_ids[1] = 0U;
    __tmp_agg_6_1.note_ids[2] = 0U;
    zF_9daadfc5_07a08eec_diagnosticArrayListAppend(self->diagnostics, __tmp_agg_6_1);
    if (level == 0) {
        (void)(self->error_count += 1);
    } else     if (level == 1) {
        (void)(self->warning_count += 1);
    }

}

int zF_9daadfc5_b734257d_diagnosticCollectorHasErrors(struct zS_9daadfc5_490018d3_DiagnosticCollector* self) {
    return self->error_count > 0;
}

unsigned int zF_9daadfc5_736f6f1b_diagnosticCollectorErrorCount(struct zS_9daadfc5_490018d3_DiagnosticCollector* self) {
    return (unsigned int)self->error_count;
}

unsigned int zF_9daadfc5_3ff34e2d_diagnosticCollectorWarningCount(struct zS_9daadfc5_490018d3_DiagnosticCollector* self) {
    return (unsigned int)self->warning_count;
}

void zF_9daadfc5_3ea45a74_diagnosticCollectorPrintAll(struct zS_9daadfc5_490018d3_DiagnosticCollector* self) {
    Slice_zS_9daadfc5_bac763ac_Diagnostic diags;
    usize i = 0;
    if (self->diagnostics->len == 0) {
        return;
    }
    diags = zF_9daadfc5_3c86285a_diagnosticArrayListGetSlice(self->diagnostics);
    zF_9daadfc5_7d11c958_sortDiagnostics(diags);
    __loop_0_start: ;
    if (!(i < self->diagnostics->len)) goto __loop_0_end;
    {
        struct zS_9daadfc5_bac763ac_Diagnostic* d;
        struct zS_2b6fc0a6_c7df22f9_Location loc;
        Slice_u8 fname;
        Slice_u8 col_s;
        unsigned char line_buf[16];
        unsigned int line_len;
        Slice_u8 col_s2;
        unsigned char col_buf[16];
        unsigned int col_len;
        Slice_u8 sep;
        Slice_u8 lb;
        unsigned char code_buf[8];
        unsigned int code_len;
        Slice_u8 rb;
        struct zS_4c1e99d4_7c9905b1_InternEntry entry;
        Slice_u8 nl;
        Slice_u8 content;
        Slice_u32 offsets;
        unsigned int line_idx;
        usize line_start;
        usize line_end;
        unsigned int next_line;
        usize l_start;
        usize l_end;
        d = &diags.ptr[i];
        loc = zF_2b6fc0a6_4fc7c2f2_sourceManagerGetLocation(self->source_manager, d->file_id, d->span_start);
        fname = zF_2b6fc0a6_e1999a6c_sourceManagerGetFileName(self->source_manager, d->file_id);
        zF_9daadfc5_dff904ce_writeStr(fname);
        col_s = __make_slice_u8(":", 1);
        zF_9daadfc5_dff904ce_writeStr(col_s);
        line_len = zF_9daadfc5_ebac3b9b_formatU32(loc.line, __make_slice_u8(&line_buf[0], 16 - 0));
        zF_9daadfc5_dff904ce_writeStr(__make_slice_u8(&line_buf[0], (usize)line_len - 0));
        col_s2 = __make_slice_u8(":", 1);
        zF_9daadfc5_dff904ce_writeStr(col_s2);
        col_len = zF_9daadfc5_ebac3b9b_formatU32(loc.col, __make_slice_u8(&col_buf[0], 16 - 0));
        zF_9daadfc5_dff904ce_writeStr(__make_slice_u8(&col_buf[0], (usize)col_len - 0));
        sep = __make_slice_u8(": ", 2);
        zF_9daadfc5_dff904ce_writeStr(sep);
        zF_9daadfc5_dff904ce_writeStr(zF_9daadfc5_ba10ec31_getLevelName(d->level));
        lb = __make_slice_u8("[", 1);
        zF_9daadfc5_dff904ce_writeStr(lb);
        code_len = zF_9daadfc5_ebac3b9b_formatU32(d->code, __make_slice_u8(&code_buf[0], 8 - 0));
        zF_9daadfc5_dff904ce_writeStr(__make_slice_u8(&code_buf[0], (usize)code_len - 0));
        rb = __make_slice_u8("]: ", 3);
        zF_9daadfc5_dff904ce_writeStr(rb);
        entry = self->interner->entries->items[(usize)d->message_id];
        zF_9daadfc5_dff904ce_writeStr(entry.text);
        nl = __make_slice_u8("\n", 1);
        zF_9daadfc5_dff904ce_writeStr(nl);
        content = zF_2b6fc0a6_00b6dec1_sourceManagerGetSourceContent(self->source_manager, d->file_id);
        offsets = zF_2b6fc0a6_570f3f69_sourceManagerGetLineOffsets(self->source_manager, d->file_id);
        line_idx = zF_edc59eed_96a91e4f_binary_search(offsets, d->span_start);
        if (line_idx > 0) {
            (void)(line_idx -= 1);
        }
        line_start = (usize)offsets.ptr[(usize)line_idx];
        line_end = content.len;
        next_line = line_idx + 1;
        if (next_line < (unsigned int)offsets.len) {
            line_end = (usize)offsets.ptr[(usize)next_line];
            if (line_end > 0 && content.ptr[line_end - 1] == '\n') {
                (void)(line_end -= 1);
            }
        }
        l_start = line_start;
        l_end = line_end;
        if (l_start < l_end && l_end <= content.len) {
            Slice_u8 line_text;
            Slice_u8 nl2;
            usize loc_col;
            usize cspan;
            unsigned char caret_buf[256];
            usize caret_len = 0;
            usize space_count;
            usize ulen;
            usize max_carets;
            Slice_u8 nl3;
            line_text = __make_slice_u8(content.ptr + l_start, l_end - l_start);
            zF_9daadfc5_dff904ce_writeStr(line_text);
            nl2 = __make_slice_u8("\n", 1);
            zF_9daadfc5_dff904ce_writeStr(nl2);
            loc_col = (usize)loc.col;
            cspan = (usize)d->span_end - d->span_start;
            if (cspan == 0) {
                cspan = 1;
            }
            space_count = loc_col;
            if (space_count > 256) {
                space_count = 256;
            }
            {
                usize for_idx;
                usize for_len;
                for_idx = 0;
                for_len = space_count;
                __loop_1_start: ;
                while (for_idx < for_len) {
                    {
                        caret_buf[caret_len] = ' ';
                        (void)(caret_len += 1);
                    }
                    for_idx++;
                    goto __loop_1_start;
                }
                __loop_1_end: ;
            }
            ulen = cspan;
            if (ulen > 256 - loc_col) {
                ulen = 256 - loc_col;
            }
            max_carets = ulen;
            if (max_carets > 256 - caret_len) {
                max_carets = 256 - caret_len;
            }
            {
                usize for_idx_1;
                usize for_len_1;
                for_idx_1 = 0;
                for_len_1 = max_carets;
                __loop_2_start: ;
                while (for_idx_1 < for_len_1) {
                    {
                        caret_buf[caret_len] = '^';
                        (void)(caret_len += 1);
                    }
                    for_idx_1++;
                    goto __loop_2_start;
                }
                __loop_2_end: ;
            }
            zF_9daadfc5_dff904ce_writeStr(__make_slice_u8(&caret_buf[0], caret_len - 0));
            nl3 = __make_slice_u8("\n", 1);
            zF_9daadfc5_dff904ce_writeStr(nl3);
        }
        (void)(i += 1);
    }
    goto __loop_0_start;
    __loop_0_end: ;
}
