/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "growable_array.h"
#include "allocator.h"
#include "ast.h"


struct zS_26b5a9a4_43f95de6_Sand;
struct zS_c313e0ed_f3385aec_AstNode;
struct zS_c313e0ed_42ae50fe_FnProto;
#ifndef ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
#define ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
struct zS_26b5a9a4_43f95de6_Sand {
    unsigned char* start;
    usize pos;
    usize end;
    usize peak;
};

#endif /* ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand */

#ifndef ZIG_STRUCT_zS_c313e0ed_f3385aec_AstNode
#define ZIG_STRUCT_zS_c313e0ed_f3385aec_AstNode
struct zS_c313e0ed_f3385aec_AstNode {
    enum zS_c313e0ed_906c25e2_AstKind kind;
    unsigned char flags;
    unsigned short span_len;
    unsigned int span_start;
    unsigned int child_0;
    unsigned int child_1;
    unsigned int child_2;
    unsigned int payload;
};

#endif /* ZIG_STRUCT_zS_c313e0ed_f3385aec_AstNode */

#ifndef ZIG_STRUCT_zS_c313e0ed_42ae50fe_FnProto
#define ZIG_STRUCT_zS_c313e0ed_42ae50fe_FnProto
struct zS_c313e0ed_42ae50fe_FnProto {
    unsigned int name_id;
    unsigned short params_start;
    unsigned short params_count;
    unsigned int return_type_node;
};

#endif /* ZIG_STRUCT_zS_c313e0ed_42ae50fe_FnProto */

struct zS_16d7ab7a_840ccd30_U32ArrayList zF_16d7ab7a_9eafada9_u32ArrayListInit(struct zS_26b5a9a4_43f95de6_Sand* allocator) {
    {
        struct zS_16d7ab7a_840ccd30_U32ArrayList __return_val = {0};
        __return_val.len = 0;
        __return_val.capacity = 0;
        __return_val.allocator = allocator;
        return __return_val;
    }
}

void zF_16d7ab7a_a304de89_u32ArrayListEnsureCapacity(struct zS_16d7ab7a_840ccd30_U32ArrayList* self, usize new_capacity) {
    usize new_cap;
    unsigned char* __tmp_catch_5_11 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_12;
    unsigned char* raw;
    unsigned int* new_items;
    if (new_capacity <= self->capacity) {
        return;
    }
    new_cap = new_capacity;
    if (new_cap < self->capacity * 2) {
        new_cap = self->capacity * 2;
    }
    if (new_cap < 8) {
        new_cap = 8;
    }
    __tmp_catch_res_5_12 = zF_26b5a9a4_6fa59c42_sandAlloc(self->allocator, 4 * new_cap, 4);
    if (__tmp_catch_res_5_12.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_11 = __tmp_catch_res_5_12.data.payload;
    }
    raw = __tmp_catch_5_11;
    new_items = (unsigned int*)raw;
    {
        Slice_u32 for_iter;
        usize for_idx;
        usize for_len;
        for_iter = __make_slice_u32(self->items + 0, self->len - 0);
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            unsigned int item;
            item = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                new_items[i] = item;
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    self->items = new_items;
    self->capacity = new_cap;
}

void zF_16d7ab7a_42a80787_u32ArrayListAppend(struct zS_16d7ab7a_840ccd30_U32ArrayList* self, unsigned int value) {
    zF_16d7ab7a_a304de89_u32ArrayListEnsureCapacity(self, self->len + 1);
    self->items[self->len] = value;
    (void)(self->len += 1);
}

Optional_u32 zF_16d7ab7a_89114f92_u32ArrayListPopOrNull(struct zS_16d7ab7a_840ccd30_U32ArrayList* self) {
    if (self->len == 0) {
        {
            Optional_u32 __return_val = {0};
            __return_val.has_value = 0;
            return __return_val;
        }
    }
    (void)(self->len -= 1);
    {
        Optional_u32 __return_val = {0};
        __return_val.has_value = 1;
        __return_val.value = self->items[self->len];
        return __return_val;
    }
}

Slice_u32 zF_16d7ab7a_163e748d_u32ArrayListGetSlice(struct zS_16d7ab7a_840ccd30_U32ArrayList* self) {
    return __make_slice_u32(self->items + 0, self->len - 0);
}

struct zS_16d7ab7a_95cf740f_U8ArrayList zF_16d7ab7a_757eb041_byteArrayListInit(struct zS_26b5a9a4_43f95de6_Sand* allocator) {
    {
        struct zS_16d7ab7a_95cf740f_U8ArrayList __return_val = {0};
        __return_val.len = 0;
        __return_val.capacity = 0;
        __return_val.allocator = allocator;
        return __return_val;
    }
}

void zF_16d7ab7a_dbb9a334_byteArrayListGrow(struct zS_16d7ab7a_95cf740f_U8ArrayList* self, usize new_capacity) {
    usize new_cap;
    unsigned char* __tmp_catch_5_9 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_10;
    unsigned char* raw;
    unsigned char* new_items;
    if (new_capacity <= self->capacity) {
        return;
    }
    new_cap = new_capacity;
    if (new_cap < self->capacity * 2) {
        new_cap = self->capacity * 2;
    }
    if (new_cap < 8) {
        new_cap = 8;
    }
    __tmp_catch_res_5_10 = zF_26b5a9a4_6fa59c42_sandAlloc(self->allocator, 1 * new_cap, 1);
    if (__tmp_catch_res_5_10.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_9 = __tmp_catch_res_5_10.data.payload;
    }
    raw = __tmp_catch_5_9;
    new_items = (unsigned char*)raw;
    {
        Slice_u8 for_iter;
        usize for_idx;
        usize for_len;
        for_iter = __make_slice_u8(self->items + 0, self->len - 0);
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            unsigned char item;
            item = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                new_items[i] = item;
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    self->items = new_items;
    self->capacity = new_cap;
}

void zF_16d7ab7a_311f9e3f_byteArrayListAppend(struct zS_16d7ab7a_95cf740f_U8ArrayList* self, unsigned char value) {
    zF_16d7ab7a_dbb9a334_byteArrayListGrow(self, self->len + 1);
    self->items[self->len] = value;
    (void)(self->len += 1);
}

Slice_u8 zF_16d7ab7a_71d232b5_byteArrayListGetSlice(struct zS_16d7ab7a_95cf740f_U8ArrayList* self) {
    return __make_slice_u8(self->items + 0, self->len - 0);
}

struct zS_16d7ab7a_2bc6fbde_AstNodeArrayList zF_16d7ab7a_612498a3_astNodeArrayListInit(struct zS_26b5a9a4_43f95de6_Sand* allocator, usize initial_capacity) {
    struct zS_16d7ab7a_2bc6fbde_AstNodeArrayList list;
    list.len = 0;
    list.capacity = 0;
    list.allocator = allocator;
    zF_16d7ab7a_dd2bbd13_astNodeArrayListEnsureCapacity(&list, initial_capacity);
    return list;
}

void zF_16d7ab7a_dd2bbd13_astNodeArrayListEnsureCapacity(struct zS_16d7ab7a_2bc6fbde_AstNodeArrayList* self, usize new_capacity) {
    usize new_cap;
    unsigned char* __tmp_catch_5_7 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_8;
    unsigned char* raw;
    struct zS_c313e0ed_f3385aec_AstNode* new_items;
    if (new_capacity <= self->capacity) {
        return;
    }
    new_cap = new_capacity;
    if (new_cap < self->capacity * 2) {
        new_cap = self->capacity * 2;
    }
    if (new_cap < 8) {
        new_cap = 8;
    }
    __tmp_catch_res_5_8 = zF_26b5a9a4_6fa59c42_sandAlloc(self->allocator, 24 * new_cap, 4);
    if (__tmp_catch_res_5_8.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_7 = __tmp_catch_res_5_8.data.payload;
    }
    raw = __tmp_catch_5_7;
    new_items = (struct zS_c313e0ed_f3385aec_AstNode*)raw;
    {
        Slice_zS_c313e0ed_f3385aec_AstNode for_iter;
        usize for_idx;
        usize for_len;
        for_iter = __make_slice_zS_c313e0ed_f3385aec_AstNode(self->items + 0, self->len - 0);
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            struct zS_c313e0ed_f3385aec_AstNode item;
            item = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                new_items[i] = item;
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    self->items = new_items;
    self->capacity = new_cap;
}

void zF_16d7ab7a_9aaaacf1_astNodeArrayListAppend(struct zS_16d7ab7a_2bc6fbde_AstNodeArrayList* self, struct zS_c313e0ed_f3385aec_AstNode value) {
    zF_16d7ab7a_dd2bbd13_astNodeArrayListEnsureCapacity(self, self->len + 1);
    self->items[self->len] = value;
    (void)(self->len += 1);
}

Slice_zS_c313e0ed_f3385aec_AstNode zF_16d7ab7a_8c103497_astNodeArrayListGetSlice(struct zS_16d7ab7a_2bc6fbde_AstNodeArrayList* self) {
    return __make_slice_zS_c313e0ed_f3385aec_AstNode(self->items + 0, self->len - 0);
}

struct zS_16d7ab7a_ad5c2721_U64ArrayList zF_16d7ab7a_46450984_u64ArrayListInit(struct zS_26b5a9a4_43f95de6_Sand* allocator, usize initial_capacity) {
    struct zS_16d7ab7a_ad5c2721_U64ArrayList list;
    list.len = 0;
    list.capacity = 0;
    list.allocator = allocator;
    zF_16d7ab7a_412e9c1c_u64ArrayListEnsureCapacity(&list, initial_capacity);
    return list;
}

void zF_16d7ab7a_412e9c1c_u64ArrayListEnsureCapacity(struct zS_16d7ab7a_ad5c2721_U64ArrayList* self, usize new_capacity) {
    usize new_cap;
    unsigned char* __tmp_catch_5_5 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_6;
    unsigned char* raw;
    u64* new_items;
    if (new_capacity <= self->capacity) {
        return;
    }
    new_cap = new_capacity;
    if (new_cap < self->capacity * 2) {
        new_cap = self->capacity * 2;
    }
    if (new_cap < 8) {
        new_cap = 8;
    }
    __tmp_catch_res_5_6 = zF_26b5a9a4_6fa59c42_sandAlloc(self->allocator, 8 * new_cap, 4);
    if (__tmp_catch_res_5_6.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_5 = __tmp_catch_res_5_6.data.payload;
    }
    raw = __tmp_catch_5_5;
    new_items = (u64*)raw;
    {
        Slice_u64 for_iter;
        usize for_idx;
        usize for_len;
        for_iter = __make_slice_u64(self->items + 0, self->len - 0);
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            u64 item;
            item = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                new_items[i] = item;
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    self->items = new_items;
    self->capacity = new_cap;
}

void zF_16d7ab7a_4ab008ba_u64ArrayListAppend(struct zS_16d7ab7a_ad5c2721_U64ArrayList* self, u64 value) {
    zF_16d7ab7a_412e9c1c_u64ArrayListEnsureCapacity(self, self->len + 1);
    self->items[self->len] = value;
    (void)(self->len += 1);
}

Slice_u64 zF_16d7ab7a_24aa3530_u64ArrayListGetSlice(struct zS_16d7ab7a_ad5c2721_U64ArrayList* self) {
    return __make_slice_u64(self->items + 0, self->len - 0);
}

struct zS_16d7ab7a_06dd9f8a_F64ArrayList zF_16d7ab7a_dc157e53_f64ArrayListInit(struct zS_26b5a9a4_43f95de6_Sand* allocator, usize initial_capacity) {
    struct zS_16d7ab7a_06dd9f8a_F64ArrayList list;
    list.len = 0;
    list.capacity = 0;
    list.allocator = allocator;
    zF_16d7ab7a_0e9bd563_f64ArrayListEnsureCapacity(&list, initial_capacity);
    return list;
}

void zF_16d7ab7a_0e9bd563_f64ArrayListEnsureCapacity(struct zS_16d7ab7a_06dd9f8a_F64ArrayList* self, usize new_capacity) {
    usize new_cap;
    unsigned char* __tmp_catch_5_3 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_4;
    unsigned char* raw;
    double* new_items;
    if (new_capacity <= self->capacity) {
        return;
    }
    new_cap = new_capacity;
    if (new_cap < self->capacity * 2) {
        new_cap = self->capacity * 2;
    }
    if (new_cap < 8) {
        new_cap = 8;
    }
    __tmp_catch_res_5_4 = zF_26b5a9a4_6fa59c42_sandAlloc(self->allocator, 8 * new_cap, 4);
    if (__tmp_catch_res_5_4.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_3 = __tmp_catch_res_5_4.data.payload;
    }
    raw = __tmp_catch_5_3;
    new_items = (double*)raw;
    {
        Slice_f64 for_iter;
        usize for_idx;
        usize for_len;
        for_iter = __make_slice_f64(self->items + 0, self->len - 0);
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            double item;
            item = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                new_items[i] = item;
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    self->items = new_items;
    self->capacity = new_cap;
}

void zF_16d7ab7a_fe8768c1_f64ArrayListAppend(struct zS_16d7ab7a_06dd9f8a_F64ArrayList* self, double value) {
    zF_16d7ab7a_0e9bd563_f64ArrayListEnsureCapacity(self, self->len + 1);
    self->items[self->len] = value;
    (void)(self->len += 1);
}

Slice_f64 zF_16d7ab7a_abc75ea7_f64ArrayListGetSlice(struct zS_16d7ab7a_06dd9f8a_F64ArrayList* self) {
    return __make_slice_f64(self->items + 0, self->len - 0);
}

struct zS_16d7ab7a_35e082a4_FnProtoArrayList zF_16d7ab7a_bd2cf011_fnProtoArrayListInit(struct zS_26b5a9a4_43f95de6_Sand* allocator, usize initial_capacity) {
    struct zS_16d7ab7a_35e082a4_FnProtoArrayList list;
    list.len = 0;
    list.capacity = 0;
    list.allocator = allocator;
    zF_16d7ab7a_a61c8131_fnProtoArrayListEnsureCapacity(&list, initial_capacity);
    return list;
}

void zF_16d7ab7a_a61c8131_fnProtoArrayListEnsureCapacity(struct zS_16d7ab7a_35e082a4_FnProtoArrayList* self, usize new_capacity) {
    usize new_cap;
    unsigned char* __tmp_catch_5_1 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_2;
    unsigned char* raw;
    struct zS_c313e0ed_42ae50fe_FnProto* new_items;
    if (new_capacity <= self->capacity) {
        return;
    }
    new_cap = new_capacity;
    if (new_cap < self->capacity * 2) {
        new_cap = self->capacity * 2;
    }
    if (new_cap < 8) {
        new_cap = 8;
    }
    __tmp_catch_res_5_2 = zF_26b5a9a4_6fa59c42_sandAlloc(self->allocator, 12 * new_cap, 4);
    if (__tmp_catch_res_5_2.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_1 = __tmp_catch_res_5_2.data.payload;
    }
    raw = __tmp_catch_5_1;
    new_items = (struct zS_c313e0ed_42ae50fe_FnProto*)raw;
    {
        Slice_zS_c313e0ed_42ae50fe_FnProto for_iter;
        usize for_idx;
        usize for_len;
        for_iter = __make_slice_zS_c313e0ed_42ae50fe_FnProto(self->items + 0, self->len - 0);
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            struct zS_c313e0ed_42ae50fe_FnProto item;
            item = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                new_items[i] = item;
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    self->items = new_items;
    self->capacity = new_cap;
}

void zF_16d7ab7a_a8a6a1ef_fnProtoArrayListAppend(struct zS_16d7ab7a_35e082a4_FnProtoArrayList* self, struct zS_c313e0ed_42ae50fe_FnProto value) {
    zF_16d7ab7a_a61c8131_fnProtoArrayListEnsureCapacity(self, self->len + 1);
    self->items[self->len] = value;
    (void)(self->len += 1);
}

Slice_zS_c313e0ed_42ae50fe_FnProto zF_16d7ab7a_a034ee25_fnProtoArrayListGetSlice(struct zS_16d7ab7a_35e082a4_FnProtoArrayList* self) {
    return __make_slice_zS_c313e0ed_42ae50fe_FnProto(self->items + 0, self->len - 0);
}
