/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "hash.h"


unsigned int zF_6e9f9e18_a60d1698_fnv1a(Slice_u8 data) {
    unsigned int hash = 2166136261;
    {
        Slice_u8 for_iter;
        usize for_idx;
        usize for_len;
        for_iter = data;
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            unsigned char byte;
            byte = for_iter.ptr[for_idx];
            {
                (void)(hash ^= (unsigned int)byte);
                hash = hash * 16777619;
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    return hash;
}
