/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "mem.h"


int zF_edc59eed_700ff121_mem_eql(Slice_u8 a, Slice_u8 b) {
    if (a.len != b.len) {
        return 0;
    }
    {
        Slice_u8 for_iter;
        usize for_idx;
        usize for_len;
        for_iter = a;
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            unsigned char c;
            c = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                if (c != b.ptr[i]) {
                    return 0;
                }
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    return 1;
}

unsigned int zF_edc59eed_96a91e4f_binary_search(Slice_u32 offsets, unsigned int target) {
    unsigned int lo = 0;
    unsigned int hi;
    hi = (unsigned int)offsets.len;
    __loop_0_start: ;
    if (!(lo < hi)) goto __loop_0_end;
    {
        unsigned int mid;
        mid = lo + (hi - lo) / 2;
        if (offsets.ptr[(usize)mid] <= target) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    goto __loop_0_start;
    __loop_0_end: ;
    if (lo == 0) {
        return 0U;
    } else {
        return (unsigned int)lo - 1;
    }
}
