/* Generated by Z98 bootstrap compiler */
#include <string.h>
#include "zig_runtime.h"
#include "zig_special_types.h"

/* Error tags */
#define ERROR_UnexpectedToken 1
#define ERROR_OutOfMemory 2

#include "source_manager.h"
#include "allocator.h"
#include "growable_array.h"
#include "mem.h"
#include "util.h"


struct zS_26b5a9a4_43f95de6_Sand;
struct zS_16d7ab7a_840ccd30_U32ArrayList;
struct zS_2b6fc0a6_c93555ae_SourceFileArrayList;
struct zS_2b6fc0a6_a270ac29_SourceFile;
#ifndef ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
#define ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand
struct zS_26b5a9a4_43f95de6_Sand {
    unsigned char* start;
    usize pos;
    usize end;
    usize peak;
};

#endif /* ZIG_STRUCT_zS_26b5a9a4_43f95de6_Sand */

#ifndef ZIG_STRUCT_zS_16d7ab7a_840ccd30_U32ArrayList
#define ZIG_STRUCT_zS_16d7ab7a_840ccd30_U32ArrayList
struct zS_16d7ab7a_840ccd30_U32ArrayList {
    unsigned int* items;
    usize len;
    usize capacity;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_16d7ab7a_840ccd30_U32ArrayList */

#ifndef ZIG_STRUCT_zS_2b6fc0a6_c93555ae_SourceFileArrayList
#define ZIG_STRUCT_zS_2b6fc0a6_c93555ae_SourceFileArrayList
struct zS_2b6fc0a6_c93555ae_SourceFileArrayList {
    struct zS_2b6fc0a6_a270ac29_SourceFile* items;
    usize len;
    usize capacity;
    struct zS_26b5a9a4_43f95de6_Sand* allocator;
};

#endif /* ZIG_STRUCT_zS_2b6fc0a6_c93555ae_SourceFileArrayList */

static struct zS_2b6fc0a6_c93555ae_SourceFileArrayList zF_2b6fc0a6_31e5b0a1_sourceFileArrayListInit(struct zS_26b5a9a4_43f95de6_Sand*);
static void zF_2b6fc0a6_ce0ade61_urceFileArrayListEnsureCapacity(struct zS_2b6fc0a6_c93555ae_SourceFileArrayList*, usize);
static void zF_2b6fc0a6_bb2a959f_sourceFileArrayListAppend(struct zS_2b6fc0a6_c93555ae_SourceFileArrayList*, struct zS_2b6fc0a6_a270ac29_SourceFile);
static Slice_zS_2b6fc0a6_a270ac29_SourceFile zF_2b6fc0a6_db2b28d5_sourceFileArrayListGetSlice(struct zS_2b6fc0a6_c93555ae_SourceFileArrayList*);
static unsigned char* zF_2b6fc0a6_652f7e8a_sourceManagerCopyToArena(struct zS_2b6fc0a6_29be27be_SourceManager*, Slice_u8);

static struct zS_2b6fc0a6_c93555ae_SourceFileArrayList zF_2b6fc0a6_31e5b0a1_sourceFileArrayListInit(struct zS_26b5a9a4_43f95de6_Sand* allocator) {
    {
        struct zS_2b6fc0a6_c93555ae_SourceFileArrayList __return_val = {0};
        __return_val.len = 0;
        __return_val.capacity = 0;
        __return_val.allocator = allocator;
        return __return_val;
    }
}

static void zF_2b6fc0a6_ce0ade61_urceFileArrayListEnsureCapacity(struct zS_2b6fc0a6_c93555ae_SourceFileArrayList* self, usize new_capacity) {
    usize new_cap;
    unsigned char* __tmp_catch_5_8 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_9;
    unsigned char* raw;
    struct zS_2b6fc0a6_a270ac29_SourceFile* new_items;
    if (new_capacity <= self->capacity) {
        return;
    }
    new_cap = new_capacity;
    if (new_cap < self->capacity * 2) {
        new_cap = self->capacity * 2;
    }
    if (new_cap < 8) {
        new_cap = 8;
    }
    __tmp_catch_res_5_9 = zF_26b5a9a4_6fa59c42_sandAlloc(self->allocator, 20 * new_cap, 4);
    if (__tmp_catch_res_5_9.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_8 = __tmp_catch_res_5_9.data.payload;
    }
    raw = __tmp_catch_5_8;
    new_items = (struct zS_2b6fc0a6_a270ac29_SourceFile*)raw;
    {
        Slice_zS_2b6fc0a6_a270ac29_SourceFile for_iter;
        usize for_idx;
        usize for_len;
        for_iter = __make_slice_zS_2b6fc0a6_a270ac29_SourceFile(self->items + 0, self->len - 0);
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            struct zS_2b6fc0a6_a270ac29_SourceFile item;
            item = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                new_items[i] = item;
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    self->items = new_items;
    self->capacity = new_cap;
}

static void zF_2b6fc0a6_bb2a959f_sourceFileArrayListAppend(struct zS_2b6fc0a6_c93555ae_SourceFileArrayList* self, struct zS_2b6fc0a6_a270ac29_SourceFile value) {
    zF_2b6fc0a6_ce0ade61_urceFileArrayListEnsureCapacity(self, self->len + 1);
    self->items[self->len] = value;
    (void)(self->len += 1);
}

static Slice_zS_2b6fc0a6_a270ac29_SourceFile zF_2b6fc0a6_db2b28d5_sourceFileArrayListGetSlice(struct zS_2b6fc0a6_c93555ae_SourceFileArrayList* self) {
    return __make_slice_zS_2b6fc0a6_a270ac29_SourceFile(self->items + 0, self->len - 0);
}

struct zS_2b6fc0a6_29be27be_SourceManager zF_2b6fc0a6_b845e969_sourceManagerInit(struct zS_26b5a9a4_43f95de6_Sand* allocator) {
    unsigned char* __tmp_catch_5_6 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_7;
    unsigned char* f_raw;
    struct zS_2b6fc0a6_c93555ae_SourceFileArrayList* f_ptr;
    __tmp_catch_res_5_7 = zF_26b5a9a4_6fa59c42_sandAlloc(allocator, 16, 4);
    if (__tmp_catch_res_5_7.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_6 = __tmp_catch_res_5_7.data.payload;
    }
    f_raw = __tmp_catch_5_6;
    f_ptr = (struct zS_2b6fc0a6_c93555ae_SourceFileArrayList*)f_raw;
    *f_ptr = zF_2b6fc0a6_31e5b0a1_sourceFileArrayListInit(allocator);
    {
        struct zS_2b6fc0a6_29be27be_SourceManager __return_val = {0};
        __return_val.files = f_ptr;
        __return_val.allocator = allocator;
        return __return_val;
    }
}

unsigned int zF_2b6fc0a6_50e5e8cc_sourceManagerAddFile(struct zS_2b6fc0a6_29be27be_SourceManager* self, Slice_u8 filename, Slice_u8 content) {
    unsigned char* fname_raw;
    Slice_u8 fname_copy;
    unsigned char* content_raw;
    Slice_u8 content_copy;
    usize hint;
    unsigned int cap;
    unsigned char* __tmp_catch_5_4 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_5;
    unsigned char* lo_raw;
    struct zS_16d7ab7a_840ccd30_U32ArrayList* lo_ptr;
    struct zS_2b6fc0a6_a270ac29_SourceFile __tmp_agg_6_3;
    fname_raw = zF_2b6fc0a6_652f7e8a_sourceManagerCopyToArena(self, filename);
    fname_copy = __make_slice_u8(fname_raw + 0, filename.len - 0);
    content_raw = zF_2b6fc0a6_652f7e8a_sourceManagerCopyToArena(self, content);
    content_copy = __make_slice_u8(content_raw + 0, content.len - 0);
    hint = content.len / 40 + 16;
    cap = zF_4282907c_00ab5888_max((unsigned int)hint, 64);
    __tmp_catch_res_5_5 = zF_26b5a9a4_6fa59c42_sandAlloc(self->allocator, 16, 4);
    if (__tmp_catch_res_5_5.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_4 = __tmp_catch_res_5_5.data.payload;
    }
    lo_raw = __tmp_catch_5_4;
    lo_ptr = (struct zS_16d7ab7a_840ccd30_U32ArrayList*)lo_raw;
    *lo_ptr = zF_16d7ab7a_9eafada9_u32ArrayListInit(self->allocator);
    zF_16d7ab7a_a304de89_u32ArrayListEnsureCapacity(lo_ptr, cap);
    zF_16d7ab7a_42a80787_u32ArrayListAppend(lo_ptr, 0);
    {
        Slice_u8 for_iter;
        usize for_idx;
        usize for_len;
        for_iter = content;
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            unsigned char c;
            c = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                if (c == '\n') {
                    zF_16d7ab7a_42a80787_u32ArrayListAppend(lo_ptr, (unsigned int)i + 1);
                }
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    __tmp_agg_6_3.filename = fname_copy;
    __tmp_agg_6_3.content = content_copy;
    __tmp_agg_6_3.line_offsets = lo_ptr;
    zF_2b6fc0a6_bb2a959f_sourceFileArrayListAppend(self->files, __tmp_agg_6_3);
    return (unsigned int)self->files->len - 1;
}

Slice_u8 zF_2b6fc0a6_e1999a6c_sourceManagerGetFileName(struct zS_2b6fc0a6_29be27be_SourceManager* self, unsigned int file_id) {
    Slice_zS_2b6fc0a6_a270ac29_SourceFile files_slice;
    files_slice = zF_2b6fc0a6_db2b28d5_sourceFileArrayListGetSlice(self->files);
    return files_slice.ptr[(usize)file_id].filename;
}

Slice_u8 zF_2b6fc0a6_00b6dec1_sourceManagerGetSourceContent(struct zS_2b6fc0a6_29be27be_SourceManager* self, unsigned int file_id) {
    Slice_zS_2b6fc0a6_a270ac29_SourceFile files_slice;
    files_slice = zF_2b6fc0a6_db2b28d5_sourceFileArrayListGetSlice(self->files);
    return files_slice.ptr[(usize)file_id].content;
}

Slice_u32 zF_2b6fc0a6_570f3f69_sourceManagerGetLineOffsets(struct zS_2b6fc0a6_29be27be_SourceManager* self, unsigned int file_id) {
    Slice_zS_2b6fc0a6_a270ac29_SourceFile files_slice;
    files_slice = zF_2b6fc0a6_db2b28d5_sourceFileArrayListGetSlice(self->files);
    return zF_16d7ab7a_163e748d_u32ArrayListGetSlice(files_slice.ptr[(usize)file_id].line_offsets);
}

struct zS_2b6fc0a6_c7df22f9_Location zF_2b6fc0a6_4fc7c2f2_sourceManagerGetLocation(struct zS_2b6fc0a6_29be27be_SourceManager* self, unsigned int file_id, unsigned int offset) {
    Slice_zS_2b6fc0a6_a270ac29_SourceFile files_slice;
    struct zS_2b6fc0a6_a270ac29_SourceFile* file;
    Slice_u32 offsets;
    unsigned int line_idx;
    unsigned int col;
    files_slice = zF_2b6fc0a6_db2b28d5_sourceFileArrayListGetSlice(self->files);
    file = &files_slice.ptr[(usize)file_id];
    offsets = zF_16d7ab7a_163e748d_u32ArrayListGetSlice(file->line_offsets);
    line_idx = zF_edc59eed_96a91e4f_binary_search(offsets, offset);
    col = offset - offsets.ptr[(usize)line_idx];
    {
        struct zS_2b6fc0a6_c7df22f9_Location __return_val = {0};
        __return_val.file_id = file_id;
        __return_val.line = line_idx + 1;
        __return_val.col = col;
        return __return_val;
    }
}

static unsigned char* zF_2b6fc0a6_652f7e8a_sourceManagerCopyToArena(struct zS_2b6fc0a6_29be27be_SourceManager* self, Slice_u8 text) {
    unsigned char* __tmp_catch_5_1 = 0;
    ErrorUnion_Ptr_u8 __tmp_catch_res_5_2;
    unsigned char* raw;
    if (text.len == 0) {
        return 0;
    }
    __tmp_catch_res_5_2 = zF_26b5a9a4_6fa59c42_sandAlloc(self->allocator, text.len, 1);
    if (__tmp_catch_res_5_2.is_error) {
        __bootstrap_panic((const char*)("reached unreachable"), (const char*)(__FILE__), __LINE__);
    } else {
        __tmp_catch_5_1 = __tmp_catch_res_5_2.data.payload;
    }
    raw = __tmp_catch_5_1;
    {
        Slice_u8 for_iter;
        usize for_idx;
        usize for_len;
        for_iter = text;
        for_idx = 0;
        for_len = for_iter.len;
        __loop_0_start: ;
        while (for_idx < for_len) {
            unsigned char c;
            c = for_iter.ptr[for_idx];
            usize i;
            i = for_idx;
            {
                raw[i] = c;
            }
            for_idx++;
            goto __loop_0_start;
        }
        __loop_0_end: ;
    }
    return raw;
}
