// emit_support.zig — hand-written support-file emitter for the C89 backend.
//
// Holds the canonical bytes of the compiler's runtime/platform support files as
// Z98 string constants and writes them into the user's output directory, so the
// emitted tree is self-contained (`-I .` + compiling every emitted `.c`).
// Canonical single source of truth on disk:
//   sf/src/include/zig_compat.h, zig_runtime.h, net_prelude.h,
//   zig_runtime.c, zig_pal.c, and sf/src/c_exit.c
// scripts/check_emit_support.sh asserts emitted == canonical byte-for-byte.
//
// This module is the "std-kind helper" the compiler imports; the bytes live in
// the compiler source (NO host-side generator, NO perl, NO generated module).

const c89_mod = @import("c89_emit.zig");
const BufferedWriter = c89_mod.BufferedWriter;

pub fn emitZigCompatHSupport(writer: *BufferedWriter) void {
    c89_mod.bufferedWriterWrite(writer, "/* zig_compat.h - C89 compatibility layer */\n");
    c89_mod.bufferedWriterWrite(writer, "#ifndef ZIG_COMPAT_H\n");
    c89_mod.bufferedWriterWrite(writer, "#define ZIG_COMPAT_H\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _MSC_VER\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef __int64 z64;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef unsigned __int64 zu64;\n");
    c89_mod.bufferedWriterWrite(writer, "#elif defined(__WATCOMC__)\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef long long z64;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef unsigned long long zu64;\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef long long z64;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef unsigned long long zu64;\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "#if !defined(__cplusplus) && !defined(__WATCOMC__)\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef signed char i8;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef short i16;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef int i32;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef z64 i64;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef unsigned char u8;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef unsigned short u16;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef unsigned int u32;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef zu64 u64;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef float f32;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef double f64;\n");
    c89_mod.bufferedWriterWrite(writer, "    typedef unsigned int usize;\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "typedef int bool;\n");
    c89_mod.bufferedWriterWrite(writer, "#define true 1\n");
    c89_mod.bufferedWriterWrite(writer, "#define false 0\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "#ifndef NULL\n");
    c89_mod.bufferedWriterWrite(writer, "#define NULL ((void*)0)\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "#endif /* ZIG_COMPAT_H */\n");
}

pub fn emitNetPreludeHSupport(writer: *BufferedWriter) void {
    c89_mod.bufferedWriterWrite(writer, "/* net_prelude.h — target-neutral net include prelude for std_net extern calls\n");
    c89_mod.bufferedWriterWrite(writer, "   (S2 std_net extern rewrite). The include set mirrors the legacy socket-builtin\n");
    c89_mod.bufferedWriterWrite(writer, "   net include block (c89_emit.zig emitBuiltinIncludes); whichever C toolchain\n");
    c89_mod.bufferedWriterWrite(writer, "   compiles the dump (gcc -m32 / i686-w64-mingw32-gcc) selects the branch, so the\n");
    c89_mod.bufferedWriterWrite(writer, "   only prototype source for every std_net extern is the matching OS header. */\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "#define WIN32_LEAN_AND_MEAN\n");
    c89_mod.bufferedWriterWrite(writer, "#include <windows.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <winsock.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#pragma comment(lib, \"wsock32.lib\")\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "#include <sys/socket.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <netinet/in.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <arpa/inet.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <sys/select.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <sys/time.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <unistd.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <netdb.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* std_net extern-call aliases. std_net's public API owns the names\n");
    c89_mod.bufferedWriterWrite(writer, "   accept/connect/send/recv/close/select, so those externs are declared with an\n");
    c89_mod.bufferedWriterWrite(writer, "   _os Z98 identifier and mapped here to the real OS symbols. Declared AFTER the\n");
    c89_mod.bufferedWriterWrite(writer, "   includes so they never rewrite the OS headers; only the emitted std_net call\n");
    c89_mod.bufferedWriterWrite(writer, "   sites (compiled into the same TU) are affected. */\n");
    c89_mod.bufferedWriterWrite(writer, "#define accept_os accept\n");
    c89_mod.bufferedWriterWrite(writer, "#define connect_os connect\n");
    c89_mod.bufferedWriterWrite(writer, "#define send_os send\n");
    c89_mod.bufferedWriterWrite(writer, "#define recv_os recv\n");
    c89_mod.bufferedWriterWrite(writer, "#define close_os close\n");
    c89_mod.bufferedWriterWrite(writer, "#define select_os select\n");
}

pub fn emitCExitCSupport(writer: *BufferedWriter) void {
    c89_mod.bufferedWriterWrite(writer, "#include <stdlib.h>\n");
    c89_mod.bufferedWriterWrite(writer, "void c_exit(int code) { exit(code); }\n");
}

pub fn emitZigRuntimeHSupport(writer: *BufferedWriter, safe_checks: bool) void {
    c89_mod.bufferedWriterWrite(writer, "#ifndef ZIG_RUNTIME_H\n");
    c89_mod.bufferedWriterWrite(writer, "#define ZIG_RUNTIME_H\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "#include \"zig_compat.h\"\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "extern void pal_print_stderr(const char* s, unsigned int len);\n");
    c89_mod.bufferedWriterWrite(writer, "extern void pal_abort(void);\n");
    c89_mod.bufferedWriterWrite(writer, "extern void pal_trap(void);\n");
    c89_mod.bufferedWriterWrite(writer, "extern int pal_i64_to_str(long long val, char* buf, int bufsize);\n");
    c89_mod.bufferedWriterWrite(writer, "extern int pal_u64_to_str(unsigned long long val, char* buf, int bufsize);\n");
    c89_mod.bufferedWriterWrite(writer, "extern int pal_f64_to_str(double val, char* buf, int bufsize);\n");
    if (safe_checks) {
        c89_mod.bufferedWriterWrite(writer, "\n");
        c89_mod.bufferedWriterWrite(writer, "/* -fsafe undefined poison: byte-exact 0xAA fill (emitted only under -fsafe). */\n");
        c89_mod.bufferedWriterWrite(writer, "void zig_poison_fill(void* p, unsigned int n);\n");
        c89_mod.bufferedWriterWrite(writer, "\n");
        c89_mod.bufferedWriterWrite(writer, "/* -fsafe integer-overflow helpers (A15). The UB-free wrap/flag math lives\n");
        c89_mod.bufferedWriterWrite(writer, "   here (header-static, like the __bootstrap_* cast helpers) so every\n");
        c89_mod.bufferedWriterWrite(writer, "   emitted module is self-sufficient; the C89 emitter only maps the LIR\n");
        c89_mod.bufferedWriterWrite(writer, "   *_with_overflow / overflow_flag ops to these calls. Emitted under -fsafe\n");
        c89_mod.bufferedWriterWrite(writer, "   only, so -ffast output is byte-unchanged. */\n");
        c89_mod.bufferedWriterWrite(writer, "static long long zig_ovf_sext(unsigned long long x, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    unsigned long long m;\n");
        c89_mod.bufferedWriterWrite(writer, "    if (w == 0u) return 0;\n");
        c89_mod.bufferedWriterWrite(writer, "    if (w >= 64u) return (long long)x;\n");
        c89_mod.bufferedWriterWrite(writer, "    m = (1ULL << w) - 1ULL;\n");
        c89_mod.bufferedWriterWrite(writer, "    x = x & m;\n");
        c89_mod.bufferedWriterWrite(writer, "    if ((x & (1ULL << (w - 1u))) != 0ULL) x = x | (~m);\n");
        c89_mod.bufferedWriterWrite(writer, "    return (long long)x;\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static unsigned long long zig_ovf_mask(unsigned long long x, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    if (w == 0u) return 0;\n");
        c89_mod.bufferedWriterWrite(writer, "    if (w >= 64u) return x;\n");
        c89_mod.bufferedWriterWrite(writer, "    return x & ((1ULL << w) - 1ULL);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static unsigned long long zig_ovf_maxu(unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    if (w >= 64u) return ~0ULL;\n");
        c89_mod.bufferedWriterWrite(writer, "    return (1ULL << w) - 1ULL;\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static long long zig_ovf_maxs(unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    if (w >= 64u) return 9223372036854775807LL;\n");
        c89_mod.bufferedWriterWrite(writer, "    return (long long)((1ULL << (w - 1u)) - 1ULL);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static long long zig_ovf_mins(unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    if (w >= 64u) return -9223372036854775807LL - 1LL;\n");
        c89_mod.bufferedWriterWrite(writer, "    return -(long long)(1ULL << (w - 1u));\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static long long zig_wrap_add_s(long long a, long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return zig_ovf_sext((unsigned long long)a + (unsigned long long)b, w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static long long zig_wrap_sub_s(long long a, long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return zig_ovf_sext((unsigned long long)a - (unsigned long long)b, w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static long long zig_wrap_mul_s(long long a, long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return zig_ovf_sext((unsigned long long)a * (unsigned long long)b, w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static long long zig_wrap_shl_s(long long a, long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return zig_ovf_sext(((unsigned long long)a) << (((unsigned long long)b) & 63ULL), w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static long long zig_wrap_neg_s(long long a, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return zig_ovf_sext((unsigned long long)0 - (unsigned long long)a, w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static unsigned long long zig_wrap_add_u(unsigned long long a, unsigned long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return zig_ovf_mask(a + b, w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static unsigned long long zig_wrap_sub_u(unsigned long long a, unsigned long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return zig_ovf_mask(a - b, w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static unsigned long long zig_wrap_mul_u(unsigned long long a, unsigned long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return zig_ovf_mask(a * b, w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static unsigned long long zig_wrap_shl_u(unsigned long long a, unsigned long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return zig_ovf_mask(a << (b & 63ULL), w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static unsigned long long zig_wrap_neg_u(unsigned long long a, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return zig_ovf_mask((unsigned long long)0 - a, w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static int zig_overflow_flag_add_s(long long a, long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    long long maxs = zig_ovf_maxs(w);\n");
        c89_mod.bufferedWriterWrite(writer, "    long long mins = zig_ovf_mins(w);\n");
        c89_mod.bufferedWriterWrite(writer, "    if (b > 0 && a > maxs - b) return 1;\n");
        c89_mod.bufferedWriterWrite(writer, "    if (b < 0 && a < mins - b) return 1;\n");
        c89_mod.bufferedWriterWrite(writer, "    return 0;\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static int zig_overflow_flag_add_u(unsigned long long a, unsigned long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return a > zig_ovf_maxu(w) - b;\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static int zig_overflow_flag_sub_s(long long a, long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    long long maxs = zig_ovf_maxs(w);\n");
        c89_mod.bufferedWriterWrite(writer, "    long long mins = zig_ovf_mins(w);\n");
        c89_mod.bufferedWriterWrite(writer, "    if (b < 0 && a > maxs + b) return 1;\n");
        c89_mod.bufferedWriterWrite(writer, "    if (b > 0 && a < mins + b) return 1;\n");
        c89_mod.bufferedWriterWrite(writer, "    return 0;\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static int zig_overflow_flag_sub_u(unsigned long long a, unsigned long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    (void)w;\n");
        c89_mod.bufferedWriterWrite(writer, "    return a < b;\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static int zig_overflow_flag_mul_s(long long a, long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    long long maxs = zig_ovf_maxs(w);\n");
        c89_mod.bufferedWriterWrite(writer, "    long long mins = zig_ovf_mins(w);\n");
        c89_mod.bufferedWriterWrite(writer, "    if (a == 0 || b == 0) return 0;\n");
        c89_mod.bufferedWriterWrite(writer, "    if (a > 0) {\n");
        c89_mod.bufferedWriterWrite(writer, "        if (b > 0) return a > maxs / b;\n");
        c89_mod.bufferedWriterWrite(writer, "        return b < mins / a;\n");
        c89_mod.bufferedWriterWrite(writer, "    }\n");
        c89_mod.bufferedWriterWrite(writer, "    if (b > 0) return a < mins / b;\n");
        c89_mod.bufferedWriterWrite(writer, "    return a < maxs / b;\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static int zig_overflow_flag_mul_u(unsigned long long a, unsigned long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    if (b == 0ULL) return 0;\n");
        c89_mod.bufferedWriterWrite(writer, "    return a > zig_ovf_maxu(w) / b;\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static int zig_overflow_flag_shl_s(long long a, long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    long long maxs = zig_ovf_maxs(w);\n");
        c89_mod.bufferedWriterWrite(writer, "    long long mins = zig_ovf_mins(w);\n");
        c89_mod.bufferedWriterWrite(writer, "    if (a == 0 || b <= 0) return 0;\n");
        c89_mod.bufferedWriterWrite(writer, "    if (b >= (long long)w) return 1;\n");
        c89_mod.bufferedWriterWrite(writer, "    return a > (maxs >> b) || a < (mins >> b);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static int zig_overflow_flag_shl_u(unsigned long long a, unsigned long long b, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    if (a == 0ULL || b == 0ULL) return 0;\n");
        c89_mod.bufferedWriterWrite(writer, "    if (b >= (unsigned long long)w) return 1;\n");
        c89_mod.bufferedWriterWrite(writer, "    return a > (zig_ovf_maxu(w) >> b);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static int zig_overflow_flag_neg_s(long long a, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    return a == zig_ovf_mins(w);\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
        c89_mod.bufferedWriterWrite(writer, "static int zig_overflow_flag_neg_u(unsigned long long a, unsigned int w) {\n");
        c89_mod.bufferedWriterWrite(writer, "    (void)w;\n");
        c89_mod.bufferedWriterWrite(writer, "    return a != 0ULL;\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
    }
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* Backward compat aliases __bootstrap_print* / __bootstrap_write /\n");
    c89_mod.bufferedWriterWrite(writer, "   __bootstrap_sleep_ms / __bootstrap_panic REMOVED (F4, 2026-08-08) — the\n");
    c89_mod.bufferedWriterWrite(writer, "   examples migrated to std.io (std_io.zig); the cast helpers below now call\n");
    c89_mod.bufferedWriterWrite(writer, "   std_panic directly (operator ruling m0564). */\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* Arena */\n");
    c89_mod.bufferedWriterWrite(writer, "void* arena_alloc_default(unsigned int size);\n");
    c89_mod.bufferedWriterWrite(writer, "extern void* zig_default_arena;\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_panic(const char* msg);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print(const char* s);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_len(const char* s, unsigned int len);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_i32(int val);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_u32(unsigned int val);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_i64(long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_u64(unsigned long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_f64(double val);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_bool(int val);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_char(unsigned char val);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_str(const unsigned char* ptr, unsigned int len);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_hex_u32(unsigned int val);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_hex_i32(int val);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_hex_u64(unsigned long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_hex_i64(long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "signed char std_checked_cast_i8(unsigned long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "unsigned char std_checked_cast_u8(unsigned long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "short std_checked_cast_i16(unsigned long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "unsigned short std_checked_cast_u16(unsigned long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "int std_checked_cast_i32(unsigned long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "unsigned int std_checked_cast_u32(unsigned long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "long long std_checked_cast_i64(unsigned long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "unsigned long long std_checked_cast_u64(unsigned long long val);\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* @intCast range-check helpers (F1, 2026-08-06). Per-pair signed-aware;\n");
    c89_mod.bufferedWriterWrite(writer, "   std_checked_cast_* is upper-bound-only and must NOT be used for @intCast\n");
    c89_mod.bufferedWriterWrite(writer, "   (false-panics on in-range negatives). Defined `static` in this header so\n");
    c89_mod.bufferedWriterWrite(writer, "   every emitted-C TU (single-stream and multi-module) is self-sufficient,\n");
    c89_mod.bufferedWriterWrite(writer, "   and also as extern in zig_runtime.c for direct-linkers. Copied from the\n");
    c89_mod.bufferedWriterWrite(writer, "   zig0-oracle header (src/include/zig_runtime.h:96-185), message standardized\n");
    c89_mod.bufferedWriterWrite(writer, "   to \"integer cast overflow in @intCast\". */\n");
    c89_mod.bufferedWriterWrite(writer, "typedef char c_char;\n");
    c89_mod.bufferedWriterWrite(writer, "static usize __bootstrap_usize_from_i64(i64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (usize)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static i32 __bootstrap_i32_from_u32(u32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > 2147483647U) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static u32 __bootstrap_u32_from_u64(u64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > (u64)4294967295U) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static usize __bootstrap_usize_from_u64(u64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > (u64)4294967295U) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (usize)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static u32 __bootstrap_u32_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static usize __bootstrap_usize_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (usize)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static i32 __bootstrap_i32_from_usize(usize x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > 2147483647U) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static u8 __bootstrap_u8_from_usize(usize x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > 255) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u8)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static u8 __bootstrap_u8_from_bool(bool b) {\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u8)b;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static f32 __bootstrap_f32_from_f64(double x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    return (f32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static i32 __bootstrap_i32_from_u8(u8 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static u8 __bootstrap_u8_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0 || x > 255) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u8)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static u8 __bootstrap_u8_from_u32(u32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > 255) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u8)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static u16 __bootstrap_u16_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0 || x > 65535) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u16)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static u32 __bootstrap_u32_from_i64(i64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0 || x > (i64)4294967295U) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static u64 __bootstrap_u64_from_i64(i64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u64)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static i8 __bootstrap_i8_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < -128 || x > 127) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i8)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static i16 __bootstrap_i16_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < -32768 || x > 32767) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i16)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static i32 __bootstrap_i32_from_i64(i64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < (i64)-2147483647 - 1 || x > (i64)2147483647) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "static c_char __bootstrap_c_char_from_u8(u8 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    return (c_char)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
}

pub fn emitZigRuntimeCSupport(writer: *BufferedWriter, safe_checks: bool) void {
    c89_mod.bufferedWriterWrite(writer, "/* zig_runtime.c - Z98 Runtime Library (generated) */\n");
    c89_mod.bufferedWriterWrite(writer, "#include \"zig_compat.h\"\n");
    c89_mod.bufferedWriterWrite(writer, "#include <string.h>\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* Forward declarations for PAL functions */\n");
    c89_mod.bufferedWriterWrite(writer, "extern void pal_print_stderr(const char* s, unsigned int len);\n");
    c89_mod.bufferedWriterWrite(writer, "extern void pal_print_stdout(const char* s, unsigned int len);\n");
    c89_mod.bufferedWriterWrite(writer, "extern void pal_abort(void);\n");
    c89_mod.bufferedWriterWrite(writer, "extern void pal_trap(void);\n");
    c89_mod.bufferedWriterWrite(writer, "extern int pal_i64_to_str(long long val, char* buf, int bufsize);\n");
    c89_mod.bufferedWriterWrite(writer, "extern int pal_u64_to_str(unsigned long long val, char* buf, int bufsize);\n");
    c89_mod.bufferedWriterWrite(writer, "extern int pal_f64_to_str(double val, char* buf, int bufsize);\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* Panic handler */\n");
    c89_mod.bufferedWriterWrite(writer, "void std_panic(const char* msg) {\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_print_stderr(\"panic: \", 7);\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_print_stderr(msg, strlen(msg));\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_print_stderr(\"\\n\", 1);\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_trap();\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* Print helpers */\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print(const char* s) { if (s) pal_print_stdout(s, strlen(s)); }\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_len(const char* s, unsigned int len) { if (s && len) pal_print_stdout(s, len); }\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_i32(int val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    char buf[16];\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_i64_to_str((long long)val, buf, sizeof(buf));\n");
    c89_mod.bufferedWriterWrite(writer, "    std_print(buf);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_u32(unsigned int val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    char buf[16];\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_u64_to_str((unsigned long long)val, buf, sizeof(buf));\n");
    c89_mod.bufferedWriterWrite(writer, "    std_print(buf);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_i64(long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    char buf[24];\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_i64_to_str(val, buf, sizeof(buf));\n");
    c89_mod.bufferedWriterWrite(writer, "    std_print(buf);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_u64(unsigned long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    char buf[24];\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_u64_to_str(val, buf, sizeof(buf));\n");
    c89_mod.bufferedWriterWrite(writer, "    std_print(buf);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_f64(double val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    char buf[32];\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_f64_to_str(val, buf, sizeof(buf));\n");
    c89_mod.bufferedWriterWrite(writer, "    std_print(buf);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_bool(int val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (val) std_print(\"true\");\n");
    c89_mod.bufferedWriterWrite(writer, "    else std_print(\"false\");\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_char(unsigned char val) { char c = (char)val; pal_print_stdout(&c, 1); }\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_hex_u32(unsigned int val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    const char* hex_digits = \"0123456789abcdef\";\n");
    c89_mod.bufferedWriterWrite(writer, "    char buf[16];\n");
    c89_mod.bufferedWriterWrite(writer, "    char tmp[16];\n");
    c89_mod.bufferedWriterWrite(writer, "    int pos;\n");
    c89_mod.bufferedWriterWrite(writer, "    int tpos;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (val == 0) {\n");
    c89_mod.bufferedWriterWrite(writer, "        std_print(\"0\");\n");
    c89_mod.bufferedWriterWrite(writer, "        return;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    pos = 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    tpos = 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (val > 0) {\n");
    c89_mod.bufferedWriterWrite(writer, "        tmp[tpos] = hex_digits[val & 0xF];\n");
    c89_mod.bufferedWriterWrite(writer, "        tpos++;\n");
    c89_mod.bufferedWriterWrite(writer, "        val = val >> 4;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    while (tpos > 0) {\n");
    c89_mod.bufferedWriterWrite(writer, "        tpos--;\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[pos] = tmp[tpos];\n");
    c89_mod.bufferedWriterWrite(writer, "        pos++;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    std_print_len(buf, (unsigned int)pos);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_hex_i32(int val) { std_print_hex_u32((unsigned int)val); }\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_hex_u64(unsigned long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    const char* hex_digits = \"0123456789abcdef\";\n");
    c89_mod.bufferedWriterWrite(writer, "    char buf[24];\n");
    c89_mod.bufferedWriterWrite(writer, "    char tmp[24];\n");
    c89_mod.bufferedWriterWrite(writer, "    int pos;\n");
    c89_mod.bufferedWriterWrite(writer, "    int tpos;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (val == 0) {\n");
    c89_mod.bufferedWriterWrite(writer, "        std_print(\"0\");\n");
    c89_mod.bufferedWriterWrite(writer, "        return;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    pos = 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    tpos = 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (val > 0) {\n");
    c89_mod.bufferedWriterWrite(writer, "        tmp[tpos] = hex_digits[(int)(val & 0xFULL)];\n");
    c89_mod.bufferedWriterWrite(writer, "        tpos++;\n");
    c89_mod.bufferedWriterWrite(writer, "        val = val >> 4;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    while (tpos > 0) {\n");
    c89_mod.bufferedWriterWrite(writer, "        tpos--;\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[pos] = tmp[tpos];\n");
    c89_mod.bufferedWriterWrite(writer, "        pos++;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    std_print_len(buf, (unsigned int)pos);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_hex_i64(long long val) { std_print_hex_u64((unsigned long long)val); }\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void std_print_str(const unsigned char* ptr, unsigned int len) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (ptr && len) pal_print_stdout((const char*)ptr, len);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* Backward compat I/O aliases __bootstrap_print* / __bootstrap_write /\n");
    c89_mod.bufferedWriterWrite(writer, "   __bootstrap_sleep_ms / __bootstrap_panic REMOVED (F4, 2026-08-08) — the\n");
    c89_mod.bufferedWriterWrite(writer, "   examples migrated to std.io (std_io.zig builtins). The cast helpers below\n");
    c89_mod.bufferedWriterWrite(writer, "   call std_panic directly (operator ruling m0564). */\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* Checked conversions (u64 -> target type) */\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "signed char std_checked_cast_i8(unsigned long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (val > 127ULL) std_panic(\"int cast overflow for i8\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (signed char)val;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "unsigned char std_checked_cast_u8(unsigned long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (val > 255ULL) std_panic(\"int cast overflow for u8\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (unsigned char)val;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "short std_checked_cast_i16(unsigned long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (val > 32767ULL) std_panic(\"int cast overflow for i16\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (short)val;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "unsigned short std_checked_cast_u16(unsigned long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (val > 65535ULL) std_panic(\"int cast overflow for u16\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (unsigned short)val;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "int std_checked_cast_i32(unsigned long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (val > 2147483647ULL) std_panic(\"int cast overflow for i32\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (int)val;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "unsigned int std_checked_cast_u32(unsigned long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (val > 4294967295ULL) std_panic(\"int cast overflow for u32\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (unsigned int)val;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "long long std_checked_cast_i64(unsigned long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (val > 9223372036854775807ULL) std_panic(\"int cast overflow for i64\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (long long)val;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "unsigned long long std_checked_cast_u64(unsigned long long val) {\n");
    c89_mod.bufferedWriterWrite(writer, "    return val;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* @intCast range-check helpers (F1, 2026-08-06).\n");
    c89_mod.bufferedWriterWrite(writer, "   Copied from the zig0-oracle header (src/include/zig_runtime.h:96-185),\n");
    c89_mod.bufferedWriterWrite(writer, "   standardized panic message: \"integer cast overflow in @intCast\".\n");
    c89_mod.bufferedWriterWrite(writer, "   c_char is char; not typedef'd in zig_compat.h, so typedef'd here. */\n");
    c89_mod.bufferedWriterWrite(writer, "typedef char c_char;\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "usize __bootstrap_usize_from_i64(i64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (usize)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "i32 __bootstrap_i32_from_u32(u32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > 2147483647U) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "u32 __bootstrap_u32_from_u64(u64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > (u64)4294967295U) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "usize __bootstrap_usize_from_u64(u64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > (u64)4294967295U) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (usize)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "u32 __bootstrap_u32_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "usize __bootstrap_usize_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (usize)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "i32 __bootstrap_i32_from_usize(usize x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > 2147483647U) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "u8 __bootstrap_u8_from_usize(usize x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > 255) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u8)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "u8 __bootstrap_u8_from_bool(bool b) {\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u8)b;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "f32 __bootstrap_f32_from_f64(double x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    return (f32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "i32 __bootstrap_i32_from_u8(u8 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "u8 __bootstrap_u8_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0 || x > 255) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u8)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "u8 __bootstrap_u8_from_u32(u32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x > 255) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u8)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "u16 __bootstrap_u16_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0 || x > 65535) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u16)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "u32 __bootstrap_u32_from_i64(i64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0 || x > (i64)4294967295U) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "u64 __bootstrap_u64_from_i64(i64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < 0) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (u64)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "i8 __bootstrap_i8_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < -128 || x > 127) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i8)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "i16 __bootstrap_i16_from_i32(i32 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < -32768 || x > 32767) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i16)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "i32 __bootstrap_i32_from_i64(i64 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    if (x < (i64)-2147483647 - 1 || x > (i64)2147483647) std_panic(\"integer cast overflow in @intCast\");\n");
    c89_mod.bufferedWriterWrite(writer, "    return (i32)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "c_char __bootstrap_c_char_from_u8(u8 x) {\n");
    c89_mod.bufferedWriterWrite(writer, "    return (c_char)x;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    if (safe_checks) {
        c89_mod.bufferedWriterWrite(writer, "\n");
        c89_mod.bufferedWriterWrite(writer, "/* -fsafe undefined poison: byte-exact 0xAA fill. */\n");
        c89_mod.bufferedWriterWrite(writer, "void zig_poison_fill(void* p, unsigned int n) {\n");
        c89_mod.bufferedWriterWrite(writer, "    unsigned char* b = (unsigned char*)p;\n");
        c89_mod.bufferedWriterWrite(writer, "    unsigned int i;\n");
        c89_mod.bufferedWriterWrite(writer, "    for (i = 0; i < n; i++) {\n");
        c89_mod.bufferedWriterWrite(writer, "        b[i] = (unsigned char)0xAAu;\n");
        c89_mod.bufferedWriterWrite(writer, "    }\n");
        c89_mod.bufferedWriterWrite(writer, "}\n");
    }
}

pub fn emitZigPalCSupport(writer: *BufferedWriter) void {
    c89_mod.bufferedWriterWrite(writer, "/* zig_pal.c - Platform Abstraction Layer (generated by zig1) */\n");
    c89_mod.bufferedWriterWrite(writer, "#ifndef ZIG_PAL_C\n");
    c89_mod.bufferedWriterWrite(writer, "#define ZIG_PAL_C\n");
    c89_mod.bufferedWriterWrite(writer, "#include \"zig_compat.h\"\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "#include <windows.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "#include <stdlib.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <string.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <unistd.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <fcntl.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <errno.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#include <sys/stat.h>\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "typedef void* PlatFile;\n");
    c89_mod.bufferedWriterWrite(writer, "#define PLAT_INVALID_FILE ((void*)-1)\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "typedef int PlatFile;\n");
    c89_mod.bufferedWriterWrite(writer, "#define PLAT_INVALID_FILE (-1)\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* pal_file_open mode encoding: WRITE (0) = truncate/create write path\n");
    c89_mod.bufferedWriterWrite(writer, " * (byte-identical legacy behavior, all existing callers pass 0); READ (1) =\n");
    c89_mod.bufferedWriterWrite(writer, " * read-only open of an existing file. */\n");
    c89_mod.bufferedWriterWrite(writer, "#define PAL_FILE_OPEN_WRITE 0\n");
    c89_mod.bufferedWriterWrite(writer, "#define PAL_FILE_OPEN_READ  1\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "static usize pal_strlen(const char* s)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    const char* p = s;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (*p) p++;\n");
    c89_mod.bufferedWriterWrite(writer, "    return (usize)(p - s);\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    return (usize)strlen(s);\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "static void pal_memcpy(void* dst, const void* src, usize n)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    char* d = (char*)dst;\n");
    c89_mod.bufferedWriterWrite(writer, "    const char* s = (const char*)src;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (n--) *d++ = *s++;\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    memcpy(dst, src, (size_t)n);\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "static void pal_reverse(char* buf, int len)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "    int i = 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    int j = len - 1;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (i < j) {\n");
    c89_mod.bufferedWriterWrite(writer, "        char t = buf[i];\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[i] = buf[j];\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[j] = t;\n");
    c89_mod.bufferedWriterWrite(writer, "        i++;\n");
    c89_mod.bufferedWriterWrite(writer, "        j--;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "static int pal_u64_to_str_buf(u64 value, char* buf, int bufsize)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "    int i;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (bufsize <= 0) return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (value == 0) {\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[0] = '0';\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[1] = '\\0';\n");
    c89_mod.bufferedWriterWrite(writer, "        return 1;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    i = 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (value > 0 && i < bufsize - 1) {\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[i++] = '0' + (char)(value % 10);\n");
    c89_mod.bufferedWriterWrite(writer, "        value /= 10;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    buf[i] = '\\0';\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_reverse(buf, i);\n");
    c89_mod.bufferedWriterWrite(writer, "    return i;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void pal_print_stderr(const char* msg, usize len)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    HANDLE h;\n");
    c89_mod.bufferedWriterWrite(writer, "    DWORD written;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (!msg || len == 0) return;\n");
    c89_mod.bufferedWriterWrite(writer, "    h = GetStdHandle(STD_ERROR_HANDLE);\n");
    c89_mod.bufferedWriterWrite(writer, "    if (h == INVALID_HANDLE_VALUE || h == NULL) return;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (!WriteConsoleA(h, msg, (DWORD)len, &written, NULL))\n");
    c89_mod.bufferedWriterWrite(writer, "        WriteFile(h, msg, (DWORD)len, &written, NULL);\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    write(2, msg, (size_t)len);\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void pal_print_stdout(const char* msg, usize len)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    HANDLE h;\n");
    c89_mod.bufferedWriterWrite(writer, "    DWORD written;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (!msg || len == 0) return;\n");
    c89_mod.bufferedWriterWrite(writer, "    h = GetStdHandle(STD_OUTPUT_HANDLE);\n");
    c89_mod.bufferedWriterWrite(writer, "    if (h == INVALID_HANDLE_VALUE || h == NULL) return;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (!WriteConsoleA(h, msg, (DWORD)len, &written, NULL))\n");
    c89_mod.bufferedWriterWrite(writer, "        WriteFile(h, msg, (DWORD)len, &written, NULL);\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    write(1, msg, (size_t)len);\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void pal_abort(void)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    TerminateProcess(GetCurrentProcess(), 3);\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    abort();\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "void pal_trap(void)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _MSC_VER\n");
    c89_mod.bufferedWriterWrite(writer, "    __asm { int 3 }\n");
    c89_mod.bufferedWriterWrite(writer, "#elif defined(__WATCOMC__)\n");
    c89_mod.bufferedWriterWrite(writer, "    __asm { int 3 }\n");
    c89_mod.bufferedWriterWrite(writer, "#elif defined(__i386__) || defined(__x86_64__)\n");
    c89_mod.bufferedWriterWrite(writer, "    __asm__ __volatile__(\"int3\");\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    pal_abort();\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "int pal_i64_to_str(i64 value, char* buf, int bufsize)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "    u64 uval;\n");
    c89_mod.bufferedWriterWrite(writer, "    int is_neg;\n");
    c89_mod.bufferedWriterWrite(writer, "    int dlen;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (bufsize <= 0) return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (value == 0) {\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[0] = '0';\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[1] = '\\0';\n");
    c89_mod.bufferedWriterWrite(writer, "        return 1;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    is_neg = (value < 0) ? 1 : 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    uval = is_neg ? (u64)(-(value + 1)) + 1 : (u64)value;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (is_neg) {\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[0] = '-';\n");
    c89_mod.bufferedWriterWrite(writer, "        dlen = pal_u64_to_str_buf(uval, buf + 1, bufsize - 1);\n");
    c89_mod.bufferedWriterWrite(writer, "        return dlen + 1;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    return pal_u64_to_str_buf(uval, buf, bufsize);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "int pal_u64_to_str(u64 value, char* buf, int bufsize)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "    return pal_u64_to_str_buf(value, buf, bufsize);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "int pal_f64_to_str(f64 value, char* buf, int bufsize)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "    int int_len;\n");
    c89_mod.bufferedWriterWrite(writer, "    int i;\n");
    c89_mod.bufferedWriterWrite(writer, "    f64 frac_part;\n");
    c89_mod.bufferedWriterWrite(writer, "    i64 int_part;\n");
    c89_mod.bufferedWriterWrite(writer, "    u64 frac_int;\n");
    c89_mod.bufferedWriterWrite(writer, "    int pos;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (bufsize < 2) {\n");
    c89_mod.bufferedWriterWrite(writer, "        if (bufsize == 1) buf[0] = '\\0';\n");
    c89_mod.bufferedWriterWrite(writer, "        return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    if (value < 0.0) {\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[0] = '-';\n");
    c89_mod.bufferedWriterWrite(writer, "        pos = 1;\n");
    c89_mod.bufferedWriterWrite(writer, "        value = -value;\n");
    c89_mod.bufferedWriterWrite(writer, "    } else {\n");
    c89_mod.bufferedWriterWrite(writer, "        pos = 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    int_part = (i64)value;\n");
    c89_mod.bufferedWriterWrite(writer, "    int_len = pal_i64_to_str(int_part, buf + pos, bufsize - pos);\n");
    c89_mod.bufferedWriterWrite(writer, "    if (int_len <= 0) return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    pos += int_len;\n");
    c89_mod.bufferedWriterWrite(writer, "    buf[pos++] = '.';\n");
    c89_mod.bufferedWriterWrite(writer, "    frac_part = value - (f64)int_part;\n");
    c89_mod.bufferedWriterWrite(writer, "    i = 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (i < 6 && pos < bufsize - 1) {\n");
    c89_mod.bufferedWriterWrite(writer, "        frac_part *= 10.0;\n");
    c89_mod.bufferedWriterWrite(writer, "        frac_int = (u64)frac_part;\n");
    c89_mod.bufferedWriterWrite(writer, "        buf[pos++] = '0' + (char)(frac_int % 10);\n");
    c89_mod.bufferedWriterWrite(writer, "        frac_part -= (f64)frac_int;\n");
    c89_mod.bufferedWriterWrite(writer, "        i++;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    while (pos > 0 && buf[pos - 1] == '0') pos--;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (buf[pos - 1] == '.') pos++;\n");
    c89_mod.bufferedWriterWrite(writer, "    buf[pos] = '\\0';\n");
    c89_mod.bufferedWriterWrite(writer, "    return pos;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "PlatFile pal_file_open(const char* path, int flags) {\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    HANDLE h;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (flags == PAL_FILE_OPEN_READ) {\n");
    c89_mod.bufferedWriterWrite(writer, "        h = CreateFileA(path, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING,\n");
    c89_mod.bufferedWriterWrite(writer, "                        FILE_ATTRIBUTE_NORMAL, NULL);\n");
    c89_mod.bufferedWriterWrite(writer, "    } else {\n");
    c89_mod.bufferedWriterWrite(writer, "        h = CreateFileA(path, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS,\n");
    c89_mod.bufferedWriterWrite(writer, "                        FILE_ATTRIBUTE_NORMAL, NULL);\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    if (h == INVALID_HANDLE_VALUE) return PLAT_INVALID_FILE;\n");
    c89_mod.bufferedWriterWrite(writer, "    return h;\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    if (!path) return PLAT_INVALID_FILE;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (flags == PAL_FILE_OPEN_READ) return open(path, O_RDONLY, 0);\n");
    c89_mod.bufferedWriterWrite(writer, "    return open(path, O_WRONLY | O_CREAT | O_TRUNC | flags, 0644);\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "int pal_file_read(PlatFile fd, char* buf, unsigned int len) {\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    HANDLE h = (HANDLE)fd; DWORD r = 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (!buf || !ReadFile(h, buf, (DWORD)len, &r, NULL)) return -1;\n");
    c89_mod.bufferedWriterWrite(writer, "    return (int)r;\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    size_t off = 0; if (!buf) return -1;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (off < (size_t)len) {\n");
    c89_mod.bufferedWriterWrite(writer, "        ssize_t n = read(fd, buf + off, (size_t)len - off);\n");
    c89_mod.bufferedWriterWrite(writer, "        if (n < 0) { if (errno == EINTR) continue; return -1; }\n");
    c89_mod.bufferedWriterWrite(writer, "        if (n == 0) break;\n");
    c89_mod.bufferedWriterWrite(writer, "        off += (size_t)n;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    return (int)off;\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "int pal_file_write(PlatFile fd, const char* buf, unsigned int len) {\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    HANDLE h = (HANDLE)fd; DWORD w = 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (!buf || !WriteFile(h, buf, (DWORD)len, &w, NULL)) return -1;\n");
    c89_mod.bufferedWriterWrite(writer, "    return (int)w;\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    size_t off = 0; if (!buf) return -1;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (off < (size_t)len) {\n");
    c89_mod.bufferedWriterWrite(writer, "        ssize_t n = write(fd, buf + off, (size_t)len - off);\n");
    c89_mod.bufferedWriterWrite(writer, "        if (n <= 0) return -1;\n");
    c89_mod.bufferedWriterWrite(writer, "        off += (size_t)n;\n");
    c89_mod.bufferedWriterWrite(writer, "    }\n");
    c89_mod.bufferedWriterWrite(writer, "    return (int)off;\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "int pal_file_close(PlatFile fd) {\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    return CloseHandle((HANDLE)fd) ? 0 : -1;\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    return close(fd);\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "int pal_dir_exists(const char* path)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    DWORD attr;\n");
    c89_mod.bufferedWriterWrite(writer, "    attr = GetFileAttributesA(path);\n");
    c89_mod.bufferedWriterWrite(writer, "    return (attr != INVALID_FILE_ATTRIBUTES && (attr & FILE_ATTRIBUTE_DIRECTORY));\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    struct stat sb;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (path == 0 || stat(path, &sb) != 0) return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    return (sb.st_mode & 0040000) != 0;\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "/* pal_get_default_lib_path: compute the compiler-binary-relative default\n");
    c89_mod.bufferedWriterWrite(writer, " * install path <exe_dir>/lib. Win9x-primary via GetModuleFileNameA (kernel32,\n");
    c89_mod.bufferedWriterWrite(writer, " * present since Win95); Linux best-effort via readlink(\"/proc/self/exe\").\n");
    c89_mod.bufferedWriterWrite(writer, " * Returns the length of the written path (excluding NUL), or 0 on failure. */\n");
    c89_mod.bufferedWriterWrite(writer, "int pal_get_default_lib_path(char* buf, int bufsize)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "#ifdef _WIN32\n");
    c89_mod.bufferedWriterWrite(writer, "    DWORD n;\n");
    c89_mod.bufferedWriterWrite(writer, "    int i;\n");
    c89_mod.bufferedWriterWrite(writer, "    int dir_len;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (!buf || bufsize < 2) return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    n = GetModuleFileNameA(NULL, buf, (DWORD)bufsize);\n");
    c89_mod.bufferedWriterWrite(writer, "    if (n == 0 || n >= (DWORD)bufsize) return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    i = (int)n - 1;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (i >= 0 && buf[i] != '\\\\' && buf[i] != '/') i--;\n");
    c89_mod.bufferedWriterWrite(writer, "    dir_len = i;\n");
    c89_mod.bufferedWriterWrite(writer, "#else\n");
    c89_mod.bufferedWriterWrite(writer, "    ssize_t n;\n");
    c89_mod.bufferedWriterWrite(writer, "    int i;\n");
    c89_mod.bufferedWriterWrite(writer, "    int dir_len;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (!buf || bufsize < 2) return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    n = readlink(\"/proc/self/exe\", buf, (size_t)bufsize - 1);\n");
    c89_mod.bufferedWriterWrite(writer, "    if (n <= 0 || n >= (ssize_t)bufsize - 1) return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    buf[n] = '\\0';\n");
    c89_mod.bufferedWriterWrite(writer, "    i = (int)n - 1;\n");
    c89_mod.bufferedWriterWrite(writer, "    while (i >= 0 && buf[i] != '/') i--;\n");
    c89_mod.bufferedWriterWrite(writer, "    dir_len = i;\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "    if (dir_len < 0) return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    if (dir_len + 5 > bufsize) return 0;\n");
    c89_mod.bufferedWriterWrite(writer, "    buf[dir_len] = '/';\n");
    c89_mod.bufferedWriterWrite(writer, "    buf[dir_len + 1] = 'l';\n");
    c89_mod.bufferedWriterWrite(writer, "    buf[dir_len + 2] = 'i';\n");
    c89_mod.bufferedWriterWrite(writer, "    buf[dir_len + 3] = 'b';\n");
    c89_mod.bufferedWriterWrite(writer, "    buf[dir_len + 4] = '\\0';\n");
    c89_mod.bufferedWriterWrite(writer, "    return dir_len + 4;\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "#if defined(_WIN32) && defined(ZIG_NO_CRT)\n");
    c89_mod.bufferedWriterWrite(writer, "int main(void);\n");
    c89_mod.bufferedWriterWrite(writer, "void __cdecl mainCRTStartup(void)\n");
    c89_mod.bufferedWriterWrite(writer, "{\n");
    c89_mod.bufferedWriterWrite(writer, "    int result = main();\n");
    c89_mod.bufferedWriterWrite(writer, "    ExitProcess((UINT)result);\n");
    c89_mod.bufferedWriterWrite(writer, "}\n");
    c89_mod.bufferedWriterWrite(writer, "#endif\n");
    c89_mod.bufferedWriterWrite(writer, "\n");
    c89_mod.bufferedWriterWrite(writer, "#endif /* ZIG_PAL_C */\n");
}
