pub const TokenKind = enum(u16) {
    integer_literal,
    float_literal,
    string_literal,
    char_literal,
    identifier,
    builtin_identifier,
    lparen,
    rparen,
    lbracket,
    rbracket,
    lbrace,
    rbrace,
    semicolon,
    colon,
    comma,
    dot,
    at_sign,
    underscore,
    question_mark,
    bang,
    plus,
    minus,
    star,
    slash,
    percent,
    ampersand,
    pipe,
    caret,
    tilde,
    shl,
    shr,
    eq_eq,
    bang_eq,
    less,
    less_eq,
    greater,
    greater_eq,
    eq,
    plus_eq,
    minus_eq,
    star_eq,
    slash_eq,
    percent_eq,
    ampersand_eq,
    pipe_eq,
    caret_eq,
    shl_eq,
    shr_eq,
    dot_dot,
    dot_dot_dot,
    dot_lbrace,
    dot_star,
    fat_arrow,
    kw_const,
    kw_var,
    kw_fn,
    kw_pub,
    kw_extern,
    kw_export,
    kw_test,
    kw_struct,
    kw_enum,
    kw_union,
    kw_if,
    kw_else,
    kw_while,
    kw_for,
    kw_switch,
    kw_return,
    kw_break,
    kw_continue,
    kw_defer,
    kw_errdefer,
    kw_try,
    kw_catch,
    kw_orelse,
    kw_error,
    kw_and,
    kw_or,
    kw_true,
    kw_false,
    kw_null,
    kw_undefined,
    kw_unreachable,
    kw_void,
    kw_bool,
    kw_noreturn,
    kw_c_char,
    eof,
    err_token,            // unrecognized character (error recovery)
};

pub const SyncContext = enum(u8) {
    stmt_list,      // ;, }, kw_fn, kw_const, kw_var, kw_pub, eof
    expression,     // ), ], }, ,, ;, eof
    switch_prong,   // =>, ,, }, else, eof
    fn_body,        // }, eof
    module_root,    // kw_fn, kw_const, kw_var, kw_test, eof
};

pub const TokenValue = union {
    int_val: u64,
    float_val: f64,
    string_id: u32,
    none: void,
};

pub const Token = struct {
    kind: TokenKind,
    span_start: u32,
    span_len: u16,
    value: TokenValue,
};
